'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';

type Item={productId:string;offerId?:string;qty:number;name:string;unitPrice:number;lineTotal:number;stock:number;image?:string;sellerId?:string;offerValid:boolean};
type Journey={cart:{items:Item[];subtotal:number;shipping:number;total:number;currency:string;invalidLines:number;stockWarnings:string[]};checkout:{ready:boolean;blockers:string[];itemCount:number;sellerCount:number;next:string}};

export default function CartPage(){
 const [journey,setJourney]=useState<Journey|null>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 async function load(){setError(''); const r=await fetch('/api/commerce/journey',{cache:'no-store'}); const d=await r.json().catch(()=>({})); if(!r.ok){setError(d.error??'تعذر تحميل السلة');return;} setJourney(d.journey);}
 useEffect(()=>{load()},[]);
 async function qty(item:Item,next:number){setBusy(true);try{const r=await fetch('/api/cart/items',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({productId:item.productId,offerId:item.offerId,qty:next})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error??'تعذر تحديث السلة');await load();}catch(e){setError(e instanceof Error?e.message:'تعذر تحديث السلة')}finally{setBusy(false)}}
 if(!journey&&!error)return <main style={{maxWidth:1000,margin:'0 auto',padding:40}}>جارٍ تحميل السلة…</main>;
 if(error)return <main style={{maxWidth:1000,margin:'0 auto',padding:40}}><h1>السلة</h1><p>{error}</p><button onClick={load}>إعادة المحاولة</button></main>;
 const j=journey!; if(!j.cart.items.length)return <main style={{maxWidth:1000,margin:'0 auto',padding:40}}><h1>سلة التسوق</h1><p>السلة فارغة.</p><Link href="/shop">ابدأ التسوق</Link></main>;
 return <main style={{maxWidth:1100,margin:'0 auto',padding:'36px 18px'}}><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center'}}><div><p style={{opacity:.6}}>TRUST MARKETPLACE</p><h1>سلة التسوق</h1><p>{j.checkout.itemCount} قطعة · {j.checkout.sellerCount} بائع</p></div><Link href="/shop">← متابعة التسوق</Link></div>
 <section style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) 320px',gap:20,alignItems:'start'}}><div style={{display:'grid',gap:12}}>{j.cart.items.map(i=><article key={`${i.productId}:${i.offerId??''}`} style={{border:'1px solid #ddd',borderRadius:16,padding:16,display:'grid',gridTemplateColumns:'90px 1fr auto',gap:16,alignItems:'center'}}>{i.image?<img src={i.image} alt={i.name} style={{width:90,height:90,objectFit:'cover',borderRadius:12}}/>:<div style={{width:90,height:90,borderRadius:12,background:'#eee'}}/>}<div><Link href={`/product/${i.productId}`}><strong>{i.name}</strong></Link><p>{i.sellerId?`البائع: ${i.sellerId}`:'منتج مباشر'} · {i.unitPrice.toFixed(2)} {j.cart.currency}</p><small>{i.offerValid?'العرض متاح':'العرض لم يعد متاحًا'}</small></div><div style={{textAlign:'right'}}><strong>{i.lineTotal.toFixed(2)} {j.cart.currency}</strong><div style={{display:'flex',gap:6,marginTop:10}}><button disabled={busy||i.qty<=1} onClick={()=>qty(i,i.qty-1)}>-</button><span>{i.qty}</span><button disabled={busy||i.qty>=i.stock} onClick={()=>qty(i,i.qty+1)}>+</button><button disabled={busy} onClick={()=>qty(i,0)}>حذف</button></div></div></article>)}</div>
 <aside style={{border:'1px solid #ddd',borderRadius:18,padding:18,position:'sticky',top:18}}><h2>ملخص الطلب</h2><p>الإجمالي الفرعي: {j.cart.subtotal.toFixed(2)} {j.cart.currency}</p><p>الشحن: {j.cart.shipping.toFixed(2)} {j.cart.currency}</p><hr/><h2>{j.cart.total.toFixed(2)} {j.cart.currency}</h2>{j.checkout.ready?<Link href="/checkout" style={{display:'block',padding:14,textAlign:'center',borderRadius:12,background:'#111',color:'#fff',textDecoration:'none'}}>الانتقال للدفع</Link>:<div><strong>لا يمكن المتابعة الآن</strong><ul>{j.checkout.blockers.map(x=><li key={x}>{x}</li>)}</ul><button onClick={load}>تحديث السلة</button></div>}</aside></section></main>;
}
