-- TRUST V137 — sovereign platform controls.
CREATE TABLE IF NOT EXISTS trust_api_contracts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),version text NOT NULL,method text NOT NULL,route text NOT NULL,request_schema_hash text NOT NULL,response_schema_hash text NOT NULL,deprecated_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(version,method,route));
CREATE TABLE IF NOT EXISTS trust_policy_decisions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid REFERENCES trust_tenants(id) ON DELETE CASCADE,actor_id uuid REFERENCES trust_users(id) ON DELETE SET NULL,action text NOT NULL,resource_type text NOT NULL,resource_id text,effect text NOT NULL CHECK(effect IN ('allow','deny')),policy_version integer NOT NULL CHECK(policy_version>0),policy_fingerprint text NOT NULL,request_id text,decided_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS trust_policy_decisions_tenant_time_idx ON trust_policy_decisions(tenant_id,decided_at DESC);
CREATE TABLE IF NOT EXISTS trust_outbox_deliveries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),outbox_event_id uuid NOT NULL,destination text NOT NULL,attempt integer NOT NULL DEFAULT 0 CHECK(attempt>=0),state text NOT NULL CHECK(state IN ('PENDING','DELIVERED','RETRYING','DEAD')) DEFAULT 'PENDING',next_attempt_at timestamptz NOT NULL DEFAULT now(),delivered_at timestamptz,last_error text,UNIQUE(outbox_event_id,destination));
CREATE INDEX IF NOT EXISTS trust_outbox_delivery_due_idx ON trust_outbox_deliveries(state,next_attempt_at);
CREATE TABLE IF NOT EXISTS trust_data_governance_rules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid REFERENCES trust_tenants(id) ON DELETE CASCADE,data_class text NOT NULL CHECK(data_class IN ('PUBLIC','INTERNAL','CONFIDENTIAL','RESTRICTED')),retention_days integer NOT NULL CHECK(retention_days BETWEEN 1 AND 36500),legal_hold_allowed boolean NOT NULL DEFAULT true,version integer NOT NULL DEFAULT 1 CHECK(version>0),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,data_class,version));
CREATE TABLE IF NOT EXISTS trust_incidents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),severity text NOT NULL CHECK(severity IN ('SEV0','SEV1','SEV2','SEV3')),status text NOT NULL CHECK(status IN ('OPEN','MITIGATING','RESOLVED')) DEFAULT 'OPEN',started_at timestamptz NOT NULL DEFAULT now(),resolved_at timestamptz,owner text,summary text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS trust_release_provenance (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),version text NOT NULL UNIQUE,source_commit text,sbom_sha256 text NOT NULL,migration_manifest_sha256 text NOT NULL,tests_passed integer NOT NULL CHECK(tests_passed>=0),tests_failed integer NOT NULL CHECK(tests_failed>=0),approved_by text,approved_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
