'use client';
import {useEffect,useState} from 'react';
export default function GlobalCommerceControlPlane(){
 const [data,setData]=useState<any>(); const [incidents,setIncidents]=useState<any[]>([]); const [error,setError]=useState('');
 const load=()=>Promise.all([fetch('/api/commerce/control-plane',{cache:'no-store'}).then(r=>r.json()),fetch('/api/commerce/control-plane?view=incidents',{cache:'no-store'}).then(r=>r.json())]).then(([a,b])=>{if(!a.ok)throw new Error(a.message||a.error);setData(a);setIncidents(b.incidents||[])}).catch(e=>setError(e.message));
 useEffect(()=>{load()},[]);
 if(error)return <main style={{padding:40,fontFamily:'system-ui'}}><h1>TRUST Global Commerce Control Plane</h1><p>{error}</p></main>;
 if(!data)return <main style={{padding:40,fontFamily:'system-ui'}}><h1>Global Commerce Control Plane</h1><p>Loading live cross-domain state…</p></main>;
 const cards=[['Orders',data.domains.orders],['Payments',data.domains.payments],['Inventory',data.domains.inventory],['Fulfillment',data.domains.fulfillment],['Delivery',data.domains.shipments],['Seller Orders',data.domains.sellerOrders],['Revenue',data.domains.revenue],['Events',data.domains.events],['Execution',data.domains.execution]];
 return <main style={{minHeight:'100vh',background:'#06101c',color:'#eef6ff',padding:32,fontFamily:'system-ui'}}><div style={{maxWidth:1500,margin:'auto'}}>
  <header style={{display:'flex',justifyContent:'space-between',gap:20,alignItems:'end',marginBottom:24}}><div><div style={{fontSize:13,opacity:.6}}>TRUST APEX OS • V375</div><h1 style={{fontSize:40,margin:'5px 0'}}>Global Commerce Control Plane</h1><p style={{opacity:.7}}>Cross-domain operational coordination over the existing commerce authorities.</p></div><div style={{padding:'10px 15px',borderRadius:12,background:data.health==='HEALTHY'?'#12351f':'#3a2911'}}>{data.health}</div></header>
  <section style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:14,marginBottom:18}}>{[['Stale consumer work',data.staleWork.consumerDeliveries],['Stale execution jobs',data.staleWork.executionJobs],['Verified recoveries 24h',data.commerce.verifiedRecoveries24h]].map(([k,v])=><div key={k as string} style={{background:'#0c1a2b',border:'1px solid #1b324b',borderRadius:15,padding:18}}><div style={{opacity:.6}}>{k}</div><strong style={{fontSize:28}}>{v}</strong></div>)}</section>
  <section style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:12}}>{cards.map(([k,v])=><div key={k as string} style={{background:'#0c1a2b',border:'1px solid #1b324b',borderRadius:14,padding:16}}><b>{k}</b><div style={{fontSize:24,margin:'7px 0'}}>{v.count}</div><small style={{opacity:.6,wordBreak:'break-word'}}>{JSON.stringify(v.statuses)}</small></div>)}</section>
  <section style={{marginTop:18,background:'#0c1a2b',border:'1px solid #1b324b',borderRadius:15,padding:20}}><h2 style={{marginTop:0}}>Active incidents</h2>{incidents.length?incidents.map(x=><div key={x.id} style={{padding:'12px 0',borderTop:'1px solid #1b324b'}}><b>{x.code}</b> — order <code>{x.orderId}</code><div style={{opacity:.65,fontSize:13}}>stale consumer: {x.evidence.staleConsumer}; stale execution: {x.evidence.staleExecution}</div></div>):<p>No stale-work incidents are currently visible.</p>}</section>
  <section style={{marginTop:18,background:'#0c1a2b',border:'1px solid #1b324b',borderRadius:15,padding:20}}><h2 style={{marginTop:0}}>Command boundary</h2>{data.commands.map((c:any)=><div key={c.id} style={{padding:'10px 0',borderTop:'1px solid #1b324b'}}><b>{c.title}</b> <span style={{opacity:.55}}>risk={c.risk}</span><div style={{fontSize:13,opacity:.65}}>{c.description} {c.mutationBoundary}</div></div>)}</section>
  <footer style={{marginTop:22,opacity:.5,fontSize:12}}>Read model + bounded coordination only. Existing payment, inventory, order, fulfillment and revenue modules remain authoritative.</footer>
 </div></main>;
}
