import type {CommerceEvent,DeadLetterEvent,EventDelivery,EventEnvelope,EventHandler,EventHandlerResult,EventPolicy,EventStatus,ReplayResult,Subscription} from './contracts.ts';
const clone=<T>(x:T):T=>JSON.parse(JSON.stringify(x));
export class EventDrivenExecutionFabric{
 private readonly events:EventEnvelope[]=[]; private readonly byId=new Map<string,EventEnvelope>(); private readonly subscriptions=new Map<string,Subscription>(); private readonly deliveries=new Set<string>(); private readonly effects=new Set<string>(); private readonly deadLetters:DeadLetterEvent[]=[]; private readonly nextSequence=new Map<string,number>();
 append<T extends Record<string,unknown>>(event:CommerceEvent<T>,policy:EventPolicy):EventEnvelope{if(!event.eventId||!event.tenantId||!event.type||!event.aggregateId)throw new Error('EVENT_IDENTITY_REQUIRED');if(policy.maxPayloadBytes<1||policy.maxAttempts<1)throw new Error('INVALID_EVENT_POLICY');if(this.byId.has(event.eventId))return clone(this.byId.get(event.eventId)!);const key=`${event.tenantId}:${event.aggregateId}`;const expected=this.nextSequence.get(key)??1;if(policy.strictOrdering&&event.sequence!==expected)throw new Error(`EVENT_SEQUENCE_GAP:${expected}`);if(event.sequence<1)throw new Error('EVENT_SEQUENCE_INVALID');const envelope:EventEnvelope={...clone(event),attempts:0,status:'APPENDED'};const bytes=JSON.stringify(envelope.payload).length;if(bytes>policy.maxPayloadBytes)throw new Error('EVENT_PAYLOAD_TOO_LARGE');this.nextSequence.set(key,event.sequence+1);this.events.push(envelope);this.byId.set(event.eventId,envelope);return clone(envelope);}
 subscribe(sub:Subscription){if(!sub.consumerId||!sub.eventTypes.length)throw new Error('SUBSCRIPTION_INVALID');if(this.subscriptions.has(sub.consumerId))throw new Error('CONSUMER_ALREADY_REGISTERED');this.subscriptions.set(sub.consumerId,sub);}
 snapshot():EventEnvelope[]{return this.events.map(clone)}
 deadLettersSnapshot():DeadLetterEvent[]{return this.deadLetters.map(clone)}
 async deliver(eventId:string,consumerId:string,policy:EventPolicy):Promise<EventDelivery>{const event=this.byId.get(eventId);const sub=this.subscriptions.get(consumerId);if(!event||!sub)throw new Error('EVENT_OR_CONSUMER_NOT_FOUND');if(!sub.eventTypes.includes('*')&&!sub.eventTypes.includes(event.type))return {eventId,tenantId:event.tenantId,consumerId,status:'SKIPPED',attempts:0,reason:'Event type not subscribed.'};const deliveryKey=`${consumerId}:${event.tenantId}:${event.eventId}`;if(this.deliveries.has(deliveryKey))return {eventId,tenantId:event.tenantId,consumerId,status:'DUPLICATE',attempts:0};let last='Handler failed.';for(let attempt=1;attempt<=policy.maxAttempts;attempt++){event.attempts=attempt;let result:EventHandlerResult;try{result=await sub.handler(clone(event));}catch(e){result={status:'RETRY',reason:e instanceof Error?e.message:'Handler failed.'};}last=result.reason||last;if(result.status==='SUCCESS'||result.status==='DROP'){if(result.effectKey){if(this.effects.has(`${event.tenantId}:${result.effectKey}`)){this.deliveries.add(deliveryKey);event.status='PROCESSED';return {eventId,tenantId:event.tenantId,consumerId,status:'DUPLICATE',attempts:attempt,reason:'Business effect already applied.'};}this.effects.add(`${event.tenantId}:${result.effectKey}`);}this.deliveries.add(deliveryKey);event.status='PROCESSED';return {eventId,tenantId:event.tenantId,consumerId,status:'PROCESSED',attempts:attempt,reason:result.reason};}}
const dl={event:clone(event),consumerId,reason:last,createdAt:Date.now()};this.deadLetters.push(dl);event.status='DEAD_LETTERED';return {eventId,tenantId:event.tenantId,consumerId,status:'DEAD_LETTERED',attempts:policy.maxAttempts,reason:last};}
 async publish(eventId:string,policy:EventPolicy):Promise<EventDelivery[]>{const subs=[...this.subscriptions.keys()];const out:EventDelivery[]=[];for(const id of subs)out.push(await this.deliver(eventId,id,policy));return out;}
 async replay(filter:(event:EventEnvelope)=>boolean,policy:EventPolicy):Promise<ReplayResult>{const selected=this.events.filter(filter);let replayed=0,skipped=0;for(const event of selected){for(const id of this.subscriptions.keys()){this.deliveries.delete(`${id}:${event.tenantId}:${event.eventId}`);const r=await this.deliver(event.eventId,id,policy);if(r.status==='PROCESSED'||r.status==='DUPLICATE')replayed++;else skipped++;}event.status='REPLAYED';}return {requested:selected.length,replayed,skipped};}
}
