import type { AgentId, AgentRisk } from './contracts';
import { TRUST_VERSION } from '../../lib/runtime/version';
import { query, withPgTransaction } from '../platform/db/postgres';
export type AgentControlState='RUNNING'|'PAUSED'|'KILLED';
export type ControlScope='GLOBAL_KILL_SWITCH'|'AGENT_KILL'|'SERVICE_FREEZE'|'TENANT_ISOLATION'|'ROLLOUT_FREEZE';
export type ApprovalState='NOT_REQUIRED'|'PENDING'|'APPROVED'|'REJECTED';
export interface AgentBudget{agentId:AgentId;dailyTokens:number;dailyExecutions:number;maxExecutionRisk:AgentRisk;}
export interface AgentPolicy{agentId:AgentId;state:AgentControlState;allowedTools:string[];maxRisk:AgentRisk;approvalFor:string[];rateLimitPerMinute:number;}
export interface AgentMessage{id:string;from:AgentId;to:AgentId;type:'REQUEST'|'RESULT'|'ESCALATION';task:string;createdAt:string;}
const budgets:AgentBudget[]=[{agentId:'pricing',dailyTokens:12000,dailyExecutions:40,maxExecutionRisk:'HIGH'},{agentId:'inventory',dailyTokens:12000,dailyExecutions:80,maxExecutionRisk:'MEDIUM'},{agentId:'customer',dailyTokens:10000,dailyExecutions:60,maxExecutionRisk:'MEDIUM'},{agentId:'growth',dailyTokens:14000,dailyExecutions:30,maxExecutionRisk:'HIGH'},{agentId:'risk',dailyTokens:18000,dailyExecutions:100,maxExecutionRisk:'CRITICAL'},{agentId:'logistics',dailyTokens:12000,dailyExecutions:70,maxExecutionRisk:'HIGH'}];
const defaults:AgentPolicy[]=[{agentId:'pricing',state:'RUNNING',allowedTools:['catalog.read','pricing.simulate'],maxRisk:'HIGH',approvalFor:['pricing.write'],rateLimitPerMinute:12},{agentId:'inventory',state:'RUNNING',allowedTools:['inventory.read','inventory.simulate'],maxRisk:'MEDIUM',approvalFor:['inventory.write'],rateLimitPerMinute:20},{agentId:'customer',state:'RUNNING',allowedTools:['customer.segment','campaign.simulate'],maxRisk:'MEDIUM',approvalFor:['campaign.send'],rateLimitPerMinute:15},{agentId:'growth',state:'RUNNING',allowedTools:['analytics.read','experiment.simulate'],maxRisk:'HIGH',approvalFor:['campaign.spend','experiment.publish'],rateLimitPerMinute:8},{agentId:'risk',state:'RUNNING',allowedTools:['risk.read','risk.flag'],maxRisk:'CRITICAL',approvalFor:['account.block'],rateLimitPerMinute:30},{agentId:'logistics',state:'RUNNING',allowedTools:['shipment.read','routing.simulate'],maxRisk:'HIGH',approvalFor:['shipment.reroute'],rateLimitPerMinute:18}];
async function ensurePolicies(){await query(`insert into trust_v144_global_controls(control_id) values('default') on conflict(control_id) do nothing`);for(const p of defaults)await query(`insert into trust_agent_policies(agent_id,state,allowed_tools,max_risk,approval_for,rate_limit_per_minute) values($1,$2,$3,$4,$5,$6) on conflict(agent_id) do nothing`,[p.agentId,p.state,JSON.stringify(p.allowedTools),p.maxRisk,JSON.stringify(p.approvalFor),p.rateLimitPerMinute]);}
export async function controlSnapshot(){await ensurePolicies();const [pol,ms,ap,global]=await Promise.all([query(`select agent_id,state,allowed_tools,max_risk,approval_for,rate_limit_per_minute from trust_agent_policies order by agent_id`),query(`select id,from_agent,to_agent,message_type,task,created_at from trust_agent_messages order by created_at desc limit 30`),query(`select id,state from trust_agent_approvals order by updated_at desc limit 100`),query(`select global_kill_switch,service_freeze,tenant_isolation,rollout_freeze from trust_v144_global_controls where control_id='default'`)]);const g=global.rows[0]||{};return{version:TRUST_VERSION,globalKillSwitch:Boolean(g.global_kill_switch),killSwitch:Boolean(g.global_kill_switch),policies:pol.rows.map((r:any)=>({agentId:r.agent_id,state:r.state,allowedTools:r.allowed_tools,maxRisk:r.max_risk,approvalFor:r.approval_for,rateLimitPerMinute:Number(r.rate_limit_per_minute)})),budgets,messages:ms.rows.reverse().map((r:any)=>({id:String(r.id),from:r.from_agent,to:r.to_agent,type:r.message_type,task:r.task,createdAt:new Date(r.created_at).toISOString()})),approvals:Object.fromEntries(ap.rows.map((r:any)=>[String(r.id),r.state]))};}
export async function setKillSwitch(enabled:boolean){return withPgTransaction(async client=>{await ensurePolicies();await client.query(`update trust_v144_global_controls set global_kill_switch=$1,updated_at=now() where control_id='default'`,[enabled]);return controlSnapshot();});}
export async function setAgentState(agentId:AgentId,state:AgentControlState){await ensurePolicies();const r=await query(`update trust_agent_policies set state=$2,updated_at=now() where agent_id=$1 returning agent_id,state,allowed_tools,max_risk,approval_for,rate_limit_per_minute`,[agentId,state]);if(!r.rows[0])return null;return{agentId:r.rows[0].agent_id,state:r.rows[0].state,allowedTools:r.rows[0].allowed_tools,maxRisk:r.rows[0].max_risk,approvalFor:r.rows[0].approval_for,rateLimitPerMinute:Number(r.rows[0].rate_limit_per_minute)} as AgentPolicy;}
export async function requestApproval(id:string){await query(`insert into trust_agent_approvals(id,state,updated_at) values($1,'PENDING',now()) on conflict(id) do update set state='PENDING',updated_at=now()`,[id]);return'PENDING' as const;}
export async function resolveApproval(id:string,approved:boolean){const r=await query(`update trust_agent_approvals set state=$2,resolved_at=now(),updated_at=now() where id=$1 returning state`,[id,approved?'APPROVED':'REJECTED']);return r.rows[0]?.state as ApprovalState|undefined;}
export async function sendMessage(from:AgentId,to:AgentId,task:string,type:AgentMessage['type']='REQUEST'){const r=await query(`insert into trust_agent_messages(id,from_agent,to_agent,message_type,task) values($1,$2,$3,$4,$5) returning id,from_agent,to_agent,message_type,task,created_at`,[crypto.randomUUID(),from,to,type,task]);const x=r.rows[0];return{id:String(x.id),from:x.from_agent,to:x.to_agent,type:x.message_type,task:x.task,createdAt:new Date(x.created_at).toISOString()};}
export async function authorize(agentId:AgentId,tool:string,risk:AgentRisk){await ensurePolicies();const r=await query(`select state,allowed_tools,max_risk from trust_agent_policies where agent_id=$1`,[agentId]);const [gq]=await Promise.all([query(`select global_kill_switch from trust_v144_global_controls where control_id='default'`)]);const p=r.rows[0];if(!p)return{allowed:false,reason:'AGENT_NOT_FOUND'};if(Boolean(gq.rows[0]?.global_kill_switch))return{allowed:false,reason:'GLOBAL_KILL_SWITCH'};if(p.state==='KILLED')return{allowed:false,reason:'AGENT_KILL'};if(p.state==='PAUSED')return{allowed:false,reason:'AGENT_PAUSED'};if(!Array.isArray(p.allowed_tools)||!p.allowed_tools.includes(tool))return{allowed:false,reason:'TOOL_SCOPE_DENIED'};const rank={LOW:1,MEDIUM:2,HIGH:3,CRITICAL:4};if(rank[risk]>rank[p.max_risk as AgentRisk])return{allowed:false,reason:'RISK_CAP_EXCEEDED'};return{allowed:true,reason:'AUTHORIZED'};}
