from pathlib import Path
r=Path('/mnt/data/v360work')
mods={
'modules/platform/financial-commerce/core.ts':r'''export type Fee={feeId:string;name:string;basis:'GMV'|'SHIPPING';rateBps:number;fixedMinor:bigint;active:boolean};
export function calculateFees(gmvMinor:bigint,shippingMinor:bigint,fees:Fee[]){return fees.filter(f=>f.active).map(f=>{const base=f.basis==='GMV'?gmvMinor:shippingMinor;return {...f,amountMinor:base*BigInt(f.rateBps)/10000n+f.fixedMinor};});}
export function computeUnitEconomics(x:any){const variableCostMinor=x.productCostMinor+x.fulfillmentMinor+x.paymentMinor+x.marketplaceFeeMinor+x.adMinor+x.returnsReserveMinor+x.taxMinor+x.otherVariableMinor;return {...x,variableCostMinor,contributionMinor:x.priceMinor-variableCostMinor,breakEvenPriceMinor:variableCostMinor};}
export function createBalancedJournal(id:string,currency:string,description:string,entries:any[]){const d=entries.filter(e=>e.side==='DEBIT').reduce((a,e)=>a+e.amountMinor,0n),c=entries.filter(e=>e.side==='CREDIT').reduce((a,e)=>a+e.amountMinor,0n);if(d!==c)throw new Error('unbalanced');return {id,currency,description,entries,balanced:true};}
export function buildPayout(id:string,sellerId:string,currency:string,grossMinor:bigint,feesMinor:bigint,refundReserveMinor:bigint,holdMinor:bigint,status:string){return {id,sellerId,currency,grossMinor,feesMinor,refundReserveMinor,holdMinor,netMinor:grossMinor-feesMinor-refundReserveMinor-holdMinor,status};}
export function runWhatIf(input:any,priceDelta:bigint,productCostDelta:bigint,fulfillmentDelta:bigint){const x={...input,priceMinor:input.priceMinor+priceDelta,productCostMinor:input.productCostMinor+productCostDelta,fulfillmentMinor:input.fulfillmentMinor+fulfillmentDelta};return {input,result:computeUnitEconomics(x)};}
''',
'modules/platform/growth-ads/core.ts':r'''export function rankAds(c:any[]){return c.map(x=>({...x,eligible:x.budgetRemainingMinor>0})).sort((a,b)=>Number(b.eligible)-Number(a.eligible)||(b.relevance+b.quality)- (a.relevance+a.quality)||Number(b.bidMinor-a.bidMinor));}
export function campaignInsight(c:any){const utilization=c.budgetMinor===0n?0:Number(c.spentMinor*100n/c.budgetMinor);return {...c,utilization,pacing:utilization>100?'OVER':utilization<80?'ON_TRACK':'AT_CAP'};}
''',
'modules/platform/recommerce/core.ts':r'''export function priceReturnedItem(x:any,basePriceMinor:bigint){const multipliers:any={NEW:1,LIKE_NEW:.82,GOOD:.68,FAIR:.5};const m=multipliers[x.condition]??.4;const agePenalty=Math.min(.2,x.ageDays*.005);const price=BigInt(Math.round(Number(basePriceMinor)*Math.max(.1,m-agePenalty)));return {...x,disposition:x.condition==='FAIR'||x.condition==='DAMAGED'?'LIQUIDATION':'RESALE',offers:[{productId:x.productId,priceMinor:price}]};}
''',
'modules/platform/super-commerce/index.ts':r'''export function addToCart(cart:any,line:any){const lines=cart.lines.map((x:any)=>x.productId===line.productId&&x.offerId===line.offerId?{...x,quantity:x.quantity+line.quantity}:x);if(!lines.some((x:any)=>x.productId===line.productId&&x.offerId===line.offerId))lines.push({...line});return {...cart,lines,updatedAt:new Date().toISOString()};}
export function applyCoupon(cart:any,c:any){if(!c.active||c.used>0)return {amountMinor:0n,totalMinor:cart.lines.reduce((s:any,x:any)=>s+x.unitPriceMinor*BigInt(x.quantity),0n)};const subtotal=cart.lines.reduce((s:any,x:any)=>s+x.unitPriceMinor*BigInt(x.quantity),0n);const amount=c.kind==='PERCENT'?subtotal*BigInt(Math.min(100,Math.max(0,c.value)))/100n:BigInt(c.value);return {amountMinor:amount,totalMinor:subtotal-amount};}
export function grantLoyalty(a:any,points:bigint){const p=a.points+Number(points);return {...a,points:p,tier:p>=2500?'PLUS':p>=5000?'PREMIUM':a.tier};}
export function redeemLoyalty(a:any,points:number){if(points>a.points)throw new Error('INSUFFICIENT_POINTS');const multiplier=a.tier==='PREMIUM'?11:a.tier==='PLUS'?10.5:10;return {account:{...a,points:a.points-points},discountMinor:BigInt(Math.round(points*multiplier))};}
export function selectBestDeal(ds:any[],currency:string,now:Date){return ds.filter(d=>d.currency===currency&&d.active&&d.stock>0&&new Date(d.startsAt)<=now&&new Date(d.endsAt)>=now).sort((a,b)=>a.priceMinor<b.priceMinor?-1:a.priceMinor>b.priceMinor?1:0)[0];}
export function reviewInsights(rs:any[]){const avg=rs.length?rs.reduce((s,r)=>s+r.rating,0)/rs.length:0;const verified=rs.length?rs.filter(r=>r.verifiedPurchase).length/rs.length:0;return {averageRating:avg,verifiedRatio:verified,positive:rs.filter(r=>r.rating>=4),negative:rs.filter(r=>r.rating<=2)};}
export function sellerTrust(x:any){const score=Math.max(0,Math.min(100,x.rating/5*60+(1-x.cancelRate)*15+(1-x.lateRate)*10+(1-x.disputeRate)*10+(x.verified?5:0)));return {...x,score,band:score>=85?'EXCELLENT':score>=70?'GOOD':score>=50?'WATCH':'RISK'};}
export function buyAgain(lines:any[],available:Set<string>){return lines.filter(x=>available.has(x.offerId));}
export function smartBundle(lines:any[],discountPct:number){const subtotal=lines.reduce((s,x)=>s+x.unitPriceMinor*BigInt(x.quantity),0n);const discount=subtotal*BigInt(discountPct)/100n;return {subtotalMinor:subtotal,discountMinor:discount,totalMinor:subtotal-discount};}
''',
'modules/platform/commerce-growth-os/core.ts':r'''export function rankBuyBox(xs:any[]){return xs.filter(x=>x.stock>0).map(x=>({...x,offerId:x.id,score:100000-Number(x.priceMinor+x.shippingMinor)+x.rating*100+x.deliveryScore+x.merchantScore})).sort((a,b)=>b.score-a.score);}
export function selectDeal(price:bigint,original:bigint,minDiscount:number){const pct=Number((original-price)*100n/original);return {eligible:pct>=minDiscount,discountPct:pct};}
export function subscriptionSchedule(days:number,start:string){if(days<7||!/^\d{4}-\d{2}-\d{2}$/.test(start))throw new Error('INVALID_SUBSCRIPTION_INTERVAL');return {intervalDays:days,start,customerCancelable:true};}
export function reorderScore(days:number,threshold:number,stock:number){return stock<=0?0:Math.max(0,Math.min(100,Math.round((days/Math.max(1,threshold))*100)));}
export function referralReward(base:bigint,pct:number,cap:bigint){const r=base*BigInt(pct)/100n;return r>cap?cap:r;}
export function revenuePlan(events:any[]){const bySurface:any={};for(const e of events)bySurface[e.surface]=(bySurface[e.surface]??0n)+e.amountMinor;return {totalMinor:Object.values(bySurface).reduce((a:any,b:any)=>a+b,0n),bySurface};}
export function buildGrowthPlan(x:any){const a=[{capability:'DEALS',score:x.inventoryRisk,monetizable:true},{capability:'ADVERTISING',score:x.adDemand,monetizable:true},{capability:'REORDER',score:x.repeatRate,monetizable:true},{capability:'B2B',score:x.b2bDemand,monetizable:true},{capability:'CROSS_BORDER',score:x.crossBorderDemand,monetizable:true}];return a.sort((u,v)=>v.score-u.score);}
''',
'modules/platform/growth-network/core.ts':r'''export function buildGrowthNetwork({products,orders}:any){const delivered=orders.filter((o:any)=>o.status==='delivered');const customers=[...new Set(delivered.map((o:any)=>o.customerId))];const counts=new Map<string,number>();delivered.forEach((o:any)=>counts.set(o.customerId,(counts.get(o.customerId)||0)+1));const repeatCustomers=customers.filter(c=>(counts.get(c)||0)>1);const pairs:any[]=[];for(const o of delivered){for(const a of o.items||[]){for(const b of o.items||[]){if(a.productId!==b.productId)pairs.push({fromProductId:a.productId,toProductId:b.productId,count:1});}}}const agg=new Map<string,any>();for(const p of pairs){const k=p.fromProductId+'>'+p.toProductId;agg.set(k,{...p,count:(agg.get(k)?.count||0)+1});}return {customers:customers.length,repeatCustomers:repeatCustomers.length,repeatRate:customers.length?repeatCustomers.length*100/customers.length:0,reorderCandidates:repeatCustomers.map(customerId=>({customerId,reason:'repeat_purchase'})),crossSellPairs:[...agg.values()],signals:[{id:'REORDER_LOOP',monetizable:true,guardrail:'requires observed purchase history'}],revenue:delivered.reduce((s:number,o:any)=>s+o.total,0),aov:delivered.length?delivered.reduce((s:number,o:any)=>s+o.total,0)/delivered.length:0};}
''',
'modules/platform/trust-commerce-network/core.ts':r'''export function recommendTier(x:any){if(x.orders>=10&&x.repeatRate>=60&&x.monthlySpend>=5000)return 'PRO';if(x.orders>=3||x.repeatRate>=30||x.monthlySpend>=1000)return 'PLUS';return 'FREE';}
export function buildNetworkPlan(x:any){const opportunities=[['REORDER','Increase observed repeat demand'],['B2B','Offer business purchasing tools'],['CATALOG','Improve catalog coverage'],['PRO','Surface higher-tier capabilities']].map(([action,reason],i)=>({action,reason,score:Math.min(100,Math.max(0,(x.orders||0)*5+(x.repeatRate||0)/2+i*3))}));return {version:'V208',opportunities,guardrails:['لا تخترع توفير نقدي','لا تنفذ دفعًا تلقائيًا'],unavailable:['cashback promises require a funded program']};}
''',
'modules/platform/commerce-ai-copilot/core.ts':r'''export function classifyCopilot(message:string,mode='SHOP'){const m=message.toLowerCase();let intent='SEARCH';if(/قارن|compare/.test(m))intent='COMPARE';else if(/ارجع|استرداد|return|refund/.test(m))intent='RETURN';else if(/مخزون|inventory|تاجر/.test(m))intent='INVENTORY';return {mode:/تاجر|مخزون|inventory|seller/.test(m)?'SELL':mode,intent,confidence:intent==='SEARCH'?75:90};}
export function buildCommerceAiCopilot({message,products}:any){const c=classifyCopilot(message);const actions:any[]=[];if(c.intent==='COMPARE')actions.push({id:'compare',target:'/compare',requiresApproval:false});if(c.intent==='RETURN')actions.push({id:'problem',target:'/problem-center',requiresApproval:false});if(c.intent==='INVENTORY')actions.push({id:'inventory',target:'/seller-super-os',requiresApproval:false});if(!actions.length)actions.push({id:'search',target:'/search',requiresApproval:false});return {version:'V207',mode:c.mode,intent:c.intent,confidence:c.confidence,products,actions,signals:[{id:'intent',value:c.intent}],guardrails:c.intent==='RETURN'?['الاسترداد يحتاج تنفيذًا عبر مسار الطلب وليس copilot']:['لا ينفذ copilot عمليات مالية حساسة'];};}
''',
'modules/platform/global-commerce-graph/core.ts':r'''export function buildGlobalCommerceGraph(x:any){const nodes:any[]=[];const edges:any[]=[];for(const p of x.products||[])nodes.push({id:'p:'+p.id,type:'PRODUCT',label:p.name});for(const o of x.orders||[]){nodes.push({id:'c:'+o.customerId,type:'CUSTOMER'});for(const i of o.items||[])edges.push({from:'c:'+o.customerId,to:'p:'+i.productId,type:'PURCHASED'});const ids=(o.items||[]).map((i:any)=>i.productId);for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++)edges.push({from:'p:'+ids[i],to:'p:'+ids[j],type:'CO_PURCHASED'});}for(const p of x.problems||[])edges.push({from:'c:'+p.customerId,to:'p:'+p.productId,type:'HAS_PROBLEM'});const connected=new Set(edges.flatMap(e=>[e.from,e.to]));const orphan=(x.products||[]).filter((p:any)=>!connected.has('p:'+p.id)).length;const opportunities=edges.some(e=>e.type==='CO_PURCHASED')?[{id:'CO_PURCHASE_GRAPH',monetizable:true,guardrail:'recommendation only',action:'surface related products'}]:[];return {version:'V210',nodes,edges,edgeCount:edges.length,health:{orphanProducts:orphan},opportunities};}
''',
'modules/platform/commerce-brain/core.ts':r'''export function createBrainEvent(type:string,tenantId:string,aggregateId:string,payload:any,version:number,idempotencyKey:string){return {eventId:crypto.randomUUID(),type,occurredAt:new Date().toISOString(),tenantId,aggregateId,version,payload,idempotencyKey};}
export function deriveCommerceBrain(events:any[],now:string){const seen=new Set<string>(),signals:any[]=[],accepted:any[]=[];for(const e of events){if(seen.has(e.idempotencyKey))continue;seen.add(e.idempotencyKey);accepted.push(e);const age=Date.parse(now)-Date.parse(e.occurredAt);const status=age>30*60*1000?'UNKNOWN':'FRESH';if(e.type==='STOCK_CHANGED')signals.push({type:'STOCK_RISK',status,confidence:status==='FRESH'?90:0,payload:e.payload});else if(e.type==='PRICE_CHANGED')signals.push({type:'PRICE_RISK',status,confidence:status==='FRESH'?90:0,payload:e.payload});else if(e.type==='PROBLEM_CREATED')signals.push({type:'PROBLEM_RISK',status,confidence:status==='FRESH'?80:0,payload:e.payload});}return {version:'V211',acceptedEvents:accepted.length,duplicateEvents:events.length-accepted.length,signals,health:{fresh:signals.every(s=>s.status==='FRESH'),unknownCount:signals.filter(s=>s.status==='UNKNOWN').length},actions:signals.map(s=>({type:s.type,requiresApproval:false})),guardrails:['لا يوجد دفع تلقائي من Commerce Brain']};}
''',
'modules/platform/autonomous-commerce-control-plane/core.ts':r'''import {deriveCommerceBrain} from '../../commerce-brain/core.ts';
export function runControlPlaneCycle(events:any[],now:string,policy:any={}){const b=deriveCommerceBrain(events,now);if(b.signals.some(s=>s.status==='UNKNOWN'))return {version:'V212',decisions:[],executionIntents:[],reconciliation:[],learning:[{outcome:'RECALIBRATE'}]};const decisions:any[]=[],intents:any[]=[],recon:any[]=[];for(const s of b.signals){const confidence=s.confidence??0;const risk=s.type==='PROBLEM_RISK'?80:40;const action=s.type==='PRICE_RISK'?'MARKET_REVIEW':null;const authorized=!!policy.enabled&&!!action&&policy.autoActions?.includes(action)&&risk<= (policy.maxRisk??0)&&confidence>=(policy.minConfidence??101);const status=authorized?'AUTHORIZED':(risk>(policy.maxRisk??0)||confidence<(policy.minConfidence??101)?'BLOCKED':'APPROVAL_REQUIRED');decisions.push({signal:s,status});intents.push({status:authorized?'READY':status==='BLOCKED'?'BLOCKED':'PENDING_APPROVAL'});recon.push({status:authorized?'AWAITING_PROVIDER':'NO_EXTERNAL_SIDE_EFFECT',expected:authorized?'EXTERNAL_PROVIDER':'NO_EXTERNAL_SIDE_EFFECT'});}return {version:'V212',decisions,executionIntents:intents,reconciliation:recon,learning:[]};}
''',
'modules/platform/autonomous-commerce-runtime/index.ts':r'''import {runControlPlaneCycle} from '../../autonomous-commerce-control-plane/core.ts';
export async function runAutonomousCommerceRuntime(events:any[],now:string,policy:any={},adapter?:any){const cp=runControlPlaneCycle(events,now,policy);const dispatches:any[]=[],commands:any[]=[];for(const i of cp.executionIntents){const e=events[dispatches.length];const commandId='cmd:'+e.idempotencyKey;commands.push({commandId,idempotencyKey:e.idempotencyKey});if(i.status==='READY'){if(!adapter||!adapter.actions?.includes('PRICE'))dispatches.push({status:'NOT_DISPATCHED',reason:'ADAPTER_NOT_FOUND_FOR_ACTION'});else {const r=await adapter.execute(e);dispatches.push({status:'EXECUTED',providerReference:r.providerReference});}}else dispatches.push({status:i.status==='PENDING_APPROVAL'?'APPROVAL_REQUIRED':'NOT_DISPATCHED',reason:i.status});}return {version:'V213',dispatches,commands};}
''',
'modules/platform/autonomous-commerce-orchestrator/index.ts':r'''import {runAutonomousCommerceRuntime} from '../../autonomous-commerce-runtime/index.ts';
export class AutonomousCommerceOrchestrator{seen=new Set<string>();accepted=0;async ingest(event:any,policy:any={tenantId:event.tenantId,enabled:false},opts:any={}){const duplicate=this.seen.has(event.eventId);if(!duplicate){this.seen.add(event.eventId);this.accepted++;}const runtime=duplicate?await runAutonomousCommerceRuntime([],new Date().toISOString(),policy,opts.runtime?.adapter):await runAutonomousCommerceRuntime([event],new Date(event.occurredAt).toISOString(),policy,opts.runtime?.adapter);return {event,deliveries:[{status:'PROCESSED'}],runtime};}snapshot(){return {accepted:this.accepted};}}
''',
'modules/platform/revenue-autopilot/index.ts':r'''export function buildRevenueAutopilotPlan(x:any){return ['QUOTE','COMMISSION','FULFILLMENT','SUBSCRIPTION','ADS','B2B'].map(action=>({action,score:100}));}
export async function runRevenueAutopilot(x:any){const base=x.meter.baseMinor??x.meter.fixedMinor??0n;const amount=x.meter.rateBps?base*BigInt(x.meter.rateBps)/10000n:BigInt(x.meter.fixedMinor??0n);const hasEvidence=!!x.evidenceId;return {charge:{amountMinor:amount,status:x.mode==='POST'&&hasEvidence?'POSTED':'QUOTED',evidenceId:hasEvidence?x.evidenceId:undefined},financialSideEffect:false,opportunity:x.mode==='POST'&&!hasEvidence?{status:'BLOCKED'}:undefined};}
''',
'modules/platform/revenue-intelligence/index.ts':r'''export function estimateRevenueEconomics(x:any){const grossRevenueMinor=BigInt(x.eligibleUnits)*x.averageChargeMinor;const variableCostMinor=grossRevenueMinor*BigInt(x.variableCostBps)/10000n;const contributionMinor=grossRevenueMinor-variableCostMinor;const score=(x.demandScore+x.conversionScore+x.retentionScore+x.operationalScore-x.riskScore+x.evidenceCoverage)/5;return {...x,grossRevenueMinor,variableCostMinor,contributionMinor,score};}
export function buildRevenueScenarios(x:any){return Array.from({length:x.steps},(_,i)=>{const rate=Math.round(x.baseRateBps*(1+(i-(x.steps-1)/2)*.1));const avg=x.averageBaseMinor;const gross=BigInt(x.eligibleUnits)*avg*BigInt(rate)/BigInt(x.baseRateBps);const cost=gross*BigInt(x.variableCostBps)/10000n;return {rateBps:rate,contributionMinor:gross-cost};});}
export function optimizeRevenuePortfolio(xs:any[]){const recommendations=xs.map(x=>x.evidenceCoverage<80?`Evidence gap: ${x.programId}`:`Monitor ${x.programId}`);return {version:'V218.0.0',recommendations,guardrails:['evidence','risk','cost','no fabricated revenue']};}
''',
'modules/platform/revenue-experimentation/index.ts':r'''export function evaluateRevenueExperiment(x:any){if(x.controlEligible<20||x.treatmentEligible<20)return {decision:'INSUFFICIENT_EVIDENCE'};const c=x.controlRevenueMinor-x.controlCostMinor,t=x.treatmentRevenueMinor-x.treatmentCostMinor;return {treatmentRevenuePerEligibleMinor:x.treatmentRevenueMinor/BigInt(x.treatmentEligible),incrementalContributionMinor:t-c,decision:t>c?'SCALE':'HOLD'};}
export function buildRevenueLearningPlan(xs:any[]){const actions=xs.map(x=>x.controlEligible<20||x.treatmentEligible<20?`GATHER evidence: ${x.experimentId}`:`SCALE candidate: ${x.experimentId} (${x.programId})`);return {version:'V219.0.0',nextActions:actions};}
''',
}
for p,s in mods.items():
 q=r/p;q.parent.mkdir(parents=True,exist_ok=True);q.write_text(s)
