import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const root=process.cwd();
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const write=(f,v)=>{fs.mkdirSync(path.dirname(path.join(root,f)),{recursive:true});fs.writeFileSync(path.join(root,f),v)};
const hash=v=>crypto.createHash('sha256').update(v).digest('hex');
const config=JSON.parse(read('config/reality/promotion-authorization-v265.json'));
if(config.algorithm!=='ed25519'||config.policy.signatureRequiredForEveryTransition!==true||config.policy.autoPromotion!==false)throw new Error('Invalid V265 authorization policy');
const {publicKey,privateKey}=crypto.generateKeyPairSync('ed25519');
const publicKeyPem=publicKey.export({type:'spki',format:'pem'});
const privateKeyPem=privateKey.export({type:'pkcs8',format:'pem'});
const payload={decisionId:'v265-demo-decision',decisionHash:'a'.repeat(64),fromState:'PENDING_EXPLICIT_REVIEW',toState:'APPROVED',actorId:'demo-reviewer',keyId:'demo-ed25519-key',rationale:'Explicit review approval for executable evidence.',attestationRoot:'b'.repeat(64),evidenceLeaf:'c'.repeat(64)};
const canonical=v=>{if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return `[${v.map(canonical).join(',')}]`;return `{${Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${canonical(x)}`).join(',')}}`};
const message=Buffer.from(canonical(payload));
const signature=crypto.sign(null,message,privateKeyPem).toString('base64');
const valid=crypto.verify(null,message,publicKeyPem,Buffer.from(signature,'base64'));
const tampered=crypto.verify(null,Buffer.from(canonical({...payload,toState:'REJECTED'})),publicKeyPem,Buffer.from(signature,'base64'));
if(!valid||tampered)throw new Error('V265 signature verification harness failed');
const payloadHash=hash(message);
const report={version:'V265.0.0',algorithm:'ed25519',status:'CRYPTOGRAPHIC_AUTHORIZATION_VERIFIED',demo:{keyId:payload.keyId,actorId:payload.actorId,payloadHash,signatureBytes:Buffer.from(signature,'base64').length,validSignature:valid,tamperedPayloadRejected:!tampered},policy:config.policy,privateKeyPersisted:false};
write('artifacts/reality/reality-promotion-authorization-v265.json',JSON.stringify(report,null,2)+'\n');
write('artifacts/reality/reality-promotion-authorization-v265.md',`# TRUST V265 — Cryptographic Promotion Authorization\n\n- Algorithm: Ed25519\n- Signature verification: PASS\n- Tampered payload rejection: PASS\n- Private key persisted in artifact: NO\n- Auto-promotion: disabled\n- Payload hash: ${payloadHash}\n`);
console.log(`V265 Cryptographic Promotion Authorization PASS — Ed25519 verification and tamper rejection verified; payloadHash=${payloadHash}`);
