'use client';
import { FormEvent, useState } from 'react';
import { useSearchParams } from 'next/navigation';
export default function AdminLogin(){
 const params=useSearchParams(); const rawNext=params.get('next'); const next=rawNext&&rawNext.startsWith('/')&&!rawNext.startsWith('//')&&!rawNext.includes('://')?rawNext:'/admin';
 const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [code,setCode]=useState('');const [mfaRequired,setMfaRequired]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const res=await fetch('/api/admin/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,code})});const data=await res.json();if(data?.mfaRequired)setMfaRequired(true);if(!res.ok)throw new Error(data?.error||'تعذر الدخول');window.location.assign(next);}catch(err){setError(err instanceof Error?err.message:'تعذر الدخول');setBusy(false);}}
 return <main className="admin-login-page" dir="rtl"><section className="admin-login-card"><div className="admin-lock">◈</div><span className="eyebrow">TRUST APEX · PRIVATE CONTROL PLANE</span><h1>غرفة التحكم</h1><p>الوصول محصور بصاحب الحساب الإداري المصرح له. لا تُعرض بيانات تشغيلية قبل التحقق.</p><form onSubmit={submit}><label>البريد الإداري<input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required /></label><label>كلمة مرور غرفة التحكم<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required /></label>{mfaRequired&&<label>رمز التحقق الثنائي<input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} required /></label>}{error&&<div className="admin-login-error">{error}</div>}<button disabled={busy}>{busy?'جاري التحقق…':'دخول آمن'}</button></form><a href="/">← العودة إلى TRUST</a></section></main>;
}
