-- TRUST V81 transactional foundation (PostgreSQL)
create extension if not exists pgcrypto;
create table if not exists trust_users(id uuid primary key default gen_random_uuid(),email text not null unique,password_hash text not null,role text not null,created_at timestamptz not null default now());
create table if not exists trust_merchants(id uuid primary key default gen_random_uuid(),user_id uuid not null references trust_users(id),name text not null,slug text not null unique,status text not null default 'pending',created_at timestamptz not null default now());
create table if not exists trust_products(id uuid primary key default gen_random_uuid(),merchant_id uuid not null references trust_merchants(id),name text not null,sku text not null unique,price numeric(12,2) not null check(price>=0),stock integer not null default 0 check(stock>=0),active boolean not null default true,created_at timestamptz not null default now());
create table if not exists trust_carts(id uuid primary key default gen_random_uuid(),customer_id uuid not null references trust_users(id) unique,updated_at timestamptz not null default now());
create table if not exists trust_cart_items(cart_id uuid not null references trust_carts(id) on delete cascade,product_id uuid not null references trust_products(id),quantity integer not null check(quantity>0),primary key(cart_id,product_id));
create table if not exists trust_orders(id uuid primary key default gen_random_uuid(),customer_id uuid not null references trust_users(id),status text not null,subtotal numeric(12,2) not null,discount numeric(12,2) not null default 0,shipping numeric(12,2) not null,total numeric(12,2) not null,currency text not null default 'EGP',idempotency_key text unique,created_at timestamptz not null default now());
create table if not exists trust_order_items(order_id uuid not null references trust_orders(id) on delete cascade,product_id uuid not null references trust_products(id),quantity integer not null check(quantity>0),unit_price numeric(12,2) not null,primary key(order_id,product_id));
create table if not exists trust_inventory_ledger(id uuid primary key default gen_random_uuid(),product_id uuid not null references trust_products(id),delta integer not null,reason text not null,reference_id text,created_at timestamptz not null default now());
create table if not exists trust_returns(id uuid primary key default gen_random_uuid(),order_id uuid not null references trust_orders(id),customer_id uuid not null references trust_users(id),reason text not null,status text not null default 'requested',created_at timestamptz not null default now());
create table if not exists trust_reviews(id uuid primary key default gen_random_uuid(),product_id uuid not null references trust_products(id),customer_id uuid not null references trust_users(id),rating integer not null check(rating between 1 and 5),title text,body text,created_at timestamptz not null default now(),unique(product_id,customer_id));
create index if not exists trust_orders_customer_idx on trust_orders(customer_id,created_at desc);
create index if not exists trust_products_merchant_idx on trust_products(merchant_id,active);
