'use client';
import {useEffect,useState} from 'react';
import {ORDER_STATUS_LABELS} from '../../../modules/platform/order-experience';
const money=(n:number)=>new Intl.NumberFormat('ar-EG',{style:'currency',currency:'EGP',maximumFractionDigits:0}).format(n);
export default function OrderDetail({params}:{params:{id:string}}){const [data,setData]=useState<any>();const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const load=()=>fetch(`/api/commerce/journey/${params.id}`,{cache:'no-store'}).then(r=>r.json()).then(x=>{if(!x.ok)throw new Error(x.error);setData(x);setError('')}).catch(e=>setError(e.message==='ORDER_ACCESS_DENIED'?'مش مسموح لك تشوف الطلب ده':e.message==='ORDER_NOT_FOUND'?'الطلب مش موجود':'تعذّر تحميل الطلب'));
 useEffect(()=>{load()},[params.id]);
 async function cancel(){if(!confirm('متأكد إنك عايز تلغي الطلب؟'))return;setBusy(true);try{const x=await fetch(`/api/orders/${params.id}/cancel`,{method:'POST'}).then(r=>r.json());if(!x.ok){setError(x.error);return}await load()}finally{setBusy(false)}}
 if(error&&!data)return <main dir="rtl" className="min-h-screen bg-black p-8 text-white"><div className="mx-auto max-w-2xl rounded-3xl border border-red-500/30 bg-red-500/10 p-6 text-red-300">{error}</div></main>;
 if(!data)return <main dir="rtl" className="min-h-screen bg-black p-8 text-white">جاري تحميل الطلب...</main>;
 const o=data.journey.order; const timeline=data.journey.events??[]; const items=data.journey.items??[]; const shipments=data.journey.shipments??[]; return <main dir="rtl" className="min-h-screen bg-black px-5 py-10 text-white"><div className="mx-auto max-w-3xl"><a href="/orders" className="text-sm text-amber-300">← كل الطلبات</a><div className="mt-5 flex flex-wrap items-center justify-between gap-4"><div><div className="text-xs tracking-[.3em] text-amber-400">ORDER EXPERIENCE 3.0</div><h1 className="mt-2 text-3xl font-semibold">طلب #{o.id}</h1></div><span className="rounded-full border border-amber-400/30 px-4 py-2 text-sm text-amber-300">{ORDER_STATUS_LABELS[o.status]??o.status}</span></div>
 <section className="mt-8 rounded-3xl border border-white/10 bg-white/[.03] p-6"><h2 className="font-semibold">رحلة الطلب</h2><div className="mt-5 space-y-4">{timeline.map((e:any,i:number)=><div key={`${e.status}-${e.at}-${i}`} className="flex gap-4"><div className={`mt-1 h-3 w-3 shrink-0 rounded-full ${e.current?'bg-amber-400':'bg-white/20'}`}/><div><b>{e.label}</b><div className="text-xs text-zinc-500">{new Date(e.at).toLocaleString('ar-EG')}</div></div></div>)}</div></section>
 <section className="mt-5 rounded-3xl border border-white/10 bg-white/[.03] p-6"><h2 className="font-semibold">المنتجات والبائعون</h2><div className="mt-4 space-y-3">{items.map((it:any)=><div key={it.id} className="rounded-2xl border border-white/5 p-4"><div className="flex justify-between gap-4 text-sm"><span>{it.name} × {it.quantity}</span><span>{money(it.unitPrice*it.quantity)}</span></div><div className="mt-1 text-xs text-zinc-500">البائع: {it.seller?.storeName || 'البائع'}</div></div>)}</div><div className="mt-5 space-y-2 border-t border-white/10 pt-4 text-sm"><div className="flex justify-between"><span className="text-zinc-400">المنتجات</span><span>{money(o.subtotal)}</span></div><div className="flex justify-between"><span className="text-zinc-400">الشحن</span><span>{o.shipping===0?'مجاني':money(o.shipping)}</span></div><div className="flex justify-between text-lg font-semibold"><span>الإجمالي</span><span>{money(o.total)}</span></div></div></section>

 <section className="mt-5 rounded-3xl border border-white/10 bg-white/[.03] p-6"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold">الشحن والتتبع</h2><span className="text-xs text-zinc-500">{data.journey.summary?.shipmentCount ?? 0} شحنة نشطة</span></div><div className="mt-4 space-y-4">{(shipments).map((s:any)=><div key={s.id} className="rounded-2xl border border-white/5 p-4"><div className="flex flex-wrap justify-between gap-2 text-sm"><span>{s.carrier} · {s.service}</span><b>{s.status}</b></div>{s.trackingNumber&&<div className="mt-1 text-xs text-zinc-400">رقم التتبع: {s.trackingNumber}</div>} {s.etaAt&&<div className="mt-1 text-xs text-amber-300">الموعد المتوقع: {new Date(s.etaAt).toLocaleString('ar-EG')}</div>}<div className="mt-3 space-y-2">{(s.events??[]).slice(-5).reverse().map((e:any,i:number)=><div key={i} className="text-xs text-zinc-400"><b className="text-zinc-200">{e.status}</b> · {e.description||'تحديث شحن'} · {new Date(e.occurred_at??e.occurredAt).toLocaleString('ar-EG')}</div>)}</div></div>)}{!(shipments).length&&<div className="text-sm text-zinc-500">لم يتم إنشاء شحنة بعد.</div>}</div></section>
 {data.actions?.some((a:any)=>a.action==='cancel'&&a.allowed)&&<button disabled={busy} onClick={cancel} className="mt-5 min-h-11 rounded-full border border-red-500/40 px-5 py-3 text-red-300 disabled:opacity-50">{busy?'جاري الإلغاء...':'إلغاء الطلب'}</button>}
 {error&&<div className="mt-4 rounded-2xl border border-red-500/30 bg-red-500/10 p-4 text-red-300">{error}</div>}
 </div></main>}
