'use client';
import {useEffect,useMemo,useState} from 'react';
import {buildCustomerOverview,buildCustomerPriorities,buildCustomerTimeline} from '../../modules/customer-os/experience-2';

type Product={id:string;name:string;price:number;stock:number;merchantName:string;category:string;image:string;rating:number};
type Cart={items:Array<{productId:string;qty:number;name:string;unitPrice:number;lineTotal:number;stock:number;image:string}>;subtotal:number;shipping:number;total:number};

export default function CustomerOS(){
 const [products,setProducts]=useState<Product[]>([]); const [cart,setCart]=useState<Cart|null>(null); const [q,setQ]=useState(''); const [busy,setBusy]=useState(''); const [error,setError]=useState(''); const [profile,setProfile]=useState<any>(null); const [orders,setOrders]=useState<any[]>([]); const [returns,setReturns]=useState<any[]>([]); const [loading,setLoading]=useState(true);
 const filtered=useMemo(()=>products.filter(p=>[p.name,p.category,p.merchantName].join(' ').toLowerCase().includes(q.toLowerCase())),[products,q]);
 async function load(){setLoading(true);try{const [p,c,pr,o,r]=await Promise.all([fetch('/api/catalog').then(x=>x.json()),fetch('/api/cart').then(x=>x.json()),fetch('/api/customer/profile',{cache:'no-store'}).then(x=>x.json()),fetch('/api/customer/orders',{cache:'no-store'}).then(x=>x.json()),fetch('/api/returns',{cache:'no-store'}).then(x=>x.json())]);if(p.ok)setProducts(p.items??[]);if(c.ok)setCart(c);if(pr.ok)setProfile(pr.profile);if(o.ok)setOrders(o.orders??[]);if(r.ok)setReturns(r.returns??[]);}catch{setError('تعذر تحميل مركز العميل الآن. جرّب تحديث الصفحة.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function add(id:string){setBusy(id);setError('');const r=await fetch('/api/cart/items',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({productId:id,qty:1})});const d=await r.json();if(!r.ok)setError(d.error??'تعذر إضافة المنتج');else setCart(d.summary);setBusy('')}
 const snapshot={profile:profile??{},orders,returns}; const overview=buildCustomerOverview(snapshot); const timeline=buildCustomerTimeline(snapshot); const priorities=buildCustomerPriorities(snapshot);
 return <main id="main-content" className="mx-auto max-w-7xl p-4 sm:p-6 space-y-8">
  <header className="rounded-[2rem] border p-6 md:p-8"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-sm opacity-60">TRUST APEX · CUSTOMER OS 2.0</p><h1 className="text-4xl font-black">{overview.displayName}</h1><p className="mt-2 opacity-70">حسابك، طلباتك، مرتجعاتك، وسلة الشراء في مساحة واحدة.</p></div><input aria-label="البحث في المنتجات" value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث عن منتج..." className="rounded-2xl border p-3 w-full md:w-80"/></div>
   <div className="mt-6 grid gap-3 grid-cols-2 lg:grid-cols-4"><Metric title="الطلبات" value={overview.orderCount}/><Metric title="طلبات مفتوحة" value={overview.openOrders}/><Metric title="المرتجعات" value={overview.returnCount}/><Metric title="إجمالي المشتريات" value={`${overview.totalSpent.toLocaleString('ar-EG')} ج.م`}/></div>
  </header>
  {error&&<div role="alert" className="rounded-2xl border border-red-400/40 p-4">{error}</div>}
  <section className="grid gap-5 lg:grid-cols-[1fr_340px]">
   <div className="space-y-6">
    <section className="rounded-3xl border p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="text-2xl font-black">مركز الاهتمام</h2><p className="opacity-60 text-sm">أهم الحاجات اللي تستحق انتباهك الآن.</p></div><a href="/purchase-guardian" className="rounded-xl border px-3 py-2">حماية المشتريات</a></div><div className="mt-4 grid gap-3">{priorities.map((x,i)=><div key={x} className="rounded-2xl bg-black/5 p-4"><b>{i+1}.</b> {x}</div>)}</div></section>
    <section className="rounded-3xl border p-5"><div className="flex justify-between"><div><h2 className="text-2xl font-black">آخر النشاط</h2><p className="opacity-60 text-sm">Timeline موحّد للطلبات والمرتجعات.</p></div><a href="/order-tracker" className="rounded-xl border px-3 py-2">كل الطلبات</a></div><div className="mt-4 space-y-3">{timeline.length?timeline.map(item=><a href={item.href} key={item.id} className="flex items-center justify-between gap-4 rounded-2xl border p-4 hover:bg-black/5"><div><b>{item.title}</b><div className="text-sm opacity-60">{item.detail} · {item.status}</div></div><span className="text-xs opacity-50">{item.timestamp?new Date(item.timestamp).toLocaleDateString('ar-EG'):'—'}</span></a>):<p className="opacity-60">لسه مفيش نشاط مسجل.</p>}</div></section>
   </div>
   <aside className="h-fit sticky top-5 rounded-3xl border p-5 space-y-4"><h2 className="text-2xl font-black">سلة الشراء</h2>{!cart?.items?.length?<p className="opacity-60">السلة فارغة.</p>:cart.items.map(i=><div key={i.productId} className="flex justify-between gap-3 border-b pb-3"><div><b>{i.name}</b><div className="text-sm opacity-60">× {i.qty}</div></div><span>{i.lineTotal.toLocaleString('ar-EG')} ج.م</span></div>)}<div className="flex justify-between"><span>الشحن</span><b>{(cart?.shipping??0).toLocaleString('ar-EG')} ج.م</b></div><div className="flex justify-between text-xl"><span>الإجمالي</span><b>{(cart?.total??0).toLocaleString('ar-EG')} ج.م</b></div><a href="/order-tracker" className="block text-center rounded-xl border px-4 py-3">تتبع طلباتي</a></aside>
  </section>
  <section><div className="mb-4 flex items-end justify-between"><div><h2 className="text-3xl font-black">اكتشف المنتجات</h2><p className="opacity-60">تسوق من نفس مساحة حسابك.</p></div><span className="text-sm opacity-50">{loading?'جاري التحميل...':`${filtered.length} منتج`}</span></div><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(p=><article key={p.id} className="overflow-hidden rounded-3xl border bg-black/5"><img src={p.image} alt="" loading="lazy" decoding="async" className="h-56 w-full object-cover"/><div className="p-4 space-y-2"><div className="text-xs opacity-60">{p.merchantName} · {p.category}</div><h2 className="font-bold">{p.name}</h2><div className="flex justify-between"><b>{p.price.toLocaleString('ar-EG')} ج.م</b><span>★ {p.rating}</span></div><button disabled={busy===p.id||p.stock<1} onClick={()=>add(p.id)} className="w-full rounded-xl bg-black px-4 py-3 text-white disabled:opacity-40">{p.stock<1?'نفد المخزون':busy===p.id?'جاري الإضافة...':'أضف للسلة'}</button></div></article>)}</div></section>
 </main>
}
function Metric({title,value}:{title:string;value:string|number}){return <div className="rounded-2xl border p-4"><div className="text-sm opacity-60">{title}</div><strong className="mt-1 block text-2xl font-black">{value}</strong></div>}
