'use client';
import {useMemo,useState} from 'react';

type Risk='LOW'|'MEDIUM'|'HIGH'|'CRITICAL';
type View='cockpit'|'warroom'|'ai'|'governance'|'finance'|'audit';
const systems=[
 ['Marketplace','99.99%','142ms','HEALTHY'],['Checkout','99.94%','184ms','HEALTHY'],['Payments','99.81%','241ms','DEGRADED'],['Inventory','99.97%','128ms','HEALTHY'],['Fulfillment','99.92%','301ms','HEALTHY'],['Trust & Fraud','99.98%','167ms','HEALTHY'],['AI Platform','99.76%','412ms','DEGRADED'],['Analytics','99.99%','109ms','HEALTHY']
] as const;
const decisions=[
 ['Reallocate ad budget','EGP +42,800','82%','LOW'],['Raise price on 3 SKUs','EGP +18,400','79%','MEDIUM'],['Pause suspicious merchant','Risk reduction','94%','HIGH'],['Restock warehouse A','Prevent stockout','91%','LOW']
] as [string,string,string,Risk][];
const actions=[['Freeze checkout','Stops new checkout attempts','CRITICAL'],['Drain payment traffic','Shift traffic to healthy processors','HIGH'],['Enable read-only','Block destructive admin writes','HIGH'],['Rebuild inventory reservations','Reconcile reservation ledger','MEDIUM'],['Open fraud investigation','Create investigation workspace','HIGH'],['Run revenue simulation','No production changes','LOW'] ] as [string,string,Risk][];
const audit=['AI decision simulated: ad budget reallocation','Payment degradation acknowledged','Inventory reservation reconciliation queued','Merchant risk policy evaluated','Release gate completed','Admin session policy checked'];
export default function Admin(){
 const [view,setView]=useState<View>('cockpit'),[safe,setSafe]=useState(false),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState('');
 const flash=(s:string)=>{setNotice(s);setTimeout(()=>setNotice(''),2500)};
 const filtered=useMemo(()=>systems.filter(x=>!query||x[0].toLowerCase().includes(query.toLowerCase())),[query]);
 return <main className="war-room">
  <header className="war-head"><div><span className="eyebrow">TRUST APEX · V95 · SUPER ADMIN</span><h1>غرفة القيادة المركزية</h1><p>مركز تشغيل موحّد للمخاطر، التجارة، الذكاء الاصطناعي، المال، البنية التحتية والحوكمة.</p></div><div className="war-actions"><button onClick={()=>setSafe(!safe)} className={safe?'armed':''}>{safe?'SAFE MODE ON':'SAFE MODE'}</button><button onClick={()=>flash('Command palette ready — Ctrl/⌘ + K')}>⌘ Command</button></div></header>
  <div className="war-strip"><b>● PLATFORM HEALTH 99.96%</b><span>8 SYSTEMS</span><span>2 DEGRADED</span><span>3 APPROVALS</span><span>1 HIGH-RISK INCIDENT</span><span>REGION: GLOBAL</span></div>
  {safe&&<div className="war-banner">🛡️ SAFE MODE: الإجراءات المدمرة متوقفة. يسمح بالمراقبة، المحاكاة، والموافقات غير التنفيذية فقط.</div>}
  {notice&&<div className="admin-notice">✓ {notice}</div>}
  <nav className="war-nav">{[['cockpit','Cockpit'],['warroom','War Room'],['ai','AI Command'],['governance','Governance'],['finance','Finance'],['audit','Audit']].map(([id,label])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id as View)}>{label}</button>)}</nav>
  {view==='cockpit'&&<Cockpit onAction={flash}/>} 
  {view==='warroom'&&<WarRoom systems={filtered} query={query} setQuery={setQuery} onAction={flash}/>} 
  {view==='ai'&&<AICommand onAction={flash}/>} 
  {view==='governance'&&<Governance onAction={flash}/>} 
  {view==='finance'&&<Finance onAction={flash}/>} 
  {view==='audit'&&<Audit/>}
  <footer className="war-foot"><b>TRUST V95 APEX</b><span>Control actions are policy-aware control surfaces. Production execution still requires real server-side authentication, RBAC, durable state and infrastructure integrations.</span></footer>
 </main>
}
function Cockpit({onAction}:{onAction:(s:string)=>void}){return <div className="war-body"><div className="kpi-grid"><Kpi t="GMV Today" v="EGP 2.84M" s="+18.7%"/><Kpi t="Orders" v="3,842" s="+12.4%"/><Kpi t="Net Revenue" v="EGP 612K" s="+21.3%"/><Kpi t="Trust Score" v="98.7" s="+1.8"/></div><div className="war-grid"><section className="war-panel"><Head e="COMMAND DECK" t="أوامر عالية التأثير"/><div className="command-grid">{actions.map(a=><button key={a[0]} onClick={()=>onAction(`${a[0]} — ${a[2]} risk — dry-run control surface`) }><b>{a[0]}</b><span>{a[1]}</span><em className={a[2].toLowerCase()}>{a[2]}</em></button>)}</div></section><section className="war-panel"><Head e="EXECUTIVE SIGNAL" t="نبض المنصة"/><div className="pulse">{[61,73,66,82,78,91,86,94,89,96,92,97].map((n,i)=><i key={i} style={{height:n+'%'}}/> )}</div><div className="mini-grid"><span>Traffic <b>+18.4%</b></span><span>CVR <b>4.82%</b></span><span>AOV <b>EGP 739</b></span><span>P95 <b>184ms</b></span></div></section></div><div className="war-grid"><section className="war-panel"><Head e="RISK RADAR" t="ما يحتاج انتباهك الآن"/><div className="risk-list"><RiskRow t="Payment latency elevated" d="P95 above target in one processor" r="MEDIUM" on={onAction}/><RiskRow t="High-impact AI approval" d="Price policy change awaiting approval" r="HIGH" on={onAction}/><RiskRow t="Warehouse anomaly" d="12 SKUs show unusual delta" r="MEDIUM" on={onAction}/></div></section><section className="war-panel"><Head e="SLO BOARD" t="الاعتمادية"/><div className="slo">{[['Checkout','99.94%','184ms'],['Payments','99.81%','241ms'],['Inventory','99.97%','128ms'],['Fraud','99.98%','167ms']].map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><small>{x[2]}</small></div>)}</div></section></div></div>}
function WarRoom({systems,query,setQuery,onAction}:{systems:readonly (readonly [string,string,string,string])[];query:string;setQuery:(s:string)=>void;onAction:(s:string)=>void}){return <div className="war-body"><section className="war-panel"><Head e="SYSTEM TOPOLOGY" t="كل الأنظمة في شاشة واحدة"/><input className="war-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث عن خدمة…"/><div className="system-grid">{systems.map(x=><button key={x[0]} onClick={()=>onAction(`${x[0]} opened in diagnostic mode`)}><div><b>{x[0]}</b><span>{x[3]}</span></div><strong>{x[1]}</strong><small>P95 {x[2]}</small></button>)}</div></section><section className="war-panel"><Head e="INCIDENT TIMELINE" t="آخر الأحداث التشغيلية"/><div className="timeline">{['Payment processor latency crossed threshold','AI policy simulation completed','Inventory reconciliation started','Fraud model score updated','Checkout SLO recovered'].map((x,i)=><div key={x}><i>{String(i+1).padStart(2,'0')}</i><b>{x}</b><small>{i+2} min ago</small></div>)}</div></section></div>}
function AICommand({onAction}:{onAction:(s:string)=>void}){return <div className="war-body"><div className="war-grid"><section className="war-panel"><Head e="AI ORCHESTRATOR" t="قرارات الذكاء الاصطناعي"/><div className="decision-list">{decisions.map(d=><div key={d[0]}><div><b>{d[0]}</b><span>{d[1]} · confidence {d[2]}</span></div><em className={d[3].toLowerCase()}>{d[3]}</em><button onClick={()=>onAction(`${d[0]} sent to approval — no execution`)}>Review</button></div>)}</div></section><section className="war-panel"><Head e="SIMULATION LAB" t="اختبر قبل ما تنفذ"/><div className="sim-form"><label>Price change <input type="range" min="-10" max="10" defaultValue="3"/></label><label>Discount <input type="range" min="0" max="30" defaultValue="12"/></label><label>Ad spend <input type="range" min="10" max="100" defaultValue="55"/></label><button className="primary" onClick={()=>onAction('Simulation completed — no production mutation')}>RUN SIMULATION</button></div><div className="sim-result"><b>Scenario score 91/100</b><span>Expected revenue +8.4% · Risk LOW · Confidence 84%</span></div></section></div></div>}
function Governance({onAction}:{onAction:(s:string)=>void}){const rows=[['Super Admin','All domains','Dual approval','ACTIVE'],['Operations','Commerce + Fulfillment','Single approval','ACTIVE'],['AI Operator','AI + Analytics','No money movement','ACTIVE'],['Auditor','Read + Audit','Read only','ACTIVE']];return <div className="war-body"><section className="war-panel"><Head e="POLICY ENGINE" t="صلاحيات وحوكمة"/><div className="policy-list">{rows.map(r=><div key={r[0]}><b>{r[0]}</b><span>{r[1]}</span><span>{r[2]}</span><em>{r[3]}</em></div>)}</div><button className="primary" onClick={()=>onAction('Policy simulation opened')}>SIMULATE POLICY CHANGE</button></section><section className="war-panel"><Head e="GUARDRAILS" t="حواجز لا يمكن تجاوزها من الواجهة"/><div className="guard-grid">{['Server-side RBAC','Immutable audit trail','Dual control for money','Webhook verification','Idempotency enforcement','Read-only emergency mode'].map(x=><div key={x}><i>✓</i><b>{x}</b></div>)}</div></section></div>}
function Finance({onAction}:{onAction:(s:string)=>void}){return <div className="war-body"><div className="kpi-grid"><Kpi t="Gross Margin" v="28.4%" s="+2.1%"/><Kpi t="Refund Rate" v="2.7%" s="-0.4%"/><Kpi t="Payment Success" v="98.9%" s="+0.6%"/><Kpi t="Payout Queue" v="EGP 184K" s="14 merchants"/></div><section className="war-panel"><Head e="MONEY MOVEMENT CONTROL" t="العمليات المالية الحساسة"/><div className="finance-list">{['Refund batch pending approval','Merchant payout reconciliation','Chargeback review queue','Settlement mismatch detection'].map((x,i)=><div key={x}><b>{x}</b><span>{i%2?'Medium':'High'} risk · requires approval</span><button onClick={()=>onAction(`${x} opened — execution blocked until approval`)}>Review</button></div>)}</div></section></div>}
function Audit(){return <div className="war-body"><section className="war-panel"><Head e="IMMUTABLE INTENT" t="سجل الإدارة"/><div className="timeline">{audit.map((x,i)=><div key={x}><i>{String(i+1).padStart(2,'0')}</i><b>{x}</b><small>V95 control plane</small></div>)}</div></section></div>}
function Kpi({t,v,s}:{t:string;v:string;s:string}){return <div className="kpi"><span>{t}</span><b>{v}</b><small>{s} vs previous period</small></div>}
function Head({e,t}:{e:string;t:string}){return <div className="war-panel-head"><div><span>{e}</span><h2>{t}</h2></div><i>LIVE</i></div>}
function RiskRow({t,d,r,on}:{t:string;d:string;r:Risk;on:(s:string)=>void}){return <div className="risk-row"><i className={r.toLowerCase()}>{r}</i><div><b>{t}</b><span>{d}</span></div><button onClick={()=>on(`${t} acknowledged`)}>Review</button></div>}
