import type {NetworkAllocation,NetworkCandidate,NetworkCapacity,NetworkObjective,NetworkShipment,NetworkPlan,LearnedNetworkProfile} from './contracts.ts';
import {listCarriers,listCarrierServices} from '../global-carrier-v304/registry.ts';
import {reliabilityScore} from '../global-logistics-v305/scoring.ts';
const norm=(x:number)=>Math.max(0,Math.min(1,x));
function urgency(shipment:NetworkShipment,now:string){const p=shipment.promisedAt?Date.parse(shipment.promisedAt):NaN;if(!Number.isFinite(p))return 0;return norm(1-(p-Date.parse(now))/86400000/3);}
function objectiveWeight(o:NetworkObjective){if(o==='COST')return {cost:.65,speed:.1,reliability:.15,promise:.1};if(o==='SPEED')return {cost:.1,speed:.65,reliability:.15,promise:.1};if(o==='RELIABILITY')return {cost:.1,speed:.15,reliability:.65,promise:.1};if(o==='PROMISE')return {cost:.1,speed:.3,reliability:.2,promise:.4};return {cost:.3,speed:.25,reliability:.3,promise:.15};}
export function buildCandidates(shipment:NetworkShipment,capacities:NetworkCapacity[]=[],now=new Date().toISOString(),learned:LearnedNetworkProfile[]=[]):NetworkCandidate[]{
 const country=shipment.country.trim().toUpperCase(),currency=shipment.currency.trim().toUpperCase(); const base:any[]=[]; for(const carrier of listCarriers()){if(!carrier.enabled||(carrier.countries[0]!=='*'&&!carrier.countries.includes(country))||(carrier.currencies[0]!=='*'&&!carrier.currencies.includes(currency)))continue; const service=listCarrierServices(country,shipment.mode).find(s=>s.carrierCode===carrier.carrierCode&&s.currency===currency); if(!service)continue; base.push({carrierCode:carrier.carrierCode,serviceCode:service.serviceCode,costMinor:service.basePriceMinor,minDays:service.minDays,maxDays:service.maxDays,reliability:reliabilityScore(0,0,'CLOSED'),score:0,reasons:[]});}
 const w=objectiveWeight(shipment.priority==='SPEED'?'SPEED':shipment.priority==='COST'?'COST':shipment.priority==='RELIABILITY'?'RELIABILITY':'BALANCED');
 const u=urgency(shipment,now);const relevant=capacities.filter(c=>c.country.toUpperCase()===shipment.country.toUpperCase()&&c.currency.toUpperCase()===shipment.currency.toUpperCase()&&c.mode===shipment.mode);
 return base.map(c=>{const learnedProfile=learned.find(x=>x.carrierCode.toUpperCase()===c.carrierCode&&x.serviceCode.toUpperCase()===c.serviceCode);const adaptiveReliability=learnedProfile?norm(c.reliability*(1-learnedProfile.confidence)+learnedProfile.adaptiveReliability*learnedProfile.confidence):c.reliability;const cap=relevant.find(x=>x.carrierCode===c.carrierCode&&x.serviceCode===c.serviceCode);const remaining=cap?Math.max(0,cap.maxShipments-(cap.reservedShipments??0)):null;const costNorm=1/(1+Number(c.costMinor)/10000);const speedNorm=1/(1+c.maxDays);const promiseNorm=shipment.promisedAt?norm(1-(c.maxDays*24*60)/Math.max(1,Math.max(1,(Date.parse(shipment.promisedAt)-Date.parse(now))/60000))):0.5;const score=w.cost*costNorm+w.speed*speedNorm+w.reliability*adaptiveReliability+w.promise*promiseNorm+u*(c.reliability*.05);const reasons=[`OBJECTIVE_${shipment.priority??'BALANCED'}`];if(remaining!==null&&remaining<=0)reasons.push('CAPACITY_EXHAUSTED');if(remaining!==null&&remaining<=5)reasons.push('CAPACITY_NEAR_LIMIT');if(u>=.75)reasons.push('PROMISE_URGENT');if(adaptiveReliability>=.95)reasons.push('HIGH_RELIABILITY');if(learnedProfile)reasons.push(`LEARNED_CONFIDENCE_${Math.round(learnedProfile.confidence*100)}`);return {...c,reliability:adaptiveReliability,capacityRemaining:remaining,networkScore:Number(score.toFixed(6)),reasons};}).filter(c=>c.capacityRemaining===null||c.capacityRemaining>0).sort((a,b)=>b.networkScore-a.networkScore||a.maxDays-b.maxDays||a.costMinor<b.costMinor?-1:a.costMinor>b.costMinor?1:a.carrierCode.localeCompare(b.carrierCode));
}
export function optimizeNetwork(shipments:NetworkShipment[],capacities:NetworkCapacity[]=[],objective:NetworkObjective='BALANCED',now=new Date().toISOString(),idempotencyKey='preview',learned:LearnedNetworkProfile[]=[]) : NetworkPlan {
 if(!idempotencyKey.trim())throw new Error('IDEMPOTENCY_KEY_REQUIRED');
 const remaining=new Map<string,number>();for(const c of capacities)remaining.set(`${c.carrierCode}:${c.serviceCode}:${c.country}:${c.currency}:${c.mode}`,Math.max(0,c.maxShipments-(c.reservedShipments??0)));
 const ordered=[...shipments].sort((a,b)=>urgency(b,now)-urgency(a,now)||a.shipmentId.localeCompare(b.shipmentId));const allocations:NetworkAllocation[]=[];const unallocated:string[]=[];
 for(const s of ordered){const candidates=buildCandidates({...s,priority:objective==='PROMISE'?'SPEED':objective==='COST'?'COST':objective==='SPEED'?'SPEED':objective==='RELIABILITY'?'RELIABILITY':'BALANCED'},capacities,now,learned).map(c=>{const key=`${c.carrierCode}:${c.serviceCode}:${s.country.toUpperCase()}:${s.currency.toUpperCase()}:${s.mode}`;const r=remaining.get(key);return {...c,capacityRemaining:r===undefined?c.capacityRemaining:r};}).filter(c=>c.capacityRemaining===null||c.capacityRemaining>0);if(!candidates.length){unallocated.push(s.shipmentId);continue;}const chosen=candidates[0];const key=`${chosen.carrierCode}:${chosen.serviceCode}:${s.country.toUpperCase()}:${s.currency.toUpperCase()}:${s.mode}`;if(remaining.has(key))remaining.set(key,Math.max(0,(remaining.get(key)??0)-1));allocations.push({shipmentId:s.shipmentId,carrierCode:chosen.carrierCode,serviceCode:chosen.serviceCode,score:chosen.networkScore,costMinor:chosen.costMinor,maxDays:chosen.maxDays,reliability:chosen.reliability,reasons:[...chosen.reasons,`NETWORK_OBJECTIVE_${objective}`]});}
 const total=allocations.reduce((n,a)=>n+a.costMinor,0n);const avg=allocations.length?Number((allocations.reduce((n,a)=>n+a.maxDays,0)/allocations.length).toFixed(2)):null;return {version:'V311.0.0',objective,allocations,unallocatedShipmentIds:unallocated,summary:{shipments:shipments.length,allocated:allocations.length,unallocated:unallocated.length,carriersUsed:new Set(allocations.map(a=>a.carrierCode)).size,totalCostMinor:total,averageMaxDays:avg},idempotencyKey:idempotencyKey.trim()};
}
