export type WorkflowStage='OBSERVE'|'PREDICT'|'DECIDE'|'AUTHORIZE'|'ACT'|'VERIFY'|'LEARN'|'COMPLETED'|'FAILED';
export type ApprovalLevel='NONE'|'HUMAN'|'SECURITY_REVIEW';
export type WorkflowCommand={id:string;tenantId:string;workflow:string;stage:WorkflowStage;approval:ApprovalLevel;idempotencyKey:string;correlationId:string;createdAt:string};
export type WorkflowEvent={commandId:string;stage:WorkflowStage;status:'STARTED'|'SUCCEEDED'|'FAILED';at:string;metadata:Record<string,string|number|boolean>};
const order:WorkflowStage[]=['OBSERVE','PREDICT','DECIDE','AUTHORIZE','ACT','VERIFY','LEARN','COMPLETED'];
export function nextStage(current:WorkflowStage):WorkflowStage{const i=order.indexOf(current);if(i<0||i===order.length-1)throw new Error('WORKFLOW_ALREADY_TERMINAL');return order[i+1];}
export function assertTransition(from:WorkflowStage,to:WorkflowStage):void{if(from==='FAILED'||from==='COMPLETED')throw new Error('WORKFLOW_TERMINAL');const i=order.indexOf(from),j=order.indexOf(to);if(i<0||j!==i+1)throw new Error('INVALID_WORKFLOW_TRANSITION');}
export function createCommand(input:{id:string;tenantId:string;workflow:string;idempotencyKey:string;correlationId:string;approval?:ApprovalLevel;now?:string}):WorkflowCommand{if(!input.id||!input.tenantId||!input.workflow||!input.idempotencyKey||!input.correlationId)throw new Error('INVALID_WORKFLOW_COMMAND');return {id:input.id,tenantId:input.tenantId,workflow:input.workflow,stage:'OBSERVE',approval:input.approval??'NONE',idempotencyKey:input.idempotencyKey,correlationId:input.correlationId,createdAt:input.now??new Date().toISOString()};}
export function advanceCommand(c:WorkflowCommand,to:WorkflowStage):WorkflowCommand{assertTransition(c.stage,to);return {...c,stage:to};}
export function requiresApproval(risk:number,threshold:number):ApprovalLevel{if(!Number.isFinite(risk)||!Number.isFinite(threshold))throw new Error('INVALID_RISK_GATE');return risk>=threshold?'HUMAN':'NONE';}
export function executeDeterministicLoop(input:{command:WorkflowCommand;risk:number;approvalThreshold:number;verified:boolean}):{command:WorkflowCommand;events:WorkflowEvent[]}{let c=input.command;const events:WorkflowEvent[]=[];const emit=(status:'STARTED'|'SUCCEEDED'|'FAILED')=>events.push({commandId:c.id,stage:c.stage,status,at:new Date().toISOString(),metadata:{tenantId:c.tenantId,workflow:c.workflow}});emit('STARTED');for(const s of ['PREDICT','DECIDE'] as WorkflowStage[]){c=advanceCommand(c,s);emit('SUCCEEDED');}const approval=requiresApproval(input.risk,input.approvalThreshold);c={...c,approval};c=advanceCommand(c,'AUTHORIZE');if(approval!=='NONE'){emit('FAILED');return {command:{...c,stage:'FAILED'},events};}emit('SUCCEEDED');c=advanceCommand(c,'ACT');emit('SUCCEEDED');c=advanceCommand(c,'VERIFY');if(!input.verified){emit('FAILED');return {command:{...c,stage:'FAILED'},events};}emit('SUCCEEDED');c=advanceCommand(c,'LEARN');emit('SUCCEEDED');c=advanceCommand(c,'COMPLETED');emit('SUCCEEDED');return {command:c,events};}
