import test from 'node:test';
import assert from 'node:assert/strict';
import {InMemoryRuntimeEnforcer} from '../modules/platform/autonomous-reliability-loop/enforcer.ts';
import {runAutonomousReliabilityLoop} from '../modules/platform/autonomous-reliability-loop/loop.ts';
import {executeCase} from '../modules/platform/reliability-lab/engine.ts';

test('V144 healthy signal resumes rollout after verification',()=>{const e=new InMemoryRuntimeEnforcer();const r=executeCase(1441,[{id:'1',kind:'OPEN'}],[]);const out=runAutonomousReliabilityLoop({incidentId:'inc-1',signal:{serviceId:'checkout',availability:1,errorRate:0,p95Ms:1,budgetConsumedPct:0,replayMatches:true,newFailure:false},result:r,rolloutId:'roll-1',blastRadius:{serviceIds:['checkout'],tenantIds:['t1'],rolloutIds:['roll-1']}},e);assert.equal(out.status,'RECOVERED');assert.equal(out.decision,'RESUME');assert.deepEqual(e.snapshot().frozenRollouts,[])});
test('V144 SLO breach freezes, isolates, mitigates and escalates when recovery fails',()=>{const e=new InMemoryRuntimeEnforcer();const r=executeCase(1442,[{id:'1',kind:'OPEN'}],[{at:0,kind:'THROW',operationId:'1'}]);const out=runAutonomousReliabilityLoop({incidentId:'inc-2',signal:{serviceId:'payments',tenantId:'t2',availability:0,errorRate:1,p95Ms:900,budgetConsumedPct:100,replayMatches:false,newFailure:true},result:r,rolloutId:'roll-2',blastRadius:{serviceIds:['payments'],tenantIds:['t2'],rolloutIds:['roll-2']}},e);const s=e.snapshot();assert.equal(out.status,'ESCALATED');assert.equal(out.decision,'ESCALATE');assert.deepEqual(s.frozenRollouts,['roll-2']);assert.deepEqual(s.isolatedServices,['payments']);assert.deepEqual(s.isolatedTenants,['t2']);assert.equal(s.mitigations.length,1);assert.equal(s.rollbacks.length,1);assert.equal(s.escalations.length,1)});
test('V144 successful recovery permits resume',()=>{const e=new InMemoryRuntimeEnforcer();const failed=executeCase(1443,[{id:'1',kind:'OPEN'}],[{at:0,kind:'THROW',operationId:'1'}]);const healthy=executeCase(1443,[{id:'1',kind:'OPEN'}],[]);const out=runAutonomousReliabilityLoop({incidentId:'inc-3',signal:{serviceId:'catalog',availability:0.8,errorRate:.2,p95Ms:800,budgetConsumedPct:20,replayMatches:true,newFailure:true},result:failed,rolloutId:'roll-3',blastRadius:{serviceIds:['catalog'],tenantIds:[],rolloutIds:['roll-3']}},e,undefined,healthy);assert.equal(out.status,'RECOVERED');assert.equal(out.recovery.verified,true);assert.deepEqual(e.snapshot().frozenRollouts,[])});
test('V144 evidence hash is stable for equivalent control decisions',()=>{const r=executeCase(1444,[{id:'1',kind:'OPEN'}],[{at:0,kind:'THROW',operationId:'1'}]);const mk=()=>runAutonomousReliabilityLoop({incidentId:'inc-4',signal:{serviceId:'x',availability:0,errorRate:1,p95Ms:999,budgetConsumedPct:100,replayMatches:false,newFailure:true},result:r,rolloutId:'r',blastRadius:{serviceIds:['x'],tenantIds:[],rolloutIds:['r']}},new InMemoryRuntimeEnforcer());assert.equal(mk().evidenceHash,mk().evidenceHash)});

test('V144 learn phase records a policy learning hash',async()=>{const {InMemoryReliabilityLearner}=await import('../modules/platform/autonomous-reliability-loop/learning.ts');const e=new InMemoryRuntimeEnforcer();const r=executeCase(1445,[{id:'1',kind:'OPEN'}],[{at:0,kind:'THROW',operationId:'1'}]);const out=runAutonomousReliabilityLoop({incidentId:'inc-5',signal:{serviceId:'x',availability:0,errorRate:1,p95Ms:999,budgetConsumedPct:100,replayMatches:false,newFailure:true,failureHash:'h1'},result:r,rolloutId:'r',blastRadius:{serviceIds:['x'],tenantIds:[],rolloutIds:['r']}},e,undefined,undefined,new InMemoryReliabilityLearner());assert.match(out.learningHash,/^[a-f0-9]{64}$/)});
