import test from 'node:test';
import assert from 'node:assert/strict';
import {executeCase} from '../modules/platform/reliability-lab/engine.ts';
import {InMemoryProductionReliabilityRuntime} from '../modules/platform/production-reliability/runtime.ts';
import {runProductionReliabilityCycle} from '../modules/platform/production-reliability/controller.ts';
import {createReleaseCandidate} from '../modules/platform/production-reliability/candidate.ts';
import {createEvidenceBundle} from '../modules/platform/production-reliability/evidence.ts';

test('V145 healthy production signal resumes and reconciles runtime state',()=>{const r=new InMemoryProductionReliabilityRuntime();r.setSignal({serviceId:'checkout',rolloutId:'r1',availability:1,errorRate:0,p95Ms:10,budgetConsumedPct:0,replayMatches:true,newFailure:false});const out=runProductionReliabilityCycle({incidentId:'i1',serviceId:'checkout',rolloutId:'r1',result:executeCase(1451,[{id:'1',kind:'OPEN'}],[]),blastRadius:{serviceIds:['checkout'],tenantIds:[],rolloutIds:['r1']}},r);assert.equal(out.loop.decision,'RESUME');assert.equal(out.runtimeVerified,true);assert.equal(out.incident.status,'RECOVERED');assert.deepEqual(r.snapshot().frozenRollouts,[])});
test('V145 failed recovery remains frozen and escalates',()=>{const r=new InMemoryProductionReliabilityRuntime();r.setSignal({serviceId:'payments',rolloutId:'r2',availability:0,errorRate:1,p95Ms:900,budgetConsumedPct:100,replayMatches:false,newFailure:true});const failed=executeCase(1452,[{id:'1',kind:'OPEN'}],[{at:0,kind:'THROW',operationId:'1'}]);const out=runProductionReliabilityCycle({incidentId:'i2',serviceId:'payments',rolloutId:'r2',result:failed,blastRadius:{serviceIds:['payments'],tenantIds:['t2'],rolloutIds:['r2']}},r);assert.equal(out.loop.decision,'ESCALATE');assert.equal(out.runtimeVerified,true);assert.equal(out.incident.status,'ESCALATED');assert.deepEqual(r.snapshot().frozenRollouts,['r2'])});
test('V145 rollback verification can reach a verified terminal state',()=>{const r=new InMemoryProductionReliabilityRuntime();r.setSignal({serviceId:'orders',rolloutId:'r3',availability:0.8,errorRate:.2,p95Ms:800,budgetConsumedPct:20,replayMatches:false,newFailure:true});const failed=executeCase(1453,[{id:'1',kind:'OPEN'}],[{at:0,kind:'THROW',operationId:'1'}]);const healthy=executeCase(1453,[{id:'1',kind:'OPEN'}],[]);const out=runProductionReliabilityCycle({incidentId:'i3',serviceId:'orders',rolloutId:'r3',result:failed,blastRadius:{serviceIds:['orders'],tenantIds:[],rolloutIds:['r3']}},r,undefined,undefined,healthy);assert.equal(out.loop.status,'ROLLED_BACK');assert.equal(out.loop.recovery.verified,true);assert.equal(out.runtimeVerified,true);assert.deepEqual(r.snapshot().frozenRollouts,[])})
test('V145 release candidate and evidence hashes are deterministic',()=>{const a=createReleaseCandidate({version:'145.0.0',sourceFingerprint:'s',migrationFingerprint:'m',policyRevision:'p',buildRef:'b',createdAt:'2026-09-03T00:00:00.000Z'});const b=createReleaseCandidate({version:'145.0.0',sourceFingerprint:'s',migrationFingerprint:'m',policyRevision:'p',buildRef:'b',createdAt:'2026-09-03T00:00:00.000Z'});assert.equal(a.candidateHash,b.candidateHash);const r=new InMemoryProductionReliabilityRuntime();r.setSignal({serviceId:'x',rolloutId:'r',availability:1,errorRate:0,p95Ms:1,budgetConsumedPct:0,replayMatches:true,newFailure:false});const cycle=runProductionReliabilityCycle({incidentId:'i4',serviceId:'x',rolloutId:'r',result:executeCase(1454,[{id:'1',kind:'OPEN'}],[]),blastRadius:{serviceIds:['x'],tenantIds:[],rolloutIds:['r']}},r);const e1=createEvidenceBundle(a.candidateHash,cycle),e2=createEvidenceBundle(a.candidateHash,cycle);assert.equal(e1.bundleHash,e2.bundleHash)})
