import test from 'node:test'; import assert from 'node:assert/strict';
import {ProductionControlPlane} from '../modules/platform/production-control-plane/controller.ts'; import {MemoryControlPlaneStore} from '../modules/platform/production-control-plane/store.ts'; import {StaticTelemetrySource,MemoryTelemetrySink} from '../modules/platform/production-control-plane/telemetry.ts';
class Fake{constructor(){this.calls=[];this.healthy=true}async preflight(){this.calls.push('preflight');return true}async deploy(){this.calls.push('deploy');return{revision:'sha256:demo'}}async shiftTraffic(){this.calls.push('shift');return true}async promote(){this.calls.push('promote');return true}async rollback(){this.calls.push('rollback');return true}async verify(){this.calls.push('verify');return this.healthy}}
const intent=(id='v150-1')=>({deploymentId:id,owner:'control-plane',idempotencyKey:id,target:{namespace:'prod',workload:'web',container:'web',image:'registry/app@sha256:abc',replicas:3},traffic:{service:'web',weightPct:10}});
const good={service:'web',timestampMs:1700000000000,availability:.999,errorRate:.001,p95Ms:120,saturationPct:40,healthy:true}; const policy={minAvailability:.995,maxErrorRate:.005,maxP95Ms:500,maxSaturationPct:90,requireHealthy:true};
test('V150 production control plane promotes after real reliability gates',async()=>{const f=new Fake(),cp=new ProductionControlPlane(f,new MemoryControlPlaneStore(),new StaticTelemetrySource(good),new MemoryTelemetrySink(),policy),r=await cp.execute(intent());assert.equal(r.phase,'COMPLETE');assert.equal(r.decision,'PROMOTE');assert.equal(r.runtimeVerified,true);assert.match(r.evidenceHash,/^[a-f0-9]{64}$/);assert.deepEqual(f.calls,['preflight','deploy','shift','verify','promote','verify'])});
test('V150 reliability failure rolls back and verifies recovery',async()=>{const f=new Fake(),bad={...good,errorRate:.2},cp=new ProductionControlPlane(f,new MemoryControlPlaneStore(),new StaticTelemetrySource(bad),new MemoryTelemetrySink(),policy);await assert.rejects(()=>cp.execute(intent('v150-2')),/RELIABILITY_GATE_FAILED/);assert.equal(f.calls.includes('rollback'),true);assert.equal(f.calls.filter(x=>x==='verify').length,1)});
test('V150 rollback verification fails closed',async()=>{const f=new Fake();f.healthy=false;const cp=new ProductionControlPlane(f,new MemoryControlPlaneStore(),new StaticTelemetrySource(good),new MemoryTelemetrySink(),policy);await assert.rejects(()=>cp.execute(intent('v150-3')),/ROLLBACK_VERIFICATION_FAILED/)});
test('V150 idempotency returns cached completed result',async()=>{const f=new Fake(),cp=new ProductionControlPlane(f,new MemoryControlPlaneStore(),new StaticTelemetrySource(good),new MemoryTelemetrySink(),policy);const a=await cp.execute(intent('v150-4')),b=await cp.execute(intent('v150-4'));assert.equal(b.evidenceHash,a.evidenceHash);assert.equal(f.calls.filter(x=>x==='deploy').length,1)});
test('V150 OTLP sink performs a real HTTP export',async()=>{const {createServer}=await import('node:http');let received=false;const server=createServer((req,res)=>{received=req.method==='POST'&&req.headers['content-type']==='application/json';req.resume();req.on('end',()=>{res.statusCode=200;res.end('ok')})});await new Promise(r=>server.listen(0,'127.0.0.1',r));const {OtlpHttpTelemetrySink}=await import('../modules/platform/production-control-plane/telemetry.ts');const port=server.address().port;await new OtlpHttpTelemetrySink(`http://127.0.0.1:${port}/v1/logs`).emit(good);await new Promise(r=>server.close(r));assert.equal(received,true)});
