import test from 'node:test'; import assert from 'node:assert/strict';
import {forecastDemand,planReplenishment,rankSuppliers,buildPurchaseOrder,calculateLandedCost,allocateInventory} from '../modules/platform/global-supply-chain/core.ts';

test('V168 forecasts weighted demand deterministically',()=>{const f=forecastDemand('p',[{date:'2026-09-01',quantity:10,weight:1},{date:'2026-09-02',quantity:20,weight:2}],14);assert.equal(f.dailyDemand,50/3);assert.equal(f.peakDailyDemand,20);assert.ok(f.confidence>.5);});
test('V168 replenishment protects lead-time and safety stock',()=>{const f=forecastDemand('p',[{date:'1',quantity:10},{date:'2',quantity:10}],14);const p=planReplenishment(f,{productId:'p',onHand:20,reserved:5,inbound:0,leadTimeDays:5,safetyDays:2,reviewDays:2});assert.equal(p.targetStock,90);assert.equal(p.recommendedQuantity,75);assert.equal(p.urgency,'NOW');});
test('V168 supplier ranking fails closed on critical risk',()=>{const r=rankSuppliers([{supplierId:'bad',name:'Bad',active:true,leadTimeDays:2,minOrderQty:1,capacityUnits:100,qualityScore:99,onTimeScore:99,priceScore:99,regions:['EG'],risk:'CRITICAL'},{supplierId:'good',name:'Good',active:true,leadTimeDays:3,minOrderQty:1,capacityUnits:100,qualityScore:90,onTimeScore:90,priceScore:90,regions:['EG'],risk:'LOW'}],'EG',10);assert.equal(r[0].supplierId,'good');assert.equal(r[1].eligible,false);});
test('V168 purchase order uses bigint money arithmetic',()=>{const s={supplierId:'s1',name:'S',active:true,leadTimeDays:7,minOrderQty:1,capacityUnits:100,qualityScore:90,onTimeScore:90,priceScore:90,regions:['EG'],risk:'LOW'};const po=buildPurchaseOrder('po1',s,'EGP',[{productId:'p',quantity:3,unitCostMinor:1001n}]);assert.equal(po.subtotalMinor,3003n);});
test('V168 landed cost includes logistics and trade costs',()=>{const x=calculateLandedCost({unitCostMinor:1000n,freightMinor:500n,dutyMinor:200n,taxMinor:300n,otherMinor:0n,quantity:2});assert.equal(x.totalMinor,3000n);assert.equal(x.unitLandedMinor,1500n);});
test('V168 inventory allocation is capacity bounded and deterministic',()=>{const x=allocateInventory(120,[{nodeId:'a',region:'EG',availableUnits:100,capacityUnits:100,distanceScore:50},{nodeId:'b',region:'EG',availableUnits:100,capacityUnits:200,distanceScore:60}],'EG');assert.equal(x.reduce((s,v)=>s+v.quantity,0),120);assert.equal(x[0].nodeId,'a');});
