import test from 'node:test'; import assert from 'node:assert/strict';
import {calculateFees,computeUnitEconomics,createBalancedJournal,buildPayout,runWhatIf} from '../modules/platform/financial-commerce/core.ts';

test('V169 fee engine calculates deterministic bps fees',()=>{const x=calculateFees(10000n,500n,[{feeId:'f',name:'marketplace',basis:'GMV',rateBps:1500,fixedMinor:30n,active:true}]);assert.equal(x[0].amountMinor,1530n);});
test('V169 unit economics uses bigint and exposes contribution',()=>{const x=computeUnitEconomics({priceMinor:10000n,productCostMinor:3500n,fulfillmentMinor:1000n,paymentMinor:300n,marketplaceFeeMinor:1200n,adMinor:500n,returnsReserveMinor:300n,taxMinor:700n,otherVariableMinor:100n});assert.equal(x.variableCostMinor,7600n);assert.equal(x.contributionMinor,2400n);assert.equal(x.breakEvenPriceMinor,7600n);});
test('V169 ledger rejects imbalance',()=>{assert.throws(()=>createBalancedJournal('j','EGP','sale',[{entryId:'1',accountId:'cash',side:'DEBIT',amountMinor:100n,currency:'EGP',reference:'s',status:'POSTED',createdAt:'2026-09-05'}]),/unbalanced/);});
test('V169 ledger accepts balanced double entry',()=>{const j=createBalancedJournal('j','EGP','sale',[{entryId:'1',accountId:'cash',side:'DEBIT',amountMinor:100n,currency:'EGP',reference:'s',status:'POSTED',createdAt:'2026-09-05'},{entryId:'2',accountId:'revenue',side:'CREDIT',amountMinor:100n,currency:'EGP',reference:'s',status:'POSTED',createdAt:'2026-09-05'}]);assert.equal(j.balanced,true);});
test('V169 payout reserves fees refunds and held balance',()=>{const p=buildPayout('p','seller','EGP',10000n,1200n,500n,300n,'HELD');assert.equal(p.netMinor,8000n);assert.equal(p.status,'HELD');});
test('V169 what-if scenario changes economics without mutating input',()=>{const input={priceMinor:10000n,productCostMinor:4000n,fulfillmentMinor:1000n,paymentMinor:300n,marketplaceFeeMinor:1000n,adMinor:500n,returnsReserveMinor:200n,taxMinor:500n,otherVariableMinor:100n};const x=runWhatIf(input,1000,-2000,-1000);assert.equal(x.result.revenueMinor,11000n);assert.equal(input.priceMinor,10000n);});
