import test from 'node:test'; import assert from 'node:assert/strict';
import {authorizeAction,buildOverview,fraudRisk,fraudScore,rankNextBestAction,registerAgent} from '../modules/platform/autonomous-commerce-fabric/core.ts';
const agent={agentId:'a1',tenantId:'t1',name:'Ops',version:'1',capabilities:['ship'],status:'ACTIVE',trustScore:.95,maxRisk:'medium',maxAutonomy:'AUTO_EXECUTE'};
test('agent registry replaces same tenant identity deterministically',()=>{const next=registerAgent([],agent);assert.equal(registerAgent(next,{...agent,version:'2'}).length,1);assert.equal(registerAgent(next,{...agent,version:'2'})[0].version,'2');});
test('zero trust blocks cross tenant and missing capability',()=>{assert.equal(authorizeAction({tenantId:'t2',agentId:'a1',capability:'ship',risk:'low',confidence:.99,reversible:true,estimatedCost:1,budget:10,payload:{}},agent).reason,'AGENT_NOT_TRUSTED');assert.equal(authorizeAction({tenantId:'t1',agentId:'a1',capability:'refund',risk:'low',confidence:.99,reversible:true,estimatedCost:1,budget:10,payload:{}},agent).reason,'CAPABILITY_DENIED');});
test('autonomy firewall enforces confidence risk and budget',()=>{assert.equal(authorizeAction({tenantId:'t1',agentId:'a1',capability:'ship',risk:'high',confidence:.99,reversible:true,estimatedCost:1,budget:10,payload:{}},agent).reason,'RISK_CEILING_EXCEEDED');assert.equal(authorizeAction({tenantId:'t1',agentId:'a1',capability:'ship',risk:'low',confidence:.7,reversible:true,estimatedCost:1,budget:10,payload:{}},agent).approvalRequired,true);assert.equal(authorizeAction({tenantId:'t1',agentId:'a1',capability:'ship',risk:'low',confidence:.99,reversible:true,estimatedCost:11,budget:10,payload:{}},agent).reason,'BUDGET_EXCEEDED');});
test('fraud engine exposes score and multi-signal risk',()=>{assert.ok(fraudScore({velocity:90,returnRate:60,deviceRisk:70,paymentMismatch:true,accountAgeDays:2,shippingMismatch:true})>=75);assert.equal(fraudRisk({velocity:90,returnRate:60,deviceRisk:70,paymentMismatch:true,accountAgeDays:2,shippingMismatch:true}),'critical');});
test('next best action filters invalid candidates and ranks by value',()=>{const r=rankNextBestAction([{id:'a',impact:100,confidence:1,cost:2,risk:'low',reversible:true},{id:'b',impact:10,confidence:1,cost:0,risk:'low',reversible:true},{id:'bad',impact:-1,confidence:1,cost:0,risk:'low',reversible:true}]);assert.equal(r[0].id,'a');assert.ok(!r.find(x=>x.id==='bad'));});
test('fabric overview is data driven, not a name-only page',()=>{const o=buildOverview({agents:[agent],pendingActions:1,events:100,failedExecutions:2,products:[{id:'p',name:'P',price:100,oldPrice:120,rating:5,stock:10,merchant:'M',category:'C',tags:['x']}],fraudSignals:[]});assert.equal(o.topProducts[0].id,'p');assert.ok(o.inventoryValue===1000);assert.ok(o.healthScore>0);});
