import test from 'node:test';import assert from 'node:assert/strict';import {assertProviderReady,validateRegistration,registerProvider,checkProviderReady} from '../modules/platform/provider-capability-registry/core.ts';
const base={provider:'sandbox-psp',adapter:'sandbox-psp-adapter',environment:'SANDBOX',capabilities:['PAYMENT_AUTHORIZE'],certification:'PASSED',health:'HEALTHY'};
test('V188 validates and deduplicates capabilities',()=>{assert.deepEqual(validateRegistration({...base,capabilities:['PAYMENT_AUTHORIZE','PAYMENT_AUTHORIZE']} ).capabilities,['PAYMENT_AUTHORIZE']);});
test('V188 blocks unregistered capability',()=>{assert.equal(assertProviderReady(base,'PAYMENT_REFUND').reason,'CAPABILITY_NOT_REGISTERED');});
test('V188 requires certification before execution',()=>{assert.equal(assertProviderReady({...base,certification:'UNVERIFIED'},'PAYMENT_AUTHORIZE').ready,false);assert.equal(assertProviderReady({...base,certification:'UNVERIFIED'},'PAYMENT_AUTHORIZE').reason,'CERTIFICATION_UNVERIFIED');});
test('V188 requires healthy live provider',()=>{assert.equal(assertProviderReady({...base,environment:'LIVE',health:'DEGRADED'},'PAYMENT_AUTHORIZE').reason,'HEALTH_DEGRADED');});
test('V188 blocks expired certification',()=>{assert.equal(assertProviderReady({...base,expiresAt:'2020-01-01T00:00:00Z'},'PAYMENT_AUTHORIZE',new Date('2026-01-01')).reason,'CERTIFICATION_EXPIRED');});
test('V188 persists provider registration',async()=>{let sql='';const store={query:async(q)=>{sql=q;return {rows:[]}}};const r=await registerProvider(store,base);assert.equal(r.provider,'sandbox-psp');assert.match(sql,/trust_provider_capabilities/);assert.match(sql,/on conflict/i);});
test('V188 fails closed when provider is absent',async()=>{const store={query:async()=>({rows:[]})};const r=await checkProviderReady(store,{provider:'missing',environment:'LIVE',capability:'PAYMENT_AUTHORIZE'});assert.equal(r.ready,false);assert.equal(r.reason,'PROVIDER_NOT_REGISTERED');});
