import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=f=>fs.readFileSync(f,'utf8');

test('V233 defines a real fulfillment provider adapter boundary',()=>{const c=read('modules/platform/fulfillment-providers/contracts.ts');const a=read('modules/platform/fulfillment-providers/http-adapter.ts');assert.match(c,/FulfillmentProviderAdapter/);assert.match(c,/createLabel/);assert.match(c,/getTracking/);assert.match(a,/PROVIDER_REQUIRED/);assert.match(a,/fetch\(/);});
test('V233 label execution is transactional and provider-backed',()=>{const s=read('modules/platform/fulfillment-providers/execution.ts');assert.match(s,/withPgTransaction/);assert.match(s,/createLabel/);assert.match(s,/provider_reference/);assert.match(s,/fulfillment\.label\.created/);});
test('V233 shipment webhooks are signed and durably queued',()=>{const r=read('app/api/fulfillment/providers/webhook/route.ts');const e=read('modules/platform/fulfillment-providers/execution.ts');assert.match(r,/x-trust-signature/);assert.match(r,/x-trust-timestamp/);assert.match(e,/verifyWebhook/);assert.match(e,/ingestWebhook/);assert.match(e,/trust_shipment_provider_events/);assert.match(e,/trust_shipment_reconciliation_jobs/);});
test('V233 reconciliation worker is lease based with retries',()=>{const s=read('modules/platform/fulfillment-providers/execution.ts');assert.match(s,/for update skip locked/);assert.match(s,/lease_until/);assert.match(s,/attempts>=5/);assert.match(s,/fulfillment\.tracking\.reconciled/);});
test('V233 control tower is database-backed and privileged',()=>{const r=read('app/api/fulfillment/control-tower/route.ts');const p=read('app/fulfillment-control-tower/page.tsx');assert.match(r,/trust_shipments/);assert.match(r,/trust_shipment_reconciliation_jobs/);assert.match(r,/PRIVILEGED_ACCESS_REQUIRED/);assert.match(p,/FulfillmentControlTowerSurface/);});
test('V233 migration adds provider references and reconciliation durable state',()=>{const s=read('db/migrations/083_v233_fulfillment_provider_execution.sql');assert.match(s,/provider_reference/);assert.match(s,/trust_shipment_provider_events/);assert.match(s,/trust_shipment_reconciliation_jobs/);});
test('V233 migration manifest and runtime are canonical',()=>{const m=JSON.parse(read('db/migrations/MANIFEST.json'));const row=m.migrations.find(x=>x.file==='083_v233_fulfillment_provider_execution.sql');assert.ok(row?.checksum);assert.equal(m.latest,'101');assert.equal(m.version.match(/^V\d+\.0\.0$/)?.[0],m.version);assert.match(read('lib/runtime/version.ts'),/V\d+\.0\.0/);assert.equal(JSON.parse(read('package.json')).version.match(/^\d+\.0\.0$/)?.[0],JSON.parse(read('package.json')).version);});
