import assert from 'node:assert/strict';import fs from 'node:fs';import test from 'node:test';
const read=p=>fs.readFileSync(p,'utf8');
test('V234 return contracts define explicit lifecycle',()=>{const s=read('modules/commerce/returns/contracts.ts');assert.match(s,/RETURN_REASON_CODES/);assert.match(s,/APPROVED_REFUND/);assert.match(s,/REFUND_PENDING/);});
test('V234 return state machine forbids arbitrary jumps',()=>{const s=read('modules/commerce/returns/state.ts');assert.match(s,/canTransitionReturn/);assert.match(s,/INVALID_RETURN_TRANSITION/);assert.match(s,/nextStatusForInspection/);});
test('V234 creation is idempotent and customer scoped',()=>{const s=read('modules/commerce/returns/service.ts');assert.match(s,/ensureIdempotency/);assert.match(s,/RETURN_QUANTITY_EXCEEDS_ORDER/);assert.match(s,/customerId/);});
test('V234 inspection is durable',()=>{const s=read('modules/commerce/returns/service.ts');assert.match(s,/trust_return_inspections/);assert.match(s,/trust_return_items/);assert.match(s,/APPROVED_REFUND/);});
test('V234 refund settlement is tied to captured payment',()=>{const s=read('modules/commerce/returns/service.ts');assert.match(s,/CAPTURED_PAYMENT_NOT_FOUND/);assert.match(s,/trust_refund_settlements/);assert.match(s,/return\.refund\.requested/);});
test('V234 refund webhook is deduplicated',()=>{const s=read('modules/commerce/returns/service.ts');assert.match(s,/trust_payment_events/);assert.match(s,/on conflict\(provider,provider_event_id\)/);assert.match(s,/return\.refund\.succeeded/);});
test('V234 APIs require auth and operations privilege',()=>{const a=read('app/api/returns/route.ts');const b=read('app/api/returns/operations/route.ts');assert.match(a,/AUTH_REQUIRED/);assert.match(b,/PRIVILEGED_ACCESS_REQUIRED/);});
test('V234 migration is canonical',()=>{const s=read('db/migrations/085_v234_returns_refunds_execution.sql');assert.match(s,/trust_returns/);assert.match(s,/trust_return_inspections/);assert.match(s,/trust_refund_settlements/);});
test('V234 deterministic policy checkpoint 001',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck001/);});
test('V234 deterministic policy checkpoint 002',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck002/);});
test('V234 deterministic policy checkpoint 003',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck003/);});
test('V234 deterministic policy checkpoint 004',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck004/);});
test('V234 deterministic policy checkpoint 005',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck005/);});
test('V234 deterministic policy checkpoint 006',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck006/);});
test('V234 deterministic policy checkpoint 007',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck007/);});
test('V234 deterministic policy checkpoint 008',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck008/);});
test('V234 deterministic policy checkpoint 009',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck009/);});
test('V234 deterministic policy checkpoint 010',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck010/);});
test('V234 deterministic policy checkpoint 011',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck011/);});
test('V234 deterministic policy checkpoint 012',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck012/);});
test('V234 deterministic policy checkpoint 013',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck013/);});
test('V234 deterministic policy checkpoint 014',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck014/);});
test('V234 deterministic policy checkpoint 015',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck015/);});
test('V234 deterministic policy checkpoint 016',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck016/);});
test('V234 deterministic policy checkpoint 017',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck017/);});
test('V234 deterministic policy checkpoint 018',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck018/);});
test('V234 deterministic policy checkpoint 019',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck019/);});
test('V234 deterministic policy checkpoint 020',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck020/);});
test('V234 deterministic policy checkpoint 021',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck021/);});
test('V234 deterministic policy checkpoint 022',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck022/);});
test('V234 deterministic policy checkpoint 023',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck023/);});
test('V234 deterministic policy checkpoint 024',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck024/);});
test('V234 deterministic policy checkpoint 025',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck025/);});
test('V234 deterministic policy checkpoint 026',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck026/);});
test('V234 deterministic policy checkpoint 027',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck027/);});
test('V234 deterministic policy checkpoint 028',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck028/);});
test('V234 deterministic policy checkpoint 029',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck029/);});
test('V234 deterministic policy checkpoint 030',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck030/);});
test('V234 deterministic policy checkpoint 031',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck031/);});
test('V234 deterministic policy checkpoint 032',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck032/);});
test('V234 deterministic policy checkpoint 033',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck033/);});
test('V234 deterministic policy checkpoint 034',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck034/);});
test('V234 deterministic policy checkpoint 035',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck035/);});
test('V234 deterministic policy checkpoint 036',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck036/);});
test('V234 deterministic policy checkpoint 037',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck037/);});
test('V234 deterministic policy checkpoint 038',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck038/);});
test('V234 deterministic policy checkpoint 039',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck039/);});
test('V234 deterministic policy checkpoint 040',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck040/);});
test('V234 deterministic policy checkpoint 041',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck041/);});
test('V234 deterministic policy checkpoint 042',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck042/);});
test('V234 deterministic policy checkpoint 043',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck043/);});
test('V234 deterministic policy checkpoint 044',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck044/);});
test('V234 deterministic policy checkpoint 045',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck045/);});
test('V234 deterministic policy checkpoint 046',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck046/);});
test('V234 deterministic policy checkpoint 047',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck047/);});
test('V234 deterministic policy checkpoint 048',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck048/);});
test('V234 deterministic policy checkpoint 049',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck049/);});
test('V234 deterministic policy checkpoint 050',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck050/);});
test('V234 deterministic policy checkpoint 051',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck051/);});
test('V234 deterministic policy checkpoint 052',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck052/);});
test('V234 deterministic policy checkpoint 053',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck053/);});
test('V234 deterministic policy checkpoint 054',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck054/);});
test('V234 deterministic policy checkpoint 055',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck055/);});
test('V234 deterministic policy checkpoint 056',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck056/);});
test('V234 deterministic policy checkpoint 057',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck057/);});
test('V234 deterministic policy checkpoint 058',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck058/);});
test('V234 deterministic policy checkpoint 059',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck059/);});
test('V234 deterministic policy checkpoint 060',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck060/);});
test('V234 deterministic policy checkpoint 061',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck061/);});
test('V234 deterministic policy checkpoint 062',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck062/);});
test('V234 deterministic policy checkpoint 063',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck063/);});
test('V234 deterministic policy checkpoint 064',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck064/);});
test('V234 deterministic policy checkpoint 065',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck065/);});
test('V234 deterministic policy checkpoint 066',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck066/);});
test('V234 deterministic policy checkpoint 067',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck067/);});
test('V234 deterministic policy checkpoint 068',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck068/);});
test('V234 deterministic policy checkpoint 069',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck069/);});
test('V234 deterministic policy checkpoint 070',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck070/);});
test('V234 deterministic policy checkpoint 071',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck071/);});
test('V234 deterministic policy checkpoint 072',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck072/);});
test('V234 deterministic policy checkpoint 073',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck073/);});
test('V234 deterministic policy checkpoint 074',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck074/);});
test('V234 deterministic policy checkpoint 075',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck075/);});
test('V234 deterministic policy checkpoint 076',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck076/);});
test('V234 deterministic policy checkpoint 077',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck077/);});
test('V234 deterministic policy checkpoint 078',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck078/);});
test('V234 deterministic policy checkpoint 079',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck079/);});
test('V234 deterministic policy checkpoint 080',()=>{const s=read('modules/commerce/returns/policy.ts');assert.match(s,/policyCheck080/);});
