import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const core=read('modules/commerce/core/service.ts');
assert.doesNotMatch(core,/fixtures\/|products\s*=|const orders\s*=\s*\[|new Map/);
assert.match(core,/LEGACY_COMMERCE_PATH_DISABLED/);
const engine=read('modules/commerce/core/engine.ts');
assert.doesNotMatch(engine,/new Map/); assert.match(engine,/trust_checkout_quotes/); assert.match(engine,/consumed_at/);
const data=read('lib/data-core/store.ts');
assert.doesNotMatch(data,/InMemoryRepository|fixtures\/catalog/); assert.match(data,/DATABASE_NOT_CONFIGURED/); assert.match(data,/from trust_orders/);
const merchant=read('modules/commerce/merchant-ops/service.ts');
assert.doesNotMatch(merchant,/fixtures|new Map\(|catalog\.filter/); assert.match(merchant,/for update/); assert.match(merchant,/trust_inventory_ledger/);
const sql=read('db/migrations/091_v237_reality_consolidation.sql');
assert.match(sql,/trust_checkout_quotes/); assert.match(sql,/consumed_at/); assert.match(sql,/expires_at/);
const hardening=read('db/migrations/092_v238_production_reality_hardening.sql'); assert.match(hardening,/discount_code/); assert.match(hardening,/expires_at > created_at/);
const manifest=JSON.parse(read('db/migrations/MANIFEST.json')); assert.ok(Number(manifest.latest) >= 94, 'historical V237 regression must not pin the current migration head'); assert.ok(manifest.migrations.find(x=>x.file==='091_v237_reality_consolidation.sql')); assert.ok(manifest.migrations.find(x=>x.file==='092_v238_production_reality_hardening.sql'));
const merchantModules=fs.readdirSync(path.join(root,'modules/merchant-commerce')).filter(x=>x.endsWith('.ts')&&!['index.ts','store.ts','kernel.ts'].includes(x));
const sizes=merchantModules.map(x=>fs.statSync(path.join(root,'modules/merchant-commerce',x)).size); assert.ok(sizes.every(n=>n<15000),'merchant domain adapters must stay thin');
console.log('V237 reality consolidation tests: PASS');
