import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const registry=fs.readFileSync(path.join(root,'modules/platform/commerce-events/registry.ts'),'utf8');
const publisher=fs.readFileSync(path.join(root,'scripts/commerce_event_publisher.mjs'),'utf8');
const worker=fs.readFileSync(path.join(root,'scripts/commerce_consumer_mesh.mjs'),'utf8');
const tx=fs.readFileSync(path.join(root,'modules/platform/durable-events/tx.ts'),'utf8');
const migration=fs.readFileSync(path.join(root,'db/migrations/100_v246_runtime_consumer_registry.sql'),'utf8');
assert.match(registry,/export async function getSubscription/);
assert.match(registry,/export async function setSubscription/);
assert.match(registry,/export async function registerEventSchema/);
assert.match(registry,/enqueueSubscribedDeliveriesTx/);
assert.match(publisher,/enqueueSubscribedDeliveriesTx/);
assert.doesNotMatch(publisher,/CONSUMER_DEFINITIONS/);
assert.match(worker,/getSubscription/);
assert.match(worker,/subscription\.maxAttempts/);
assert.match(worker,/CONTRACT_VERSION_MISMATCH/);
assert.match(tx,/validateEventContractTx/);
assert.match(tx,/schema_version/);
assert.match(migration,/ADD COLUMN IF NOT EXISTS schema_version/);
assert.match(migration,/Backfill delivery/);
console.log('V246 runtime consumer registry contract: PASS');
