import assert from 'node:assert/strict';
import fs from 'node:fs';
import { execFileSync } from 'node:child_process';
import crypto from 'node:crypto';
import { promotionAuthorizationMessage, promotionAuthorizationPayloadHash, verifyPromotionSignature } from '../modules/platform/reality-promotion/authorization.ts';

const {publicKey,privateKey}=crypto.generateKeyPairSync('ed25519');
const publicKeyPem=publicKey.export({type:'spki',format:'pem'});
const privateKeyPem=privateKey.export({type:'pkcs8',format:'pem'});
const payload={decisionId:'test-decision',decisionHash:'a'.repeat(64),fromState:'PENDING_EXPLICIT_REVIEW',toState:'APPROVED',actorId:'reviewer-1',keyId:'key-1',rationale:'explicit approval',attestationRoot:'b'.repeat(64),evidenceLeaf:'c'.repeat(64)};
const signature=crypto.sign(null,promotionAuthorizationMessage(payload),privateKeyPem).toString('base64');
assert.equal(verifyPromotionSignature({algorithm:'ed25519',publicKeyPem,signatureBase64:signature,payload}),true);
assert.equal(verifyPromotionSignature({algorithm:'ed25519',publicKeyPem,signatureBase64:signature,payload:{...payload,toState:'REJECTED'}}),false);
assert.match(promotionAuthorizationPayloadHash(payload),/^[a-f0-9]{64}$/);
const migration=fs.readFileSync('db/migrations/103_v265_cryptographic_promotion_authorization.sql','utf8');
assert.match(migration,/trust_reality_promotion_signing_keys/);
assert.match(migration,/trust_reality_promotion_authorizations/);
assert.match(migration,/authorization_id/);
const store=fs.readFileSync('modules/platform/reality-promotion/store.ts','utf8');
assert.match(store,/verifyPromotionSignature/);
assert.match(store,/PROMOTION_SIGNATURE_INVALID/);
assert.match(store,/PROMOTION_SIGNER_ACTOR_MISMATCH/);
execFileSync(process.execPath,['scripts/reality_promotion_authorization.mjs'],{stdio:'pipe'});
const report=JSON.parse(fs.readFileSync('artifacts/reality/reality-promotion-authorization-v265.json','utf8'));
assert.equal(report.status,'CRYPTOGRAPHIC_AUTHORIZATION_VERIFIED');
assert.equal(report.demo.validSignature,true);
assert.equal(report.demo.tamperedPayloadRejected,true);
assert.equal(report.privateKeyPersisted,false);
console.log('V265 Promotion Authorization Test PASS — Ed25519 signature, payload binding, actor/key binding, and tamper rejection verified.');
