import assert from 'node:assert/strict';
import fs from 'node:fs';
import {execFileSync} from 'node:child_process';
const migration=fs.readFileSync('db/migrations/106_v268_promotion_command_gateway.sql','utf8');
for(const marker of ['trust_reality_promotion_commands','command_hash','uq_trust_reality_promotion_commands_hash_v268','command_id','result_event_hash','signature_digest','RECEIVED','APPLIED']) assert.ok(migration.includes(marker), marker);
const command=fs.readFileSync('modules/platform/reality-promotion/command.ts','utf8');
for(const marker of ['PROMOTION_COMMAND_VERSION','assertPromotionCommand','promotionCommandHash','commandTargetState']) assert.ok(command.includes(marker), marker);
const store=fs.readFileSync('modules/platform/reality-promotion/store.ts','utf8');
for(const marker of ['trust_reality_promotion_commands','promotionCommandHash','PROMOTION_COMMAND_TARGET_MISMATCH','idempotentReplay','command_id','PROMOTION_COMMAND_SIGNATURE_REPLAY_MISMATCH']) assert.ok(store.includes(marker), marker);
execFileSync(process.execPath,['scripts/reality_promotion_command_gateway.mjs'],{stdio:'pipe'});
const r=JSON.parse(fs.readFileSync('artifacts/reality/reality-promotion-command-gateway-v268.json','utf8'));
assert.equal(r.status,'PROMOTION_COMMAND_GATEWAY_VERIFIED');
assert.equal(r.command.tamperedCommandRejected,true);
assert.equal(r.command.idempotencyKeyBound,true);
assert.equal(r.command.targetStateBound,true);
assert.equal(r.controls.noAutoPromotion,true);
assert.equal(r.controls.privateKeyPersisted,false);
assert.equal(r.migration.latest,106);
console.log('V268 Promotion Command Gateway Test PASS — durable command identity, deterministic hashing, idempotent replay and authorization/event binding verified.');
