import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=f=>fs.readFileSync(f,'utf8');
const sql=read('db/migrations/122_v284_financial_loop.sql');
const mod=read('modules/marketplace/financial-loop.ts');
const tracking=read('modules/platform/fulfillment-tracking-3/core.ts');
const refunds=read('modules/commerce/payments/orchestrator.ts');
const route=read('app/api/merchant/finance/route.ts');
assert.match(sql,/trust_marketplace_payout_requests/);
assert.match(sql,/trust_marketplace_balance_releases/);
assert.match(sql,/trust_marketplace_reconciliation_runs/);
assert.match(sql,/idempotency_key text NOT NULL UNIQUE/);
assert.match(mod,/for update/i);
assert.match(mod,/INSUFFICIENT_AVAILABLE_BALANCE/);
assert.match(mod,/PAYOUT_REVERSAL/);
assert.match(mod,/reverseSellerSettlementForRefundTx/);
assert.match(tracking,/releaseDeliveredSettlementTx/);
assert.match(tracking,/delivery-release:/);
assert.match(refunds,/reverseSellerSettlementForRefundTx/);
assert.match(route,/getMerchantByUserId/);
assert.match(route,/requestPayoutTx/);
console.log('V284 financial loop contracts: 12/12 PASS');
