import assert from 'node:assert/strict';
import fs from 'node:fs';
import { planMarketplaceRun, transition } from '../modules/platform/v316/marketplace/engine.ts';

const command={tenantId:'tenant-1',sellerId:'seller-1',productId:'product-1',offerId:'offer-1',customerId:'customer-1',quantity:3,unitPriceMinor:10000n,shippingMinor:1500n,currency:'EGP',commissionBps:2000,idempotencyKey:'idem-1'};
const run=planMarketplaceRun(command);
assert.equal(run.subtotal.amountMinor,30000n);
assert.equal(run.total.amountMinor,31500n);
assert.equal(run.commission.amountMinor,6000n);
assert.equal(run.sellerNet.amountMinor,24000n);
assert.equal(run.steps.length,9);
assert.deepEqual(run.steps.map(s=>s.stage),['TENANT','SELLER','CATALOG','INVENTORY','ORDER','PAYMENT','FULFILLMENT','FINANCE','ANALYTICS']);
assert.equal(run.status,'READY');
transition(run,'TENANT','COMPLETED');
transition(run,'SELLER','COMPLETED');
transition(run,'CATALOG','COMPLETED');
transition(run,'INVENTORY','COMPLETED');
transition(run,'ORDER','COMPLETED');
transition(run,'PAYMENT','COMPLETED');
transition(run,'FULFILLMENT','COMPLETED');
transition(run,'FINANCE','COMPLETED');
transition(run,'ANALYTICS','COMPLETED');
assert.equal(run.status,'COMPLETED');
assert.throws(()=>planMarketplaceRun({...command,quantity:0}),/MARKETPLACE_QUANTITY_INVALID/);
assert.throws(()=>planMarketplaceRun({...command,currency:'US'}),/MARKETPLACE_CURRENCY_INVALID/);
assert.throws(()=>planMarketplaceRun({...command,commissionBps:10001}),/MARKETPLACE_COMMISSION_INVALID/);
const sql=fs.readFileSync('db/migrations/154_v316_marketplace_os_vertical_slice.sql','utf8');
for(const table of ['trust_v316_marketplace_runs','trust_v316_marketplace_events']) assert.match(sql,new RegExp(`CREATE TABLE IF NOT EXISTS ${table}`));
console.log('V316 Marketplace OS vertical slice tests PASS');
