import assert from 'node:assert/strict';
import fs from 'node:fs';
const sql=fs.readFileSync('db/migrations/179_v347_dispute_refund_execution.sql','utf8');
const dispute=fs.readFileSync('modules/marketplace/seller-disputes.ts','utf8');
const payments=fs.readFileSync('modules/commerce/payments/orchestrator.ts','utf8');
assert.match(sql,/dispute_case_id/);
assert.match(sql,/refund_status/);
assert.match(sql,/refunded_amount/);
assert.match(sql,/trust_refunds_dispute_case_unique/);
assert.match(dispute,/settleSellerDisputeRefundTx/);
assert.match(dispute,/dispute-refund:/);
assert.match(dispute,/trust_payment_provider_jobs/);
assert.match(dispute,/entryType:'CHARGEBACK'/);
assert.match(dispute,/entryType:'RELEASE'/);
assert.match(dispute,/held_balance/);
assert.match(payments,/settleSellerDisputeRefundTx/);
assert.match(payments,/dispute_case_id/);
assert.match(payments,/status:'succeeded'/);
assert.match(payments,/status:'failed'/);
console.log('V347 dispute refund execution: PASS');
