import assert from 'node:assert/strict';
import fs from 'node:fs';
const sql=fs.readFileSync('db/migrations/180_v348_payout_protection.sql','utf8');
const finance=fs.readFileSync('modules/marketplace/financial-loop.ts','utf8');
const sellerOps=fs.readFileSync('modules/marketplace/seller-operations.ts','utf8');
const route=fs.readFileSync('app/api/merchant/finance/route.ts','utf8');
const eligibility=fs.readFileSync('app/api/merchant/finance/payout-eligibility/route.ts','utf8');
assert.match(sql,/trust_marketplace_payout_eligibility_snapshots/);
assert.match(sql,/trust_marketplace_payout_eligibility_holds/);
assert.match(sql,/trust_marketplace_payout_eligibility_allocations/);
assert.match(sql,/eligibility_snapshot_id/);
assert.match(finance,/calculatePayoutEligibilityTx/);
assert.match(finance,/PAYOUT_NOT_ELIGIBLE/);
assert.match(finance,/INSUFFICIENT_PAYOUT_ELIGIBILITY/);
assert.match(finance,/held_balance=held_balance\+\$1/);
assert.match(finance,/dispute_hold/);
assert.match(finance,/return_exposure/);
assert.match(finance,/refund_provider_exposure/);
assert.match(finance,/RELEASED_SELLER_ORDER/);
assert.match(finance,/NON_ORDER_AVAILABLE/);
assert.match(finance,/status='CONSUMED'/);
assert.match(finance,/status='RELEASED'/);
assert.match(sellerOps,/requestPayoutTx/);
assert.match(route,/calculatePayoutEligibilityTx/);
assert.match(eligibility,/calculatePayoutEligibilityTx/);
console.log('V348 payout protection: PASS');
