import fs from 'node:fs';
import assert from 'node:assert/strict';
const migration=fs.readFileSync('db/migrations/181_v349_payout_provider_execution.sql','utf8');
const contracts=fs.readFileSync('modules/platform/payment-providers/contracts.ts','utf8');
const adapter=fs.readFileSync('modules/platform/payment-providers/http-adapter.ts','utf8');
const worker=fs.readFileSync('scripts/payment_provider_worker.mjs','utf8');
const financial=fs.readFileSync('modules/marketplace/financial-loop.ts','utf8');
const version=fs.readFileSync('lib/runtime/version.ts','utf8');
assert.match(migration,/kind IN \('CREATE_PAYMENT','REFUND','PAYOUT'\)/);
assert.match(migration,/payout_id uuid REFERENCES trust_marketplace_payout_requests/);
assert.match(migration,/trust_marketplace_payout_provider_attempts/);
assert.match(contracts,/createPayout\(input:/);
assert.match(adapter,/request\('\/payouts'/);
assert.match(worker,/job\.kind === 'PAYOUT'/);
assert.match(worker,/PAYOUT_ACCOUNT_NOT_ACTIVE/);
assert.match(worker,/applyPayoutProviderEvent/);
assert.match(financial,/values\('PAYOUT',\$1,\$2,\$3\)/);
assert.match(financial,/providerJobId/);
assert.match(version,/V(?:349|350|351|352|357)\.0\.0/);
console.log('V349 payout provider execution: PASS');
