import fs from 'node:fs';
import assert from 'node:assert/strict';
const migration=fs.readFileSync('db/migrations/182_v350_payout_webhook_reconciliation.sql','utf8');
const financial=fs.readFileSync('modules/marketplace/financial-loop.ts','utf8');
const route=fs.readFileSync('app/api/payments/payout/webhook/route.ts','utf8');
const version=fs.readFileSync('lib/runtime/version.ts','utf8');
assert.match(migration,/trust_marketplace_payout_provider_events/);
assert.match(migration,/UNIQUE\(provider,provider_event_id\)/);
assert.match(migration,/amount numeric\(18,2\)/);
assert.match(financial,/applyPayoutProviderWebhookTx/);
assert.match(financial,/PAYOUT_AMOUNT_MISMATCH/);
assert.match(financial,/PAYOUT_CURRENCY_MISMATCH/);
assert.match(financial,/PAYOUT_PROVIDER_EVENT_PAYLOAD_CONFLICT/);
assert.match(financial,/marketplace\.payout\.provider_webhook_processed/);
assert.match(route,/x-provider-signature/);
assert.match(route,/webhookVerifier\.verify/);
assert.match(route,/applyPayoutProviderWebhookTx/);
assert.match(route,/payout-webhook:/);
assert.match(version,/V(?:350|351|352|355|357)\.0\.0/);
console.log('V350 payout webhook reconciliation: PASS');
