import fs from 'node:fs';
import assert from 'node:assert/strict';
const migration=fs.readFileSync('db/migrations/183_v351_financial_integrity_reconciliation.sql','utf8');
const module=fs.readFileSync('modules/marketplace/financial-integrity.ts','utf8');
const route=fs.readFileSync('app/api/finance/seller-integrity-reconciliation/route.ts','utf8');
assert.match(migration,/trust_marketplace_reconciliation_findings/);
assert.match(migration,/BALANCE_LEDGER_DRIFT/);
assert.match(migration,/PAYOUT_OVERALLOCATION/);
assert.match(migration,/PAYOUT_HOLD_DRIFT/);
assert.match(migration,/SELLER_ORDER_PAYOUT_DRIFT/);
assert.match(module,/runSellerFinancialIntegrityReconciliationTx/);
assert.match(module,/FOR UPDATE|for update/);
assert.match(module,/SELLER_CREDIT/);
assert.match(module,/PAYOUT_OVERALLOCATION/);
assert.match(module,/PAYOUT_HOLD_DRIFT/);
assert.match(module,/SELLER_ORDER_PAYOUT_DRIFT/);
assert.match(module,/status='FAILED'/);
assert.match(route,/admin','operations/);
assert.match(route,/idempotency-key/);
assert.match(route,/surfaceStatus:'LIVE'/);
console.log('V351 financial integrity reconciliation: PASS');
