import fs from 'node:fs';
import assert from 'node:assert/strict';
const migration=fs.readFileSync('db/migrations/184_v352_unified_inventory_reservation.sql','utf8');
const reservations=fs.readFileSync('modules/commerce/inventory/reservations.ts','utf8');
const checkout=fs.readFileSync('modules/commerce/transactions/checkout.ts','utf8');
const globalCheckout=fs.readFileSync('modules/commerce/transactions/global-checkout.ts','utf8');
const version=fs.readFileSync('lib/runtime/version.ts','utf8');
assert.match(migration,/trust_inventory_reservations_order_offer_idx/);
assert.match(migration,/single checkout reservation authority/);
assert.match(reservations,/reserveInventoryTx/);
assert.match(reservations,/FOR UPDATE/);
assert.match(reservations,/trust_inventory_reservation_events/);
assert.match(reservations,/CHECKOUT_RESERVED/);
assert.match(reservations,/COD_CHECKOUT_CONSUMED/);
assert.match(reservations,/reservationStatus === 'reserved'/);
assert.match(reservations,/row.status === 'reserved' \|\| row.status === 'expired'|reservationStatus/);
assert.match(checkout,/reserveInventoryTx/);
assert.doesNotMatch(checkout,/update trust_marketplace_offers set stock=stock-\$1/);
assert.doesNotMatch(checkout,/insert into trust_inventory_reservations\(/);
assert.match(globalCheckout,/reserveInventoryTx/);
assert.doesNotMatch(globalCheckout,/update trust_marketplace_offers set stock=stock-\$1/);
assert.doesNotMatch(globalCheckout,/insert into trust_inventory_reservations\(/);
assert.match(version,/V(35[2-7]|40[0-3])\.0\.0/);
console.log('V352 unified inventory reservation: PASS');
