import fs from 'node:fs';
import assert from 'node:assert/strict';
const migration=fs.readFileSync('db/migrations/185_v353_fulfillment_allocation_authority.sql','utf8');
const allocation=fs.readFileSync('modules/marketplace/fulfillment-allocation.ts','utf8');
const fulfillment=fs.readFileSync('modules/marketplace/fulfillment-runtime.ts','utf8');
const reservations=fs.readFileSync('modules/commerce/inventory/reservations.ts','utf8');
const checkout=fs.readFileSync('modules/commerce/transactions/checkout.ts','utf8');
const globalCheckout=fs.readFileSync('modules/commerce/transactions/global-checkout.ts','utf8');
const version=fs.readFileSync('lib/runtime/version.ts','utf8');
assert.match(migration,/trust_fulfillment_allocations/);
assert.match(migration,/reservation_id uuid NOT NULL UNIQUE/);
assert.match(migration,/order_item_id uuid NOT NULL/);
assert.match(migration,/trust_sync_fulfillment_allocation_reservation_status/);
assert.match(allocation,/allocateFulfillmentOrderTx/);
assert.match(allocation,/AMBIGUOUS_LEGACY_RESERVATION/);
assert.match(allocation,/RESERVATION_LOCATION_MISMATCH/);
assert.match(allocation,/trust_fulfillment_allocations/);
assert.match(fulfillment,/allocateFulfillmentOrderTx/);
assert.match(fulfillment,/assertFulfillmentAllocationsReadyTx/);
assert.match(fulfillment,/transitionFulfillmentAllocationsTx/);
assert.match(reservations,/orderItemId\?: string/);
assert.match(reservations,/order_item_id/);
assert.match(checkout,/returning id/);
assert.match(checkout,/orderItemId:orderItem.id/);
assert.match(globalCheckout,/returning id/);
assert.match(globalCheckout,/orderItemId:orderItem.id/);
assert.match(version,/V35[3-7]\.0\.0/);
console.log('V353 fulfillment allocation authority: PASS');
