import fs from 'node:fs';
import assert from 'node:assert/strict';
const migration=fs.readFileSync('db/migrations/186_v354_fulfillment_inventory_execution.sql','utf8');
const execution=fs.readFileSync('modules/marketplace/fulfillment-inventory-execution.ts','utf8');
const fulfillment=fs.readFileSync('modules/marketplace/fulfillment-runtime.ts','utf8');
const version=fs.readFileSync('lib/runtime/version.ts','utf8');
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
const lock=JSON.parse(fs.readFileSync('package-lock.json','utf8'));
assert.match(migration,/trust_fulfillment_inventory_executions/);
assert.match(migration,/UNIQUE\(allocation_id, execution_type\)/);
assert.match(migration,/HANDOFF_SHIP/);
assert.match(migration,/movement_type.*SHIP/);
assert.match(execution,/executeFulfillmentHandoffTx/);
assert.match(execution,/for update/);
assert.match(execution,/FULFILLMENT_ON_HAND_INSUFFICIENT/);
assert.match(execution,/FULFILLMENT_RESERVED_INSUFFICIENT/);
assert.match(execution,/movement_type,quantity,reference_key,note/);
assert.match(execution,/HANDOFF_SHIP/);
assert.match(fulfillment,/executeFulfillmentHandoffTx/);
assert.match(fulfillment,/inventory-handoff/);
assert.match(version,/V(?:354|355|356|357)\.0\.0/);
assert.match(pkg.version,/35[4567]\.0\.0/);
assert.match(lock.packages[''].version,/35[4567]\.0\.0/);
console.log('V354 fulfillment inventory execution: PASS');
