import fs from 'node:fs';
import assert from 'node:assert/strict';
const migration=fs.readFileSync('db/migrations/187_v355_commerce_execution_kernel.sql','utf8');
const kernel=fs.readFileSync('modules/commerce/core/execution-kernel.ts','utf8');
const orderExec=fs.readFileSync('modules/commerce/core/order-execution.ts','utf8');
const version=fs.readFileSync('lib/runtime/version.ts','utf8');
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
const lock=JSON.parse(fs.readFileSync('package-lock.json','utf8'));
const manifest=JSON.parse(fs.readFileSync('db/migrations/MANIFEST.json','utf8'));
assert.match(migration,/trust_commerce_execution_steps/);
assert.match(migration,/FULFILLMENT_PREPARE/);
assert.match(migration,/UNIQUE\(execution_run_id, step_code\)/);
assert.match(migration,/status IN \('PENDING','RUNNING','SUCCEEDED','BLOCKED','FAILED'\)/);
assert.match(kernel,/beginCommerceExecutionStepTx/);
assert.match(kernel,/finishCommerceExecutionStepTx/);
assert.match(kernel,/resumeCommerceExecutionTx/);
assert.match(kernel,/prepareOrderFulfillmentTx/);
assert.match(kernel,/completeDeliveredOrderExecutionTx/);
assert.match(kernel,/FULFILLMENT_WAITING_FOR_OPERATIONAL_PROGRESS/);
assert.match(orderExec,/trust_commerce_execution_runs/);
assert.match(version,/V35[5-7]\.0\.0/);
assert.match(pkg.version,/35[5-7]\.0\.0/);
assert.match(lock.packages[''].version,/35[5-7]\.0\.0/);
assert.match(manifest.migrations.at(-1).id,/18[78]/);
assert.match(manifest.migrations.at(-1).file,/18[78]_.+\.sql/);
console.log('V355 commerce execution kernel: PASS');
