import fs from 'node:fs';
import assert from 'node:assert/strict';
const migration=fs.readFileSync('db/migrations/188_v356_distributed_commerce_workers.sql','utf8');
const worker=fs.readFileSync('modules/commerce/core/execution-worker.ts','utf8');
const runner=fs.readFileSync('scripts/commerce_execution_worker.mjs','utf8');
const orderExec=fs.readFileSync('modules/commerce/core/order-execution.ts','utf8');
const version=fs.readFileSync('lib/runtime/version.ts','utf8');
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
const lock=JSON.parse(fs.readFileSync('package-lock.json','utf8'));
const manifest=JSON.parse(fs.readFileSync('db/migrations/MANIFEST.json','utf8'));
assert.match(migration,/trust_commerce_execution_jobs/);
assert.match(migration,/trust_commerce_execution_attempts/);
assert.match(migration,/status IN \('PENDING','PROCESSING','WAITING','SUCCEEDED','DEAD'\)/);
assert.match(migration,/lease_until/);
assert.match(migration,/UNIQUE\(job_id, attempt_number\)/);
assert.match(worker,/enqueueCommerceExecutionJobTx/);
assert.match(worker,/for update skip locked/i);
assert.match(worker,/MAX_ATTEMPTS = 12/);
assert.match(migration,/failure_count integer NOT NULL DEFAULT 0/);
assert.match(worker,/status='DEAD'/);
assert.match(worker,/WORKER_LEASE_EXPIRED/);
assert.match(worker,/runCommerceExecutionWorker/);
assert.match(worker,/deadLetterCommerceExecutionJobs/);
assert.match(worker,/lease_token/);
assert.match(worker,/failure_count/);
assert.match(runner,/runCommerceExecutionWorker/);
assert.match(runner,/recoverExpiredCommerceExecutionLeases/);
assert.match(orderExec,/commerce-execution:\$\{input\.orderId\}:initial/);
assert.match(version,/V(?:356|357)\.0\.0/);
assert.match(pkg.version,/35[67]\.0\.0/);
assert.match(lock.packages[''].version,/35[67]\.0\.0/);
assert.equal(manifest.migrations.at(-1).id,'188');
assert.equal(manifest.migrations.at(-1).file,'188_v356_distributed_commerce_workers.sql');
console.log('V356 distributed commerce workers: PASS');
