'use client';

import { useEffect, useMemo, useState } from 'react';

type Signal={id:string;domain:string;label:string;value:number;unit?:string;confidence:number};
type Rec={id:string;priority:string;title:string;rationale:string;impact:string;confidence:number;requiresApproval:boolean};
type Scenario={id:string;name:string;description:string;projected:{revenueDelta:number;conversionDelta:number;marginDelta:number;riskScore:number}};
type Snapshot={signals:Signal[];recommendations:Rec[];scenarios:Scenario[];guardrails:{autonomousFinancialActions:false;approvalRequiredFor:string[]}};

export default function IntelligenceBrain(){
 const [data,setData]=useState<Snapshot|null>(null); const [loading,setLoading]=useState(true); const [selected,setSelected]=useState<string>(''); const [result,setResult]=useState<any>(null);
 useEffect(()=>{fetch('/api/intelligence',{cache:'no-store'}).then(r=>r.json()).then(setData).finally(()=>setLoading(false));},[]);
 const groups=useMemo(()=>{const m=new Map<string,Signal[]>(); (data?.signals??[]).forEach(s=>m.set(s.domain,[...(m.get(s.domain)??[]),s])); return [...m.entries()];},[data]);
 async function simulate(id:string){setSelected(id);setResult(null); const r=await fetch('/api/intelligence/scenario',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({scenarioId:id})}); setResult(await r.json());}
 return <main className="ib-page" dir="rtl"><div className="ib-shell"><header className="ib-hero"><div><span className="ib-eyebrow">TRUST APEX · V112 · INTELLIGENCE BRAIN</span><h1>Commerce Intelligence<span>.</span></h1><p>طبقة قرار موحّدة تقرأ إشارات التجارة، تحلل الفرص، تختبر السيناريوهات، وتطلب موافقة قبل أي إجراء حساس.</p></div><div className="ib-mode"><b>DECISION SUPPORT</b><span>Autonomous financial actions: OFF</span><small>AI يوصي ويشرح ويُحاكي؛ لا ينفّذ عمليات مالية حساسة تلقائيًا.</small></div></header>
 <section className="ib-command"><div><span className="ib-label">APEX LOOP</span><h2>Observe → Analyze → Predict → Simulate → Approve → Execute → Verify</h2></div><div className="ib-chip-row">{['Signals','Recommendations','Scenarios','Guardrails'].map(x=><span key={x}>{x}</span>)}</div></section>
 {loading?<div className="ib-loading">جاري تجميع إشارات الذكاء…</div>:<>
 <section><div className="ib-section-head"><div><span className="ib-label">SIGNAL GRAPH</span><h2>نبض المنظومة</h2></div><span className="ib-live">LIVE SNAPSHOT</span></div><div className="ib-signal-grid">{groups.map(([domain,items])=><article className="ib-card" key={domain}><span className="ib-domain">{domain.toUpperCase()}</span>{items.map(s=><div className="ib-signal" key={s.id}><div><b>{s.label}</b><small>confidence {Math.round(s.confidence*100)}%</small></div><strong>{s.value}{s.unit&&<em>{s.unit}</em>}</strong><i style={{width:`${Math.min(100,Math.max(5,s.confidence*100))}%`}}/></div>)}</article>)}</div></section>
 <section><div className="ib-section-head"><div><span className="ib-label">DECISION QUEUE</span><h2>أفضل القرارات المقترحة</h2></div></div><div className="ib-rec-grid">{data?.recommendations.map(r=><article className="ib-card ib-rec" key={r.id}><div className="ib-rec-top"><span className={`ib-priority ${r.priority}`}>{r.priority}</span><span>{Math.round(r.confidence*100)}% confidence</span></div><h3>{r.title}</h3><p>{r.rationale}</p><small>{r.impact}</small><button>{r.requiresApproval?'يتطلب موافقة':'مراجعة القرار'} →</button></article>)}</div></section>
 <section><div className="ib-section-head"><div><span className="ib-label">SCENARIO LAB</span><h2>جرّب المستقبل قبل التنفيذ</h2></div></div><div className="ib-scenarios">{data?.scenarios.map(s=><article className="ib-card ib-scenario" key={s.id}><span className="ib-domain">{s.name}</span><h3>{s.description}</h3><div className="ib-proj"><span>Revenue <b>{s.projected.revenueDelta>0?'+':''}{s.projected.revenueDelta}%</b></span><span>Conversion <b>+{s.projected.conversionDelta}%</b></span><span>Margin <b>{s.projected.marginDelta>0?'+':''}{s.projected.marginDelta}%</b></span><span>Risk <b>{s.projected.riskScore}</b></span></div><button onClick={()=>simulate(s.id)} className={selected===s.id?'selected':''}>محاكاة السيناريو</button></article>)}</div>{result&&<div className="ib-result"><b>{result.scenario.name}</b><span>Confidence {result.confidence}%</span><strong>{result.decision==='review'?'جاهز للمراجعة البشرية':'مرفوض تلقائيًا بسبب المخاطر'}</strong></div>}</section>
 <section className="ib-guard"><div><span className="ib-label">GOVERNANCE</span><h2>AI لا يتجاوز الحواجز</h2><p>القرارات المالية والحساسة تمر عبر Approval Gate وتُسجل في Decision Ledger قبل التنفيذ.</p></div><div className="ib-guards">{data?.guardrails.approvalRequiredFor.map(x=><span key={x}>✓ {x}</span>)}</div></section>
 </>}</div></main>
}
