'use client';
import {useEffect,useMemo,useState} from 'react';

type Opportunity={id:string;title:string;priority:number;impact:'HIGH'|'MEDIUM'|'LOW';reason:string;action:string;monetizable:boolean;evidence:string[]};
type Brief={healthScore:number;availability:number;fulfillment:number;catalog:number;stockUnits:number;orders:number;revenue:number;aov:number;lowStock:number;outOfStock:number;processing:number;shipped:number;opportunities:Opportunity[];restock:Array<{productId:string;productName:string;stock:number;urgency:number;action:string}>;listings:Array<{productId:string;score:number;missing:string[];strengths:string[];titleSuggestion:string;descriptionPrompt:string}>};
type Payload={ok:boolean;merchant?:{storeName:string;verificationStatus:string};brief?:Brief;error?:string};
const money=(n:number)=>new Intl.NumberFormat('ar-EG',{style:'currency',currency:'EGP',maximumFractionDigits:0}).format(n);
const tabs=[['command','مركز القيادة'],['catalog','جودة الكتالوج'],['inventory','المخزون'],['growth','النمو والربح']] as const;
export default function SellerSuperOS(){const [data,setData]=useState<Payload|null>(null);const [tab,setTab]=useState<typeof tabs[number][0]>('command');const [busy,setBusy]=useState(true);const [copied,setCopied]=useState('');
 useEffect(()=>{fetch('/api/seller-super-os',{cache:'no-store'}).then(async r=>{const d=await r.json();setData(d)}).catch(()=>setData({ok:false,error:'NETWORK'})).finally(()=>setBusy(false))},[]);
 const b=data?.brief; const urgent=useMemo(()=>b?.opportunities.slice(0,3)??[],[b]);
 const copy=(text:string)=>{navigator.clipboard?.writeText(text);setCopied(text);setTimeout(()=>setCopied(''),1600)};
 if(busy)return <main className="sso" dir="rtl"><div className="sso-shell sso-loading">جاري تشغيل Seller Super OS 3.0…</div></main>;
 if(!data?.ok||!b)return <main className="sso" dir="rtl"><div className="sso-shell"><div className="sso-alert">{data?.error==='AUTH_REQUIRED'?'سجّل الدخول بحساب تاجر.':data?.error==='MERCHANT_REQUIRED'?'الحساب الحالي ليس مرتبطًا بمتجر تاجر.':'تعذر تحميل مركز التاجر.'}</div></div></main>;
 return <main className="sso" dir="rtl"><div className="sso-shell"><header className="sso-hero"><div><span className="sso-eyebrow">TRUST APEX · V204 · SELLER SUPER OS 3.0</span><h1>{data.merchant?.storeName||'Seller Super OS'}<em>.</em></h1><p>مركز قيادة واحد للتاجر: الكتالوج، المخزون، الطلبات، الثقة، النمو والفرص القابلة للقياس — بدون أرقام وهمية.</p></div><div className="sso-score"><span>SELLER HEALTH</span><strong>{b.healthScore}</strong><small>/ 100</small><b>{data.merchant?.verificationStatus==='verified'?'VERIFIED':'REVIEW'}</b></div></header>
 <nav className="sso-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}<a href="/merchant-super-os">Merchant OS السابق</a><a href="/commerce-growth">Growth OS</a></nav>
 {tab==='command'&&<Command b={b} urgent={urgent}/>} {tab==='catalog'&&<Catalog b={b} copy={copy} copied={copied}/>} {tab==='inventory'&&<Inventory b={b}/>} {tab==='growth'&&<Growth b={b}/>} 
 <footer className="sso-footer"><span>V204 · Provider-neutral seller control plane</span><span>الاقتراحات لا تنفّذ مدفوعات أو إعلانات أو شحنات حساسة تلقائيًا.</span></footer></div></main>}
function Command({b,urgent}:{b:Brief;urgent:Opportunity[]}){return <section><div className="sso-kpis">{[['الإيرادات المرصودة',money(b.revenue),'من الطلبات المتاحة'],['الطلبات',String(b.orders),`${b.processing} قيد التجهيز`],['الكتالوج',String(b.catalog),`${b.outOfStock} نافد`],['المخزون',String(b.stockUnits),`${b.lowStock} منخفض`]].map(([a,c,d])=><article key={a}><span>{a}</span><strong>{c}</strong><small>{d}</small></article>)}</div><div className="sso-grid"><article className="sso-card sso-command"><span className="sso-label">COMMAND BRIEF</span><h2>أهم 3 قرارات الآن</h2>{urgent.map(o=><div className="sso-op" key={o.id}><div className="sso-op-priority">{o.priority}</div><div><b>{o.title}</b><p>{o.reason}</p><small>{o.action}</small></div><span className={o.impact==='HIGH'?'hot':''}>{o.impact}</span></div>)}</article><article className="sso-card"><span className="sso-label">OPERATIONS RADAR</span><h2>الصحة التشغيلية</h2><Meter label="توفر الكتالوج" value={b.availability}/><Meter label="إتمام الطلبات" value={b.fulfillment}/><Meter label="جودة صفحات المنتج" value={b.listings.length?Math.round(b.listings.reduce((s,x)=>s+x.score,0)/b.listings.length):100}/><div className="sso-mini-grid"><b>{b.processing}<small>تجهيز</small></b><b>{b.shipped}<small>شحن</small></b><b>{b.outOfStock}<small>نافد</small></b></div></article></div><div className="sso-card"><span className="sso-label">MOAT</span><h2>منصة تاجر بدل لوحة أرقام</h2><p className="sso-muted">كل إشارة مرتبطة ببيانات تشغيلية فعلية، وكل فرصة لها سبب وإجراء وأثر monetization واضح. الربح الحقيقي لا يظهر إلا عندما تتوفر بيانات التكلفة والتسوية ومزوّد الدفع.</p></div></section>}
function Meter({label,value}:{label:string;value:number}){return <div className="sso-meter"><div><span>{label}</span><b>{value}%</b></div><i style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div>}
function Catalog({b,copy,copied}:{b:Brief;copy:(x:string)=>void;copied:string}){return <section><div className="sso-card"><span className="sso-label">LISTING INTELLIGENCE</span><h2>AI Listing Studio — بدون اختراع بيانات</h2><p className="sso-muted">راجع الصفحات الأضعف أولًا. الاقتراح النصي هنا مبني فقط على بيانات المنتج المتاحة، وليس ادعاءً بأن نموذجًا خارجيًا متصل.</p><div className="sso-listings">{b.listings.map(x=><article key={x.productId}><div className="sso-list-score">{x.score}</div><div><b>{x.productId}</b><p>{x.missing.length?`ناقص: ${x.missing.join('، ')}`:'الصفحة مكتملة مبدئيًا.'}</p><small>{x.titleSuggestion}</small></div><button onClick={()=>copy(x.descriptionPrompt)}>{copied===x.descriptionPrompt?'تم النسخ ✓':'نسخ Prompt'}</button></article>)}{!b.listings.length&&<p className="sso-muted">لا توجد منتجات للمراجعة.</p>}</div></div></section>}
function Inventory({b}:{b:Brief}){return <section><div className="sso-card"><span className="sso-label">INVENTORY COMMAND</span><h2>Restock Radar</h2>{b.restock.map(x=><div className="sso-restock" key={x.productId}><div><b>{x.productName}</b><small>{x.productId} · {x.action}</small></div><strong>{x.stock===0?'OUT':x.stock}</strong><span>{x.urgency}</span></div>)}{!b.restock.length&&<p className="sso-muted">المخزون الحالي لا يحتوي إشارات عاجلة.</p>}</div></section>}
function Growth({b}:{b:Brief}){return <section><div className="sso-grid"><article className="sso-card"><span className="sso-label">REVENUE ENGINE</span><h2>فرص قابلة للتحويل</h2>{b.opportunities.filter(x=>x.monetizable).map(x=><div className="sso-growth" key={x.id}><div><b>{x.title}</b><small>{x.reason}</small></div><strong>{x.priority}</strong></div>)}</article><article className="sso-card sso-ai"><span className="sso-label">SELLER COPILOT</span><h2>من القرار إلى التنفيذ</h2><p className="sso-muted">Deals، Coupons، Sponsored placements، Subscriptions، B2B وFulfillment موجودة كطبقات قابلة للربط. التنفيذ الخارجي يمر عبر الصلاحيات والـprovider adapters بدل نجاح وهمي.</p><a className="sso-primary" href="/commerce-growth">فتح Commerce Growth OS →</a></article></div><div className="sso-card"><span className="sso-label">FINANCE TRUTH</span><h2>AOV</h2><strong className="sso-big">{money(b.aov)}</strong><p className="sso-muted">متوسط قيمة الطلب المحسوب من البيانات المتاحة. Margin وPayout غير معروضة كأرقام حتى تتوفر تكلفة البضاعة والتسويات الفعلية.</p></div></section>}
