export type PaymentOperation='AUTHORIZE'|'CAPTURE'|'REFUND'|'CHARGEBACK';
export type PaymentProvider={id:string;currencies:string[];methods:string[];health:number;priority:number;enabled:boolean;capacityPct:number};
export type ProviderAttempt={providerId:string;attempt:number;status:'SELECTED'|'SUCCEEDED'|'FAILED';reason?:string};
export function routeWithFailover(providers:PaymentProvider[],input:{currency:string;method:string;exclude?:string[]}):{provider:PaymentProvider;attempts:ProviderAttempt[]}{const c=input.currency.toUpperCase(),m=input.method.toLowerCase(),excluded=new Set(input.exclude??[]);const eligible=providers.filter(p=>p.enabled&&!excluded.has(p.id)&&p.health>0&&p.capacityPct>0&&p.currencies.map(x=>x.toUpperCase()).includes(c)&&p.methods.map(x=>x.toLowerCase()).includes(m)).sort((a,b)=>b.health-a.health||b.capacityPct-a.capacityPct||a.priority-b.priority||a.id.localeCompare(b.id));if(!eligible[0])throw new Error('NO_PAYMENT_PROVIDER');return {provider:eligible[0],attempts:[{providerId:eligible[0].id,attempt:1,status:'SELECTED'}]};}
export type FinancialCommand={operation:PaymentOperation;idempotencyKey:string;amountMinor:bigint;currency:string;tenantId:string;orderId:string};
export function validateFinancialCommand(c:FinancialCommand):void{if(!c.tenantId||!c.orderId||!c.idempotencyKey||c.amountMinor<=0n||!/^[A-Z]{3}$/.test(c.currency.toUpperCase()))throw new Error('INVALID_FINANCIAL_COMMAND');}
export function idempotencyFingerprint(c:FinancialCommand):string{return [c.tenantId,c.orderId,c.operation,c.currency.toUpperCase(),c.amountMinor.toString(),c.idempotencyKey].join('|');}
export type LedgerLine={account:string;side:'DEBIT'|'CREDIT';amountMinor:bigint;currency:string};
export function balanced(lines:LedgerLine[]):boolean{if(!lines.length)return false;const d=new Map<string,bigint>(),cr=new Map<string,bigint>();for(const l of lines){if(l.amountMinor<=0n)throw new Error('INVALID_LEDGER_AMOUNT');const k=l.currency.toUpperCase();(l.side==='DEBIT'?d:cr).set(k,((l.side==='DEBIT'?d:cr).get(k)??0n)+l.amountMinor);}const currencies=new Set([...d.keys(),...cr.keys()]);for(const c of currencies)if((d.get(c)??0n)!==(cr.get(c)??0n))return false;return true;}
export function captureLedger(input:{grossMinor:bigint;platformFeeMinor:bigint;providerFeeMinor:bigint;currency:string}):LedgerLine[]{const seller=input.grossMinor-input.platformFeeMinor-input.providerFeeMinor;if(input.grossMinor<=0n||seller<0n)throw new Error('INVALID_CAPTURE_SPLIT');const lines=[{account:'cash',side:'DEBIT' as const,amountMinor:input.grossMinor,currency:input.currency},{account:'seller_payable',side:'CREDIT' as const,amountMinor:seller,currency:input.currency},{account:'platform_revenue',side:'CREDIT' as const,amountMinor:input.platformFeeMinor,currency:input.currency},{account:'payment_fees',side:'CREDIT' as const,amountMinor:input.providerFeeMinor,currency:input.currency}];if(!balanced(lines))throw new Error('UNBALANCED_LEDGER');return lines;}
export function reconcile(expectedMinor:bigint,providerMinor:bigint){const delta=providerMinor-expectedMinor;return {status:delta===0n?'MATCH':'MISMATCH' as const,deltaMinor:delta};}
