import type {ExecutionCommand,ExecutionPlan,ExecutionPolicy,ExecutionReceipt,RollbackResult} from './contracts.ts';
const finite=(n:number,k:string)=>{if(!Number.isFinite(n))throw new Error(`${k} must be finite`)};
const allowed=(a:ExecutionCommand['action'],p:ExecutionPolicy)=>!p.allowedActions||p.allowedActions.includes(a);
function validatePolicy(p:ExecutionPolicy){finite(p.maxRiskBps,'maxRiskBps');if(p.maxRiskBps<0)throw new Error('invalid maxRiskBps');if(p.maxBudgetMinor!==undefined&&p.maxBudgetMinor<0n)throw new Error('negative max budget');}
function validateCommand(c:ExecutionCommand){if(!c.commandId||!c.tenantId||!c.decisionId)throw new Error('command identity required');finite(c.riskBps,'riskBps');if(c.riskBps<0||c.riskBps>10000)throw new Error('invalid riskBps');if(c.budgetMinor!==undefined&&c.budgetMinor<0n)throw new Error('negative budget');}
export function planExecution(c:ExecutionCommand,p:ExecutionPolicy):ExecutionPlan{validatePolicy(p);validateCommand(c);if(!allowed(c.action,p))return {...c,status:'BLOCKED',requiresApproval:true,reason:'Action is outside the execution policy.'};if(c.riskBps>p.maxRiskBps)return {...c,status:'BLOCKED',requiresApproval:true,reason:'Risk exceeds the execution policy.'};if(p.maxBudgetMinor!==undefined&&c.budgetMinor!==undefined&&c.budgetMinor>p.maxBudgetMinor)return {...c,status:'BLOCKED',requiresApproval:true,reason:'Budget exceeds the execution policy.'};const riskApproval=p.requireApprovalAboveRiskBps!==undefined&&c.riskBps>=p.requireApprovalAboveRiskBps;const actionApproval=(p.requireApprovalForActions||[]).includes(c.action);const requiresApproval=Boolean(c.requiresApproval||riskApproval||actionApproval);return {...c,status:'READY',requiresApproval,reason:requiresApproval?'Execution is ready but requires explicit approval.':'Execution is policy-safe and ready.'};}
export function executeOnce(plan:ExecutionPlan,approved=false,now=Date.now(),seen=new Set<string>()):ExecutionReceipt{if(seen.has(plan.commandId))return {receiptId:`receipt-${plan.commandId}`,commandId:plan.commandId,tenantId:plan.tenantId,decisionId:plan.decisionId,status:'DUPLICATE',action:plan.action,executedAt:now,reason:'Idempotency key was already executed.'};if(plan.status!=='READY')return {receiptId:`receipt-${plan.commandId}`,commandId:plan.commandId,tenantId:plan.tenantId,decisionId:plan.decisionId,status:'BLOCKED',action:plan.action,executedAt:now,reason:plan.reason};if(plan.requiresApproval&&!approved)return {receiptId:`receipt-${plan.commandId}`,commandId:plan.commandId,tenantId:plan.tenantId,decisionId:plan.decisionId,status:'BLOCKED',action:plan.action,executedAt:now,reason:'Explicit approval is required before execution.'};seen.add(plan.commandId);return {receiptId:`receipt-${plan.commandId}`,commandId:plan.commandId,tenantId:plan.tenantId,decisionId:plan.decisionId,status:'EXECUTED',action:plan.action,rollbackToken:`rollback-${plan.commandId}`,executedAt:now,reason:'Command executed exactly once after policy and approval checks.'};}
export function rollback(receipt:ExecutionReceipt,tenantId:string,now=Date.now()):RollbackResult{if(receipt.tenantId!==tenantId)return {commandId:receipt.commandId,tenantId,status:'NOT_FOUND',at:now,reason:'Tenant isolation prevented rollback lookup.'};if(receipt.status!=='EXECUTED'||!receipt.rollbackToken)return {commandId:receipt.commandId,tenantId,status:'NOT_ROLLBACKABLE',at:now,reason:'Receipt has no active rollback token.'};return {commandId:receipt.commandId,tenantId,status:'ROLLED_BACK',at:now,reason:'Rollback authorized by matching tenant and active rollback token.'};}
export function simulateExecution(c:ExecutionCommand,p:ExecutionPolicy):ExecutionPlan{return planExecution(c,p);}
