/** Shared deterministic merchant-domain kernel. Domain files are thin adapters. */
export type MerchantDomainRecord = { id:string; merchantId:string; status:string; amount:number; quantity:number; score:number; createdAt:string; updatedAt:string; metadata:Record<string,string> };
export type MerchantDomainCommand = { merchantId:string; actorId:string; recordId?:string; status?:string; amount?:number; quantity?:number; metadata?:Record<string,string> };
const clean=(v:unknown,max=240)=>String(v??'').trim().slice(0,max);
const finite=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0;
const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
export function validate(input:Partial<MerchantDomainRecord>, statuses:readonly string[]){const e:string[]=[];if(!clean(input.id,120))e.push('id_required');if(!clean(input.merchantId,120))e.push('merchant_required');if(!statuses.includes(String(input.status)))e.push('status_invalid');if(finite(input.amount)<0)e.push('amount_negative');if(finite(input.quantity)<0)e.push('quantity_negative');if(finite(input.score)<0||finite(input.score)>100)e.push('score_out_of_range');return e;}
export function normalize(input:Partial<MerchantDomainRecord>, statuses:readonly string[]):MerchantDomainRecord{const now=new Date().toISOString();return{id:clean(input.id??`v237_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,10)}`,120),merchantId:clean(input.merchantId,120),status:statuses.includes(String(input.status))?String(input.status):String(statuses[0]??'ACTIVE'),amount:Math.max(0,finite(input.amount)),quantity:Math.max(0,finite(input.quantity)),score:clamp(finite(input.score)),createdAt:clean(input.createdAt??now,80),updatedAt:clean(input.updatedAt??now,80),metadata:Object.fromEntries(Object.entries(input.metadata??{}).map(([k,v])=>[clean(k,80),clean(v,240)]).filter(([k])=>k))};}
export function canTransition(from:string,to:string,statuses:readonly string[]){if(from===to)return true;const a=statuses.indexOf(from),b=statuses.indexOf(to);return a>=0&&b>=0&&(b>a||b===0);}
export function transition<T extends MerchantDomainRecord>(record:T,to:string,actorId:string,statuses:readonly string[]):T{if(!canTransition(record.status,to,statuses))throw new Error('INVALID_TRANSITION');if(!clean(actorId,120))throw new Error('ACTOR_REQUIRED');return {...record,status:to,updatedAt:new Date().toISOString(),metadata:{...record.metadata,lastActor:clean(actorId,120)}};}
export function summarize(records:MerchantDomainRecord[]){const total=records.length,amount=records.reduce((s,r)=>s+r.amount,0),quantity=records.reduce((s,r)=>s+r.quantity,0),avgScore=total?records.reduce((s,r)=>s+r.score,0)/total:0;const byStatus:Record<string,number>={};for(const r of records)byStatus[r.status]=(byStatus[r.status]??0)+1;return{total,amount,quantity,active:records.filter(r=>!/FAILED|CANCELLED|CLOSED|VOID/.test(r.status)).length,avgScore,byStatus};}
export function policy(record:MerchantDomainRecord,statuses:readonly string[]){const violations=validate(record,statuses),flags:string[]=[];if(Date.now()-Date.parse(record.updatedAt)>86400000)flags.push('STALE');if(record.score>=75||record.amount>=10000)flags.push('REVIEW');if(record.amount>0)flags.push('FINANCIAL');if(record.quantity>0)flags.push('QUANTITY');if(record.score>=70)flags.push('OPERATOR');return{allowed:violations.length===0,violations,flags};}
export const rule=(record:MerchantDomainRecord,context:any={})=>record.score>=(context.threshold??50)&&!['FAILED','CANCELLED','CLOSED','VOID'].includes(record.status);
export const ruleQuantity=(record:MerchantDomainRecord,context:any={})=>record.quantity>=(context.threshold??1)&&!!clean(record.merchantId,120);
export const ruleMerchant=(record:MerchantDomainRecord,context:any={})=>record.merchantId===clean(context.merchantId??record.merchantId,120)&&record.amount>=(context.threshold??0);
export const evaluate=(record:MerchantDomainRecord,context:any={})=>({allowed:policy(record,[]).allowed,score:record.score,threshold:context.threshold??50,merchantId:record.merchantId,status:record.status});
export function rank<T extends MerchantDomainRecord>(records:T[]){return [...records].sort((a,b)=>(Number(b.score>=85)-Number(a.score>=85))||(b.score-a.score)||(b.amount-a.amount)||a.id.localeCompare(b.id));}
export const filter=<T extends MerchantDomainRecord>(records:T[],predicate:(r:T)=>boolean)=>records.filter(predicate);
export const byMerchant=<T extends MerchantDomainRecord>(records:T[],merchantId:string)=>records.filter(r=>r.merchantId===clean(merchantId,120));
export const byStatus=<T extends MerchantDomainRecord>(records:T[],status:string)=>records.filter(r=>r.status===status);
export const totalAmount=(records:MerchantDomainRecord[])=>records.reduce((s,r)=>s+r.amount,0);
export const totalQuantity=(records:MerchantDomainRecord[])=>records.reduce((s,r)=>s+r.quantity,0);
export const averageScore=(records:MerchantDomainRecord[])=>records.length?records.reduce((s,r)=>s+r.score,0)/records.length:0;
export const mergeMetadata=<T extends MerchantDomainRecord>(record:T,patch:Record<string,string>)=>({...record,metadata:{...record.metadata,...patch},updatedAt:new Date().toISOString()});
export const redact=<T extends MerchantDomainRecord>(record:T)=>{const{metadata,...rest}=record;return{...rest,metadataKeys:Object.keys(metadata).sort()};};
export const assertOwnership=(record:MerchantDomainRecord,merchantId:string)=>{if(record.merchantId!==clean(merchantId,120))throw new Error('MERCHANT_OWNERSHIP_REQUIRED');};
