import {createHmac,timingSafeEqual} from 'node:crypto';
import type {SqlExecutor} from '../persistence/postgres-boundary.ts';
import type {ProviderEvent,ProviderWebhookVerifier,ReconciliationResult,ReconciliationJob} from './contracts';

const safeEqual=(a:string,b:string)=>{try{const x=Buffer.from(a,'utf8'),y=Buffer.from(b,'utf8');return x.length===y.length&&timingSafeEqual(x,y)}catch{return false}};
export const webhookVerifier:ProviderWebhookVerifier={verify(raw,signature,secret,timestamp,maxSkewSeconds=300){if(!raw||!signature||!secret)return false;if(timestamp){const ts=Number(timestamp);if(!Number.isFinite(ts))return false;const seconds=Math.abs(Date.now()/1000-ts);if(seconds>maxSkewSeconds)return false;return safeEqual(createHmac('sha256',secret).update(`${timestamp}.${raw}`).digest('hex'),signature)}return safeEqual(createHmac('sha256',secret).update(raw).digest('hex'),signature)}};
const required=(v:string,name:string)=>{if(!v||v.length>200)throw new Error(`${name}_REQUIRED`);return v};
export function normalizeProviderEvent(input:ProviderEvent):ProviderEvent{required(input.provider,'PROVIDER');required(input.eventId,'EVENT_ID');required(input.type,'EVENT_TYPE');required(input.reference,'REFERENCE');if(!input.payload||typeof input.payload!=='object')throw new Error('PAYLOAD_REQUIRED');const occurred=new Date(input.occurredAt);if(Number.isNaN(occurred.getTime()))throw new Error('OCCURRED_AT_INVALID');return {...input,occurredAt:occurred.toISOString()};}
export async function receiveWebhook(db:SqlExecutor,event:ProviderEvent):Promise<ReconciliationResult>{const e=normalizeProviderEvent(event);const prior=await db.query<{id:string;status:string}>(`select id,status from trust_provider_webhook_events where provider=$1 and event_id=$2 for update`,[e.provider,e.eventId]);if(prior.rows[0])return {provider:e.provider,eventId:e.eventId,status:'DUPLICATE',reason:'Provider event already received.'};await db.query(`insert into trust_provider_webhook_events(provider,event_id,event_type,provider_reference,occurred_at,payload_json,status) values($1,$2,$3,$4,$5,$6::jsonb,'RECEIVED')`,[e.provider,e.eventId,e.type,e.reference,e.occurredAt,JSON.stringify(e.payload)]);await db.query(`insert into trust_provider_reconciliation_jobs(provider,event_id,status,available_at) values($1,$2,'PENDING',now()) on conflict(provider,event_id) do nothing`,[e.provider,e.eventId]);return {provider:e.provider,eventId:e.eventId,status:'RECEIVED',reason:'Webhook durably received and queued for reconciliation.'};}
export async function reconcileWebhook(db:SqlExecutor,input:{provider:string;eventId:string}):Promise<ReconciliationResult>{const row=await db.query<{provider:string;event_id:string;event_type:string;provider_reference:string;status:string;payload_json:Record<string,unknown>}>(`select provider,event_id,event_type,provider_reference,status,payload_json from trust_provider_webhook_events where provider=$1 and event_id=$2 for update`,[input.provider,input.eventId]);if(!row.rows[0])throw new Error('WEBHOOK_NOT_FOUND');if(row.rows[0].status==='PROCESSED')return {provider:input.provider,eventId:input.eventId,status:'PROCESSED',reason:'Webhook already reconciled.'};const p=row.rows[0].payload_json||{};const actionId=typeof p.actionId==='string'?p.actionId:null;if(actionId){await db.query(`update trust_purchase_guardian_actions set status=case when $2 in ('succeeded','created','authorized') then 'EXECUTED' else 'FAILED' end,execution_provider_reference=$3,execution_reason=$4,executed_at=case when $2 in ('succeeded','created','authorized') then now() else executed_at end,execution_lease_until=null,updated_at=now() where id=$1`,[actionId,String(p.status||''),row.rows[0].provider_reference,`Reconciled ${row.rows[0].event_type}`]);}await db.query(`update trust_provider_webhook_events set status='PROCESSED',processed_at=now() where provider=$1 and event_id=$2`,[input.provider,input.eventId]);await db.query(`update trust_provider_reconciliation_jobs set status='DONE',processed_at=now(),lease_until=null,updated_at=now() where provider=$1 and event_id=$2`,[input.provider,input.eventId]);await db.query(`insert into trust_outbox_events(event_type,aggregate_id,payload_json) values($1,$2,$3::jsonb)`,['provider.webhook.reconciled',input.eventId,JSON.stringify({provider:input.provider,eventId:input.eventId,actionId})]);return {provider:input.provider,eventId:input.eventId,status:'PROCESSED',actionId:actionId||undefined,reason:'Provider event reconciled.'};}
export async function claimReconciliationJobs(db:SqlExecutor,limit=50):Promise<ReconciliationJob[]>{if(!Number.isInteger(limit)||limit<1||limit>500)throw new Error('INVALID_LIMIT');const r=await db.query<ReconciliationJob>(`with candidates as (select id from trust_provider_reconciliation_jobs where status in ('PENDING','PROCESSING') and available_at<=now() and (lease_until is null or lease_until<now()) order by available_at asc for update skip locked limit $1) update trust_provider_reconciliation_jobs j set status='PROCESSING',lease_until=now()+interval '2 minutes',attempts=j.attempts+1,updated_at=now() from candidates c where j.id=c.id returning j.id,j.provider,j.event_id,j.attempts,j.status,j.available_at`,[limit]);return r.rows;}
export async function runReconciliationWorker(db:SqlExecutor,limit=50){const jobs=await claimReconciliationJobs(db,limit);const results=[];for(const job of jobs){try{results.push(await reconcileWebhook(db,{provider:job.provider,eventId:job.eventId}));}catch(error){const reason=error instanceof Error?error.message:'RECONCILIATION_FAILED';const terminal=job.attempts>=5;await db.query(`update trust_provider_reconciliation_jobs set status=$3,lease_until=null,last_error=$4,available_at=case when $3='FAILED' then now()+interval '5 minutes' else now() end,updated_at=now() where id=$1 and provider=$2`,[job.id,job.provider,terminal?'FAILED':'PENDING',reason]);results.push({provider:job.provider,eventId:job.eventId,status:'REJECTED',reason});}}return results;}
export async function recoverExpiredGuardianActions(db:SqlExecutor,limit=100){if(!Number.isInteger(limit)||limit<1||limit>500)throw new Error('INVALID_LIMIT');const r=await db.query<{id:string}>(`with candidates as (select id from trust_purchase_guardian_actions where status='EXECUTING' and execution_lease_until<now() order by execution_lease_until asc for update skip locked limit $1) update trust_purchase_guardian_actions a set status='APPROVED',execution_lease_until=null,execution_started_at=null,updated_at=now(),execution_reason='EXECUTION_LEASE_EXPIRED_RECOVERED' from candidates c where a.id=c.id returning a.id`,[limit]);return r.rows.map(x=>x.id);}
