import { NextRequest, NextResponse } from 'next/server';
import { getCurrentUser } from '../../../modules/platform/auth/current-user';
import { query, withPgTransaction } from '../../../modules/platform/db/postgres';
import { getCustomerCredits, getCreditTransactions, issueStoreCredit, redeemStoreCredit, reverseStoreCreditRedemption } from '../../../modules/commerce/reverse-commerce';
export const dynamic='force-dynamic'; export const runtime='nodejs';
const privileged=(r:string)=>['admin','operations','support'].includes(r); const out=(b:unknown,s=200)=>NextResponse.json(b,{status:s,headers:{'Cache-Control':'no-store'}});
export async function GET(req:NextRequest){const u=await getCurrentUser(req);if(!u)return out({ok:false,error:'AUTH_REQUIRED'},401);try{const creditId=req.nextUrl.searchParams.get('creditId');if(creditId)return out({ok:true,transactions:await getCreditTransactions({query,transaction:withPgTransaction},{creditId,customerId:u.id}),surfaceStatus:'LIVE'});return out({ok:true,credits:await getCustomerCredits({query,transaction:withPgTransaction},u.id),surfaceStatus:'LIVE'});}catch(e){return out({ok:false,error:e instanceof Error?e.message:'CREDIT_READ_FAILED'},500);}}
export async function POST(req:NextRequest){const u=await getCurrentUser(req);if(!u)return out({ok:false,error:'AUTH_REQUIRED'},401);const key=req.headers.get('idempotency-key')?.trim();if(!key)return out({ok:false,error:'IDEMPOTENCY_KEY_REQUIRED'},400);try{const b=await req.json();if(b.action==='redeem')return out({ok:true,result:await redeemStoreCredit({query,transaction:withPgTransaction},{...b,customerId:u.id,idempotencyKey:key}),surfaceStatus:'LIVE'},200);if(!privileged(u.role))return out({ok:false,error:'FORBIDDEN'},403);return out({ok:true,result:await issueStoreCredit({query,transaction:withPgTransaction},{...b,customerId:String(b.customerId||u.id),actorId:u.id,idempotencyKey:key}),surfaceStatus:'LIVE'},201);}catch(e){const c=e instanceof Error?e.message:'CREDIT_OPERATION_FAILED';return out({ok:false,error:c,surfaceStatus:'ERROR'},c.startsWith('INVALID_')?400:409);}}
export async function PATCH(req:NextRequest){const u=await getCurrentUser(req);if(!u)return out({ok:false,error:'AUTH_REQUIRED'},401);if(!privileged(u.role))return out({ok:false,error:'FORBIDDEN'},403);const key=req.headers.get('idempotency-key')?.trim();if(!key)return out({ok:false,error:'IDEMPOTENCY_KEY_REQUIRED'},400);try{const b=await req.json();return out({ok:true,result:await reverseStoreCreditRedemption({query,transaction:withPgTransaction},{...b,customerId:String(b.customerId||u.id),idempotencyKey:key}),surfaceStatus:'LIVE'});}catch(e){return out({ok:false,error:e instanceof Error?e.message:'CREDIT_REVERSE_FAILED',surfaceStatus:'ERROR'},409);}}
