import type {DeploymentIntent,ProductionControlPlaneResult,ReliabilityPolicy,TelemetrySignal,TelemetrySource,TelemetrySink} from './contracts.ts';
import type {ProductionInfrastructureAdapter} from '../production-infrastructure/contracts.ts';
import type {ControlPlaneStore} from './contracts.ts';
import {evidenceHash} from './evidence.ts';
const gate=(s:TelemetrySignal,p:ReliabilityPolicy)=>s.healthy&&s.availability>=p.minAvailability&&s.errorRate<=p.maxErrorRate&&s.p95Ms<=p.maxP95Ms&&s.saturationPct<=p.maxSaturationPct;
export class ProductionControlPlane {
 private infra:ProductionInfrastructureAdapter; private store:ControlPlaneStore; private telemetry:TelemetrySource; private sink:TelemetrySink; private policy:ReliabilityPolicy;
 constructor(infra:ProductionInfrastructureAdapter,store:ControlPlaneStore,telemetry:TelemetrySource,sink:TelemetrySink,policy:ReliabilityPolicy){this.infra=infra;this.store=store;this.telemetry=telemetry;this.sink=sink;this.policy=policy}

 async execute(intent:DeploymentIntent):Promise<ProductionControlPlaneResult>{const b=await this.store.begin(intent);if(b.kind==='CACHED')return b.record!;if(b.kind==='BUSY')throw new Error('CONTROL_PLANE_LEASE_UNAVAILABLE');const signals:TelemetrySignal[]=[];let revision:string|null=null;try{if(!(await this.infra.preflight(intent.target)))throw new Error('PREFLIGHT_FAILED');await this.store.transition(intent.deploymentId,'DEPLOYING');revision=(await this.infra.deploy(intent.target)).revision;await this.store.transition(intent.deploymentId,'SHIFTING_TRAFFIC',{revision});if(!(await this.infra.shiftTraffic(intent.traffic)))throw new Error('TRAFFIC_SHIFT_FAILED');await this.store.transition(intent.deploymentId,'VERIFYING',{revision});const s=await this.telemetry.observe(intent.traffic.service);signals.push(s);await this.sink.emit(s);if(!gate(s,this.policy)||!(await this.infra.verify(intent.traffic.service)))throw new Error('RELIABILITY_GATE_FAILED');await this.store.transition(intent.deploymentId,'PROMOTING',{revision});if(!(await this.infra.promote(intent.traffic.service)))throw new Error('PROMOTION_FAILED');const finalSignal=await this.telemetry.observe(intent.traffic.service);signals.push(finalSignal);await this.sink.emit(finalSignal);if(!gate(finalSignal,this.policy)||!(await this.infra.verify(intent.traffic.service)))throw new Error('POST_PROMOTION_VERIFY_FAILED');const rec:ProductionControlPlaneResult={deploymentId:intent.deploymentId,phase:'COMPLETE',decision:'PROMOTE',revision,runtimeVerified:true,error:null,evidenceHash:null,updatedAt:new Date().toISOString()};rec.evidenceHash=evidenceHash(intent,rec,signals);await this.store.complete(intent.deploymentId,rec,86400000);return rec}catch(e){const msg=e instanceof Error?e.message:String(e);await this.store.transition(intent.deploymentId,'ROLLING_BACK',{revision,decision:'ROLLBACK',error:msg});const rolled=await this.infra.rollback(intent.traffic.service).catch(()=>false);await this.store.transition(intent.deploymentId,'RECOVERY_VERIFY',{revision,decision:'ROLLBACK'});const verified=rolled&&await this.infra.verify(intent.traffic.service).catch(()=>false);if(!verified){const rec:ProductionControlPlaneResult={deploymentId:intent.deploymentId,phase:'ESCALATED',decision:'ESCALATE',revision,runtimeVerified:false,error:`ROLLBACK_VERIFICATION_FAILED:${msg}`,evidenceHash:null,updatedAt:new Date().toISOString()};rec.evidenceHash=evidenceHash(intent,rec,signals);await this.store.complete(intent.deploymentId,rec,86400000);throw new Error(rec.error!)}const rec:ProductionControlPlaneResult={deploymentId:intent.deploymentId,phase:'FAILED',decision:'ROLLBACK',revision,runtimeVerified:true,error:msg,evidenceHash:null,updatedAt:new Date().toISOString()};rec.evidenceHash=evidenceHash(intent,rec,signals);await this.store.complete(intent.deploymentId,rec,86400000);throw e}finally{await this.store.release(intent.deploymentId,intent.owner)}}}
