import type {Pool,PoolClient} from 'pg';
import type {ControlPlaneStore,DeploymentIntent,DeploymentRecord,ControlPlanePhase} from './contracts.ts';
const row=(r:any):DeploymentRecord=>({deploymentId:r.deployment_id,phase:r.phase,decision:r.decision,revision:r.revision,runtimeVerified:Boolean(r.runtime_verified),error:r.error,evidenceHash:r.evidence_hash,updatedAt:new Date(r.updated_at).toISOString()});
export class PostgresControlPlaneStore implements ControlPlaneStore { private pool:Pool; constructor(pool:Pool){this.pool=pool}
 async begin(i:DeploymentIntent){const c=await this.pool.connect();try{await c.query('BEGIN');const hit=await c.query('SELECT record FROM trust_v150_control_plane_idempotency WHERE idempotency_key=$1 AND expires_at>now() FOR UPDATE',[i.idempotencyKey]);if(hit.rowCount){await c.query('COMMIT');return {kind:'CACHED' as const,record:hit.rows[0].record as DeploymentRecord}}const rec:DeploymentRecord={deploymentId:i.deploymentId,phase:'PREFLIGHT',decision:null,revision:null,runtimeVerified:false,error:null,evidenceHash:null,updatedAt:new Date().toISOString()};await c.query(`INSERT INTO trust_v150_control_plane_deployments(deployment_id,owner,idempotency_key,phase,decision,runtime_verified,target,traffic) VALUES($1,$2,$3,'PREFLIGHT',NULL,false,$4::jsonb,$5::jsonb) ON CONFLICT(deployment_id) DO NOTHING`,[i.deploymentId,i.owner,i.idempotencyKey,JSON.stringify(i.target),JSON.stringify(i.traffic)]);const lease=await c.query(`INSERT INTO trust_v150_control_plane_leases(deployment_id,owner,expires_at) VALUES($1,$2,now()+interval '60 seconds') ON CONFLICT(deployment_id) DO UPDATE SET owner=EXCLUDED.owner,expires_at=EXCLUDED.expires_at WHERE trust_v150_control_plane_leases.expires_at<=now() RETURNING deployment_id`,[i.deploymentId,i.owner]);if(!lease.rowCount){await c.query('ROLLBACK');return {kind:'BUSY' as const}}await c.query('COMMIT');return {kind:'ACQUIRED' as const,record:rec}}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
 async transition(id:string,phase:ControlPlanePhase,patch:Partial<DeploymentRecord>={}){await this.pool.query(`UPDATE trust_v150_control_plane_deployments SET phase=$2,decision=COALESCE($3,decision),revision=COALESCE($4,revision),runtime_verified=COALESCE($5,runtime_verified),error=COALESCE($6,error),evidence_hash=COALESCE($7,evidence_hash),updated_at=now() WHERE deployment_id=$1`,[id,phase,patch.decision??null,patch.revision??null,patch.runtimeVerified??null,patch.error??null,patch.evidenceHash??null])}
 async complete(id:string,record:DeploymentRecord,ttlMs:number){const c=await this.pool.connect();try{await c.query('BEGIN');await c.query(`UPDATE trust_v150_control_plane_deployments SET phase=$2,decision=$3,revision=$4,runtime_verified=$5,error=$6,evidence_hash=$7,updated_at=now() WHERE deployment_id=$1`,[id,record.phase,record.decision,record.revision,record.runtimeVerified,record.error,record.evidenceHash]);await c.query(`INSERT INTO trust_v150_control_plane_idempotency(idempotency_key,record,expires_at) SELECT idempotency_key,$2::jsonb,now()+($3::bigint * interval '1 millisecond') FROM trust_v150_control_plane_deployments WHERE deployment_id=$1 ON CONFLICT(idempotency_key) DO UPDATE SET record=EXCLUDED.record,expires_at=EXCLUDED.expires_at`,[id,JSON.stringify(record),ttlMs]);await c.query('COMMIT')}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
 async release(id:string,owner:string){await this.pool.query('DELETE FROM trust_v150_control_plane_leases WHERE deployment_id=$1 AND owner=$2',[id,owner])}
}
export class MemoryControlPlaneStore implements ControlPlaneStore { private records=new Map<string,DeploymentRecord>(); private idem=new Map<string,DeploymentRecord>(); private idemByDeployment=new Map<string,string>(); private locks=new Map<string,string>(); async begin(i:DeploymentIntent){const cached=this.idem.get(i.idempotencyKey);if(cached)return {kind:'CACHED' as const,record:cached};if(this.locks.has(i.deploymentId)&&this.locks.get(i.deploymentId)!==i.owner)return {kind:'BUSY' as const};this.locks.set(i.deploymentId,i.owner);const r:DeploymentRecord={deploymentId:i.deploymentId,phase:'PREFLIGHT',decision:null,revision:null,runtimeVerified:false,error:null,evidenceHash:null,updatedAt:new Date().toISOString()};this.records.set(i.deploymentId,r);this.idemByDeployment.set(i.deploymentId,i.idempotencyKey);return {kind:'ACQUIRED' as const,record:r}} async transition(id:string,phase:ControlPlanePhase,p={}){this.records.set(id,{...this.records.get(id)!,...p,phase,updatedAt:new Date().toISOString()})} async complete(id:string,r:DeploymentRecord,_ttl:number){this.records.set(id,r);const key=this.idemByDeployment.get(id);if(key)this.idem.set(key,r)} async release(id:string,owner:string){if(this.locks.get(id)===owner)this.locks.delete(id)}}
