'use client';
import {useEffect,useState} from 'react';
type Tab='overview'|'addresses'|'wishlists'|'saved'|'reviews'|'preferences'|'privacy'|'timeline';
export default function CustomerExperiencePage(){const [tab,setTab]=useState<Tab>('overview');const [data,setData]=useState<any>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/customer/dashboard',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error??'LOAD_FAILED');setData(j.dashboard);}catch(e){setError(e instanceof Error?e.message:'LOAD_FAILED')}finally{setLoading(false)}}
 useEffect(()=>{load()},[]); const nav=(x:Tab)=>setTab(x);
 if(loading)return <main className="p-8"><h1>Customer Commerce OS</h1><p>Loading durable customer state…</p></main>;
 if(error)return <main className="p-8"><h1>Customer Commerce OS</h1><p role="alert">{error}</p><button onClick={load}>Retry</button></main>;
 const profile=data?.profile;
 const counts={addresses:data.addresses?.length??0,wishlists:data.wishlists?.length??0,saved:data.savedCarts?.length??0,reviews:data.reviews?.length??0,events:data.timeline?.length??0,privacy:data.privacyJobs?.length??0};
 const lifecycleLabel=profile?.lifecycle==='ACTIVE'?'Account active':profile?.lifecycle==='PENDING_DELETION'?'Deletion pending':profile?.lifecycle==='SUSPENDED'?'Account suspended':'Account unavailable';
 return <main className="p-8 space-y-6"><header><p className="text-sm opacity-70">LIVE · PostgreSQL-backed</p><h1 className="text-3xl font-semibold">Customer Commerce OS</h1><p>Profile, addresses, saved commerce state, reviews, preferences, privacy and timeline.</p></header><nav className="flex flex-wrap gap-2">{(['overview','addresses','wishlists','saved','reviews','preferences','privacy','timeline'] as Tab[]).map(x=><button key={x} onClick={()=>nav(x)} className="rounded border px-3 py-2">{x}</button>)}</nav><section className="rounded border p-5">{tab==='overview'&&<div><h2 className="text-xl">{profile?.displayName??'Customer'}</h2><p>{profile?.email}</p><p>Lifecycle: {profile?.lifecycle}</p><p>Wishlists: {data.wishlists.length} · Saved carts: {data.savedCarts.length} · Reviews: {data.reviews.length}</p></div>}{tab==='addresses'&&<List title="Addresses" items={data.addresses} fields={['label','kind','city','countryCode','isDefault']}/>} {tab==='wishlists'&&<List title="Wishlists" items={data.wishlists} fields={['name','visibility','itemCount']}/>} {tab==='saved'&&<List title="Saved carts" items={data.savedCarts} fields={['name','status','currency','itemCount']}/>} {tab==='reviews'&&<List title="Reviews" items={data.reviews} fields={['productId','rating','status','verifiedPurchase']}/>} {tab==='preferences'&&<List title="Preferences" items={data.preferences} fields={['scope','key','enabled']}/>} {tab==='privacy'&&<List title="Privacy jobs" items={data.privacyJobs} fields={['type','status','requestedAt']}/>} {tab==='timeline'&&<List title="Timeline" items={data.timeline} fields={['kind','action','summary','occurredAt']}/>}</section></main>}
function List({title,items,fields}:{title:string;items:any[];fields:string[]}){return <div><h2 className="text-xl mb-3">{title}</h2>{items.length===0?<p>No records.</p>:<div className="space-y-2">{items.map((item:any)=><article key={item.id??JSON.stringify(item)} className="rounded border p-3">{fields.map(f=><span key={f} className="mr-4"><strong>{f}:</strong> {String(item[f]??'—')}</span>)}</article>)}</div>}</div>}
