import { NextRequest, NextResponse } from 'next/server';
import { getCurrentUser } from '../../../../modules/platform/auth/current-user';
import { query, withPgTransaction } from '../../../../modules/platform/db/postgres';
import { buildReturnResolutionPlan, scheduleReturnReconciliation, resolveReturnOutcome, closeResolvedReturn } from '../../../../modules/commerce/reverse-commerce';
export const dynamic='force-dynamic'; export const runtime='nodejs';
const privileged=(r:string)=>['admin','operations','support'].includes(r);
const out=(body:unknown,status=200)=>NextResponse.json(body,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(req:NextRequest){const u=await getCurrentUser(req);if(!u)return out({ok:false,error:'AUTH_REQUIRED',surfaceStatus:'ERROR'},401);const id=req.nextUrl.searchParams.get('returnId');if(!id)return out({ok:false,error:'RETURN_ID_REQUIRED',surfaceStatus:'ERROR'},400);try{const plan=await buildReturnResolutionPlan({query,transaction:withPgTransaction},id);return out({ok:true,plan,surfaceStatus:'LIVE'});}catch(e){return out({ok:false,error:e instanceof Error?e.message:'RETURN_PLAN_FAILED',surfaceStatus:'ERROR'},500);}}
export async function POST(req:NextRequest){const u=await getCurrentUser(req);if(!u)return out({ok:false,error:'AUTH_REQUIRED',surfaceStatus:'ERROR'},401);if(!privileged(u.role))return out({ok:false,error:'FORBIDDEN',surfaceStatus:'ERROR'},403);try{const b=await req.json();if(b.action==='schedule')return out({ok:true,result:await scheduleReturnReconciliation({query,transaction:withPgTransaction},String(b.returnId||'')),surfaceStatus:'LIVE'},202);if(b.action==='outcome')return out({ok:true,result:await resolveReturnOutcome({query,transaction:withPgTransaction},{returnId:String(b.returnId||''),outcome:b.outcome,actorId:u.id,referenceId:b.referenceId}),surfaceStatus:'LIVE'},201);if(b.action==='close')return out({ok:true,result:await closeResolvedReturn({query,transaction:withPgTransaction},{returnId:String(b.returnId||''),actorId:u.id,outcome:b.outcome}),surfaceStatus:'LIVE'});return out({ok:false,error:'UNKNOWN_RETURN_PLAN_ACTION',surfaceStatus:'ERROR'},400);}catch(e){return out({ok:false,error:e instanceof Error?e.message:'RETURN_PLAN_ACTION_FAILED',surfaceStatus:'ERROR'},409);}}
