import { NextRequest, NextResponse } from 'next/server';
import { getCurrentUser } from '../../../../../modules/platform/auth/current-user';
import { getMerchantByUserId } from '../../../../../modules/merchants/core/store';
import { getMerchantFulfillmentDetail } from '../../../../../modules/commerce/order-tracking';
import { withPgTransaction } from '../../../../../modules/platform/db/postgres';
import { transitionFulfillmentOrderTx } from '../../../../../modules/marketplace/fulfillment-runtime';
export const dynamic='force-dynamic'; export const runtime='nodejs';
const allowed=new Set(['PICKING','PACKED','READY_FOR_HANDOFF','HANDED_OFF','DELIVERED','EXCEPTION','CANCELLED']);
export async function GET(req:NextRequest,{params}:{params:{id:string}}){const u=await getCurrentUser(req);if(!u)return NextResponse.json({ok:false,error:'AUTH_REQUIRED'},{status:401});const merchant=await getMerchantByUserId(u.id);if(!merchant)return NextResponse.json({ok:false,error:'MERCHANT_REQUIRED'},{status:403});try{return NextResponse.json({ok:true,fulfillment:await getMerchantFulfillmentDetail(params.id,merchant.id)},{headers:{'Cache-Control':'no-store'}})}catch(e){const m=e instanceof Error?e.message:'FULFILLMENT_DETAIL_ERROR';return NextResponse.json({ok:false,error:m},{status:m.includes('NOT_FOUND')?404:400})}}
export async function PATCH(req:NextRequest,{params}:{params:{id:string}}){const u=await getCurrentUser(req);if(!u)return NextResponse.json({ok:false,error:'AUTH_REQUIRED'},{status:401});const merchant=await getMerchantByUserId(u.id);if(!merchant)return NextResponse.json({ok:false,error:'MERCHANT_REQUIRED'},{status:403});const key=req.headers.get('idempotency-key')?.trim();if(!key)return NextResponse.json({ok:false,error:'IDEMPOTENCY_KEY_REQUIRED'},{status:400});try{const b=await req.json();const to=String(b?.status??'');if(!allowed.has(to))return NextResponse.json({ok:false,error:'INVALID_FULFILLMENT_STATUS'},{status:400});const result=await withPgTransaction(tx=>transitionFulfillmentOrderTx(tx,{fulfillmentOrderId:params.id,merchantId:merchant.id,toStatus:to,actorId:u.id,idempotencyKey:key}));return NextResponse.json({ok:true,result},{headers:{'Cache-Control':'no-store'}})}catch(e){const m=e instanceof Error?e.message:'FULFILLMENT_TRANSITION_ERROR';const status=m.includes('NOT_FOUND_OR_NOT_OWNED')?404:m.startsWith('INVALID_FULFILLMENT_TRANSITION')||m.includes('REQUIRED')?409:400;return NextResponse.json({ok:false,error:m},{status})}}
