export function addToCart(cart:any,line:any){const lines=cart.lines.map((x:any)=>x.productId===line.productId&&x.offerId===line.offerId?{...x,quantity:x.quantity+line.quantity}:x);if(!lines.some((x:any)=>x.productId===line.productId&&x.offerId===line.offerId))lines.push({...line});return {...cart,lines,updatedAt:new Date().toISOString()};}
export function applyCoupon(cart:any,c:any){if(!c.active||c.used>0)return {amountMinor:0n,totalMinor:cart.lines.reduce((s:any,x:any)=>s+x.unitPriceMinor*BigInt(x.quantity),0n)};const subtotal=cart.lines.reduce((s:any,x:any)=>s+x.unitPriceMinor*BigInt(x.quantity),0n);const amount=c.kind==='PERCENT'?subtotal*BigInt(Math.min(100,Math.max(0,c.value)))/100n:BigInt(c.value);return {amountMinor:amount,totalMinor:subtotal-amount};}
export function grantLoyalty(a:any,points:bigint){const p=a.points+Number(points);return {...a,points:p,tier:p>=2500?'PLUS':p>=5000?'PREMIUM':a.tier};}
export function redeemLoyalty(a:any,points:number){if(points>a.points)throw new Error('INSUFFICIENT_POINTS');const multiplier=a.tier==='PREMIUM'?110:a.tier==='PLUS'?105:100;return {account:{...a,points:a.points-points},discountMinor:BigInt(Math.round(points*multiplier))};}
export function selectBestDeal(ds:any[],currency:string,now:Date){return ds.filter(d=>d.currency===currency&&d.active&&d.stock>0&&new Date(d.startsAt)<=now&&new Date(d.endsAt)>=now).sort((a,b)=>a.priceMinor<b.priceMinor?-1:a.priceMinor>b.priceMinor?1:0)[0];}
export function reviewInsights(rs:any[]){const avg=rs.length?rs.reduce((s,r)=>s+r.rating,0)/rs.length:0;const verified=rs.length?rs.filter(r=>r.verifiedPurchase).length/rs.length:0;return {averageRating:avg,verifiedRatio:verified,positive:rs.filter(r=>r.rating>=4),negative:rs.filter(r=>r.rating<=2)};}
export function sellerTrust(x:any){const score=Math.max(0,Math.min(100,x.rating/5*60+(1-x.cancelRate)*15+(1-x.lateRate)*10+(1-x.disputeRate)*10+(x.verified?5:0)));return {...x,score,band:score>=85?'EXCELLENT':score>=70?'GOOD':score>=50?'WATCH':'RISK'};}
export function buyAgain(lines:any[],available:Set<string>){return lines.filter(x=>available.has(x.offerId));}
export function smartBundle(lines:any[],discountPct:number){const subtotal=lines.reduce((s,x)=>s+x.unitPriceMinor*BigInt(x.quantity),0n);const discount=subtotal*BigInt(discountPct)/100n;return {subtotalMinor:subtotal,discountMinor:discount,totalMinor:subtotal-discount};}
