import type {AgentCapability,AgentProposal,AgentTask,CommerceAgent,OrchestrationPlan,OrchestrationReceipt,TaskKind} from './contracts.ts';
const finite=(n:number,k:string)=>{if(!Number.isFinite(n))throw new Error(`${k} must be finite`)};
const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n));
export function registerAgents(agents:CommerceAgent[]):CommerceAgent[]{const ids=new Set<string>();for(const a of agents){if(!a.tenantId||ids.has(a.agentId))throw new Error('invalid or duplicate agent');ids.add(a.agentId);for(const c of a.capabilities){finite(c.weight,'capability weight');if(c.weight<0)throw new Error('negative capability weight')}}return agents.map(a=>({...a,capabilities:a.capabilities.map(c=>({...c}))}));}
export function routeTask(task:AgentTask,agents:CommerceAgent[]):CommerceAgent[]{if(!task.tenantId||!task.objective)throw new Error('invalid task');finite(task.riskBps,'riskBps');if(task.riskBps<0)throw new Error('negative risk');return agents.filter(a=>a.tenantId===task.tenantId&&a.status==='ACTIVE'&&a.capabilities.some(c=>c.task===task.kind)).sort((a,b)=>score(b,task.kind)-score(a,task.kind)||a.agentId.localeCompare(b.agentId));}
function score(a:CommerceAgent,k:TaskKind){const c=a.capabilities.find(x=>x.task===k);return (c?.weight??0)+(a.minConfidenceBps/10000)-(a.maxRiskBps/10000);}
export function propose(task:AgentTask,agent:CommerceAgent,action:string,reason:string,priority=50,confidenceBps=8500,expectedImpactBps=100):AgentProposal{if(agent.tenantId!==task.tenantId)throw new Error('tenant mismatch');if(!agent.capabilities.some(c=>c.task===task.kind))throw new Error('agent lacks task capability');const risk=clamp(task.riskBps,0,10000),confidence=clamp(confidenceBps,0,10000);if(risk>agent.maxRiskBps)throw new Error('agent risk ceiling exceeded');if(confidence<agent.minConfidenceBps)throw new Error('agent confidence floor not met');finite(priority,'priority');finite(expectedImpactBps,'expectedImpactBps');const key=`${task.tenantId}:${task.taskId}:${agent.agentId}:${action}`;return {proposalId:`agent-prop-${task.taskId}-${agent.agentId}-${action}`,agentId:agent.agentId,tenantId:task.tenantId,role:agent.role,action,priority,confidenceBps:confidence,riskBps:risk,expectedImpactBps:Math.max(0,expectedImpactBps),reason,signalIds:[...task.signalIds],idempotencyKey:key,requiresApproval:risk>2500||confidence<9000};}
export function buildOrchestrationPlan(task:AgentTask,agents:CommerceAgent[],proposals:AgentProposal[]):OrchestrationPlan{for(const p of proposals)if(p.tenantId!==task.tenantId)throw new Error('tenant mismatch');const seen=new Set<string>(),conflicts:string[]=[];for(const p of proposals){if(seen.has(p.idempotencyKey))conflicts.push(`duplicate:${p.idempotencyKey}`);seen.add(p.idempotencyKey);}const sorted=[...proposals].sort((a,b)=>b.priority-a.priority||b.confidenceBps-b.riskBps||a.proposalId.localeCompare(b.proposalId));const winners:AgentProposal[]=[];const actions=new Set<string>();for(const p of sorted){if(actions.has(p.action)){conflicts.push(`competing-action:${p.action}`);continue;}actions.add(p.action);winners.push(p);}const approved=winners.filter(p=>!p.requiresApproval).map(p=>p.proposalId);return {planId:`orch-${task.tenantId}-${task.taskId}`,tenantId:task.tenantId,taskId:task.taskId,selectedAgents:routeTask(task,agents).map(a=>a.agentId),proposals:winners,approvedForExecution:approved,requiresApproval:winners.some(p=>p.requiresApproval),conflicts,explanation:`Selected ${winners.length} non-conflicting proposals from ${new Set(winners.map(p=>p.agentId)).size} agents; execution remains bounded by proposal risk/confidence gates.`};}
export function executePlan(plan:OrchestrationPlan,seen:Set<string>,now=Date.now()):OrchestrationReceipt{if(seen.has(plan.planId))return {planId:plan.planId,tenantId:plan.tenantId,status:'DUPLICATE',executedProposalIds:[],createdAt:now};if(plan.requiresApproval)return {planId:plan.planId,tenantId:plan.tenantId,status:'APPROVAL_REQUIRED',executedProposalIds:[],createdAt:now};seen.add(plan.planId);return {planId:plan.planId,tenantId:plan.tenantId,status:'EXECUTED',executedProposalIds:[...plan.approvedForExecution],createdAt:now};}
export function handoffChain(task:AgentTask,agents:CommerceAgent[]):string[]{return routeTask(task,agents).slice(0,3).map(a=>a.agentId);}
