'use client';
import {useEffect,useState} from 'react';
export default function OwnerControlRoom({ownerEmail}:{ownerEmail:string}){const [data,setData]=useState<any>(null);const [busy,setBusy]=useState('');const [notice,setNotice]=useState('');
 useEffect(()=>{fetch('/api/owner-control-room',{cache:'no-store'}).then(r=>r.json()).then(setData).catch(()=>setData({ok:false,error:'ROOM_UNAVAILABLE'}));},[]);
 async function request(controlId:string,enabled?:boolean){setBusy(controlId);const r=await fetch('/api/owner-control-room',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({controlId,enabled,confirmation:'I_UNDERSTAND',reason:'Owner control room command'})});const j=await r.json();setBusy('');setNotice(j.status??j.error??'done');if(j.live)setData((x:any)=>({...x,live:j.live}));setTimeout(()=>setNotice(''),3000)}
 const live=data?.live??{}; const toggle=(id:string)=>id==='MAINTENANCE_MODE'?live.maintenanceMode:id==='GLOBAL_FREEZE'?live.globalFreeze:id==='AUTONOMY_KILL_SWITCH'?live.autonomyKillSwitch:false;
 return <main style={{padding:24,maxWidth:1200,margin:'0 auto'}}><span style={{letterSpacing:2,fontSize:12}}>TRUST APEX · V227 · OWNER ONLY</span><h1>👑 Owner Control Room</h1><p>غرفة التحكم الحقيقية: الحالة الحساسة محفوظة في قاعدة البيانات، وكل تغيير يمر من Owner Guard وAudit Chain.</p><p><b>Owner:</b> {ownerEmail} · <b>System mode:</b> {data?.room?.controlMode??'loading'}</p>{notice&&<div role="status" style={{padding:12,border:'1px solid currentColor',margin:'12px 0'}}>{notice}</div>}
 <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:12}}>{(data?.room?.controls??[]).map((c:any)=>{const isLive=['MAINTENANCE_MODE','GLOBAL_FREEZE','AUTONOMY_KILL_SWITCH'].includes(c.id);const on=toggle(c.id);return <article key={c.id} style={{border:'1px solid #ddd',borderRadius:16,padding:16}}><small>{c.risk} · {isLive?(on?'ON':'OFF'):(c.requiresApproval?'APPROVAL GATED':'READ ONLY')}</small><h2>{c.title}</h2><p>{c.description}</p><button disabled={busy===c.id} onClick={()=>request(c.id,isLive?!on:undefined)}>{busy===c.id?'جاري التنفيذ...':isLive?(on?'Disable':'Enable'):c.readOnly?'Inspect':'Request control'}</button></article>})}</section>
 <section style={{marginTop:28}}><h2>Live Safety State</h2><p>Maintenance: <b>{live.maintenanceMode?'ON':'OFF'}</b> · Global Freeze: <b>{live.globalFreeze?'ON':'OFF'}</b> · Autonomy Kill Switch: <b>{live.autonomyKillSwitch?'ON':'OFF'}</b></p></section>
 <section style={{marginTop:28}}><h2>Immutable Owner Audit</h2>{(data?.room?.audit??[]).map((a:any)=><div key={a.eventId} style={{padding:'10px 0',borderBottom:'1px solid #eee'}}><b>{a.action}</b> · {a.target} · {a.result}<br/><small>{a.createdAt} · hash {a.eventHash.slice(0,16)}…</small></div>)}</section></main>}
