'use client';
import {useEffect,useState} from 'react';
const modes=['NORMAL','SAFE','READONLY','EMERGENCY'];
const live=['MAINTENANCE_MODE','GLOBAL_FREEZE','AUTONOMY_KILL_SWITCH'];
export default function SuperControlPlane(){const [d,setD]=useState<any>();const [busy,setBusy]=useState('');const [reason,setReason]=useState('');const [notice,setNotice]=useState('');
 const load=()=>fetch('/api/owner-control-room/super',{cache:'no-store'}).then(r=>r.json()).then(setD).catch(()=>setD({ok:false,error:'CONTROL_PLANE_UNAVAILABLE'}));useEffect(()=>{load()},[]);
 async function run(action:string,target:string,enabled?:boolean){if(reason.trim().length<8){setNotice('اكتب سبب واضح من 8 حروف على الأقل');return}setBusy(target);const r=await fetch('/api/owner-control-room/super',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,target,enabled,reason})});const j=await r.json();setBusy('');setNotice(j.ok?`تم تنفيذ ${target}`:(j.error??'فشل التنفيذ'));await load()}
 const c=d?.controlPlane?.counts??{};const liveState=d?.controlPlane?.live??{};const map:any={MAINTENANCE_MODE:liveState.maintenanceMode,GLOBAL_FREEZE:liveState.globalFreeze,AUTONOMY_KILL_SWITCH:liveState.autonomyKillSwitch};
 const cards=[['Orders 24h',c.orders_24h],['Payments 24h',c.payments_24h],['Merchants',c.merchants],['Offers',c.offers],['Open Fulfillment',c.open_fulfillment],['Open Shipments',c.open_shipments],['Open Returns',c.open_returns],['Pending Refunds',c.pending_refunds],['Pending Payouts',c.pending_payouts],['Active Automation',c.active_automation],['Incident Snapshots 24h',c.incident_snapshots]];
 return <main style={{padding:24,maxWidth:1400,margin:'0 auto'}}><small>TRUST APEX · V390 · OWNER SUPER CONTROL PLANE</small><h1>👑 Global Super Control Plane</h1><p>مركز تحكم مالك المنصة. القراءة Live من الـ authorities الحالية، والتنفيذ يمر عبر الـ domain authority + owner audit chain.</p><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="سبب الأمر التشغيلي..." style={{width:'100%',minHeight:70,padding:12}}/> {notice&&<p role="status"><b>{notice}</b></p>}
 <h2>Live Platform State</h2><section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10}}>{cards.map(([k,v])=><article key={String(k)} style={{border:'1px solid #ddd',borderRadius:14,padding:14}}><small>{k}</small><div style={{fontSize:26,fontWeight:700}}>{v??'—'}</div></article>)}</section>
 <h2>System Mode</h2><section style={{display:'flex',gap:8,flexWrap:'wrap'}}>{modes.map(m=><button key={m} disabled={busy===m} onClick={()=>run('SET_SYSTEM_MODE',m)}>{m}{d?.controlPlane?.control?.mode===m.toLowerCase()?' ✓':''}</button>)}</section>
 <h2>Safety Controls</h2><section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:12}}>{live.map(x=><article key={x} style={{border:'1px solid #ddd',borderRadius:14,padding:16}}><b>{x}</b><p>Current: {map[x]?'ON':'OFF'}</p><button disabled={busy===x} onClick={()=>run('SET_LIVE_CONTROL',x,!map[x])}>{map[x]?'Disable':'Enable'}</button></article>)}</section>
 <h2>Recent Owner Commands</h2>{(d?.controlPlane?.recentCommands??[]).map((x:any)=><div key={x.command_id} style={{padding:10,borderBottom:'1px solid #eee'}}><b>{x.action}</b> → {x.target} · {x.status} · {x.created_at}</div>)}
 <h2>Recent Audit Chain</h2>{(d?.controlPlane?.recentAudit??[]).map((x:any)=><div key={x.event_id} style={{padding:10,borderBottom:'1px solid #eee'}}><b>{x.action}</b> → {x.target} · {x.result} · {x.created_at} · {String(x.event_hash).slice(0,18)}…</div>)}
 </main>}
