import { NextRequest, NextResponse } from 'next/server';
import { getCurrentUser } from '../../../../modules/platform/auth/current-user';
import { query, withPgTransaction } from '../../../../modules/platform/db/postgres';
import { approveCompensation, compensationExposure, issueCompensation, listCompensationOperations, listCustomerCompensations, requestCompensation, reverseCompensation } from '../../../../modules/commerce/reverse-commerce';
import type { CompensationStatus } from '../../../../modules/commerce/reverse-commerce';
export const dynamic='force-dynamic'; export const runtime='nodejs';
const privileged=(r:string)=>['admin','operations','support'].includes(r); const out=(b:unknown,s=200)=>NextResponse.json(b,{status:s,headers:{'Cache-Control':'no-store'}});
export async function GET(req:NextRequest){const u=await getCurrentUser(req);if(!u)return out({ok:false,error:'AUTH_REQUIRED',surfaceStatus:'ERROR'},401);try{if(privileged(u.role)&&req.nextUrl.searchParams.get('ops')==='1')return out({ok:true,compensations:await listCompensationOperations({query,transaction:withPgTransaction},req.nextUrl.searchParams.get('status') as CompensationStatus|null||undefined,Number(req.nextUrl.searchParams.get('limit')||100)),exposure:await compensationExposure({query,transaction:withPgTransaction}),surfaceStatus:'LIVE'});return out({ok:true,compensations:await listCustomerCompensations({query,transaction:withPgTransaction},u.id,Number(req.nextUrl.searchParams.get('limit')||100)),surfaceStatus:'LIVE'});}catch(e){return out({ok:false,error:e instanceof Error?e.message:'COMPENSATION_READ_FAILED',surfaceStatus:'ERROR'},500);}}
export async function POST(req:NextRequest){const u=await getCurrentUser(req);if(!u)return out({ok:false,error:'AUTH_REQUIRED',surfaceStatus:'ERROR'},401);if(!privileged(u.role))return out({ok:false,error:'FORBIDDEN',surfaceStatus:'ERROR'},403);const key=req.headers.get('idempotency-key')?.trim();if(!key)return out({ok:false,error:'IDEMPOTENCY_KEY_REQUIRED',surfaceStatus:'ERROR'},400);try{const b=await req.json();if(b.action==='approve')return out({ok:true,result:await approveCompensation({query,transaction:withPgTransaction},{compensationId:String(b.compensationId||''),actorId:u.id,note:b.note}),surfaceStatus:'LIVE'});if(b.action==='issue')return out({ok:true,result:await issueCompensation({query,transaction:withPgTransaction},{compensationId:String(b.compensationId||''),actorId:u.id,idempotencyKey:key}),surfaceStatus:'LIVE'},202);if(b.action==='reverse')return out({ok:true,result:await reverseCompensation({query,transaction:withPgTransaction},{compensationId:String(b.compensationId||''),actorId:u.id,idempotencyKey:key,reason:String(b.reason||'')}),surfaceStatus:'LIVE'});return out({ok:true,result:await requestCompensation({query,transaction:withPgTransaction},{...b,actorId:u.id,idempotencyKey:key}),surfaceStatus:'LIVE'},201);}catch(e){const c=e instanceof Error?e.message:'COMPENSATION_OPERATION_FAILED';return out({ok:false,error:c,surfaceStatus:'ERROR'},c.includes('NOT_FOUND')?404:c.startsWith('INVALID_')?400:409);}}
