export type PaymentStatus='AUTHORIZED'|'CAPTURED'|'FAILED'|'REFUNDED'|'CHARGEBACK';
export type Provider={id:string;currencies:string[];methods:string[];health:number;priority:number;enabled:boolean};
export function routePayment(providers:Provider[],input:{currency:string;method:string}):Provider{const c=input.currency.toUpperCase(),m=input.method.toLowerCase();const p=providers.filter(x=>x.enabled&&x.health>0&&x.currencies.includes(c)&&x.methods.includes(m)).sort((a,b)=>b.health-a.health||a.priority-b.priority)[0];if(!p)throw new Error('NO_PAYMENT_PROVIDER');return p;}
export type JournalLine={account:string;side:'DEBIT'|'CREDIT';amountMinor:bigint;currency:string};
export function validateJournal(lines:JournalLine[]):void{if(!lines.length)throw new Error('EMPTY_JOURNAL');const totals=new Map<string,bigint>();for(const l of lines){if(l.amountMinor<=0n)throw new Error('INVALID_AMOUNT');const k=l.currency.toUpperCase();totals.set(`${k}:D`,(totals.get(`${k}:D`)??0n)+ (l.side==='DEBIT'?l.amountMinor:0n));totals.set(`${k}:C`,(totals.get(`${k}:C`)??0n)+(l.side==='CREDIT'?l.amountMinor:0n));}for(const [k,v] of totals){if(k.endsWith(':D')&&(v!==(totals.get(k.replace(':D',':C'))??0n)))throw new Error(`UNBALANCED_JOURNAL:${k.slice(0,-2)}`);}}
export function captureJournal(input:{amountMinor:bigint;currency:string;platformFeeMinor:bigint;paymentFeeMinor:bigint}):JournalLine[]{if(input.amountMinor<=0n||input.platformFeeMinor<0n||input.paymentFeeMinor<0n)throw new Error('INVALID_PAYMENT_AMOUNT');const seller=input.amountMinor-input.platformFeeMinor-input.paymentFeeMinor;if(seller<0n)throw new Error('FEES_EXCEED_GROSS');const lines:JournalLine[]=[{account:'cash',side:'DEBIT',amountMinor:input.amountMinor,currency:input.currency},{account:'seller_payable',side:'CREDIT',amountMinor:seller,currency:input.currency},{account:'platform_revenue',side:'CREDIT',amountMinor:input.platformFeeMinor,currency:input.currency},{account:'payment_fees',side:'CREDIT',amountMinor:input.paymentFeeMinor,currency:input.currency}];validateJournal(lines);return lines;}
export function reconcileProvider(input:{expectedMinor:bigint;providerMinor:bigint}):{status:'MATCH'|'MISMATCH';deltaMinor:bigint}{const d=input.providerMinor-input.expectedMinor;return {status:d===0n?'MATCH':'MISMATCH',deltaMinor:d};}
export type FinancialOperation={operation:'REFUND'|'CHARGEBACK';idempotencyKey:string;amountMinor:bigint;currency:string;status:'ACCEPTED'};
export function acceptFinancialOperation(input:Omit<FinancialOperation,'status'>):FinancialOperation{if(!input.idempotencyKey||input.amountMinor<=0n)throw new Error('INVALID_FINANCIAL_OPERATION');return {...input,status:'ACCEPTED'};}
export function settlementJournal(input:{grossMinor:bigint;platformFeeMinor:bigint;paymentFeeMinor:bigint;taxMinor:bigint;currency:string}):JournalLine[]{const seller=input.grossMinor-input.platformFeeMinor-input.paymentFeeMinor-input.taxMinor;if(seller<0n)throw new Error('INVALID_SETTLEMENT_SPLIT');const lines:JournalLine[]=[{account:'settlement_receivable',side:'DEBIT',amountMinor:input.grossMinor,currency:input.currency},{account:'seller_payable',side:'CREDIT',amountMinor:seller,currency:input.currency},{account:'platform_revenue',side:'CREDIT',amountMinor:input.platformFeeMinor,currency:input.currency},{account:'payment_fees',side:'CREDIT',amountMinor:input.paymentFeeMinor,currency:input.currency},{account:'tax_payable',side:'CREDIT',amountMinor:input.taxMinor,currency:input.currency}];validateJournal(lines);return lines;}
