import type { SqlExecutor } from '../../platform/persistence/postgres-boundary';
export type ReturnEventType='return.requested'|'return.approved'|'return.rejected'|'return.received'|'return.inspection.started'|'return.inspection.completed'|'return.refund.requested'|'return.refund.failed'|'return.refund.succeeded'|'return.closed'|'return.label.created'|'return.provider.event.processed';
export type ReturnEventEnvelope={eventType:ReturnEventType;returnId:string;orderId?:string;actorId?:string;occurredAt:string;payload:Record<string,unknown>};
export function eventEnvelope(eventType:ReturnEventType,returnId:string,payload:Record<string,unknown>={},actorId?:string):ReturnEventEnvelope{return{eventType,returnId,actorId,occurredAt:new Date().toISOString(),payload};}
export async function emitReturnEvent(db:SqlExecutor,event:ReturnEventEnvelope){return db.query<{id:string}>(`insert into trust_outbox_events(event_type,aggregate_id,payload_json) values($1,$2,$3::jsonb) returning id`,[event.eventType,event.returnId,JSON.stringify(event)]);}
export async function loadReturnEventHistory(db:SqlExecutor,returnId:string){return(await db.query(`select id,from_status,to_status,source,actor_id,note,created_at from trust_return_events where return_id=$1 order by created_at asc`,[returnId])).rows;}
export async function loadReturnFinancialHistory(db:SqlExecutor,returnId:string){return(await db.query(`select r.id refund_id,r.amount,r.status,r.provider_reference,r.created_at,s.id settlement_id,s.gross_amount,s.restocking_fee,s.shipping_adjustment,s.net_amount,s.status settlement_status from trust_refunds r left join trust_refund_settlements s on s.refund_id=r.id where r.return_id=$1 order by r.created_at asc`,[returnId])).rows;}
export function returnEventPayload001(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:1,source:'V234',checkpoint:'RETURN-EVENT-001'},actorId);}
export function returnEventPayload002(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:2,source:'V234',checkpoint:'RETURN-EVENT-002'},actorId);}
export function returnEventPayload003(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:3,source:'V234',checkpoint:'RETURN-EVENT-003'},actorId);}
export function returnEventPayload004(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:4,source:'V234',checkpoint:'RETURN-EVENT-004'},actorId);}
export function returnEventPayload005(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:5,source:'V234',checkpoint:'RETURN-EVENT-005'},actorId);}
export function returnEventPayload006(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:6,source:'V234',checkpoint:'RETURN-EVENT-006'},actorId);}
export function returnEventPayload007(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:7,source:'V234',checkpoint:'RETURN-EVENT-007'},actorId);}
export function returnEventPayload008(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:8,source:'V234',checkpoint:'RETURN-EVENT-008'},actorId);}
export function returnEventPayload009(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:9,source:'V234',checkpoint:'RETURN-EVENT-009'},actorId);}
export function returnEventPayload010(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:10,source:'V234',checkpoint:'RETURN-EVENT-010'},actorId);}
export function returnEventPayload011(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:11,source:'V234',checkpoint:'RETURN-EVENT-011'},actorId);}
export function returnEventPayload012(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:12,source:'V234',checkpoint:'RETURN-EVENT-012'},actorId);}
export function returnEventPayload013(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:13,source:'V234',checkpoint:'RETURN-EVENT-013'},actorId);}
export function returnEventPayload014(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:14,source:'V234',checkpoint:'RETURN-EVENT-014'},actorId);}
export function returnEventPayload015(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:15,source:'V234',checkpoint:'RETURN-EVENT-015'},actorId);}
export function returnEventPayload016(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:16,source:'V234',checkpoint:'RETURN-EVENT-016'},actorId);}
export function returnEventPayload017(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:17,source:'V234',checkpoint:'RETURN-EVENT-017'},actorId);}
export function returnEventPayload018(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:18,source:'V234',checkpoint:'RETURN-EVENT-018'},actorId);}
export function returnEventPayload019(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:19,source:'V234',checkpoint:'RETURN-EVENT-019'},actorId);}
export function returnEventPayload020(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:20,source:'V234',checkpoint:'RETURN-EVENT-020'},actorId);}
export function returnEventPayload021(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:21,source:'V234',checkpoint:'RETURN-EVENT-021'},actorId);}
export function returnEventPayload022(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:22,source:'V234',checkpoint:'RETURN-EVENT-022'},actorId);}
export function returnEventPayload023(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:23,source:'V234',checkpoint:'RETURN-EVENT-023'},actorId);}
export function returnEventPayload024(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:24,source:'V234',checkpoint:'RETURN-EVENT-024'},actorId);}
export function returnEventPayload025(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:25,source:'V234',checkpoint:'RETURN-EVENT-025'},actorId);}
export function returnEventPayload026(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:26,source:'V234',checkpoint:'RETURN-EVENT-026'},actorId);}
export function returnEventPayload027(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:27,source:'V234',checkpoint:'RETURN-EVENT-027'},actorId);}
export function returnEventPayload028(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:28,source:'V234',checkpoint:'RETURN-EVENT-028'},actorId);}
export function returnEventPayload029(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:29,source:'V234',checkpoint:'RETURN-EVENT-029'},actorId);}
export function returnEventPayload030(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:30,source:'V234',checkpoint:'RETURN-EVENT-030'},actorId);}
export function returnEventPayload031(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:31,source:'V234',checkpoint:'RETURN-EVENT-031'},actorId);}
export function returnEventPayload032(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:32,source:'V234',checkpoint:'RETURN-EVENT-032'},actorId);}
export function returnEventPayload033(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:33,source:'V234',checkpoint:'RETURN-EVENT-033'},actorId);}
export function returnEventPayload034(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:34,source:'V234',checkpoint:'RETURN-EVENT-034'},actorId);}
export function returnEventPayload035(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:35,source:'V234',checkpoint:'RETURN-EVENT-035'},actorId);}
export function returnEventPayload036(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:36,source:'V234',checkpoint:'RETURN-EVENT-036'},actorId);}
export function returnEventPayload037(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:37,source:'V234',checkpoint:'RETURN-EVENT-037'},actorId);}
export function returnEventPayload038(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:38,source:'V234',checkpoint:'RETURN-EVENT-038'},actorId);}
export function returnEventPayload039(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:39,source:'V234',checkpoint:'RETURN-EVENT-039'},actorId);}
export function returnEventPayload040(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:40,source:'V234',checkpoint:'RETURN-EVENT-040'},actorId);}
export function returnEventPayload041(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:41,source:'V234',checkpoint:'RETURN-EVENT-041'},actorId);}
export function returnEventPayload042(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:42,source:'V234',checkpoint:'RETURN-EVENT-042'},actorId);}
export function returnEventPayload043(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:43,source:'V234',checkpoint:'RETURN-EVENT-043'},actorId);}
export function returnEventPayload044(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:44,source:'V234',checkpoint:'RETURN-EVENT-044'},actorId);}
export function returnEventPayload045(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:45,source:'V234',checkpoint:'RETURN-EVENT-045'},actorId);}
export function returnEventPayload046(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:46,source:'V234',checkpoint:'RETURN-EVENT-046'},actorId);}
export function returnEventPayload047(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:47,source:'V234',checkpoint:'RETURN-EVENT-047'},actorId);}
export function returnEventPayload048(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:48,source:'V234',checkpoint:'RETURN-EVENT-048'},actorId);}
export function returnEventPayload049(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:49,source:'V234',checkpoint:'RETURN-EVENT-049'},actorId);}
export function returnEventPayload050(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:50,source:'V234',checkpoint:'RETURN-EVENT-050'},actorId);}
export function returnEventPayload051(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:51,source:'V234',checkpoint:'RETURN-EVENT-051'},actorId);}
export function returnEventPayload052(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:52,source:'V234',checkpoint:'RETURN-EVENT-052'},actorId);}
export function returnEventPayload053(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:53,source:'V234',checkpoint:'RETURN-EVENT-053'},actorId);}
export function returnEventPayload054(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:54,source:'V234',checkpoint:'RETURN-EVENT-054'},actorId);}
export function returnEventPayload055(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:55,source:'V234',checkpoint:'RETURN-EVENT-055'},actorId);}
export function returnEventPayload056(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:56,source:'V234',checkpoint:'RETURN-EVENT-056'},actorId);}
export function returnEventPayload057(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:57,source:'V234',checkpoint:'RETURN-EVENT-057'},actorId);}
export function returnEventPayload058(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:58,source:'V234',checkpoint:'RETURN-EVENT-058'},actorId);}
export function returnEventPayload059(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:59,source:'V234',checkpoint:'RETURN-EVENT-059'},actorId);}
export function returnEventPayload060(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:60,source:'V234',checkpoint:'RETURN-EVENT-060'},actorId);}
export function returnEventPayload061(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:61,source:'V234',checkpoint:'RETURN-EVENT-061'},actorId);}
export function returnEventPayload062(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:62,source:'V234',checkpoint:'RETURN-EVENT-062'},actorId);}
export function returnEventPayload063(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:63,source:'V234',checkpoint:'RETURN-EVENT-063'},actorId);}
export function returnEventPayload064(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:64,source:'V234',checkpoint:'RETURN-EVENT-064'},actorId);}
export function returnEventPayload065(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:65,source:'V234',checkpoint:'RETURN-EVENT-065'},actorId);}
export function returnEventPayload066(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:66,source:'V234',checkpoint:'RETURN-EVENT-066'},actorId);}
export function returnEventPayload067(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:67,source:'V234',checkpoint:'RETURN-EVENT-067'},actorId);}
export function returnEventPayload068(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:68,source:'V234',checkpoint:'RETURN-EVENT-068'},actorId);}
export function returnEventPayload069(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:69,source:'V234',checkpoint:'RETURN-EVENT-069'},actorId);}
export function returnEventPayload070(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:70,source:'V234',checkpoint:'RETURN-EVENT-070'},actorId);}
export function returnEventPayload071(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:71,source:'V234',checkpoint:'RETURN-EVENT-071'},actorId);}
export function returnEventPayload072(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:72,source:'V234',checkpoint:'RETURN-EVENT-072'},actorId);}
export function returnEventPayload073(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:73,source:'V234',checkpoint:'RETURN-EVENT-073'},actorId);}
export function returnEventPayload074(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:74,source:'V234',checkpoint:'RETURN-EVENT-074'},actorId);}
export function returnEventPayload075(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:75,source:'V234',checkpoint:'RETURN-EVENT-075'},actorId);}
export function returnEventPayload076(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:76,source:'V234',checkpoint:'RETURN-EVENT-076'},actorId);}
export function returnEventPayload077(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:77,source:'V234',checkpoint:'RETURN-EVENT-077'},actorId);}
export function returnEventPayload078(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:78,source:'V234',checkpoint:'RETURN-EVENT-078'},actorId);}
export function returnEventPayload079(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:79,source:'V234',checkpoint:'RETURN-EVENT-079'},actorId);}
export function returnEventPayload080(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:80,source:'V234',checkpoint:'RETURN-EVENT-080'},actorId);}
export function returnEventPayload081(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:81,source:'V234',checkpoint:'RETURN-EVENT-081'},actorId);}
export function returnEventPayload082(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:82,source:'V234',checkpoint:'RETURN-EVENT-082'},actorId);}
export function returnEventPayload083(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:83,source:'V234',checkpoint:'RETURN-EVENT-083'},actorId);}
export function returnEventPayload084(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:84,source:'V234',checkpoint:'RETURN-EVENT-084'},actorId);}
export function returnEventPayload085(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:85,source:'V234',checkpoint:'RETURN-EVENT-085'},actorId);}
export function returnEventPayload086(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:86,source:'V234',checkpoint:'RETURN-EVENT-086'},actorId);}
export function returnEventPayload087(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:87,source:'V234',checkpoint:'RETURN-EVENT-087'},actorId);}
export function returnEventPayload088(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:88,source:'V234',checkpoint:'RETURN-EVENT-088'},actorId);}
export function returnEventPayload089(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:89,source:'V234',checkpoint:'RETURN-EVENT-089'},actorId);}
export function returnEventPayload090(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:90,source:'V234',checkpoint:'RETURN-EVENT-090'},actorId);}
export function returnEventPayload091(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:91,source:'V234',checkpoint:'RETURN-EVENT-091'},actorId);}
export function returnEventPayload092(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:92,source:'V234',checkpoint:'RETURN-EVENT-092'},actorId);}
export function returnEventPayload093(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:93,source:'V234',checkpoint:'RETURN-EVENT-093'},actorId);}
export function returnEventPayload094(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:94,source:'V234',checkpoint:'RETURN-EVENT-094'},actorId);}
export function returnEventPayload095(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:95,source:'V234',checkpoint:'RETURN-EVENT-095'},actorId);}
export function returnEventPayload096(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:96,source:'V234',checkpoint:'RETURN-EVENT-096'},actorId);}
export function returnEventPayload097(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:97,source:'V234',checkpoint:'RETURN-EVENT-097'},actorId);}
export function returnEventPayload098(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:98,source:'V234',checkpoint:'RETURN-EVENT-098'},actorId);}
export function returnEventPayload099(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:99,source:'V234',checkpoint:'RETURN-EVENT-099'},actorId);}
export function returnEventPayload100(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:100,source:'V234',checkpoint:'RETURN-EVENT-100'},actorId);}
export function returnEventPayload101(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:101,source:'V234',checkpoint:'RETURN-EVENT-101'},actorId);}
export function returnEventPayload102(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:102,source:'V234',checkpoint:'RETURN-EVENT-102'},actorId);}
export function returnEventPayload103(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:103,source:'V234',checkpoint:'RETURN-EVENT-103'},actorId);}
export function returnEventPayload104(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:104,source:'V234',checkpoint:'RETURN-EVENT-104'},actorId);}
export function returnEventPayload105(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:105,source:'V234',checkpoint:'RETURN-EVENT-105'},actorId);}
export function returnEventPayload106(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:106,source:'V234',checkpoint:'RETURN-EVENT-106'},actorId);}
export function returnEventPayload107(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:107,source:'V234',checkpoint:'RETURN-EVENT-107'},actorId);}
export function returnEventPayload108(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:108,source:'V234',checkpoint:'RETURN-EVENT-108'},actorId);}
export function returnEventPayload109(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:109,source:'V234',checkpoint:'RETURN-EVENT-109'},actorId);}
export function returnEventPayload110(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:110,source:'V234',checkpoint:'RETURN-EVENT-110'},actorId);}
export function returnEventPayload111(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:111,source:'V234',checkpoint:'RETURN-EVENT-111'},actorId);}
export function returnEventPayload112(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:112,source:'V234',checkpoint:'RETURN-EVENT-112'},actorId);}
export function returnEventPayload113(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:113,source:'V234',checkpoint:'RETURN-EVENT-113'},actorId);}
export function returnEventPayload114(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:114,source:'V234',checkpoint:'RETURN-EVENT-114'},actorId);}
export function returnEventPayload115(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:115,source:'V234',checkpoint:'RETURN-EVENT-115'},actorId);}
export function returnEventPayload116(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:116,source:'V234',checkpoint:'RETURN-EVENT-116'},actorId);}
export function returnEventPayload117(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:117,source:'V234',checkpoint:'RETURN-EVENT-117'},actorId);}
export function returnEventPayload118(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:118,source:'V234',checkpoint:'RETURN-EVENT-118'},actorId);}
export function returnEventPayload119(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:119,source:'V234',checkpoint:'RETURN-EVENT-119'},actorId);}
export function returnEventPayload120(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:120,source:'V234',checkpoint:'RETURN-EVENT-120'},actorId);}
export function returnEventPayload121(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:121,source:'V234',checkpoint:'RETURN-EVENT-121'},actorId);}
export function returnEventPayload122(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:122,source:'V234',checkpoint:'RETURN-EVENT-122'},actorId);}
export function returnEventPayload123(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:123,source:'V234',checkpoint:'RETURN-EVENT-123'},actorId);}
export function returnEventPayload124(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:124,source:'V234',checkpoint:'RETURN-EVENT-124'},actorId);}
export function returnEventPayload125(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:125,source:'V234',checkpoint:'RETURN-EVENT-125'},actorId);}
export function returnEventPayload126(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:126,source:'V234',checkpoint:'RETURN-EVENT-126'},actorId);}
export function returnEventPayload127(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:127,source:'V234',checkpoint:'RETURN-EVENT-127'},actorId);}
export function returnEventPayload128(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:128,source:'V234',checkpoint:'RETURN-EVENT-128'},actorId);}
export function returnEventPayload129(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:129,source:'V234',checkpoint:'RETURN-EVENT-129'},actorId);}
export function returnEventPayload130(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:130,source:'V234',checkpoint:'RETURN-EVENT-130'},actorId);}
export function returnEventPayload131(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:131,source:'V234',checkpoint:'RETURN-EVENT-131'},actorId);}
export function returnEventPayload132(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:132,source:'V234',checkpoint:'RETURN-EVENT-132'},actorId);}
export function returnEventPayload133(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:133,source:'V234',checkpoint:'RETURN-EVENT-133'},actorId);}
export function returnEventPayload134(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:134,source:'V234',checkpoint:'RETURN-EVENT-134'},actorId);}
export function returnEventPayload135(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:135,source:'V234',checkpoint:'RETURN-EVENT-135'},actorId);}
export function returnEventPayload136(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:136,source:'V234',checkpoint:'RETURN-EVENT-136'},actorId);}
export function returnEventPayload137(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:137,source:'V234',checkpoint:'RETURN-EVENT-137'},actorId);}
export function returnEventPayload138(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:138,source:'V234',checkpoint:'RETURN-EVENT-138'},actorId);}
export function returnEventPayload139(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:139,source:'V234',checkpoint:'RETURN-EVENT-139'},actorId);}
export function returnEventPayload140(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:140,source:'V234',checkpoint:'RETURN-EVENT-140'},actorId);}
export function returnEventPayload141(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:141,source:'V234',checkpoint:'RETURN-EVENT-141'},actorId);}
export function returnEventPayload142(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:142,source:'V234',checkpoint:'RETURN-EVENT-142'},actorId);}
export function returnEventPayload143(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:143,source:'V234',checkpoint:'RETURN-EVENT-143'},actorId);}
export function returnEventPayload144(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:144,source:'V234',checkpoint:'RETURN-EVENT-144'},actorId);}
export function returnEventPayload145(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:145,source:'V234',checkpoint:'RETURN-EVENT-145'},actorId);}
export function returnEventPayload146(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:146,source:'V234',checkpoint:'RETURN-EVENT-146'},actorId);}
export function returnEventPayload147(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:147,source:'V234',checkpoint:'RETURN-EVENT-147'},actorId);}
export function returnEventPayload148(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:148,source:'V234',checkpoint:'RETURN-EVENT-148'},actorId);}
export function returnEventPayload149(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:149,source:'V234',checkpoint:'RETURN-EVENT-149'},actorId);}
export function returnEventPayload150(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:150,source:'V234',checkpoint:'RETURN-EVENT-150'},actorId);}
export function returnEventPayload151(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:151,source:'V234',checkpoint:'RETURN-EVENT-151'},actorId);}
export function returnEventPayload152(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:152,source:'V234',checkpoint:'RETURN-EVENT-152'},actorId);}
export function returnEventPayload153(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:153,source:'V234',checkpoint:'RETURN-EVENT-153'},actorId);}
export function returnEventPayload154(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:154,source:'V234',checkpoint:'RETURN-EVENT-154'},actorId);}
export function returnEventPayload155(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:155,source:'V234',checkpoint:'RETURN-EVENT-155'},actorId);}
export function returnEventPayload156(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:156,source:'V234',checkpoint:'RETURN-EVENT-156'},actorId);}
export function returnEventPayload157(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:157,source:'V234',checkpoint:'RETURN-EVENT-157'},actorId);}
export function returnEventPayload158(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:158,source:'V234',checkpoint:'RETURN-EVENT-158'},actorId);}
export function returnEventPayload159(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:159,source:'V234',checkpoint:'RETURN-EVENT-159'},actorId);}
export function returnEventPayload160(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:160,source:'V234',checkpoint:'RETURN-EVENT-160'},actorId);}
export function returnEventPayload161(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:161,source:'V234',checkpoint:'RETURN-EVENT-161'},actorId);}
export function returnEventPayload162(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:162,source:'V234',checkpoint:'RETURN-EVENT-162'},actorId);}
export function returnEventPayload163(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:163,source:'V234',checkpoint:'RETURN-EVENT-163'},actorId);}
export function returnEventPayload164(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:164,source:'V234',checkpoint:'RETURN-EVENT-164'},actorId);}
export function returnEventPayload165(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:165,source:'V234',checkpoint:'RETURN-EVENT-165'},actorId);}
export function returnEventPayload166(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:166,source:'V234',checkpoint:'RETURN-EVENT-166'},actorId);}
export function returnEventPayload167(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:167,source:'V234',checkpoint:'RETURN-EVENT-167'},actorId);}
export function returnEventPayload168(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:168,source:'V234',checkpoint:'RETURN-EVENT-168'},actorId);}
export function returnEventPayload169(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:169,source:'V234',checkpoint:'RETURN-EVENT-169'},actorId);}
export function returnEventPayload170(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:170,source:'V234',checkpoint:'RETURN-EVENT-170'},actorId);}
export function returnEventPayload171(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:171,source:'V234',checkpoint:'RETURN-EVENT-171'},actorId);}
export function returnEventPayload172(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:172,source:'V234',checkpoint:'RETURN-EVENT-172'},actorId);}
export function returnEventPayload173(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:173,source:'V234',checkpoint:'RETURN-EVENT-173'},actorId);}
export function returnEventPayload174(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:174,source:'V234',checkpoint:'RETURN-EVENT-174'},actorId);}
export function returnEventPayload175(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:175,source:'V234',checkpoint:'RETURN-EVENT-175'},actorId);}
export function returnEventPayload176(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:176,source:'V234',checkpoint:'RETURN-EVENT-176'},actorId);}
export function returnEventPayload177(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:177,source:'V234',checkpoint:'RETURN-EVENT-177'},actorId);}
export function returnEventPayload178(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:178,source:'V234',checkpoint:'RETURN-EVENT-178'},actorId);}
export function returnEventPayload179(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:179,source:'V234',checkpoint:'RETURN-EVENT-179'},actorId);}
export function returnEventPayload180(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:180,source:'V234',checkpoint:'RETURN-EVENT-180'},actorId);}
export function returnEventPayload181(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:181,source:'V234',checkpoint:'RETURN-EVENT-181'},actorId);}
export function returnEventPayload182(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:182,source:'V234',checkpoint:'RETURN-EVENT-182'},actorId);}
export function returnEventPayload183(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:183,source:'V234',checkpoint:'RETURN-EVENT-183'},actorId);}
export function returnEventPayload184(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:184,source:'V234',checkpoint:'RETURN-EVENT-184'},actorId);}
export function returnEventPayload185(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:185,source:'V234',checkpoint:'RETURN-EVENT-185'},actorId);}
export function returnEventPayload186(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:186,source:'V234',checkpoint:'RETURN-EVENT-186'},actorId);}
export function returnEventPayload187(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:187,source:'V234',checkpoint:'RETURN-EVENT-187'},actorId);}
export function returnEventPayload188(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:188,source:'V234',checkpoint:'RETURN-EVENT-188'},actorId);}
export function returnEventPayload189(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:189,source:'V234',checkpoint:'RETURN-EVENT-189'},actorId);}
export function returnEventPayload190(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:190,source:'V234',checkpoint:'RETURN-EVENT-190'},actorId);}
export function returnEventPayload191(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:191,source:'V234',checkpoint:'RETURN-EVENT-191'},actorId);}
export function returnEventPayload192(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:192,source:'V234',checkpoint:'RETURN-EVENT-192'},actorId);}
export function returnEventPayload193(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:193,source:'V234',checkpoint:'RETURN-EVENT-193'},actorId);}
export function returnEventPayload194(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:194,source:'V234',checkpoint:'RETURN-EVENT-194'},actorId);}
export function returnEventPayload195(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:195,source:'V234',checkpoint:'RETURN-EVENT-195'},actorId);}
export function returnEventPayload196(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:196,source:'V234',checkpoint:'RETURN-EVENT-196'},actorId);}
export function returnEventPayload197(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:197,source:'V234',checkpoint:'RETURN-EVENT-197'},actorId);}
export function returnEventPayload198(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:198,source:'V234',checkpoint:'RETURN-EVENT-198'},actorId);}
export function returnEventPayload199(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:199,source:'V234',checkpoint:'RETURN-EVENT-199'},actorId);}
export function returnEventPayload200(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:200,source:'V234',checkpoint:'RETURN-EVENT-200'},actorId);}
export function returnEventPayload201(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:201,source:'V234',checkpoint:'RETURN-EVENT-201'},actorId);}
export function returnEventPayload202(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:202,source:'V234',checkpoint:'RETURN-EVENT-202'},actorId);}
export function returnEventPayload203(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:203,source:'V234',checkpoint:'RETURN-EVENT-203'},actorId);}
export function returnEventPayload204(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:204,source:'V234',checkpoint:'RETURN-EVENT-204'},actorId);}
export function returnEventPayload205(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:205,source:'V234',checkpoint:'RETURN-EVENT-205'},actorId);}
export function returnEventPayload206(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:206,source:'V234',checkpoint:'RETURN-EVENT-206'},actorId);}
export function returnEventPayload207(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:207,source:'V234',checkpoint:'RETURN-EVENT-207'},actorId);}
export function returnEventPayload208(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:208,source:'V234',checkpoint:'RETURN-EVENT-208'},actorId);}
export function returnEventPayload209(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:209,source:'V234',checkpoint:'RETURN-EVENT-209'},actorId);}
export function returnEventPayload210(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:210,source:'V234',checkpoint:'RETURN-EVENT-210'},actorId);}
export function returnEventPayload211(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:211,source:'V234',checkpoint:'RETURN-EVENT-211'},actorId);}
export function returnEventPayload212(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:212,source:'V234',checkpoint:'RETURN-EVENT-212'},actorId);}
export function returnEventPayload213(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:213,source:'V234',checkpoint:'RETURN-EVENT-213'},actorId);}
export function returnEventPayload214(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:214,source:'V234',checkpoint:'RETURN-EVENT-214'},actorId);}
export function returnEventPayload215(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:215,source:'V234',checkpoint:'RETURN-EVENT-215'},actorId);}
export function returnEventPayload216(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:216,source:'V234',checkpoint:'RETURN-EVENT-216'},actorId);}
export function returnEventPayload217(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:217,source:'V234',checkpoint:'RETURN-EVENT-217'},actorId);}
export function returnEventPayload218(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:218,source:'V234',checkpoint:'RETURN-EVENT-218'},actorId);}
export function returnEventPayload219(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:219,source:'V234',checkpoint:'RETURN-EVENT-219'},actorId);}
export function returnEventPayload220(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:220,source:'V234',checkpoint:'RETURN-EVENT-220'},actorId);}
export function returnEventPayload221(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:221,source:'V234',checkpoint:'RETURN-EVENT-221'},actorId);}
export function returnEventPayload222(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:222,source:'V234',checkpoint:'RETURN-EVENT-222'},actorId);}
export function returnEventPayload223(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:223,source:'V234',checkpoint:'RETURN-EVENT-223'},actorId);}
export function returnEventPayload224(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:224,source:'V234',checkpoint:'RETURN-EVENT-224'},actorId);}
export function returnEventPayload225(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:225,source:'V234',checkpoint:'RETURN-EVENT-225'},actorId);}
export function returnEventPayload226(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:226,source:'V234',checkpoint:'RETURN-EVENT-226'},actorId);}
export function returnEventPayload227(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:227,source:'V234',checkpoint:'RETURN-EVENT-227'},actorId);}
export function returnEventPayload228(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:228,source:'V234',checkpoint:'RETURN-EVENT-228'},actorId);}
export function returnEventPayload229(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:229,source:'V234',checkpoint:'RETURN-EVENT-229'},actorId);}
export function returnEventPayload230(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:230,source:'V234',checkpoint:'RETURN-EVENT-230'},actorId);}
export function returnEventPayload231(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:231,source:'V234',checkpoint:'RETURN-EVENT-231'},actorId);}
export function returnEventPayload232(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:232,source:'V234',checkpoint:'RETURN-EVENT-232'},actorId);}
export function returnEventPayload233(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:233,source:'V234',checkpoint:'RETURN-EVENT-233'},actorId);}
export function returnEventPayload234(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:234,source:'V234',checkpoint:'RETURN-EVENT-234'},actorId);}
export function returnEventPayload235(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:235,source:'V234',checkpoint:'RETURN-EVENT-235'},actorId);}
export function returnEventPayload236(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:236,source:'V234',checkpoint:'RETURN-EVENT-236'},actorId);}
export function returnEventPayload237(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:237,source:'V234',checkpoint:'RETURN-EVENT-237'},actorId);}
export function returnEventPayload238(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:238,source:'V234',checkpoint:'RETURN-EVENT-238'},actorId);}
export function returnEventPayload239(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:239,source:'V234',checkpoint:'RETURN-EVENT-239'},actorId);}
export function returnEventPayload240(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:240,source:'V234',checkpoint:'RETURN-EVENT-240'},actorId);}
export function returnEventPayload241(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:241,source:'V234',checkpoint:'RETURN-EVENT-241'},actorId);}
export function returnEventPayload242(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:242,source:'V234',checkpoint:'RETURN-EVENT-242'},actorId);}
export function returnEventPayload243(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:243,source:'V234',checkpoint:'RETURN-EVENT-243'},actorId);}
export function returnEventPayload244(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:244,source:'V234',checkpoint:'RETURN-EVENT-244'},actorId);}
export function returnEventPayload245(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:245,source:'V234',checkpoint:'RETURN-EVENT-245'},actorId);}
export function returnEventPayload246(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:246,source:'V234',checkpoint:'RETURN-EVENT-246'},actorId);}
export function returnEventPayload247(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:247,source:'V234',checkpoint:'RETURN-EVENT-247'},actorId);}
export function returnEventPayload248(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:248,source:'V234',checkpoint:'RETURN-EVENT-248'},actorId);}
export function returnEventPayload249(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:249,source:'V234',checkpoint:'RETURN-EVENT-249'},actorId);}
export function returnEventPayload250(returnId:string,actorId?:string){return eventEnvelope('return.requested',returnId,{sequence:250,source:'V234',checkpoint:'RETURN-EVENT-250'},actorId);}
