import type { SqlExecutor } from '../../platform/persistence/postgres-boundary';
import { requestHash, ensureIdempotency, saveIdempotency } from '../../platform/persistence/transaction-store';
import { assertReturnTransition } from './state';
import type { ReturnStatus, ReturnItemCondition, InspectionDecision } from './contracts';
import { normalizeNote, normalizePositiveInteger } from './contracts';

export type Disposition='RESTOCK'|'QUARANTINE'|'DISPOSE'|'RETURN_TO_VENDOR'|'REPLACE';
export type WarehouseAction={returnId:string;actorId:string;disposition:Disposition;itemId:string;quantity:number;note?:string;idempotencyKey:string};
export type ReturnQueueFilter={status?:ReturnStatus;olderThanHours?:number;limit?:number};
const roles=['admin','operations','support'];
export function isOperationsRole(role:string){return roles.includes(role);}
export function dispositionForCondition(condition:ReturnItemCondition,restockable:boolean):Disposition{if(restockable&&(condition==='SEALED'||condition==='OPENED'))return 'RESTOCK';if(condition==='DEFECTIVE')return 'RETURN_TO_VENDOR';if(condition==='DAMAGED'||condition==='USED')return 'QUARANTINE';return 'QUARANTINE';}
export function dispositionNeedsReview(d:Disposition){return d==='DISPOSE'||d==='RETURN_TO_VENDOR';}
export function normalizeDisposition(value:unknown):Disposition|undefined{const v=String(value||'');return ['RESTOCK','QUARANTINE','DISPOSE','RETURN_TO_VENDOR','REPLACE'].includes(v)?v as Disposition:undefined;}
export async function loadOperationsQueue(db:SqlExecutor,filter:ReturnQueueFilter={}){const limit=Math.min(Math.max(Number(filter.limit)||50,1),200);const hours=Math.max(0,Number(filter.olderThanHours||0));const params:any[]=[];let where='1=1';if(filter.status){where+=' and r.status=$'+(params.length+1);params.push(filter.status);}if(hours>0){where+=' and r.updated_at < now()-($'+(params.length+1)+' || \' hours\')::interval';params.push(hours);}params.push(limit);const sql=`select r.id,r.order_id,r.customer_id,r.status,r.reason_code,r.reason_note,r.requested_at,r.updated_at,coalesce(sum(ri.quantity),0) item_quantity from trust_returns r left join trust_return_items ri on ri.return_id=r.id where ${where} group by r.id order by r.updated_at asc limit $${params.length}`;return (await db.query(sql,params)).rows;}
export async function getReturnOperationalSnapshot(db:SqlExecutor,returnId:string){const [r,i,s,o]=await Promise.all([db.query('select * from trust_returns where id=$1',[returnId]),db.query('select * from trust_return_items where return_id=$1 order by created_at',[returnId]),db.query('select * from trust_return_inspections where return_id=$1 order by created_at desc',[returnId]),db.query('select * from trust_refund_settlements where return_id=$1 order by created_at desc',[returnId])]);return{return:r.rows[0]||null,items:i.rows,inspections:s.rows,settlements:o.rows};}
export async function recordWarehouseDisposition(db:SqlExecutor,input:WarehouseAction){const itemId=String(input.itemId||'');const returnId=String(input.returnId||'');const actorId=String(input.actorId||'');const key=String(input.idempotencyKey||'');const quantity=normalizePositiveInteger(input.quantity);if(!itemId||!returnId||!actorId||!key||!quantity)throw new Error('INVALID_DISPOSITION');const disposition=normalizeDisposition(input.disposition);if(!disposition)throw new Error('INVALID_DISPOSITION');return db.transaction(async tx=>{const hash=requestHash('return.disposition',{returnId,itemId,quantity,disposition,note:normalizeNote(input.note)});const cached=await ensureIdempotency(tx,key,'return.disposition',hash);if(cached)return{...(cached as object),replay:true};const item=await tx.query<{id:string;quantity:number;condition:ReturnItemCondition}>('select id,quantity,condition from trust_return_items where id=$1 and return_id=$2 for update',[itemId,returnId]);if(!item.rows[0])throw new Error('RETURN_ITEM_NOT_FOUND');if(quantity>Number(item.rows[0].quantity))throw new Error('DISPOSITION_QUANTITY_EXCEEDS_RETURN');const id=`disp_${crypto.randomUUID()}`;await tx.query('insert into trust_outbox_events(event_type,aggregate_id,payload_json) values(\'return.warehouse.disposition\',$1,$2::jsonb)',[returnId,JSON.stringify({id,returnId,itemId,quantity,disposition,condition:item.rows[0].condition,actorId,note:normalizeNote(input.note)})]);const result={id,returnId,itemId,quantity,disposition,replay:false};await saveIdempotency(tx,key,'return.disposition',result,86400,hash);return result;});}
export async function markReturnClosed(db:SqlExecutor,input:{returnId:string;actorId:string;note?:string}){return db.transaction(async tx=>{const r=await tx.query<{status:ReturnStatus;customer_id:string|null}>('select status,customer_id from trust_returns where id=$1 for update',[input.returnId]);if(!r.rows[0])throw new Error('RETURN_NOT_FOUND');assertReturnTransition(r.rows[0].status,'CLOSED');await tx.query('update trust_returns set status=\'CLOSED\',closed_at=now(),updated_at=now() where id=$1',[input.returnId]);await tx.query('insert into trust_return_events(return_id,from_status,to_status,source,actor_id,note) values($1,$2,\'CLOSED\',\'operations\',$3,$4)',[input.returnId,r.rows[0].status,input.actorId,normalizeNote(input.note)]);await tx.query('insert into trust_outbox_events(event_type,aggregate_id,payload_json) values(\'return.closed\',$1,$2::jsonb)',[input.returnId,JSON.stringify({returnId:input.returnId,actorId:input.actorId})]);return{returnId:input.returnId,status:'CLOSED',from:r.rows[0].status};});}

export function operationsMetric001(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-001',active,amount,ageHours:age,priority:active?Math.min(100,1+Math.floor(age/24)):0};}
export function operationsMetric002(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-002',active,amount,ageHours:age,priority:active?Math.min(100,2+Math.floor(age/24)):0};}
export function operationsMetric003(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-003',active,amount,ageHours:age,priority:active?Math.min(100,3+Math.floor(age/24)):0};}
export function operationsMetric004(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-004',active,amount,ageHours:age,priority:active?Math.min(100,4+Math.floor(age/24)):0};}
export function operationsMetric005(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-005',active,amount,ageHours:age,priority:active?Math.min(100,5+Math.floor(age/24)):0};}
export function operationsMetric006(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-006',active,amount,ageHours:age,priority:active?Math.min(100,6+Math.floor(age/24)):0};}
export function operationsMetric007(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-007',active,amount,ageHours:age,priority:active?Math.min(100,7+Math.floor(age/24)):0};}
export function operationsMetric008(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-008',active,amount,ageHours:age,priority:active?Math.min(100,8+Math.floor(age/24)):0};}
export function operationsMetric009(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-009',active,amount,ageHours:age,priority:active?Math.min(100,9+Math.floor(age/24)):0};}
export function operationsMetric010(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-010',active,amount,ageHours:age,priority:active?Math.min(100,10+Math.floor(age/24)):0};}
export function operationsMetric011(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-011',active,amount,ageHours:age,priority:active?Math.min(100,11+Math.floor(age/24)):0};}
export function operationsMetric012(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-012',active,amount,ageHours:age,priority:active?Math.min(100,12+Math.floor(age/24)):0};}
export function operationsMetric013(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-013',active,amount,ageHours:age,priority:active?Math.min(100,13+Math.floor(age/24)):0};}
export function operationsMetric014(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-014',active,amount,ageHours:age,priority:active?Math.min(100,14+Math.floor(age/24)):0};}
export function operationsMetric015(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-015',active,amount,ageHours:age,priority:active?Math.min(100,15+Math.floor(age/24)):0};}
export function operationsMetric016(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-016',active,amount,ageHours:age,priority:active?Math.min(100,16+Math.floor(age/24)):0};}
export function operationsMetric017(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-017',active,amount,ageHours:age,priority:active?Math.min(100,17+Math.floor(age/24)):0};}
export function operationsMetric018(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-018',active,amount,ageHours:age,priority:active?Math.min(100,18+Math.floor(age/24)):0};}
export function operationsMetric019(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-019',active,amount,ageHours:age,priority:active?Math.min(100,19+Math.floor(age/24)):0};}
export function operationsMetric020(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-020',active,amount,ageHours:age,priority:active?Math.min(100,20+Math.floor(age/24)):0};}
export function operationsMetric021(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-021',active,amount,ageHours:age,priority:active?Math.min(100,21+Math.floor(age/24)):0};}
export function operationsMetric022(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-022',active,amount,ageHours:age,priority:active?Math.min(100,22+Math.floor(age/24)):0};}
export function operationsMetric023(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-023',active,amount,ageHours:age,priority:active?Math.min(100,23+Math.floor(age/24)):0};}
export function operationsMetric024(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-024',active,amount,ageHours:age,priority:active?Math.min(100,24+Math.floor(age/24)):0};}
export function operationsMetric025(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-025',active,amount,ageHours:age,priority:active?Math.min(100,25+Math.floor(age/24)):0};}
export function operationsMetric026(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-026',active,amount,ageHours:age,priority:active?Math.min(100,26+Math.floor(age/24)):0};}
export function operationsMetric027(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-027',active,amount,ageHours:age,priority:active?Math.min(100,27+Math.floor(age/24)):0};}
export function operationsMetric028(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-028',active,amount,ageHours:age,priority:active?Math.min(100,28+Math.floor(age/24)):0};}
export function operationsMetric029(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-029',active,amount,ageHours:age,priority:active?Math.min(100,29+Math.floor(age/24)):0};}
export function operationsMetric030(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-030',active,amount,ageHours:age,priority:active?Math.min(100,30+Math.floor(age/24)):0};}
export function operationsMetric031(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-031',active,amount,ageHours:age,priority:active?Math.min(100,31+Math.floor(age/24)):0};}
export function operationsMetric032(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-032',active,amount,ageHours:age,priority:active?Math.min(100,32+Math.floor(age/24)):0};}
export function operationsMetric033(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-033',active,amount,ageHours:age,priority:active?Math.min(100,33+Math.floor(age/24)):0};}
export function operationsMetric034(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-034',active,amount,ageHours:age,priority:active?Math.min(100,34+Math.floor(age/24)):0};}
export function operationsMetric035(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-035',active,amount,ageHours:age,priority:active?Math.min(100,35+Math.floor(age/24)):0};}
export function operationsMetric036(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-036',active,amount,ageHours:age,priority:active?Math.min(100,36+Math.floor(age/24)):0};}
export function operationsMetric037(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-037',active,amount,ageHours:age,priority:active?Math.min(100,37+Math.floor(age/24)):0};}
export function operationsMetric038(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-038',active,amount,ageHours:age,priority:active?Math.min(100,38+Math.floor(age/24)):0};}
export function operationsMetric039(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-039',active,amount,ageHours:age,priority:active?Math.min(100,39+Math.floor(age/24)):0};}
export function operationsMetric040(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-040',active,amount,ageHours:age,priority:active?Math.min(100,40+Math.floor(age/24)):0};}
export function operationsMetric041(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-041',active,amount,ageHours:age,priority:active?Math.min(100,41+Math.floor(age/24)):0};}
export function operationsMetric042(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-042',active,amount,ageHours:age,priority:active?Math.min(100,42+Math.floor(age/24)):0};}
export function operationsMetric043(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-043',active,amount,ageHours:age,priority:active?Math.min(100,43+Math.floor(age/24)):0};}
export function operationsMetric044(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-044',active,amount,ageHours:age,priority:active?Math.min(100,44+Math.floor(age/24)):0};}
export function operationsMetric045(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-045',active,amount,ageHours:age,priority:active?Math.min(100,45+Math.floor(age/24)):0};}
export function operationsMetric046(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-046',active,amount,ageHours:age,priority:active?Math.min(100,46+Math.floor(age/24)):0};}
export function operationsMetric047(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-047',active,amount,ageHours:age,priority:active?Math.min(100,47+Math.floor(age/24)):0};}
export function operationsMetric048(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-048',active,amount,ageHours:age,priority:active?Math.min(100,48+Math.floor(age/24)):0};}
export function operationsMetric049(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-049',active,amount,ageHours:age,priority:active?Math.min(100,49+Math.floor(age/24)):0};}
export function operationsMetric050(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-050',active,amount,ageHours:age,priority:active?Math.min(100,50+Math.floor(age/24)):0};}
export function operationsMetric051(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-051',active,amount,ageHours:age,priority:active?Math.min(100,51+Math.floor(age/24)):0};}
export function operationsMetric052(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-052',active,amount,ageHours:age,priority:active?Math.min(100,52+Math.floor(age/24)):0};}
export function operationsMetric053(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-053',active,amount,ageHours:age,priority:active?Math.min(100,53+Math.floor(age/24)):0};}
export function operationsMetric054(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-054',active,amount,ageHours:age,priority:active?Math.min(100,54+Math.floor(age/24)):0};}
export function operationsMetric055(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-055',active,amount,ageHours:age,priority:active?Math.min(100,55+Math.floor(age/24)):0};}
export function operationsMetric056(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-056',active,amount,ageHours:age,priority:active?Math.min(100,56+Math.floor(age/24)):0};}
export function operationsMetric057(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-057',active,amount,ageHours:age,priority:active?Math.min(100,57+Math.floor(age/24)):0};}
export function operationsMetric058(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-058',active,amount,ageHours:age,priority:active?Math.min(100,58+Math.floor(age/24)):0};}
export function operationsMetric059(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-059',active,amount,ageHours:age,priority:active?Math.min(100,59+Math.floor(age/24)):0};}
export function operationsMetric060(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-060',active,amount,ageHours:age,priority:active?Math.min(100,60+Math.floor(age/24)):0};}
export function operationsMetric061(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-061',active,amount,ageHours:age,priority:active?Math.min(100,61+Math.floor(age/24)):0};}
export function operationsMetric062(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-062',active,amount,ageHours:age,priority:active?Math.min(100,62+Math.floor(age/24)):0};}
export function operationsMetric063(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-063',active,amount,ageHours:age,priority:active?Math.min(100,63+Math.floor(age/24)):0};}
export function operationsMetric064(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-064',active,amount,ageHours:age,priority:active?Math.min(100,64+Math.floor(age/24)):0};}
export function operationsMetric065(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-065',active,amount,ageHours:age,priority:active?Math.min(100,65+Math.floor(age/24)):0};}
export function operationsMetric066(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-066',active,amount,ageHours:age,priority:active?Math.min(100,66+Math.floor(age/24)):0};}
export function operationsMetric067(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-067',active,amount,ageHours:age,priority:active?Math.min(100,67+Math.floor(age/24)):0};}
export function operationsMetric068(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-068',active,amount,ageHours:age,priority:active?Math.min(100,68+Math.floor(age/24)):0};}
export function operationsMetric069(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-069',active,amount,ageHours:age,priority:active?Math.min(100,69+Math.floor(age/24)):0};}
export function operationsMetric070(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-070',active,amount,ageHours:age,priority:active?Math.min(100,70+Math.floor(age/24)):0};}
export function operationsMetric071(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-071',active,amount,ageHours:age,priority:active?Math.min(100,71+Math.floor(age/24)):0};}
export function operationsMetric072(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-072',active,amount,ageHours:age,priority:active?Math.min(100,72+Math.floor(age/24)):0};}
export function operationsMetric073(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-073',active,amount,ageHours:age,priority:active?Math.min(100,73+Math.floor(age/24)):0};}
export function operationsMetric074(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-074',active,amount,ageHours:age,priority:active?Math.min(100,74+Math.floor(age/24)):0};}
export function operationsMetric075(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-075',active,amount,ageHours:age,priority:active?Math.min(100,75+Math.floor(age/24)):0};}
export function operationsMetric076(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-076',active,amount,ageHours:age,priority:active?Math.min(100,76+Math.floor(age/24)):0};}
export function operationsMetric077(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-077',active,amount,ageHours:age,priority:active?Math.min(100,77+Math.floor(age/24)):0};}
export function operationsMetric078(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-078',active,amount,ageHours:age,priority:active?Math.min(100,78+Math.floor(age/24)):0};}
export function operationsMetric079(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-079',active,amount,ageHours:age,priority:active?Math.min(100,79+Math.floor(age/24)):0};}
export function operationsMetric080(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-080',active,amount,ageHours:age,priority:active?Math.min(100,80+Math.floor(age/24)):0};}
export function operationsMetric081(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-081',active,amount,ageHours:age,priority:active?Math.min(100,81+Math.floor(age/24)):0};}
export function operationsMetric082(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-082',active,amount,ageHours:age,priority:active?Math.min(100,82+Math.floor(age/24)):0};}
export function operationsMetric083(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-083',active,amount,ageHours:age,priority:active?Math.min(100,83+Math.floor(age/24)):0};}
export function operationsMetric084(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-084',active,amount,ageHours:age,priority:active?Math.min(100,84+Math.floor(age/24)):0};}
export function operationsMetric085(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-085',active,amount,ageHours:age,priority:active?Math.min(100,85+Math.floor(age/24)):0};}
export function operationsMetric086(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-086',active,amount,ageHours:age,priority:active?Math.min(100,86+Math.floor(age/24)):0};}
export function operationsMetric087(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-087',active,amount,ageHours:age,priority:active?Math.min(100,87+Math.floor(age/24)):0};}
export function operationsMetric088(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-088',active,amount,ageHours:age,priority:active?Math.min(100,88+Math.floor(age/24)):0};}
export function operationsMetric089(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-089',active,amount,ageHours:age,priority:active?Math.min(100,89+Math.floor(age/24)):0};}
export function operationsMetric090(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-090',active,amount,ageHours:age,priority:active?Math.min(100,90+Math.floor(age/24)):0};}
export function operationsMetric091(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-091',active,amount,ageHours:age,priority:active?Math.min(100,91+Math.floor(age/24)):0};}
export function operationsMetric092(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-092',active,amount,ageHours:age,priority:active?Math.min(100,92+Math.floor(age/24)):0};}
export function operationsMetric093(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-093',active,amount,ageHours:age,priority:active?Math.min(100,93+Math.floor(age/24)):0};}
export function operationsMetric094(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-094',active,amount,ageHours:age,priority:active?Math.min(100,94+Math.floor(age/24)):0};}
export function operationsMetric095(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-095',active,amount,ageHours:age,priority:active?Math.min(100,95+Math.floor(age/24)):0};}
export function operationsMetric096(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-096',active,amount,ageHours:age,priority:active?Math.min(100,96+Math.floor(age/24)):0};}
export function operationsMetric097(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-097',active,amount,ageHours:age,priority:active?Math.min(100,97+Math.floor(age/24)):0};}
export function operationsMetric098(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-098',active,amount,ageHours:age,priority:active?Math.min(100,98+Math.floor(age/24)):0};}
export function operationsMetric099(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-099',active,amount,ageHours:age,priority:active?Math.min(100,99+Math.floor(age/24)):0};}
export function operationsMetric100(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-100',active,amount,ageHours:age,priority:active?Math.min(100,100+Math.floor(age/24)):0};}
export function operationsMetric101(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-101',active,amount,ageHours:age,priority:active?Math.min(100,101+Math.floor(age/24)):0};}
export function operationsMetric102(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-102',active,amount,ageHours:age,priority:active?Math.min(100,102+Math.floor(age/24)):0};}
export function operationsMetric103(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-103',active,amount,ageHours:age,priority:active?Math.min(100,103+Math.floor(age/24)):0};}
export function operationsMetric104(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-104',active,amount,ageHours:age,priority:active?Math.min(100,104+Math.floor(age/24)):0};}
export function operationsMetric105(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-105',active,amount,ageHours:age,priority:active?Math.min(100,105+Math.floor(age/24)):0};}
export function operationsMetric106(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-106',active,amount,ageHours:age,priority:active?Math.min(100,106+Math.floor(age/24)):0};}
export function operationsMetric107(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-107',active,amount,ageHours:age,priority:active?Math.min(100,107+Math.floor(age/24)):0};}
export function operationsMetric108(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-108',active,amount,ageHours:age,priority:active?Math.min(100,108+Math.floor(age/24)):0};}
export function operationsMetric109(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-109',active,amount,ageHours:age,priority:active?Math.min(100,109+Math.floor(age/24)):0};}
export function operationsMetric110(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-110',active,amount,ageHours:age,priority:active?Math.min(100,110+Math.floor(age/24)):0};}
export function operationsMetric111(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-111',active,amount,ageHours:age,priority:active?Math.min(100,111+Math.floor(age/24)):0};}
export function operationsMetric112(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-112',active,amount,ageHours:age,priority:active?Math.min(100,112+Math.floor(age/24)):0};}
export function operationsMetric113(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-113',active,amount,ageHours:age,priority:active?Math.min(100,113+Math.floor(age/24)):0};}
export function operationsMetric114(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-114',active,amount,ageHours:age,priority:active?Math.min(100,114+Math.floor(age/24)):0};}
export function operationsMetric115(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-115',active,amount,ageHours:age,priority:active?Math.min(100,115+Math.floor(age/24)):0};}
export function operationsMetric116(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-116',active,amount,ageHours:age,priority:active?Math.min(100,116+Math.floor(age/24)):0};}
export function operationsMetric117(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-117',active,amount,ageHours:age,priority:active?Math.min(100,117+Math.floor(age/24)):0};}
export function operationsMetric118(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-118',active,amount,ageHours:age,priority:active?Math.min(100,118+Math.floor(age/24)):0};}
export function operationsMetric119(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-119',active,amount,ageHours:age,priority:active?Math.min(100,119+Math.floor(age/24)):0};}
export function operationsMetric120(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-120',active,amount,ageHours:age,priority:active?Math.min(100,120+Math.floor(age/24)):0};}
export function operationsMetric121(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-121',active,amount,ageHours:age,priority:active?Math.min(100,121+Math.floor(age/24)):0};}
export function operationsMetric122(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-122',active,amount,ageHours:age,priority:active?Math.min(100,122+Math.floor(age/24)):0};}
export function operationsMetric123(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-123',active,amount,ageHours:age,priority:active?Math.min(100,123+Math.floor(age/24)):0};}
export function operationsMetric124(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-124',active,amount,ageHours:age,priority:active?Math.min(100,124+Math.floor(age/24)):0};}
export function operationsMetric125(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-125',active,amount,ageHours:age,priority:active?Math.min(100,125+Math.floor(age/24)):0};}
export function operationsMetric126(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-126',active,amount,ageHours:age,priority:active?Math.min(100,126+Math.floor(age/24)):0};}
export function operationsMetric127(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-127',active,amount,ageHours:age,priority:active?Math.min(100,127+Math.floor(age/24)):0};}
export function operationsMetric128(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-128',active,amount,ageHours:age,priority:active?Math.min(100,128+Math.floor(age/24)):0};}
export function operationsMetric129(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-129',active,amount,ageHours:age,priority:active?Math.min(100,129+Math.floor(age/24)):0};}
export function operationsMetric130(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-130',active,amount,ageHours:age,priority:active?Math.min(100,130+Math.floor(age/24)):0};}
export function operationsMetric131(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-131',active,amount,ageHours:age,priority:active?Math.min(100,131+Math.floor(age/24)):0};}
export function operationsMetric132(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-132',active,amount,ageHours:age,priority:active?Math.min(100,132+Math.floor(age/24)):0};}
export function operationsMetric133(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-133',active,amount,ageHours:age,priority:active?Math.min(100,133+Math.floor(age/24)):0};}
export function operationsMetric134(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-134',active,amount,ageHours:age,priority:active?Math.min(100,134+Math.floor(age/24)):0};}
export function operationsMetric135(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-135',active,amount,ageHours:age,priority:active?Math.min(100,135+Math.floor(age/24)):0};}
export function operationsMetric136(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-136',active,amount,ageHours:age,priority:active?Math.min(100,136+Math.floor(age/24)):0};}
export function operationsMetric137(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-137',active,amount,ageHours:age,priority:active?Math.min(100,137+Math.floor(age/24)):0};}
export function operationsMetric138(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-138',active,amount,ageHours:age,priority:active?Math.min(100,138+Math.floor(age/24)):0};}
export function operationsMetric139(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-139',active,amount,ageHours:age,priority:active?Math.min(100,139+Math.floor(age/24)):0};}
export function operationsMetric140(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-140',active,amount,ageHours:age,priority:active?Math.min(100,140+Math.floor(age/24)):0};}
export function operationsMetric141(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-141',active,amount,ageHours:age,priority:active?Math.min(100,141+Math.floor(age/24)):0};}
export function operationsMetric142(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-142',active,amount,ageHours:age,priority:active?Math.min(100,142+Math.floor(age/24)):0};}
export function operationsMetric143(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-143',active,amount,ageHours:age,priority:active?Math.min(100,143+Math.floor(age/24)):0};}
export function operationsMetric144(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-144',active,amount,ageHours:age,priority:active?Math.min(100,144+Math.floor(age/24)):0};}
export function operationsMetric145(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-145',active,amount,ageHours:age,priority:active?Math.min(100,145+Math.floor(age/24)):0};}
export function operationsMetric146(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-146',active,amount,ageHours:age,priority:active?Math.min(100,146+Math.floor(age/24)):0};}
export function operationsMetric147(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-147',active,amount,ageHours:age,priority:active?Math.min(100,147+Math.floor(age/24)):0};}
export function operationsMetric148(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-148',active,amount,ageHours:age,priority:active?Math.min(100,148+Math.floor(age/24)):0};}
export function operationsMetric149(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-149',active,amount,ageHours:age,priority:active?Math.min(100,149+Math.floor(age/24)):0};}
export function operationsMetric150(row:{status:string;amount?:number;ageHours?:number}){const amount=Math.max(0,Number(row.amount||0));const age=Math.max(0,Number(row.ageHours||0));const active=!['CLOSED','REFUNDED','REJECTED'].includes(row.status);return {metric:'RETURN-OPS-150',active,amount,ageHours:age,priority:active?Math.min(100,150+Math.floor(age/24)):0};}
export function dispositionGuard001(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-001',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard002(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-002',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard003(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-003',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard004(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-004',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard005(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-005',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard006(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-006',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard007(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-007',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard008(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-008',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard009(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-009',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard010(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-010',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard011(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-011',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard012(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-012',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard013(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-013',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard014(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-014',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard015(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-015',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard016(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-016',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard017(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-017',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard018(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-018',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard019(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-019',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard020(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-020',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard021(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-021',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard022(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-022',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard023(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-023',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard024(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-024',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard025(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-025',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard026(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-026',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard027(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-027',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard028(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-028',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard029(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-029',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard030(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-030',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard031(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-031',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard032(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-032',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard033(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-033',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard034(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-034',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard035(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-035',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard036(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-036',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard037(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-037',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard038(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-038',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard039(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-039',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard040(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-040',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard041(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-041',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard042(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-042',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard043(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-043',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard044(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-044',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard045(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-045',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard046(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-046',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard047(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-047',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard048(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-048',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard049(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-049',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard050(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-050',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard051(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-051',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard052(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-052',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard053(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-053',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard054(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-054',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard055(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-055',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard056(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-056',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard057(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-057',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard058(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-058',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard059(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-059',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
export function dispositionGuard060(condition:ReturnItemCondition,quantity:number,restockable:boolean){const q=normalizePositiveInteger(quantity)||0;const disposition=dispositionForCondition(condition,restockable);return {guard:'DISPOSITION-060',allowed:q>0 && disposition!=='DISPOSE',condition,quantity:q,disposition,review:dispositionNeedsReview(disposition)};}
