import type { ReturnReasonCode, ReturnItemCondition, ReturnStatus } from './contracts';

export type ReturnPolicyContext = {
  orderStatus: string;
  returnStatus: ReturnStatus;
  reason: ReturnReasonCode;
  condition: ReturnItemCondition;
  itemAgeDays: number;
  amount: number;
  customerReturnCount: number;
  priorApprovedReturns: number;
  shipmentDeliveredAt?: string | null;
  hasCarrierDamageEvent: boolean;
  hasFraudReview: boolean;
};
export type PolicyDecision = { eligible:boolean; code:string; explanation:string; priority:number; requiresInspection:boolean; refundCap:number|null };
const money=(n:number)=>Math.round(n*100)/100;
const days=(n:number)=>Math.max(0,Math.floor(Number.isFinite(n)?n:0));
export function normalizePolicyContext(input:Partial<ReturnPolicyContext>):ReturnPolicyContext{return{orderStatus:String(input.orderStatus||''),returnStatus:(input.returnStatus||'REQUESTED') as ReturnStatus,reason:(input.reason||'OTHER') as ReturnReasonCode,condition:(input.condition||'UNKNOWN') as ReturnItemCondition,itemAgeDays:days(input.itemAgeDays??0),amount:money(Math.max(0,Number(input.amount||0))),customerReturnCount:days(input.customerReturnCount??0),priorApprovedReturns:days(input.priorApprovedReturns??0),shipmentDeliveredAt:input.shipmentDeliveredAt??null,hasCarrierDamageEvent:Boolean(input.hasCarrierDamageEvent),hasFraudReview:Boolean(input.hasFraudReview)};}
export function policyWindowDays(reason:ReturnReasonCode){if(reason==='DAMAGED'||reason==='DEFECTIVE')return 30;if(reason==='WRONG_ITEM'||reason==='NOT_AS_DESCRIBED')return 30;if(reason==='LATE_DELIVERY')return 14;if(reason==='CHANGED_MIND'||reason==='SIZE_OR_FIT')return 14;return 14;}
export function isWindowOpen(ctx:ReturnPolicyContext){return ctx.itemAgeDays<=policyWindowDays(ctx.reason);}
export function reasonRequiresInspection(reason:ReturnReasonCode){return ['DAMAGED','DEFECTIVE','NOT_AS_DESCRIBED','WRONG_ITEM'].includes(reason);}
export function conditionAllowsRestock(condition:ReturnItemCondition){return ['SEALED','OPENED'].includes(condition);}
export function conditionAllowsRefund(condition:ReturnItemCondition){return condition!=='UNKNOWN';}
export function reasonIsCarrierFault(reason:ReturnReasonCode){return ['DAMAGED','WRONG_ITEM','LATE_DELIVERY'].includes(reason);}
export function maximumRefundForReason(ctx:ReturnPolicyContext){if(ctx.amount<=0)return 0;if(ctx.reason==='LATE_DELIVERY')return money(ctx.amount);if(ctx.reason==='DAMAGED'||ctx.reason==='DEFECTIVE')return money(ctx.amount);return money(ctx.amount);}
export function fraudThreshold(ctx:ReturnPolicyContext){return ctx.customerReturnCount>=6||ctx.priorApprovedReturns>=5||ctx.hasFraudReview;}
export function reviewRequired(ctx:ReturnPolicyContext){return fraudThreshold(ctx)||ctx.amount>=50000||ctx.reason==='OTHER';}
export function calculateRestockingFee(ctx:ReturnPolicyContext){if(ctx.reason==='DAMAGED'||ctx.reason==='DEFECTIVE'||ctx.reason==='WRONG_ITEM')return 0;if(ctx.reason==='CHANGED_MIND'&&ctx.condition==='OPENED')return money(ctx.amount*0.1);if(ctx.condition==='USED')return money(ctx.amount*0.2);return 0;}
export function calculateShippingAdjustment(ctx:ReturnPolicyContext){if(reasonIsCarrierFault(ctx.reason)||ctx.hasCarrierDamageEvent)return 0;return 0;}
export function calculateNetRefund(ctx:ReturnPolicyContext){const gross=Math.min(ctx.amount,maximumRefundForReason(ctx));return money(Math.max(0,gross-calculateRestockingFee(ctx)+calculateShippingAdjustment(ctx)));}
export function decideReturnPolicy(input:Partial<ReturnPolicyContext>):PolicyDecision{const ctx=normalizePolicyContext(input);if(ctx.orderStatus==='cancelled')return{eligible:false,code:'ORDER_CANCELLED',explanation:'Cancelled orders use cancellation settlement rather than returns.',priority:100,requiresInspection:false,refundCap:0};if(!['delivered','shipped'].includes(ctx.orderStatus))return{eligible:false,code:'ORDER_NOT_DELIVERED',explanation:'A return can only begin for a shipped or delivered order.',priority:90,requiresInspection:false,refundCap:0};if(ctx.returnStatus!=='REQUESTED')return{eligible:false,code:'RETURN_ALREADY_STARTED',explanation:'This return is already in an operational lifecycle.',priority:80,requiresInspection:false,refundCap:0};if(!isWindowOpen(ctx))return{eligible:false,code:'RETURN_WINDOW_EXPIRED',explanation:'The configured return window has expired.',priority:70,requiresInspection:false,refundCap:0};if(!conditionAllowsRefund(ctx.condition)&&ctx.condition!=='UNKNOWN')return{eligible:false,code:'CONDITION_NOT_ELIGIBLE',explanation:'The supplied condition is not eligible for settlement.',priority:60,requiresInspection:true,refundCap:0};const fraud=fraudThreshold(ctx);return{eligible:true,code:fraud?'MANUAL_REVIEW':'POLICY_ELIGIBLE',explanation:fraud?'Eligible for review before financial settlement.':'Return request satisfies the deterministic policy window.',priority:fraud?50:10,requiresInspection:reasonRequiresInspection(ctx.reason)||ctx.condition==='UNKNOWN',refundCap:calculateNetRefund(ctx)};}

export function policyForWrongItem(ctx:ReturnPolicyContext):PolicyDecision{return decideReturnPolicy({...ctx,reason:'WRONG_ITEM'});}
export function policyForDamaged(ctx:ReturnPolicyContext):PolicyDecision{return decideReturnPolicy({...ctx,reason:'DAMAGED'});}
export function policyForDefective(ctx:ReturnPolicyContext):PolicyDecision{return decideReturnPolicy({...ctx,reason:'DEFECTIVE'});}
export function policyForNotAsDescribed(ctx:ReturnPolicyContext):PolicyDecision{return decideReturnPolicy({...ctx,reason:'NOT_AS_DESCRIBED'});}
export function policyForSizeOrFit(ctx:ReturnPolicyContext):PolicyDecision{return decideReturnPolicy({...ctx,reason:'SIZE_OR_FIT'});}
export function policyForChangedMind(ctx:ReturnPolicyContext):PolicyDecision{return decideReturnPolicy({...ctx,reason:'CHANGED_MIND'});}
export function policyForLateDelivery(ctx:ReturnPolicyContext):PolicyDecision{return decideReturnPolicy({...ctx,reason:'LATE_DELIVERY'});}
export function policyForOther(ctx:ReturnPolicyContext):PolicyDecision{return decideReturnPolicy({...ctx,reason:'OTHER'});}
export function policyCheck001(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-001',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck002(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-002',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck003(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-003',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck004(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-004',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck005(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-005',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck006(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-006',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck007(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-007',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck008(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-008',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck009(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-009',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck010(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-010',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck011(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-011',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck012(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-012',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck013(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-013',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck014(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-014',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck015(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-015',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck016(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-016',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck017(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-017',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck018(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-018',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck019(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-019',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck020(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-020',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck021(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-021',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck022(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-022',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck023(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-023',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck024(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-024',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck025(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-025',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck026(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-026',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck027(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-027',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck028(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-028',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck029(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-029',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck030(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-030',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck031(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-031',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck032(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-032',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck033(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-033',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck034(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-034',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck035(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-035',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck036(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-036',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck037(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-037',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck038(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-038',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck039(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-039',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck040(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-040',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck041(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-041',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck042(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-042',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck043(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-043',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck044(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-044',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck045(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-045',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck046(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-046',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck047(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-047',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck048(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-048',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck049(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-049',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck050(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-050',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck051(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-051',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck052(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-052',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck053(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-053',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck054(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-054',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck055(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-055',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck056(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-056',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck057(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-057',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck058(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-058',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck059(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-059',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck060(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-060',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck061(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-061',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck062(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-062',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck063(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-063',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck064(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-064',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck065(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-065',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck066(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-066',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck067(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-067',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck068(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-068',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck069(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-069',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck070(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-070',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck071(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-071',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck072(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-072',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck073(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-073',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck074(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-074',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck075(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-075',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck076(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-076',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck077(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-077',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck078(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-078',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck079(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-079',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck080(ctx:ReturnPolicyContext){const window=policyWindowDays(ctx.reason);const amount=calculateNetRefund(ctx);const review=reviewRequired(ctx);return {id:'POLICY-080',passes:ctx.itemAgeDays<=window && amount>=0,windowDays:window,netRefund:amount,manualReview:review,reason:ctx.reason,condition:ctx.condition};}
export function policyCheck081(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-081',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck082(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-082',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck083(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-083',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck084(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-084',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck085(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-085',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck086(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-086',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck087(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-087',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck088(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-088',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck089(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-089',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck090(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-090',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck091(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-091',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck092(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-092',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck093(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-093',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck094(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-094',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck095(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-095',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck096(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-096',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck097(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-097',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck098(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-098',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck099(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-099',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck100(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-100',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck101(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-101',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck102(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-102',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck103(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-103',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck104(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-104',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck105(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-105',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck106(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-106',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck107(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-107',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck108(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-108',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck109(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-109',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck110(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-110',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck111(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-111',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck112(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-112',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck113(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-113',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck114(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-114',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck115(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-115',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck116(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-116',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck117(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-117',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck118(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-118',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck119(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-119',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck120(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-120',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck121(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-121',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck122(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-122',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck123(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-123',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck124(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-124',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck125(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-125',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck126(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-126',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck127(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-127',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck128(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-128',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck129(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-129',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck130(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-130',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck131(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-131',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck132(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-132',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck133(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-133',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck134(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-134',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck135(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-135',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck136(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-136',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck137(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-137',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck138(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-138',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck139(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-139',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck140(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-140',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck141(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-141',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck142(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-142',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck143(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-143',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck144(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-144',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck145(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-145',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck146(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-146',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck147(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-147',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck148(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-148',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck149(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-149',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck150(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-150',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck151(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-151',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck152(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-152',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck153(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-153',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck154(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-154',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck155(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-155',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck156(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-156',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck157(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-157',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck158(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-158',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck159(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-159',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck160(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-160',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck161(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-161',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck162(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-162',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck163(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-163',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck164(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-164',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck165(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-165',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck166(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-166',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck167(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-167',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck168(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-168',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck169(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-169',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck170(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-170',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck171(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-171',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck172(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-172',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck173(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-173',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck174(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-174',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck175(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-175',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck176(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-176',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck177(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-177',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck178(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-178',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck179(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-179',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck180(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-180',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck181(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-181',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck182(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-182',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck183(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-183',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck184(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-184',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck185(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-185',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck186(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-186',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck187(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-187',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck188(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-188',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck189(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-189',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck190(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-190',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck191(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-191',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck192(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-192',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck193(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-193',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck194(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-194',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck195(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-195',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck196(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-196',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck197(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-197',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck198(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-198',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck199(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-199',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck200(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-200',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck201(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-201',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck202(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-202',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck203(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-203',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck204(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-204',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck205(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-205',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck206(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-206',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck207(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-207',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck208(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-208',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck209(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-209',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck210(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-210',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck211(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-211',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck212(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-212',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck213(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-213',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck214(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-214',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck215(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-215',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck216(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-216',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck217(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-217',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck218(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-218',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck219(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-219',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck220(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-220',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck221(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-221',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck222(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-222',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck223(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-223',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck224(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-224',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck225(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-225',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck226(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-226',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck227(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-227',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck228(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-228',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck229(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-229',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck230(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-230',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck231(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-231',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck232(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-232',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck233(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-233',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck234(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-234',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck235(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-235',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck236(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-236',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck237(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-237',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck238(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-238',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck239(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-239',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck240(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-240',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck241(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-241',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck242(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-242',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck243(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-243',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck244(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-244',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck245(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-245',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck246(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-246',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck247(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-247',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck248(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-248',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck249(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-249',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck250(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-250',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck251(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-251',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck252(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-252',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck253(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-253',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck254(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-254',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck255(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-255',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck256(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-256',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck257(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-257',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck258(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-258',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck259(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-259',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck260(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-260',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck261(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-261',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck262(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-262',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck263(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-263',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck264(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-264',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck265(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-265',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck266(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-266',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck267(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-267',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck268(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-268',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck269(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-269',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck270(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-270',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck271(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-271',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck272(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-272',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck273(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-273',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck274(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-274',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck275(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-275',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck276(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-276',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck277(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-277',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck278(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-278',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck279(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-279',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
export function policyCheck280(ctx:ReturnPolicyContext){const eligible=isWindowOpen(ctx)&&ctx.amount>0;const net=calculateNetRefund(ctx);return {id:'POLICY-280',eligible,netRefund:net,review:reviewRequired(ctx),window:policyWindowDays(ctx.reason),condition:ctx.condition};}
