export type FeatureSurface = { route: string; title: string; eyebrow: string; description: string; endpoint: string };

export const FEATURE_SURFACES: Record<string, FeatureSurface> = {
  '/ai-boardroom': { route:'/ai-boardroom', title:'AI Boardroom', eyebrow:'TRUST · AI DECISION SURFACE', description:'Executive decision support backed by the current intelligence APIs. No fabricated metrics are shown.', endpoint:'/api/financial-intelligence' },
  '/ai-quality': { route:'/ai-quality', title:'AI Quality', eyebrow:'TRUST · AI QUALITY', description:'Quality signals and evaluation state from the AI quality service.', endpoint:'/api/ai-quality' },
  '/autopilot': { route:'/autopilot', title:'Commerce Autopilot', eyebrow:'TRUST · AUTOPILOT', description:'Governed automation state from the existing autopilot decision boundary.', endpoint:'/api/autopilot' },
  '/campaign-studio': { route:'/campaign-studio', title:'Campaign Studio', eyebrow:'TRUST · CAMPAIGNS', description:'Campaign state from the commerce campaign service.', endpoint:'/api/campaigns' },
  '/consent-center': { route:'/consent-center', title:'Consent Center', eyebrow:'TRUST · CONSENT', description:'Consent state from the consent service. Missing data stays missing.', endpoint:'/api/consent' },
  '/customer-journey': { route:'/customer-journey', title:'Customer Journey', eyebrow:'TRUST · CUSTOMER', description:'Customer journey signals from the customer journey service.', endpoint:'/api/customer-journey' },
  '/data-clean-room': { route:'/data-clean-room', title:'Data Clean Room', eyebrow:'TRUST · DATA', description:'Data-core state and governed event access.', endpoint:'/api/data-core' },
  '/decision-center': { route:'/decision-center', title:'Decision Center', eyebrow:'TRUST · DECISIONS', description:'Current decision-fabric state and decision evidence.', endpoint:'/api/decision-fabric' },
  '/decision-ledger': { route:'/decision-ledger', title:'Decision Ledger', eyebrow:'TRUST · LEDGER', description:'Durable decision ledger responses and provenance.', endpoint:'/api/decision-ledger' },
  '/digital-twin': { route:'/digital-twin', title:'Digital Twin', eyebrow:'TRUST · SIMULATION', description:'Scenario and simulation state. Simulation is never presented as live execution.', endpoint:'/api/scenarios' },
  '/experiments': { route:'/experiments', title:'Experiments', eyebrow:'TRUST · LEARNING', description:'Experiment state and evidence from the experimentation service.', endpoint:'/api/experiments' },
  '/financial-intelligence': { route:'/financial-intelligence', title:'Financial Intelligence', eyebrow:'TRUST · FINANCE', description:'Financial intelligence returned by the protected finance surface.', endpoint:'/api/financial-intelligence' },
  '/governance': { route:'/governance', title:'Governance', eyebrow:'TRUST · GOVERNANCE', description:'Governance state and policy evidence from the governance service.', endpoint:'/api/governance' },
  '/growth-war-room': { route:'/growth-war-room', title:'Growth War Room', eyebrow:'TRUST · GROWTH', description:'Growth opportunities and network signals from real commerce data.', endpoint:'/api/growth-network' },
  '/incident-copilot': { route:'/incident-copilot', title:'Incident Copilot', eyebrow:'TRUST · INCIDENTS', description:'Current incident signals and operational evidence.', endpoint:'/api/incidents' },
  '/intelligence-network': { route:'/intelligence-network', title:'Intelligence Network', eyebrow:'TRUST · INTELLIGENCE', description:'Cross-domain intelligence network signals.', endpoint:'/api/intelligence-network' },
  '/merchant-growth': { route:'/merchant-growth', title:'Merchant Growth', eyebrow:'TRUST · SELLER', description:'Seller growth opportunities from the seller intelligence service.', endpoint:'/api/seller-super-os' },
  '/omnichannel': { route:'/omnichannel', title:'Omnichannel Commerce', eyebrow:'TRUST · OMNICHANNEL', description:'Omnichannel commerce state from the existing service.', endpoint:'/api/omnichannel' },
  '/opportunity-radar': { route:'/opportunity-radar', title:'Opportunity Radar', eyebrow:'TRUST · OPPORTUNITIES', description:'Current opportunity signals from the opportunity service.', endpoint:'/api/opportunities' },
  '/ops': { route:'/ops', title:'Operations', eyebrow:'TRUST · OPERATIONS', description:'Operational platform state and health evidence.', endpoint:'/api/platform/overview' },
  '/reliability': { route:'/reliability', title:'Reliability', eyebrow:'TRUST · RELIABILITY', description:'Global reliability and recovery evidence.', endpoint:'/api/global-reliability' },
  '/retention': { route:'/retention', title:'Retention', eyebrow:'TRUST · CUSTOMER GROWTH', description:'Customer journey and reorder signals used for retention decisions.', endpoint:'/api/customer-journey' },
  '/revenue-copilot': { route:'/revenue-copilot', title:'Revenue Copilot', eyebrow:'TRUST · REVENUE', description:'Revenue decision support from the revenue intelligence layer.', endpoint:'/api/revenue-intelligence' },
  '/rights': { route:'/rights', title:'Rights Center', eyebrow:'TRUST · RIGHTS', description:'Customer rights and privacy state.', endpoint:'/api/rights' },
  '/scenario-lab': { route:'/scenario-lab', title:'Scenario Lab', eyebrow:'TRUST · SIMULATION', description:'Scenario modeling with explicit simulation boundaries.', endpoint:'/api/scenarios' },
  '/service-agents': { route:'/service-agents', title:'Service Agents', eyebrow:'TRUST · SERVICE', description:'Service-agent state from the existing service agent API.', endpoint:'/api/service-agents' },
  '/social-commerce': { route:'/social-commerce', title:'Social Commerce', eyebrow:'TRUST · COMMERCE', description:'Commerce growth and social opportunity signals.', endpoint:'/api/commerce-growth' },
  '/unit-economics': { route:'/unit-economics', title:'Unit Economics', eyebrow:'TRUST · ECONOMICS', description:'Contribution economics from the revenue intelligence engine.', endpoint:'/api/revenue-intelligence' },
  '/v63-command-center': { route:'/v63-command-center', title:'Command Center', eyebrow:'TRUST · PLATFORM', description:'Unified platform overview from the current operational API.', endpoint:'/api/platform/overview' },
  '/visitor-monetization': { route:'/visitor-monetization', title:'Visitor Monetization', eyebrow:'TRUST · ACQUISITION', description:'Visitor event state used for monetization decisions.', endpoint:'/api/visitor-events' },
  '/amazon-parity': { route:'/amazon-parity', title:'Commerce Parity', eyebrow:'TRUST · COMMERCE PROGRAMS', description:'Provider-neutral commerce programs and monetization surfaces.', endpoint:'/api/amazon-revenue-os' },
  '/production-readiness': { route:'/production-readiness', title:'Production Readiness', eyebrow:'TRUST · READINESS', description:'Current readiness checks and explicit blockers.', endpoint:'/api/production-readiness' },
  '/trust-commerce-network': { route:'/trust-commerce-network', title:'TRUST One Commerce Network', eyebrow:'TRUST · NETWORK', description:'Network membership and savings signals.', endpoint:'/api/trust-commerce-network' },
  '/platform-os': { route:'/platform-os', title:'Platform OS', eyebrow:'TRUST · PLATFORM', description:'Platform workflows, jobs and events state.', endpoint:'/api/platform-os' },
  '/growth-network': { route:'/growth-network', title:'Growth Network', eyebrow:'TRUST · NETWORK', description:'Observed reorder, cross-sell and growth signals.', endpoint:'/api/growth-network' },
  '/problem-solver': { route:'/problem-solver', title:'Problem Solver', eyebrow:'TRUST · CUSTOMER PROBLEMS', description:'Problem-centered commerce assistance.', endpoint:'/api/problem-solver' },
  '/commerce-growth': { route:'/commerce-growth', title:'Commerce Growth OS', eyebrow:'TRUST · GROWTH', description:'Growth opportunities and monetization signals.', endpoint:'/api/commerce-growth' },
  '/commerce-brain': { route:'/commerce-brain', title:'Real-Time Commerce Brain', eyebrow:'TRUST · BRAIN', description:'Event-driven commerce signals. Empty input is never claimed to be live.', endpoint:'/api/commerce-brain' },
  '/personal-shopper': { route:'/personal-shopper', title:'Personal Shopper', eyebrow:'TRUST · SHOPPING', description:'Shopping assistance from the existing personal shopper service.', endpoint:'/api/personal-shopper' },
  '/agents': { route:'/agents', title:'Agents', eyebrow:'TRUST · AGENTS', description:'Registered agent state from the agent registry.', endpoint:'/api/agents' },
  '/discovery': { route:'/discovery', title:'Discovery', eyebrow:'TRUST · DISCOVERY', description:'Catalog-backed discovery and recommendations.', endpoint:'/api/discovery' },
  '/data-core': { route:'/data-core', title:'Data Core', eyebrow:'TRUST · DATA', description:'Core data-plane state and health.', endpoint:'/api/data-core' },
  '/decision-fabric': { route:'/decision-fabric', title:'Decision Fabric', eyebrow:'TRUST · DECISION FABRIC', description:'Evidence-backed decisions and policy boundaries.', endpoint:'/api/decision-fabric' },
  '/global-commerce-network-admin': { route:'/global-commerce-network-admin', title:'Global Commerce Network', eyebrow:'TRUST · NETWORK ADMIN', description:'Network administration state.', endpoint:'/api/global-commerce-network' },
  '/revenue-decision-loop': { route:'/revenue-decision-loop', title:'Revenue Decision Loop', eyebrow:'TRUST · REVENUE', description:'Economics plus experiment evidence.', endpoint:'/api/revenue-decision-loop' },
  '/protection': { route:'/protection', title:'Purchase Protection', eyebrow:'TRUST · PROTECTION', description:'Protection signals and customer safeguards.', endpoint:'/api/protection' },
  '/commerce-ai-copilot': { route:'/commerce-ai-copilot', title:'Commerce AI Copilot', eyebrow:'TRUST · AI', description:'Deterministic commerce decision support.', endpoint:'/api/commerce-ai-copilot' },
  '/production-security-scale': { route:'/production-security-scale', title:'Production Security & Scale', eyebrow:'TRUST · SECURITY', description:'Route, secret and scale posture.', endpoint:'/api/production-security-scale' },
  '/payments': { route:'/payments', title:'Payments', eyebrow:'TRUST · PAYMENTS', description:'Payment intent and status state from the payments surface.', endpoint:'/api/payments' },
  '/visual-search': { route:'/visual-search', title:'Visual Search', eyebrow:'TRUST · DISCOVERY', description:'Visual discovery provider state.', endpoint:'/api/visual-search' },
  '/marketplace-intelligence': { route:'/marketplace-intelligence', title:'Marketplace Intelligence', eyebrow:'TRUST · MARKETPLACE', description:'Explainable marketplace ranking and intelligence.', endpoint:'/api/marketplace-intelligence' },
  '/prevention-admin': { route:'/prevention-admin', title:'Prevention', eyebrow:'TRUST · PREVENTION', description:'Prevention signals. Admin authorization remains enforced by the API.', endpoint:'/api/prevention' },
  '/super-app': { route:'/super-app', title:'TRUST Super App', eyebrow:'TRUST · SUPER APP', description:'Unified commerce surfaces and next actions.', endpoint:'/api/super-app' },
  '/revenue-intelligence': { route:'/revenue-intelligence', title:'Revenue Intelligence', eyebrow:'TRUST · REVENUE', description:'Contribution economics, concentration and evidence-aware recommendations.', endpoint:'/api/revenue-intelligence' },
  '/autonomous-commerce-control-plane': { route:'/autonomous-commerce-control-plane', title:'Autonomous Commerce Control Plane', eyebrow:'TRUST · AUTONOMY', description:'Policy-gated commerce control decisions.', endpoint:'/api/autonomous-commerce-control-plane' },
  '/revenue-experimentation': { route:'/revenue-experimentation', title:'Revenue Experimentation', eyebrow:'TRUST · LEARNING', description:'Experiment evidence and decision signals.', endpoint:'/api/revenue-experimentation' },
  '/observability': { route:'/observability', title:'Observability', eyebrow:'TRUST · OBSERVABILITY', description:'Telemetry, SLO, region health and incident signals.', endpoint:'/api/observability' },
  '/production-security-hardening': { route:'/production-security-hardening', title:'Production Security Hardening', eyebrow:'TRUST · SECURITY', description:'Targeted production security and query-scale hardening evidence.', endpoint:'/api/production-security-hardening' },
  '/orders': { route:'/orders', title:'Orders', eyebrow:'TRUST · ORDERS', description:'Current order data from the durable order API.', endpoint:'/api/orders' },
  '/autonomous-commerce-runtime': { route:'/autonomous-commerce-runtime', title:'Autonomous Commerce Runtime', eyebrow:'TRUST · AUTONOMY', description:'Runtime dispatch status and adapter boundaries.', endpoint:'/api/autonomous-commerce-runtime' },
  '/notifications': { route:'/notifications', title:'Notifications', eyebrow:'TRUST · POST-PURCHASE', description:'Notification queue and delivery state.', endpoint:'/api/notifications' },
  '/agent-control': { route:'/agent-control', title:'Agent Control', eyebrow:'TRUST · AGENTS', description:'Agent execution and policy state.', endpoint:'/api/agent-control' },
  '/autonomous-commerce-orchestrator': { route:'/autonomous-commerce-orchestrator', title:'Autonomous Commerce Orchestrator', eyebrow:'TRUST · AUTONOMY', description:'Event-to-decision orchestration state.', endpoint:'/api/autonomous-commerce-orchestrator' },
  '/global-reliability': { route:'/global-reliability', title:'Global Reliability', eyebrow:'TRUST · RELIABILITY', description:'Region health and disaster-recovery evidence.', endpoint:'/api/global-reliability' },
  '/global-commerce-graph': { route:'/global-commerce-graph', title:'Global Commerce Graph', eyebrow:'TRUST · GRAPH', description:'Commerce graph projection and opportunities.', endpoint:'/api/global-commerce-graph' },
  '/amazon-revenue-os': { route:'/amazon-revenue-os', title:'Revenue Engine', eyebrow:'TRUST · REVENUE', description:'Evidence-gated monetization portfolio and durable revenue ledger state.', endpoint:'/api/amazon-revenue-os' },
  '/customer-center': { route:'/customer-center', title:'Customer Center', eyebrow:'TRUST · CUSTOMER OS', description:'Authenticated customer profile state from the customer API.', endpoint:'/api/customer/profile' },
  '/life-os': { route:'/life-os', title:'Life OS', eyebrow:'TRUST · PERSONAL OS', description:'Personal commerce and life-automation state from the existing service.', endpoint:'/api/life-os' },
  '/merchant-supergraph': { route:'/merchant-supergraph', title:'Merchant Supergraph', eyebrow:'TRUST · SELLER GRAPH', description:'Merchant graph and operational state.', endpoint:'/api/merchant-supergraph' },
  '/revenue-autopilot': { route:'/revenue-autopilot', title:'Revenue Autopilot', eyebrow:'TRUST · REVENUE', description:'Evidence-gated plan, quote and post state.', endpoint:'/api/revenue-autopilot' },

};
