import {NextRequest,NextResponse} from 'next/server';
import {getCurrentUser} from '../../../../modules/platform/auth/current-user';
import {query,withPgTransaction} from '../../../../modules/platform/db/postgres';
import {getPostSaleCaseTx,recordPostSaleActionTx,findPostSaleActionTx} from '../../../../modules/platform/post-sale-orchestration';
import {approveReturn,rejectReturn,markReturnReceived,startInspection,inspectReturn,requestReturnRefund,closeReturnExplicit} from '../../../../modules/commerce/returns/service';
export const dynamic='force-dynamic';
const ops=['admin','operations','support'];
const db={query,transaction:withPgTransaction};
export async function GET(req:NextRequest,{params}:{params:{returnId:string}}){const u=await getCurrentUser(req);if(!u)return NextResponse.json({ok:false,error:'AUTH_REQUIRED'},{status:401});try{const data=await getPostSaleCaseTx({query,transaction:withPgTransaction},params.returnId);if(!data)return NextResponse.json({ok:false,error:'POST_SALE_CASE_NOT_FOUND'},{status:404});if(data.case.customer_id!==u.id&&!ops.includes(u.role))return NextResponse.json({ok:false,error:'ACCESS_DENIED'},{status:403});return NextResponse.json({ok:true,surfaceStatus:'LIVE',...data},{headers:{'Cache-Control':'no-store'}})}catch(e){return NextResponse.json({ok:false,error:e instanceof Error?e.message:'POST_SALE_GET_FAILED'},{status:500})}}
export async function POST(req:NextRequest,{params}:{params:{returnId:string}}){const u=await getCurrentUser(req);if(!u)return NextResponse.json({ok:false,error:'AUTH_REQUIRED'},{status:401});if(!ops.includes(u.role))return NextResponse.json({ok:false,error:'PRIVILEGED_ACCESS_REQUIRED'},{status:403});try{const b=await req.json();const action=String(b.action||'');const returnId=params.returnId;const key=req.headers.get('idempotency-key')?.trim();if(!key)return NextResponse.json({ok:false,error:'IDEMPOTENCY_KEY_REQUIRED'},{status:400});const prior=await findPostSaleActionTx({query,transaction:withPgTransaction},{returnId,action,idempotencyKey:key});if(prior)return NextResponse.json({ok:true,surfaceStatus:'LIVE',result:prior.result,action:{actionId:prior.actionId,replay:true,result:prior.result}},{headers:{'Cache-Control':'no-store'}});let result:any;const base={returnId,actorId:u.id,note:b.note};if(action==='APPROVE')result=await approveReturn(db,base);else if(action==='REJECT')result=await rejectReturn(db,base);else if(action==='RECEIVE')result=await markReturnReceived(db,base);else if(action==='START_INSPECTION')result=await startInspection(db,base);else if(action==='INSPECT')result=await inspectReturn(db,{returnId,actorId:u.id,decision:b.decision,condition:b.condition,recoverable:b.recoverable,restockable:b.restockable,note:b.note});else if(action==='REQUEST_REFUND'){result=await requestReturnRefund(db,{returnId,actorId:u.id,idempotencyKey:key,shippingRefundEligible:b.shippingRefundEligible,restockingFeeRate:b.restockingFeeRate});}else if(action==='CLOSE')result=await closeReturnExplicit(db,base);else return NextResponse.json({ok:false,error:'INVALID_POST_SALE_ACTION'},{status:400});
 const actionLog=await withPgTransaction(tx=>recordPostSaleActionTx(tx,{returnId,action,actorId:u.id,idempotencyKey:key,result})); return NextResponse.json({ok:true,surfaceStatus:'LIVE',result,action:actionLog},{headers:{'Cache-Control':'no-store'}})
}catch(e){const m=e instanceof Error?e.message:'POST_SALE_ACTION_FAILED';return NextResponse.json({ok:false,error:m},{status:m.includes('NOT_FOUND')?404:m.includes('ACCESS_DENIED')?403:m.startsWith('INVALID_')||m.endsWith('_REQUIRED')?400:409})}}
