'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';

type Quote={quoteId:string;subtotal:number;shipping:number;discount:number;total:number;currency:string;expiresAt:string;items:any[]};
type Payment={status:string;paymentIntentId:string;amount:number;currency:string;provider:string;clientSecret?:string};

export default function CheckoutPage(){
 const [quote,setQuote]=useState<Quote|null>(null); const [region,setRegion]=useState('GLOBAL'); const [code,setCode]=useState('');
 const [paymentMethod,setPaymentMethod]=useState<'cod'|'card'>('cod'); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const [order,setOrder]=useState<any>(null); const [payment,setPayment]=useState<Payment|null>(null);
 async function refresh(){setBusy(true);setError('');try{const r=await fetch('/api/checkout/cart',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({destinationRegion:region,discountCode:code||undefined})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error??'تعذر إنشاء عرض الدفع');setQuote(d.checkout)}catch(e){setError(e instanceof Error?e.message:'تعذر إنشاء عرض الدفع')}finally{setBusy(false)}}
 useEffect(()=>{refresh()},[]);
 async function place(){if(!quote)return;setBusy(true);setError('');try{const key=`checkout:${quote.quoteId}`;const r=await fetch('/api/checkout/cart/commit',{method:'POST',headers:{'content-type':'application/json','idempotency-key':key},body:JSON.stringify({destinationRegion:region,discountCode:code||undefined,paymentMethod})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error??'تعذر إنشاء الطلب');setOrder(d.order);setPayment(d.payment??null)}catch(e){setError(e instanceof Error?e.message:'تعذر إنشاء الطلب')}finally{setBusy(false)}}
 useEffect(()=>{if(!order?.id||paymentMethod!=='card'||payment?.status==='captured'||payment?.status==='failed'||payment?.status==='cancelled')return;let stopped=false;const poll=async()=>{try{const r=await fetch(`/api/payments/status?orderId=${encodeURIComponent(order.id)}`,{cache:'no-store'});const d=await r.json().catch(()=>({}));const p=d?.payments?.[0];if(!stopped&&p){setPayment(p);if(['captured','failed','cancelled'].includes(String(p.status))) return}}catch{}if(!stopped)setTimeout(poll,3000)};poll();return()=>{stopped=true}},[order?.id,paymentMethod,payment?.status]);
 if(order)return <main style={{maxWidth:760,margin:'0 auto',padding:40}}><h1>{paymentMethod==='card'&&payment?.status!=='captured'?'تم إنشاء الطلب، والدفع قيد المعالجة':'تم إنشاء الطلب ✓'}</h1><p>رقم الطلب: {order.id}</p><p>حالة الطلب: {order.status}</p>{paymentMethod==='card'&&payment&&<section style={{marginTop:20,padding:18,border:'1px solid #ddd',borderRadius:16}}><h2>حالة الدفع</h2><p>{payment.status}</p>{payment.status==='pending'&&<small>تم إنشاء عملية الدفع وإرسالها لمسار مزود الدفع. الصفحة تتابع الحالة تلقائيًا.</small>}{payment.status==='requires_action'&&<small>مزود الدفع يطلب إجراءً إضافيًا. تفاصيل واجهة الإجراء تعتمد على مزود الدفع المتصل.</small>}{payment.status==='captured'&&<small>تم تأكيد الدفع من خلال حدث مزود الدفع.</small>}</section>}<p style={{marginTop:20}}><Link href={`/orders/${order.id}`}>متابعة الطلب</Link></p></main>;
 return <main style={{maxWidth:900,margin:'0 auto',padding:'36px 18px'}}><p><Link href="/cart">← العودة للسلة</Link></p><h1>مراجعة الطلب والدفع</h1><p>السعر وخطة التنفيذ والطلب تُحسم على الخادم، وليس من بيانات المتصفح.</p><label>منطقة التوصيل <select value={region} onChange={e=>setRegion(e.target.value)} disabled={busy}><option>GLOBAL</option><option>EGYPT</option></select></label><div style={{marginTop:16}}><input value={code} onChange={e=>setCode(e.target.value)} placeholder="كود الخصم (اختياري)"/><button onClick={refresh} disabled={busy}>تحديث السعر</button></div>{quote&&<section style={{marginTop:20,padding:20,border:'1px solid #ddd',borderRadius:18}}><p>الإجمالي الفرعي: {quote.subtotal.toFixed(2)} {quote.currency}</p><p>الشحن: {quote.shipping.toFixed(2)} {quote.currency}</p><p>الخصم: {quote.discount.toFixed(2)} {quote.currency}</p><h2>{quote.total.toFixed(2)} {quote.currency}</h2><small>صلاحية العرض حتى {new Date(quote.expiresAt).toLocaleString()}</small><div style={{marginTop:20}}><h3>طريقة الدفع</h3><label style={{display:'block',margin:'10px 0'}}><input type="radio" checked={paymentMethod==='cod'} onChange={()=>setPaymentMethod('cod')} disabled={busy}/> الدفع عند الاستلام</label><label style={{display:'block',margin:'10px 0'}}><input type="radio" checked={paymentMethod==='card'} onChange={()=>setPaymentMethod('card')} disabled={busy}/> بطاقة / مزود دفع متصل</label><button onClick={place} disabled={busy} style={{display:'block',marginTop:18,padding:14,border:0,borderRadius:12}}>{paymentMethod==='card'?'إنشاء الطلب وبدء الدفع':'تأكيد الطلب والدفع عند الاستلام'}</button></div></section>}{!quote&&<p>{busy?'جارٍ حساب السعر…':'لم يتم إنشاء عرض دفع بعد.'}</p>}{error&&<p style={{marginTop:18}}>{error}</p>}</main>;
}
