'use client';
import { useEffect, useMemo, useState } from 'react';
import AddToCartButton from '@/components/add-to-cart-button';

function Countdown({endsAt}:{endsAt:string}){const [left,setLeft]=useState(Math.max(0,Date.parse(endsAt)-Date.now()));useEffect(()=>{const id=setInterval(()=>setLeft(Math.max(0,Date.parse(endsAt)-Date.now())),1000);return()=>clearInterval(id)},[endsAt]);const sec=Math.floor(left/1000),d=Math.floor(sec/86400),h=Math.floor(sec%86400/3600),m=Math.floor(sec%3600/60),s=sec%60;return <strong>{d?`${d}d `:''}{String(h).padStart(2,'0')}:{String(m).padStart(2,'0')}:{String(s).padStart(2,'0')}</strong>}

type Deal={id:string;offerId:string;productId:string;name:string;image?:string|null;badge:string;dealType:'PERCENT'|'FIXED';discountBps?:number|null;discountAmount?:number|null;price:number;shippingFee:number;stock:number;remainingDealQuantity:number|null;originalPrice:number;endsAt:string};
export default function DealsPage(){
 const [deals,setDeals]=useState<Deal[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[q,setQ]=useState(''),[sort,setSort]=useState('ending'),[category,setCategory]=useState('ALL');
 useEffect(()=>{let live=true;fetch('/api/marketplace/promotions',{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error('DEALS_LOAD_FAILED');return r.json()}).then(x=>{if(live)setDeals(Array.isArray(x.deals)?x.deals:[])}).catch(e=>live&&setError(e.message)).finally(()=>live&&setLoading(false));return()=>{live=false}},[]);
 const categories=useMemo(()=>['ALL',...Array.from(new Set(deals.map(d=>d.badge)))],[deals]);
 const filtered=useMemo(()=>deals.filter(d=>(category==='ALL'||d.badge===category)&&d.name.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>sort==='price'?a.price-b.price:sort==='discount'?((b.discountBps??0)-(a.discountBps??0)):new Date(a.endsAt).getTime()-new Date(b.endsAt).getTime()),[deals,q,sort,category]);
 return <main style={{padding:24,maxWidth:1200,margin:'0 auto'}}><header style={{display:'flex',gap:12,alignItems:'center',justifyContent:'space-between',flexWrap:'wrap'}}><div><h1>TRUST Deals</h1><p>Server-authoritative promotions with transparent pricing.</p></div><strong>{filtered.length} deal{filtered.length===1?'':'s'}</strong></header>
 <section style={{display:'flex',gap:10,flexWrap:'wrap',margin:'18px 0'}}><input aria-label="Search deals" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search deals…" style={{padding:12,borderRadius:10,border:'1px solid #ccc',minWidth:240}}/><select value={sort} onChange={e=>setSort(e.target.value)}><option value="ending">Ending soon</option><option value="price">Lowest price</option><option value="discount">Highest % discount</option></select><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></section>
 {loading?<p>Loading deals…</p>:error?<section role="alert"><p>Couldn’t load deals.</p><button onClick={()=>location.reload()}>Retry</button></section>:filtered.length===0?<p>No matching deals right now.</p>:<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:18}}>{filtered.map(d=><article key={d.id} style={{border:'1px solid #ddd',borderRadius:16,padding:16}}>{d.image&&<img src={d.image} alt="" style={{width:'100%',height:180,objectFit:'cover',borderRadius:12}}/>}<small>{d.badge}</small><h2 style={{fontSize:19}}>{d.name}</h2><p><del>{d.originalPrice.toFixed(2)} EGP</del> <strong>{d.price.toFixed(2)} EGP</strong> {d.discountBps?`· ${(d.discountBps/100).toFixed(0)}% off`:d.discountAmount?`· ${d.discountAmount.toFixed(2)} EGP off`:''}</p><p>Shipping: {d.shippingFee.toFixed(2)} EGP</p><p>Time left: <Countdown endsAt={d.endsAt}/></p>{d.stock<=5&&<p><strong>Only {d.stock} left</strong></p>}{d.remainingDealQuantity!==null&&d.remainingDealQuantity<=10&&<p>Deal quantity left: {d.remainingDealQuantity}</p>}<AddToCartButton productId={d.productId} offerId={d.offerId}/></article>)}</div>}</main>
}
