import type {Impact,ReplayEvent,Scenario,ScenarioResult,TwinEdge,TwinSnapshot} from './contracts.ts';
const finite=(n:number,k:string)=>{if(!Number.isFinite(n))throw new Error(`${k} must be finite`)};
const nonNegative=(n:number,k:string)=>{finite(n,k);if(n<0)throw new Error(`${k} must be non-negative`)};
function validateSnapshot(s:TwinSnapshot){if(!s.tenantId)throw new Error('tenant required');const ids=new Set<string>();for(const n of s.nodes){if(n.tenantId!==s.tenantId)throw new Error('tenant mismatch');if(ids.has(n.id))throw new Error('duplicate node');ids.add(n.id);for(const v of Object.values(n.state))finite(v,'node state')}for(const e of s.edges){if(!ids.has(e.from)||!ids.has(e.to))throw new Error('edge references unknown node');nonNegative(e.weight,'edge weight')} }
export function buildSnapshot(tenantId:string,nodes:TwinSnapshot['nodes'],edges:TwinEdge[],timestamp=Date.now()):TwinSnapshot{const s={snapshotId:`twin-${tenantId}-${timestamp}`,tenantId,timestamp,nodes:nodes.map(n=>({...n,state:{...n.state},tags:n.tags?[...n.tags]:undefined})),edges:edges.map(e=>({...e}))};validateSnapshot(s);return s;}
export function simulateScenario(snapshot:TwinSnapshot,scenario:Scenario):ScenarioResult{validateSnapshot(snapshot);if(!scenario.name)throw new Error('scenario name required');if(!Number.isInteger(scenario.horizonHours)||scenario.horizonHours<1||scenario.horizonHours>8760)throw new Error('horizonHours must be 1..8760');const nodes=new Map(snapshot.nodes.map(n=>[n.id,n]));const impacts:Impact[]=[];for(const c of scenario.changes){const n=nodes.get(c.nodeId);if(!n)throw new Error(`unknown node ${c.nodeId}`);finite(c.delta,'delta');const baseline=n.state[c.metric]??0;const projected=baseline+c.delta;const confidence=Math.max(0,Math.min(10000,10000-Math.round(Math.abs(c.delta)*100)));impacts.push({nodeId:c.nodeId,metric:c.metric,baseline,projected,delta:c.delta,confidenceBps:confidence});}const netScore=impacts.reduce((s,i)=>s+i.delta*(i.confidenceBps/10000),0);return {scenarioId:`scenario-${snapshot.tenantId}-${scenario.name}-${impacts.map(i=>i.nodeId).join('-')}`,tenantId:snapshot.tenantId,status:'SIMULATED',horizonHours:scenario.horizonHours,impacts,netScore,assumptions:['scenario changes are counterfactual','graph state is not mutated','confidence decreases with larger absolute shocks'],productionSideEffects:false};}
export function propagateImpact(snapshot:TwinSnapshot,seedNodeId:string,metric:string,delta:number,maxDepth=3):Impact[]{validateSnapshot(snapshot);if(!snapshot.nodes.some(n=>n.id===seedNodeId))throw new Error('unknown seed node');finite(delta,'delta');if(!Number.isInteger(maxDepth)||maxDepth<0||maxDepth>10)throw new Error('maxDepth must be 0..10');const adj=new Map<string,TwinEdge[]>();for(const e of snapshot.edges){const list=adj.get(e.from)??[];list.push(e);adj.set(e.from,list)}const out:Impact[]=[];const queue:[string,number,number][]=[[seedNodeId,delta,0]];const seen=new Set<string>();while(queue.length){const [id,d,depth]=queue.shift()!;const key=`${id}:${metric}`;if(seen.has(key))continue;seen.add(key);const n=snapshot.nodes.find(x=>x.id===id)!;const baseline=n.state[metric]??0;const projected=baseline+d;out.push({nodeId:id,metric,baseline,projected,delta:d,confidenceBps:Math.max(0,10000-depth*1800)});if(depth>=maxDepth)continue;for(const e of adj.get(id)??[]){queue.push([e.to,d*e.weight,depth+1]);}}return out;}
export function replayAt(events:ReplayEvent[],tenantId:string,at:number):Map<string,Record<string,number>>{if(!Number.isFinite(at))throw new Error('at must be finite');const state=new Map<string,Record<string,number>>();for(const e of [...events].filter(e=>e.tenantId===tenantId&&e.timestamp<=at).sort((a,b)=>a.timestamp-b.timestamp||a.eventId.localeCompare(b.eventId))){const row=state.get(e.nodeId)??{};row[e.metric]=e.value;state.set(e.nodeId,row)}return state;}
export function diffSnapshots(before:TwinSnapshot,after:TwinSnapshot):Impact[]{if(before.tenantId!==after.tenantId)throw new Error('tenant mismatch');const ids=new Set([...before.nodes.map(n=>n.id),...after.nodes.map(n=>n.id)]);const out:Impact[]=[];for(const id of ids){const a=before.nodes.find(n=>n.id===id),b=after.nodes.find(n=>n.id===id);const metrics=new Set([...Object.keys(a?.state??{}),...Object.keys(b?.state??{})]);for(const metric of metrics){const av=a?.state[metric]??0,bv=b?.state[metric]??0;if(av!==bv)out.push({nodeId:id,metric,baseline:av,projected:bv,delta:bv-av,confidenceBps:10000});}}return out.sort((a,b)=>a.nodeId.localeCompare(b.nodeId)||a.metric.localeCompare(b.metric));}
