import type {ChiefDecision,DecisionCandidate,DecisionMode,DecisionPolicy,DecisionSignal} from './contracts.ts';
const finite=(n:number,k:string)=>{if(!Number.isFinite(n))throw new Error(`${k} must be finite`)};
const clamp=(n:number,min=0,max=10000)=>Math.max(min,Math.min(max,n));
function validatePolicy(p:DecisionPolicy){finite(p.maxRiskBps,'maxRiskBps');finite(p.minConfidenceBps,'minConfidenceBps');finite(p.minSupportBps,'minSupportBps');if(p.maxRiskBps<0||p.minConfidenceBps<0||p.minSupportBps<0)throw new Error('invalid policy');if(p.maxBudgetMinor!==undefined&&p.maxBudgetMinor<0n)throw new Error('negative budget');}
export function normalizeCandidates(tenantId:string,candidates:DecisionCandidate[]):DecisionCandidate[]{if(!tenantId)throw new Error('tenantId required');const ids=new Set<string>();return candidates.filter(c=>c.tenantId===tenantId).map(c=>{if(ids.has(c.candidateId))throw new Error('duplicate candidate');ids.add(c.candidateId);finite(c.confidenceBps,'confidenceBps');finite(c.riskBps,'riskBps');finite(c.expectedImpactBps,'expectedImpactBps');finite(c.priority,'priority');if(!c.action)throw new Error('candidate action required');return {...c,confidenceBps:clamp(c.confidenceBps),riskBps:clamp(c.riskBps),expectedImpactBps:Math.max(0,c.expectedImpactBps)}});}
export function scoreCandidate(c:DecisionCandidate,signals:DecisionSignal[]=[]):number{const signalBoost=signals.filter(s=>s.tenantId===c.tenantId&&c.signalIds.includes(s.signalId)).reduce((n,s)=>n+clamp(s.strengthBps)/100,0);return c.priority*.35+c.confidenceBps*.45+c.expectedImpactBps*.2-c.riskBps*.3+signalBoost;}
export function arbitrate(taskId:string,tenantId:string,candidates:DecisionCandidate[],policy:DecisionPolicy,signals:DecisionSignal[]=[],now=Date.now()):ChiefDecision{validatePolicy(policy);const valid=normalizeCandidates(tenantId,candidates).filter(c=>c.riskBps<=policy.maxRiskBps&&c.confidenceBps>=policy.minConfidenceBps&&(!policy.allowedActions||policy.allowedActions.includes(c.action))&&!(policy.blockedActions||[]).includes(c.action));if(valid.length===0)return {decisionId:`chief-${tenantId}-${taskId}`,tenantId,taskId,status:'NO_DECISION',mode:'RECOMMEND',selectedProposalIds:[],supportBps:0,confidenceBps:0,riskBps:0,expectedImpactBps:0,approvalRequired:true,reason:'No candidate satisfied the tenant decision policy.',createdAt:now};
 const grouped=new Map<string,DecisionCandidate[]>();for(const c of valid){const arr=grouped.get(c.action)||[];arr.push(c);grouped.set(c.action,arr);}const ranked=[...grouped.entries()].map(([action,items])=>{const scores=items.map(c=>scoreCandidate(c,signals));const total=scores.reduce((a,b)=>a+b,0);const weight=items.reduce((a,c)=>a+c.confidenceBps,0);const confidence=Math.round(weight/items.length);const risk=Math.round(items.reduce((a,c)=>a+c.riskBps,0)/items.length);const impact=Math.round(items.reduce((a,c)=>a+c.expectedImpactBps,0)/items.length);return {action,items,score:total,confidence,risk,impact};}).sort((a,b)=>b.score-a.score||a.action.localeCompare(b.action));
 const winner=ranked[0];const matchedSignals=signals.filter(s=>s.tenantId===tenantId&&winner.items.some(c=>c.signalIds.includes(s.signalId)));const signalStrength=matchedSignals.length?matchedSignals.reduce((n,s)=>n+clamp(s.strengthBps),0)/matchedSignals.length:0;const support=Math.round(clamp(winner.confidence*.7+signalStrength*.2+clamp(winner.items.reduce((n,c)=>n+c.priority,0)/winner.items.length)*.1));const approval=winner.items.some(c=>c.requiresApproval)||winner.risk>Math.min(policy.maxRiskBps,2500)||winner.confidence<9000||support<policy.minSupportBps;const mode:DecisionMode=approval?'APPROVAL_REQUIRED':'AUTO_EXECUTE';return {decisionId:`chief-${tenantId}-${taskId}`,tenantId,taskId,status:approval?'APPROVAL_REQUIRED':'DECIDED',mode,action:winner.action,selectedProposalIds:winner.items.map(c=>c.proposalId),supportBps:clamp(support),confidenceBps:winner.confidence,riskBps:winner.risk,expectedImpactBps:winner.impact,approvalRequired:approval,reason:`Selected ${winner.action} from ${winner.items.length} supporting proposal(s); policy gates and cross-agent evidence were applied.`,createdAt:now};}
export function simulateDecision(taskId:string,tenantId:string,candidates:DecisionCandidate[],policy:DecisionPolicy,signals:DecisionSignal[]=[]):ChiefDecision{return arbitrate(taskId,tenantId,candidates,policy,signals,0);}
export function canExecute(decision:ChiefDecision,approved=false):boolean{return decision.status==='DECIDED'&&(!decision.approvalRequired||approved)&&!!decision.action;}
export function decisionDigest(decision:ChiefDecision):string{return [decision.decisionId,decision.action||'NONE',decision.status,decision.selectedProposalIds.join(','),String(decision.confidenceBps),String(decision.riskBps)].join('|');}
