import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const root = process.cwd();
const read = f => fs.readFileSync(path.join(root, f), 'utf8');
const write = (f, v) => { fs.mkdirSync(path.dirname(path.join(root, f)), { recursive: true }); fs.writeFileSync(path.join(root, f), v); };
const hash = v => crypto.createHash('sha256').update(v).digest('hex');
const pkg = JSON.parse(read('package.json'));
if (pkg.version !== '265.0.0') throw new Error(`Historical V264 ledger must run from V265 tree, got ${pkg.version}`);
const control = JSON.parse(read('artifacts/reality/reality-promotion-control-v263.json'));
if ((control.counts?.considered ?? 0) !== 4 || (control.counts?.pendingExplicitReview ?? 0) !== 4) throw new Error('V263 control plane must provide exactly 4 pending decisions');
const sql = read('db/migrations/102_v264_durable_promotion_ledger.sql');
const store = read('modules/platform/reality-promotion/store.ts');
for (const marker of ['trust_reality_promotion_decisions','trust_reality_promotion_events','event_hash','previous_event_hash']) if (!sql.includes(marker)) throw new Error(`Missing durable ledger marker: ${marker}`);
if (!store.includes('pg_advisory_xact_lock')) throw new Error('Promotion store must serialize transitions with an advisory transaction lock');
const states = { PENDING_EXPLICIT_REVIEW:['APPROVED','REJECTED'], APPROVED:['PROMOTED','REVOKED'], REJECTED:[], PROMOTED:['REVOKED'], REVOKED:[] };
const decisions = control.decisions.map(d => ({ decisionId:d.decisionId, capabilityId:d.capabilityId, state:d.state, attestationRoot:d.attestationRoot, evidenceLeaf:d.evidenceLeaf, baselineEvidenceDigest:d.baselineEvidenceDigest, decisionHash:d.decisionHash, reviewerId:null, rationale:d.rationale }));
const ledgerRoot = hash(JSON.stringify({ version:'V264.0.0', decisionRoot:control.decisionRoot, transitions:decisions.map(d=>({decisionId:d.decisionId,state:d.state,allowedNext:states[d.state]})) }));
const out = { version:'V264.0.0', schemaVersion:'1.0', source:'artifacts/reality/reality-promotion-control-v263.json', policy:{ appendOnlyEvents:true, durableState:true, explicitActorRequired:true, evidenceBindingRequired:true, autoPromotion:false }, counts:{ decisions:decisions.length, pending:decisions.filter(d=>d.state==='PENDING_EXPLICIT_REVIEW').length, approved:0, promoted:0, rejected:0 }, ledgerRoot, decisions, transitionMatrix:states };
write('artifacts/reality/reality-promotion-ledger-v264.json', JSON.stringify(out,null,2)+'\n');
write('artifacts/reality/reality-promotion-ledger-v264.md', `# TRUST V264 — Durable Reality Promotion Ledger\n\n- Decisions: ${out.counts.decisions}\n- Pending explicit review: ${out.counts.pending}\n- Approved: ${out.counts.approved}\n- Promoted: ${out.counts.promoted}\n- Ledger root: ${ledgerRoot}\n- Auto-promotion: disabled\n\nThe ledger persists current state in PostgreSQL and every transition as an append-only hash-chained event.\n`);
console.log(`V264 Durable Promotion Ledger PASS — ${decisions.length} pending decisions; ledgerRoot=${ledgerRoot}`);
