import {execFileSync} from 'node:child_process';
import fs from 'node:fs'; import {performance} from 'node:perf_hooks';
const started=new Date().toISOString();
const checks=[]; const run=(name,kind,fn)=>{const t=performance.now();try{const details=fn()||{};checks.push({name,kind,status:'PASS',durationMs:Number(Math.max(0.001,performance.now()-t).toFixed(3)),details,executed:true});}catch(e){checks.push({name,kind,status:'FAIL',durationMs:Number(Math.max(0.001,performance.now()-t).toFixed(3)),details:{error:String(e.message||e)},executed:true});}};
run('v318-contract-and-rollback-simulator','TRANSACTION',()=>{execFileSync(process.execPath,['--experimental-strip-types','tests/v318-integration-lab.test.mjs'],{stdio:'pipe'});return {deterministic:true,rollbackOnInjectedFailure:true,idempotency:true};});
run('migration-156-present','MIGRATION',()=>{const sql=fs.readFileSync('db/migrations/156_v318_production_integration_lab.sql','utf8');if(!sql.includes('trust_v318_integration_runs')||!sql.includes('trust_v318_integration_checks'))throw new Error('V318_MIGRATION_ARTIFACT_MISSING');return {migration:156};});
const liveDatabase=Boolean(process.env.DATABASE_URL); if(liveDatabase){run('live-postgres-probe','TRANSACTION',()=>{execFileSync(process.execPath,['--experimental-strip-types','scripts/v318_postgres_lab.mjs'],{stdio:'pipe'});return {liveDatabase:true};});} else checks.push({name:'live-postgres-probe',kind:'TRANSACTION',status:'SKIPPED',durationMs:0.001,executed:false,details:{reason:'DATABASE_NOT_CONFIGURED'}});
const status=checks.some(c=>c.status==='FAIL')?'FAIL':liveDatabase?'PASS':'PARTIAL'; const report={version:'V318.0.0',status,startedAt:started,completedAt:new Date().toISOString(),checks,liveDatabase,externalProvidersLive:false};
fs.mkdirSync('artifacts/v318',{recursive:true}); fs.writeFileSync('artifacts/v318/integration-lab-report.json',JSON.stringify(report,null,2)+'\n'); console.log(`V318 integration lab ${status} — ${checks.filter(c=>c.status==='PASS').length} PASS, ${checks.filter(c=>c.status==='SKIPPED').length} SKIPPED, ${checks.filter(c=>c.status==='FAIL').length} FAIL`); if(status==='FAIL')process.exit(1);
