import fs from 'node:fs'; import path from 'node:path';
const root=process.cwd(); const read=f=>fs.readFileSync(path.join(root,f),'utf8'); const exists=f=>fs.existsSync(path.join(root,f)); const errors=[];
const pkg=JSON.parse(read('package.json')); const lock=JSON.parse(read('package-lock.json')); const manifest=JSON.parse(read('db/migrations/MANIFEST.json'));
const version=read('lib/runtime/version.ts').match(/V(\d+\.\d+\.\d+)/)?.[1];
if(pkg.version!=='397.0.0'||version!=='397.0.0'||lock.version!=='397.0.0'||lock.packages?.['']?.version!=='397.0.0') errors.push('version integrity');
if(manifest.version!=='V397.0.0'||String(manifest.migrations.at(-1)?.id)!=='222'||manifest.migrations.at(-1)?.version!=='V397.0.0') errors.push('migration head');
for(const f of ['db/migrations/219_v394_commerce_reconciliation.sql','db/migrations/220_v395_commerce_journey_integrity.sql','db/migrations/221_v396_seller_settlement_truth.sql','db/migrations/222_v397_unified_commerce_command_surface.sql','scripts/v394_commerce_reconciliation.mjs','scripts/v395_commerce_journey_integrity.mjs','scripts/v396_seller_settlement_truth.mjs','scripts/v397_unified_commerce_command_surface.mjs','modules/platform/order-journey-os/command-snapshot.ts','app/api/commerce/journey/[id]/route.ts','modules/marketplace/economic-settlement.ts','modules/marketplace/seller-operations.ts','MASTER-RELEASE.md']) if(!exists(f)) errors.push('missing '+f);
const settlement=read('modules/marketplace/economic-settlement.ts'); for(const token of ['trust_seller_orders','SELLER_ORDER_TOTALS_DO_NOT_BALANCE_ORDER','trust_marketplace_fee_ledger','trust_seller_order_financials']) if(!settlement.includes(token)) errors.push('settlement invariant '+token);
const migration=read('db/migrations/221_v396_seller_settlement_truth.sql'); for(const token of ['trust_seller_settlement_truth','SETTLEMENT_NOT_BALANCED','PAYOUT_OVERALLOCATED','REFUND_ALLOCATION_MISMATCH','seller_order_id']) if(!migration.includes(token)) errors.push('truth migration '+token);
const command=read('db/migrations/222_v397_unified_commerce_command_surface.sql'); for(const token of ['trust_commerce_command_snapshot','SELLER_SPLIT_MISSING','SELLER_SPLIT_TOTAL_MISMATCH','CAPTURED_WITHOUT_FULFILLMENT']) if(!command.includes(token)) errors.push('command surface '+token); const verifier=read('scripts/v396_seller_settlement_truth.mjs'); for(const token of ['DATABASE_NOT_CONFIGURED','trust_seller_settlement_truth','UNBALANCED_FINANCIALS','DUPLICATE_FEE_LEDGER_KEYS']) if(!verifier.includes(token)) errors.push('verifier '+token);
const v=JSON.parse(read('vercel.json')); const seen=new Set(); for(const c of v.crons||[]){const k=c.path+'|'+c.schedule;if(seen.has(k)) errors.push('duplicate cron '+k);seen.add(k);}
if(errors.length){console.error('V397 RELEASE GATE FAILED'); errors.forEach(e=>console.error('- '+e)); process.exit(1);}
console.log('V397 RELEASE GATE PASS — unified buyer/seller/fulfillment/finance command surface, seller settlement truth and live verifier are wired.');
