import fs from 'node:fs';
import crypto from 'node:crypto';
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
if(pkg.version!=='409.0.0') throw new Error(`PACKAGE_VERSION_DRIFT:${pkg.version}`);
const runtime=fs.readFileSync('lib/runtime/version.ts','utf8');
if(!runtime.includes('V409.0.0')) throw new Error('RUNTIME_VERSION_DRIFT');
const manifest=JSON.parse(fs.readFileSync('db/migrations/MANIFEST.json','utf8'));
if(manifest.version!=='V409.0.0'||manifest.generatedFor!=='V409.0.0') throw new Error('MIGRATION_MANIFEST_VERSION_DRIFT');
const file='db/migrations/234_v409_production_failure_closure.sql';
if(!fs.existsSync(file)) throw new Error('MIGRATION_234_MISSING');
const entry=manifest.migrations.find(x=>String(x.id)==='234');
if(!entry) throw new Error('MIGRATION_234_MANIFEST_MISSING');
const checksum=crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
if(checksum!==entry.checksum) throw new Error(`MIGRATION_234_CHECKSUM_MISMATCH:${checksum}`);
console.log('V409 RELEASE GATE PASS — version marker, migration 234, manifest checksum and failure-closure artifacts are aligned.');
