import type {LearnedCarrierProfile,LearningObservation,LearningRun} from './contracts.ts';
const clamp=(n:number)=>Math.max(0,Math.min(1,n));
const round=(n:number,d=6)=>Number(n.toFixed(d));
const PRIOR_DELIVERY=.85, PRIOR_PROMISE=.80, PRIOR_RELIABILITY=.85, PRIOR_WEIGHT=5;
export function learnCarrierProfiles(observations:LearningObservation[]):LearningRun{
 const groups=new Map<string,LearningObservation[]>();
 for(const o of observations){if(!o.carrierCode.trim()||!o.serviceCode.trim())continue;const k=`${o.carrierCode.trim().toUpperCase()}:${o.serviceCode.trim().toUpperCase()}`;const rows=groups.get(k)??[];rows.push(o);groups.set(k,rows);}
 const profiles:LearnedCarrierProfile[]=[];
 for(const [key,rows] of groups){const [carrierCode,serviceCode]=key.split(':');const n=rows.length;const delivered=rows.filter(x=>x.outcome==='DELIVERED').length;const exception=rows.filter(x=>x.outcome==='EXCEPTION').length;const cancelled=rows.filter(x=>x.outcome==='CANCELLED').length;const promiseRows=rows.filter(x=>x.promiseHit!==null&&x.promiseHit!==undefined);const hits=promiseRows.filter(x=>x.promiseHit===true).length;const transit=rows.map(x=>x.transitDays).filter((x):x is number=>Number.isFinite(x??NaN)&&(x as number)>=0);const rawDelivery=delivered/n;const rawPromise=promiseRows.length?hits/promiseRows.length:PRIOR_PROMISE;const confidence=clamp(n/(n+PRIOR_WEIGHT));const posteriorDelivery=rawDelivery*confidence+PRIOR_DELIVERY*(1-confidence);const posteriorPromise=rawPromise*confidence+PRIOR_PROMISE*(1-confidence);const posteriorException=(exception/n)*confidence+(1-PRIOR_DELIVERY)*(1-confidence);const adaptiveReliability=clamp(posteriorDelivery*.65+posteriorPromise*.20+(1-posteriorException)*.15);profiles.push({carrierCode,serviceCode,sampleCount:n,deliveredCount:delivered,exceptionCount:exception,cancelledCount:cancelled,deliveryRate:round(rawDelivery),promiseHitRate:round(rawPromise),exceptionRate:round(exception/n),avgTransitDays:transit.length?round(transit.reduce((a,b)=>a+b,0)/transit.length,4):null,confidence:round(confidence),adaptiveReliability:round(adaptiveReliability),modelVersion:'V312.0.0',lastObservedAt:rows.map(x=>x.occurredAt).sort().at(-1)??null});}
 profiles.sort((a,b)=>b.adaptiveReliability-a.adaptiveReliability||b.sampleCount-a.sampleCount||a.carrierCode.localeCompare(b.carrierCode));return {modelVersion:'V312.0.0',sampleCount:observations.length,profileCount:profiles.length,profiles,status:profiles.length?'COMPLETED':'NO_DATA'};
}
