import {query,withPgTransaction} from '../db/postgres.ts';
import {learnCarrierProfiles} from './learning.ts';
import {optimizeAdaptiveNetwork} from './adaptive.ts';
import type {NetworkCapacity,NetworkObjective,NetworkShipment,NetworkPlan} from '../global-logistics-v311/contracts.ts';
import type {LearningObservation,LearningRun,LearnedCarrierProfile} from './contracts.ts';
export const GLOBAL_LOGISTICS_ADAPTIVE_VERSION='V312.0.0';
export async function collectLearningObservations(limit=5000):Promise<LearningObservation[]>{
 const rows=(await query(`SELECT a.shipment_id,a.carrier_code,a.service_code,a.cost_minor,a.max_days,s.promised_at,s.created_at,e.status,e.occurred_at,e.eta_at FROM trust_global_logistics_network_allocations a JOIN trust_shipments s ON s.id=a.shipment_id JOIN LATERAL (SELECT status,occurred_at,eta_at FROM trust_global_logistics_tracking_events te WHERE te.shipment_id=s.id ORDER BY te.occurred_at DESC,te.created_at DESC LIMIT 1) e ON TRUE WHERE e.status IN ('DELIVERED','EXCEPTION','CANCELLED') ORDER BY e.occurred_at DESC LIMIT $1`,[limit])).rows;
 return rows.map((r:any)=>{const occurredAt=new Date(r.occurred_at).toISOString();const createdAt=new Date(r.created_at).getTime();const transitDays=Math.max(0,(new Date(r.occurred_at).getTime()-createdAt)/86400000);const promise=r.promised_at?new Date(r.promised_at).getTime():null;return {shipmentId:r.shipment_id,carrierCode:r.carrier_code,serviceCode:r.service_code,outcome:r.status,promiseHit:promise===null?null:new Date(r.occurred_at).getTime()<=promise,transitDays,plannedMaxDays:Number(r.max_days),costMinor:r.cost_minor===null?null:BigInt(r.cost_minor),occurredAt};});
}

export async function previewAdaptiveNetwork(input:{shipments:NetworkShipment[];capacities?:NetworkCapacity[];objective?:NetworkObjective;now?:string;idempotencyKey?:string}):Promise<NetworkPlan>{
 const profiles=await listLearnedProfiles();
 return optimizeAdaptiveNetwork(input.shipments,input.capacities??[],input.objective??'BALANCED',input.now??new Date().toISOString(),input.idempotencyKey??'adaptive-preview',profiles);
}

export async function previewLearning(observations?:LearningObservation[],limit=5000){return learnCarrierProfiles(observations??await collectLearningObservations(limit));}
export async function runLearningTx(tx:import('pg').PoolClient,input:{observations?:LearningObservation[];limit?:number}){
 const observations=input.observations??await (async()=>{const rows=(await tx.query(`SELECT a.shipment_id,a.carrier_code,a.service_code,a.cost_minor,a.max_days,s.promised_at,s.created_at,e.status,e.occurred_at FROM trust_global_logistics_network_allocations a JOIN trust_shipments s ON s.id=a.shipment_id JOIN LATERAL (SELECT status,occurred_at FROM trust_global_logistics_tracking_events te WHERE te.shipment_id=s.id ORDER BY te.occurred_at DESC,te.created_at DESC LIMIT 1) e ON TRUE WHERE e.status IN ('DELIVERED','EXCEPTION','CANCELLED') ORDER BY e.occurred_at DESC LIMIT $1`,[input.limit??5000])).rows;return rows.map((r:any)=>{const t=new Date(r.occurred_at).getTime(),c=new Date(r.created_at).getTime(),p=r.promised_at?new Date(r.promised_at).getTime():null;return {shipmentId:r.shipment_id,carrierCode:r.carrier_code,serviceCode:r.service_code,outcome:r.status,promiseHit:p===null?null:t<=p,transitDays:Math.max(0,(t-c)/86400000),plannedMaxDays:Number(r.max_days),costMinor:r.cost_minor===null?null:BigInt(r.cost_minor),occurredAt:new Date(t).toISOString()};});})();
 const run=learnCarrierProfiles(observations);const runRow=(await tx.query(`INSERT INTO trust_global_logistics_learning_runs(scope,sample_count,profile_count,model_version,status,summary_json) VALUES('GLOBAL',$1,$2,$3,$4,$5::jsonb) RETURNING *`,[run.sampleCount,run.profileCount,run.modelVersion,run.status,JSON.stringify({profileCount:run.profileCount,carriers:[...new Set(run.profiles.map(p=>p.carrierCode))]})])).rows[0];
 for(const o of observations){await tx.query(`INSERT INTO trust_global_logistics_learning_observations(run_id,shipment_id,carrier_code,service_code,outcome,promise_hit,transit_days,planned_max_days,cost_minor,occurred_at,evidence_json) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb) ON CONFLICT(run_id,shipment_id) DO NOTHING`,[runRow.id,o.shipmentId,o.carrierCode,o.serviceCode,o.outcome,o.promiseHit,o.transitDays,o.plannedMaxDays,o.costMinor?.toString()??null,o.occurredAt,JSON.stringify({source:'V307_RECONCILED_TRACKING',modelVersion:run.modelVersion})]);}
 for(const p of run.profiles){await tx.query(`INSERT INTO trust_global_logistics_carrier_learning(carrier_code,service_code,sample_count,delivered_count,exception_count,cancelled_count,delivery_rate,promise_hit_rate,exception_rate,avg_transit_days,confidence,adaptive_reliability,model_version,last_observed_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,now()) ON CONFLICT(carrier_code,service_code) DO UPDATE SET sample_count=EXCLUDED.sample_count,delivered_count=EXCLUDED.delivered_count,exception_count=EXCLUDED.exception_count,cancelled_count=EXCLUDED.cancelled_count,delivery_rate=EXCLUDED.delivery_rate,promise_hit_rate=EXCLUDED.promise_hit_rate,exception_rate=EXCLUDED.exception_rate,avg_transit_days=EXCLUDED.avg_transit_days,confidence=EXCLUDED.confidence,adaptive_reliability=EXCLUDED.adaptive_reliability,model_version=EXCLUDED.model_version,last_observed_at=EXCLUDED.last_observed_at,updated_at=now()`,[p.carrierCode,p.serviceCode,p.sampleCount,p.deliveredCount,p.exceptionCount,p.cancelledCount,p.deliveryRate,p.promiseHitRate,p.exceptionRate,p.avgTransitDays,p.confidence,p.adaptiveReliability,p.modelVersion,p.lastObservedAt]);}
 await tx.query(`INSERT INTO trust_outbox_events(event_type,aggregate_id,payload_json) VALUES('global.logistics.learning.completed',$1,$2::jsonb)`,[runRow.id,JSON.stringify({version:GLOBAL_LOGISTICS_ADAPTIVE_VERSION,runId:runRow.id,sampleCount:run.sampleCount,profileCount:run.profileCount})]);return {runId:runRow.id,...run};
}
export async function runLearning(input:{observations?:LearningObservation[];limit?:number}={}):Promise<LearningRun&{runId:string}>{return withPgTransaction(tx=>runLearningTx(tx,input));}
export async function listLearnedProfiles():Promise<LearnedCarrierProfile[]>{return (await query(`SELECT carrier_code as "carrierCode",service_code as "serviceCode",sample_count as "sampleCount",delivered_count as "deliveredCount",exception_count as "exceptionCount",cancelled_count as "cancelledCount",delivery_rate as "deliveryRate",promise_hit_rate as "promiseHitRate",exception_rate as "exceptionRate",avg_transit_days as "avgTransitDays",confidence,adaptive_reliability as "adaptiveReliability",model_version as "modelVersion",last_observed_at as "lastObservedAt" FROM trust_global_logistics_carrier_learning ORDER BY adaptive_reliability DESC,sample_count DESC`)).rows;}
