import Link from 'next/link';
import AddToCartButton from '../../../components/add-to-cart-button';
import OfferSelector from '../../../components/offer-selector';
import ProductViewTracker from '../../../components/product-view-tracker';
import CustomerProductActions from '../../../components/customer-product-actions';
export default async function ProductPage({params}:{params:{id:string}}){
  const base=process.env.NEXT_PUBLIC_APP_URL;
  const response=await fetch(`${base??'http://localhost:3000'}/api/marketplace/products/${encodeURIComponent(params.id)}`,{cache:'no-store'});
  const data=await response.json().catch(()=>({ok:false}));
  if(!response.ok||!data.ok)return <main style={{padding:40}}><h1>المنتج غير موجود</h1><Link href="/shop">العودة للمتجر</Link></main>;
  const p=data.product;
  return <main style={{maxWidth:1100,margin:'0 auto',padding:'40px 20px'}}><Link href="/shop">← المتجر</Link><ProductViewTracker productId={p.id} category={p.category} price={p.price}/><section style={{display:'grid',gridTemplateColumns:'minmax(300px,1fr) minmax(300px,1fr)',gap:36,marginTop:28}}><div style={{minHeight:420,background:'#f4f4f4',borderRadius:20,overflow:'hidden'}}>{p.image&&<img src={p.image} alt={p.name} style={{width:'100%',height:'100%',objectFit:'cover'}}/>}</div><div><p style={{opacity:.6}}>{p.category} · {p.merchantName}</p><h1>{p.name}</h1><p>★ {p.rating.toFixed(1)} · {p.stock>0?`متاح (${p.stock})`:'غير متاح'}</p><h2>{p.price.toFixed(2)} EGP</h2>{p.oldPrice&&<p style={{textDecoration:'line-through',opacity:.5}}>{p.oldPrice.toFixed(2)} EGP</p>}<AddToCartButton productId={p.id} offerId={data.marketplace?.offer?.id} disabled={p.stock<=0}/><CustomerProductActions productId={p.id} currentPrice={p.price}/>{data.marketplace?.offers?.length ? <OfferSelector productId={p.id} offers={data.marketplace.offers} buyBoxId={data.marketplace.offer?.id}/> : null}</div></section><section style={{marginTop:50}}><h2>منتجات مشابهة</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(190px,1fr))',gap:12}}>{data.related.map((x:any)=><Link key={x.id} href={'/product/'+x.id} style={{padding:14,border:'1px solid #ddd',borderRadius:14,color:'inherit',textDecoration:'none'}}><strong>{x.name}</strong><p>{x.price.toFixed(2)} EGP</p></Link>)}</div></section><section style={{marginTop:50}}><h2>تقييمات العملاء</h2><p>★ {data.reviews?.summary?.ratingAverage?.toFixed?.(2)??'0.00'} · {data.reviews?.summary?.reviewCount??0} تقييم · {data.reviews?.summary?.verifiedCount??0} شراء موثّق</p><div style={{display:'grid',gap:10}}>{(data.reviews?.reviews??[]).slice(0,8).map((r:any)=><article key={r.id} style={{border:'1px solid #ddd',borderRadius:14,padding:14}}><strong>{'★'.repeat(r.rating)} </strong>{r.verifiedPurchase&&<small> شراء موثّق</small>}<p>{r.title}</p><p>{r.body}</p><small>{r.helpfulCount} وجدوا التقييم مفيدًا</small></article>)}</div></section></main>;
}
