import type {AutonomyPolicy,Calibration,LearningReport,Outcome,Prediction,AutonomyAdjustment} from './contracts.ts';
const finite=(n:number,k:string)=>{if(!Number.isFinite(n))throw new Error(`${k} must be finite`)};
const bps=(n:number,k:string)=>{finite(n,k);if(!Number.isInteger(n)||n<0||n>10000)throw new Error(`${k} must be integer 0..10000`)};
const levelRank=(l:AutonomyPolicy['currentLevel'])=>l==='SUGGEST'?0:l==='APPROVAL_REQUIRED'?1:2;
function validatePrediction(p:Prediction){if(!p.tenantId||!p.predictionId||!p.decisionId||!p.metric)throw new Error('prediction identity required');finite(p.predicted,'predicted');bps(p.confidenceBps,'confidenceBps');}
function validateOutcome(o:Outcome){if(!o.tenantId||!o.predictionId)throw new Error('outcome identity required');finite(o.observed,'observed');if(!Number.isFinite(o.observedAt))throw new Error('observedAt must be finite');}
export function calibrate(predictions:Prediction[],outcomes:Outcome[],tenantId:string):Calibration[]{if(!tenantId)throw new Error('tenant required');const byId=new Map<string,Outcome>();for(const o of outcomes){validateOutcome(o);if(o.tenantId===tenantId)byId.set(o.predictionId,o);}const out:Calibration[]=[];for(const p of predictions){validatePrediction(p);if(p.tenantId!==tenantId)continue;const o=byId.get(p.predictionId);if(!o){out.push({predictionId:p.predictionId,tenantId,metric:p.metric,predicted:p.predicted,observed:p.predicted,error:0,absoluteError:0,signedError:0,confidenceBps:p.confidenceBps,status:'MISSING'});continue;}if(o.status!=='OBSERVED'){out.push({predictionId:p.predictionId,tenantId,metric:p.metric,predicted:p.predicted,observed:o.observed,error:o.observed-p.predicted,absoluteError:Math.abs(o.observed-p.predicted),signedError:o.observed-p.predicted,confidenceBps:p.confidenceBps,status:o.status});continue;}const e=o.observed-p.predicted;out.push({predictionId:p.predictionId,tenantId,metric:p.metric,predicted:p.predicted,observed:o.observed,error:e,absoluteError:Math.abs(e),signedError:e,confidenceBps:p.confidenceBps,status:'OBSERVED'});}return out.sort((a,b)=>a.predictionId.localeCompare(b.predictionId));}
export function evaluateLearning(predictions:Prediction[],outcomes:Outcome[],tenantId:string,previousMae=0):LearningReport{finite(previousMae,'previousMae');if(previousMae<0)throw new Error('previousMae must be non-negative');const calibrations=calibrate(predictions,outcomes,tenantId),valid=calibrations.filter(c=>c.status==='OBSERVED');const mae=valid.length?valid.reduce((s,c)=>s+c.absoluteError,0)/valid.length:0;const mse=valid.length?valid.reduce((s,c)=>s+c.error*c.error,0)/valid.length:0;const meanSigned=valid.length?valid.reduce((s,c)=>s+c.signedError,0)/valid.length:0;const score=Math.max(0,Math.min(10000,Math.round(10000/(1+mae+mse/10))));const drift=previousMae===0?(mae===0?0:10000):Math.min(10000,Math.round(Math.abs(mae-previousMae)/previousMae*10000));let recommendation:AutonomyAdjustment='HOLD';if(drift>1500||mae>Math.max(1,previousMae*1.25))recommendation='LOWER';else if(valid.length>=3&&drift<500&&mae<Math.max(1,previousMae*0.9))recommendation='RAISE';return {tenantId,evaluated:calibrations.length,valid:valid.length,meanAbsoluteError:mae,meanSignedError:meanSigned,calibrationScoreBps:score,driftBps:drift,recommendation,calibrations,generatedAt:Date.now()};}
export function recommendAutonomy(report:LearningReport,policy:AutonomyPolicy):AutonomyPolicy['currentLevel']{bps(policy.minConfidenceBps,'minConfidenceBps');finite(policy.maxMeanAbsoluteError,'maxMeanAbsoluteError');if(policy.maxMeanAbsoluteError<0)throw new Error('maxMeanAbsoluteError must be non-negative');bps(policy.maxDriftBps,'maxDriftBps');if(report.tenantId==='')throw new Error('tenant required');if(report.recommendation==='LOWER'||report.driftBps>policy.maxDriftBps||report.meanAbsoluteError>policy.maxMeanAbsoluteError)return levelRank(policy.currentLevel)===0?'SUGGEST':levelRank(policy.currentLevel)===1?'SUGGEST':'APPROVAL_REQUIRED';if(report.recommendation==='RAISE'&&report.calibrationScoreBps>=policy.minConfidenceBps&&report.driftBps<=policy.maxDriftBps)return levelRank(policy.currentLevel)===2?'AUTO_EXECUTE':levelRank(policy.currentLevel)===1?'AUTO_EXECUTE':'APPROVAL_REQUIRED';return policy.currentLevel;}
export function compareLearning(before:LearningReport,after:LearningReport){if(before.tenantId!==after.tenantId)throw new Error('tenant mismatch');return {maeDelta:after.meanAbsoluteError-before.meanAbsoluteError,scoreDeltaBps:after.calibrationScoreBps-before.calibrationScoreBps,driftDeltaBps:after.driftBps-before.driftBps,improved:after.meanAbsoluteError<before.meanAbsoluteError&&after.calibrationScoreBps>=before.calibrationScoreBps};}
