'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {buildMerchantBrief, type MerchantOrder, type MerchantProduct} from '../../modules/merchant-os/experience-2';

type Overview={merchant:{storeName:string;slug:string;verificationStatus:string}};
type Analytics={metrics:{products:number;stockUnits:number;lowStock:number;outOfStock:number;orders:number;revenue:number;currency:string};statusCounts:Record<string,number>};
const money=(n:number)=>new Intl.NumberFormat('ar-EG',{style:'currency',currency:'EGP',maximumFractionDigits:0}).format(n);
const labels:Record<string,string>={pending:'قيد الانتظار',confirmed:'مؤكد',processing:'قيد التجهيز',shipped:'تم الشحن',delivered:'تم التسليم',cancelled:'ملغي'};

export default function MerchantOSPage(){
 const [overview,setOverview]=useState<Overview|null>(null),[products,setProducts]=useState<MerchantProduct[]>([]),[orders,setOrders]=useState<MerchantOrder[]>([]),[analytics,setAnalytics]=useState<Analytics|null>(null),[tab,setTab]=useState<'command'|'catalog'|'inventory'|'orders'>('command'),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[draft,setDraft]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{setLoading(true);setMessage('');try{const rs=await Promise.all(['/api/merchant/overview','/api/merchant/products','/api/merchant/orders','/api/merchant/analytics'].map(x=>fetch(x,{cache:'no-store'})));if(rs.some(r=>!r.ok))throw new Error('AUTH');const [o,p,r,a]=await Promise.all(rs.map(r=>r.json()));setOverview(o);setProducts(p.products??[]);setOrders(r.orders??[]);setAnalytics(a);}catch(e){setMessage(e instanceof Error&&e.message==='AUTH'?'سجّل الدخول بحساب تاجر لفتح مركز القيادة.':'تعذر تحميل بيانات التاجر.')}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const brief=useMemo(()=>buildMerchantBrief({products,orders,verificationStatus:overview?.merchant.verificationStatus}),[products,orders,overview]);
 const filtered=useMemo(()=>products.filter(p=>`${p.name} ${p.category} ${p.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())),[products,query]);
 const [form,setForm]=useState({name:'',category:'',price:'',stock:'',region:'',tags:'',image:''});
 const [editingId,setEditingId]=useState<string|null>(null); const [edit,setEdit]=useState({name:'',price:'',stock:''});
 const addProduct=async()=>{const price=Number(form.price),stock=Number(form.stock);if(!form.name.trim())return setMessage('اكتب اسم المنتج.');if(!Number.isFinite(price)||price<=0)return setMessage('السعر لازم يكون رقم أكبر من صفر.');if(!Number.isInteger(stock)||stock<0)return setMessage('الكمية لازم تكون رقم صحيح.');if(!form.category.trim()||!form.region.trim())return setMessage('الفئة ومنطقة الشحن مطلوبان.');const r=await fetch('/api/merchant/products',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,name:form.name.trim(),category:form.category.trim(),price,stock,region:form.region.trim(),tags:form.tags.split(',').map(x=>x.trim()).filter(Boolean)})});const d=await r.json();if(!r.ok||!d.ok)return setMessage(`فشل إضافة المنتج: ${d.error??'UNKNOWN_ERROR'}`);setForm({name:'',category:'',price:'',stock:'',region:'',tags:'',image:''});setMessage('تمت إضافة المنتج.');load()};
 const updateProduct=async(id:string)=>{const price=Number(edit.price),stock=Number(edit.stock);if(!edit.name.trim()||!Number.isFinite(price)||price<=0||!Number.isInteger(stock)||stock<0)return setMessage('بيانات التعديل غير صالحة.');const r=await fetch(`/api/merchant/products/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:edit.name.trim(),price,stock})});const d=await r.json();if(!r.ok||!d.ok)return setMessage(`فشل التعديل: ${d.error??'UNKNOWN_ERROR'}`);setEditingId(null);setMessage('تم تحديث المنتج.');load()};
 const saveInventory=async()=>{const updates=Object.entries(draft).map(([productId,stock])=>({productId,stock:Number(stock)})).filter(x=>Number.isInteger(x.stock)&&x.stock>=0);if(!updates.length)return setMessage('عدّل كمية واحدة على الأقل.');const r=await fetch('/api/merchant/inventory/bulk',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({updates})});const d=await r.json();if(!r.ok)return setMessage(`فشل تحديث المخزون: ${d.error??'UNKNOWN_ERROR'}`);setDraft({});setMessage(`تم تحديث ${d.updated} منتج.`);load()};
 return <main className="merchant2" dir="rtl"><div className="merchant2-shell"><header className="merchant2-hero"><div><span>TRUST APEX · MERCHANT OS 2.0</span><h1>{overview?.merchant.storeName??'Merchant Command Center'}<i>.</i></h1><p>مركز قيادة تشغيلي مبني على بيانات متجرك الحالية: الكتالوج، المخزون، الطلبات، والإيرادات المرصودة.</p></div><div className="merchant2-status"><b>{overview?.merchant.verificationStatus==='verified'?'VERIFIED':'REVIEW'}</b><small>{overview?.merchant.verificationStatus==='verified'?'متجر موثّق':'التوثيق غير مكتمل'}</small></div></header>
 {message&&<div className="merchant2-alert">{message}</div>}{overview&&overview.merchant.verificationStatus!=='verified'&&<div className="merchant2-alert">متجرك غير موثّق حاليًا. <a href="/merchant-verification">ابدأ التوثيق ←</a></div>}<nav className="merchant2-tabs">{[['command','مركز القيادة'],['catalog','الكتالوج'],['inventory','المخزون'],['orders','الطلبات']].map(([id,l])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id as typeof tab)}>{l}</button>)}<a href="/merchant-super-os">Merchant Super OS</a><button onClick={load}>↻ تحديث</button></nav>
 {loading?<div className="merchant2-loading">جاري تحميل بيانات المتجر…</div>:tab==='command'?<Command brief={brief} analytics={analytics}/>:tab==='catalog'?<Catalog products={filtered} query={query} setQuery={setQuery} form={form} setForm={setForm} addProduct={addProduct} editingId={editingId} setEditingId={setEditingId} edit={edit} setEdit={setEdit} updateProduct={updateProduct}/>:tab==='inventory'?<Inventory products={filtered} query={query} setQuery={setQuery} draft={draft} setDraft={setDraft} save={saveInventory}/>:<Orders orders={orders}/>}</div></main>
}
function Command({brief,analytics}:{brief:ReturnType<typeof buildMerchantBrief>;analytics:Analytics|null}){return <section><div className="merchant2-kpis">{[['الإيراد المرصود',money(brief.revenue)],['الطلبات',brief.orders],['الكتالوج',brief.products],['وحدات المخزون',brief.stockUnits],['AOV',money(brief.aov)],['صحة التشغيل',`${brief.health.score}%`]].map(([a,b])=><article key={String(a)}><span>{a}</span><strong>{b}</strong></article>)}</div><div className="merchant2-grid"><article className="merchant2-card merchant2-command"><small>COMMAND BRIEF</small><h2>إيه أهم حاجة لمتجرك دلوقتي؟</h2>{brief.priorities.map((x,i)=><div className="merchant2-priority" key={x}><b>0{i+1}</b><span>{x}</span></div>)}</article><article className="merchant2-card"><small>HEALTH RADAR</small><h2>صحة المتجر</h2><div className="merchant2-score"><strong>{brief.health.score}%</strong><span>مؤشر تشغيلي مشتق من توفر الكتالوج وتسليم الطلبات</span></div><div className="merchant2-bars"><div><i style={{width:`${brief.health.availability}%`}}/><span>توفر الكتالوج <b>{brief.health.availability}%</b></span></div><div><i style={{width:`${brief.health.fulfillment}%`}}/><span>الطلبات المسلّمة <b>{brief.health.fulfillment}%</b></span></div></div></article></div><article className="merchant2-card"><small>ORDER FLOW</small><h2>توزيع حالات الطلبات</h2><div className="merchant2-statuses">{Object.entries(analytics?.statusCounts??{}).map(([s,n])=><div key={s}><span>{labels[s]??s}</span><b>{n}</b></div>)}{!Object.keys(analytics?.statusCounts??{}).length&&<p>لا توجد طلبات حتى الآن.</p>}</div></article></section>}
function Catalog({products,query,setQuery,form,setForm,addProduct,editingId,setEditingId,edit,setEdit,updateProduct}:{products:MerchantProduct[];query:string;setQuery:(v:string)=>void;form:{name:string;category:string;price:string;stock:string;region:string;tags:string;image:string};setForm:(v:{name:string;category:string;price:string;stock:string;region:string;tags:string;image:string})=>void;addProduct:()=>void;editingId:string|null;setEditingId:(v:string|null)=>void;edit:{name:string;price:string;stock:string};setEdit:(v:{name:string;price:string;stock:string})=>void;updateProduct:(id:string)=>void}){return <section className="merchant2-card"><div className="merchant2-head"><div><small>CATALOG</small><h2>الكتالوج</h2></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث…"/></div><div className="merchant2-add"><input placeholder="اسم المنتج" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="الفئة" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><input placeholder="السعر" type="number" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><input placeholder="الكمية" type="number" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/><input placeholder="منطقة الشحن" value={form.region} onChange={e=>setForm({...form,region:e.target.value})}/><button className="merchant2-primary" onClick={addProduct}>إضافة منتج</button></div><div className="merchant2-products">{products.map(p=>editingId===p.id?<article key={p.id}><div><input value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/><input type="number" value={edit.price} onChange={e=>setEdit({...edit,price:e.target.value})}/><input type="number" value={edit.stock} onChange={e=>setEdit({...edit,stock:e.target.value})}/><button onClick={()=>updateProduct(p.id)}>حفظ</button><button onClick={()=>setEditingId(null)}>إلغاء</button></div></article>:<article key={p.id}><div className="merchant2-image" style={{backgroundImage:`url(${p.image})`}}/><div><b>{p.name}</b><span>{p.category} · {money(p.price)}</span><em className={p.stock===0?'danger':p.stock<=10?'warn':''}>{p.stock} وحدة</em><button className="merchant2-edit" onClick={()=>{setEditingId(p.id);setEdit({name:p.name,price:String(p.price),stock:String(p.stock)})}}>تعديل</button></div></article>)}{!products.length&&<p>لا توجد منتجات مطابقة.</p>}</div></section>}
function Inventory({products,query,setQuery,draft,setDraft,save}:{products:MerchantProduct[];query:string;setQuery:(v:string)=>void;draft:Record<string,string>;setDraft:(v:Record<string,string>)=>void;save:()=>void}){return <section className="merchant2-card"><div className="merchant2-head"><div><small>INVENTORY</small><h2>إدارة المخزون</h2></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث…"/></div><div className="merchant2-inventory">{products.map(p=><label key={p.id}><div><b>{p.name}</b><span>{p.stock} وحدة حالية</span></div><input type="number" min="0" value={draft[p.id]??p.stock} onChange={e=>setDraft({...draft,[p.id]:e.target.value})}/></label>)}</div><button className="merchant2-primary" onClick={save}>حفظ تغييرات المخزون</button></section>}
function Orders({orders}:{orders:MerchantOrder[]}){return <section className="merchant2-card"><small>ORDERS</small><h2>الطلبات</h2><div className="merchant2-orders">{orders.map(o=><article key={o.id}><b>{o.id}</b><span>{labels[o.status]??o.status}</span><strong>{money(o.total)}</strong><small>{new Date(o.createdAt).toLocaleString('ar-EG')}</small></article>)}{!orders.length&&<p>لا توجد طلبات مرتبطة بالمتجر.</p>}</div></section>}
