import { NextRequest, NextResponse } from 'next/server';
import { getCurrentUser } from '@/modules/platform/auth/current-user';
import { query } from '@/modules/platform/db/postgres';
import { getShipment, shipmentTimeline, transitionShipment } from '@/modules/platform/fulfillment-execution/core';
import { normalizeShipmentStatus, type ShipmentStatus } from '@/modules/platform/fulfillment-tracking-3';
const privileged=['admin','support','operations'];
export const dynamic='force-dynamic'; export const runtime='nodejs';
async function authorized(req:NextRequest,id:string){const u=await getCurrentUser(req);if(!u)return {error:NextResponse.json({ok:false,error:'AUTH_REQUIRED',surfaceStatus:'ERROR'},{status:401})};const s=await getShipment(id);if(!s)return {error:NextResponse.json({ok:false,error:'SHIPMENT_NOT_FOUND',surfaceStatus:'ERROR'},{status:404})};if(!privileged.includes(u.role)){const o=(await query(`select customer_id from trust_orders where id=$1`,[s.order_id])).rows[0];if(!o||o.customer_id!==u.id)return {error:NextResponse.json({ok:false,error:'SHIPMENT_ACCESS_DENIED',surfaceStatus:'ERROR'},{status:403})};}return {u,s};}
export async function GET(req:NextRequest,{params}:{params:{id:string}}){try{const a=await authorized(req,params.id);if(a.error)return a.error;return NextResponse.json({ok:true,surfaceStatus:'LIVE',shipment:a.s,timeline:await shipmentTimeline(params.id)},{headers:{'Cache-Control':'no-store'}})}catch(e){return NextResponse.json({ok:false,error:e instanceof Error?e.message:'SHIPMENT_ERROR',surfaceStatus:'ERROR'},{status:400})}}
export async function PATCH(req:NextRequest,{params}:{params:{id:string}}){const a=await authorized(req,params.id);if(a.error)return a.error;if(!privileged.includes(a.u!.role))return NextResponse.json({ok:false,error:'PRIVILEGED_ACCESS_REQUIRED',surfaceStatus:'ERROR'},{status:403});try{const b=await req.json();const to=normalizeShipmentStatus(String(b.status??''));if(!b.status||to!==b.status)return NextResponse.json({ok:false,error:'INVALID_SHIPMENT_STATUS',surfaceStatus:'ERROR'},{status:400});const result=await transitionShipment({shipmentId:params.id,to:to as ShipmentStatus,description:typeof b.description==='string'?b.description:undefined,location:typeof b.location==='string'?b.location:undefined,etaAt:typeof b.etaAt==='string'?b.etaAt:undefined});return NextResponse.json({ok:true,surfaceStatus:'LIVE',result},{headers:{'Cache-Control':'no-store'}})}catch(e){const message=e instanceof Error?e.message:'SHIPMENT_TRANSITION_ERROR';return NextResponse.json({ok:false,error:message,surfaceStatus:'ERROR'},{status:400})}}
