import { timingSafeEqual, createHmac, randomBytes } from 'node:crypto';
import { query } from '../db/postgres';
import { verifyPassword } from '../auth/password';
export const ADMIN_SESSION_COOKIE='trust_admin_session';
const MAX_AGE_SECONDS=60*60*8;
type AdminSession={email:string;exp:number;nonce:string;mfa:boolean};
function secret(){const value=process.env.TRUST_ADMIN_SESSION_SECRET;if(!value||value.length<32)throw new Error('TRUST_ADMIN_SESSION_SECRET must be at least 32 characters');return value;}
function sign(value:string){return createHmac('sha256',secret()).update(value).digest('base64url');}
function safeEqual(a:string,b:string){const aa=Buffer.from(a),bb=Buffer.from(b);return aa.length===bb.length&&timingSafeEqual(aa,bb);}
export function configured(){return Boolean(process.env.TRUST_ADMIN_EMAIL&&(process.env.TRUST_ADMIN_PASSWORD||process.env.TRUST_ADMIN_PASSWORD_HASH)&&process.env.TRUST_ADMIN_SESSION_SECRET);}
export function mfaRequired(){return process.env.TRUST_ADMIN_REQUIRE_MFA==='true';}
async function limited(key:string){
 const now=new Date(); const r=await query(`insert into trust_admin_rate_limits(bucket_key,count,reset_at) values($1,1,now()+interval '15 minutes') on conflict(bucket_key) do update set count=case when trust_admin_rate_limits.reset_at<=now() then 1 else trust_admin_rate_limits.count+1 end, reset_at=case when trust_admin_rate_limits.reset_at<=now() then now()+interval '15 minutes' else trust_admin_rate_limits.reset_at end, updated_at=now() returning count,reset_at`,[key]);
 return {allowed:Number(r.rows[0].count)<=8,resetAt:new Date(r.rows[0].reset_at).getTime()};
}
export async function authenticateAdmin(email:string,password:string,rateKey='unknown'){const key=`admin-login:${email.trim().toLowerCase()}:${rateKey}`;const limit=await limited(key);if(!limit.allowed)return false;const expectedEmail=process.env.TRUST_ADMIN_EMAIL?.trim().toLowerCase();if(!expectedEmail||!safeEqual(email.trim().toLowerCase(),expectedEmail))return false;const hashed=process.env.TRUST_ADMIN_PASSWORD_HASH;if(hashed)return verifyPassword(password,hashed);const expectedPassword=process.env.TRUST_ADMIN_PASSWORD;return Boolean(expectedPassword&&safeEqual(password,expectedPassword));}
function base32Decode(input:string){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';const clean=input.replace(/=+$/,'').replace(/\s+/g,'').toUpperCase();let bits='';for(const ch of clean){const n=alphabet.indexOf(ch);if(n<0)throw new Error('Invalid TOTP secret');bits+=n.toString(2).padStart(5,'0');}const bytes=[];for(let i=0;i+8<=bits.length;i+=8)bytes.push(parseInt(bits.slice(i,i+8),2));return Buffer.from(bytes);}
export function verifyTotp(code:string){const secretValue=process.env.TRUST_ADMIN_TOTP_SECRET;if(!secretValue||!/^\d{6}$/.test(code))return false;try{const key=base32Decode(secretValue);const now=Math.floor(Date.now()/1000/30);for(let offset=-1;offset<=1;offset++){const counter=Buffer.alloc(8);counter.writeBigUInt64BE(BigInt(now+offset));const mac=createHmac('sha1',key).update(counter).digest();const index=mac[mac.length-1]&15;const bin=((mac[index]&127)<<24)|(mac[index+1]<<16)|(mac[index+2]<<8)|mac[index+3];const otp=String(bin%1000000).padStart(6,'0');if(safeEqual(otp,code))return true;}}catch{}return false;}
export function createAdminSession(email:string,mfa=false){const payload:AdminSession={email:email.trim().toLowerCase(),exp:Math.floor(Date.now()/1000)+MAX_AGE_SECONDS,nonce:randomBytes(16).toString('hex'),mfa};const encoded=Buffer.from(JSON.stringify(payload)).toString('base64url');return `${encoded}.${sign(encoded)}`;}
export async function verifyAdminSession(token:string|null){if(!token||!configured())return undefined;const [encoded,signature]=token.split('.');if(!encoded||!signature||!safeEqual(sign(encoded),signature))return undefined;try{const payload=JSON.parse(Buffer.from(encoded,'base64url').toString('utf8')) as AdminSession;const expectedEmail=process.env.TRUST_ADMIN_EMAIL?.trim().toLowerCase();if(!payload.email||payload.email!==expectedEmail||!Number.isFinite(payload.exp)||payload.exp<=Math.floor(Date.now()/1000))return undefined;if(mfaRequired()&&!payload.mfa)return undefined;return payload;}catch{return undefined;}}
export const adminCookieOptions={httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax' as const,path:'/',maxAge:MAX_AGE_SECONDS};
export function isSafeAdminNext(value:string|null|undefined){if(!value)return '/admin';if(!value.startsWith('/')||value.startsWith('//')||value.includes('\\')||value.includes('://'))return '/admin';const allowed=['/admin','/decision-fabric-admin','/protection-admin','/prevention-admin','/life-os-admin','/merchant-supergraph-admin','/global-commerce-network-admin','/ops','/personal-shopper/admin','/discovery/admin','/problem-solver-admin','/merchant-verification-admin'];return allowed.some(path=>value===path||value.startsWith(`${path}/`))?value:'/admin';}
