const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function tenant(id:string){if(!id||!UUID.test(id))throw new Error('TENANT_ID_REQUIRED');}
export async function loadSnapshot(db:any){
 const product=await db.query('select count(*)::text as count from trust_products');
 const inv=await db.query(`select count(*)::text as count, coalesce(sum(price*stock),0)::text as value from trust_products where active=true`);
 const agents=await db.query('select * from trust_agent_registry');
 await Promise.all([db.query('select count(*)::text as count from trust_orders'),db.query('select count(*)::text as count from trust_merchant_profiles'),db.query('select count(*)::text as count from trust_autonomy_actions'),db.query('select count(*)::text as count from trust_fraud_assessments')]);
 return {productCount:Number(product.rows[0]?.count||0),inventoryValue:Number(inv.rows[0]?.value||0),agents:agents.rows.map((a:any)=>({agentId:a.agent_id??a.agentId,tenantId:a.tenant_id??a.tenantId,name:a.name,version:a.version,capabilities:a.capabilities,status:a.status,trustScore:a.trust_score??a.trustScore,maxRisk:a.max_risk??a.maxRisk,maxAutonomy:a.max_autonomy??a.maxAutonomy}))};
}
export async function upsertAgent(db:any,a:any){tenant(a.tenantId);return db.query(`insert into trust_agent_registry (tenant_id,agent_id,name,version,capabilities,status,trust_score,max_risk,max_autonomy) values ($1,$2,$3,$4,$5,$6,$7,$8,$9) on conflict(tenant_id,agent_id) do update set name=excluded.name,version=excluded.version,capabilities=excluded.capabilities,status=excluded.status,trust_score=excluded.trust_score,max_risk=excluded.max_risk,max_autonomy=excluded.max_autonomy`,[a.tenantId,a.agentId,a.name,a.version,a.capabilities,a.status,a.trustScore,a.maxRisk,a.maxAutonomy]);}
export async function recordAutonomyDecision(db:any,a:any){tenant(a.tenantId);if(a.confidence<0||a.confidence>1)throw new Error('INVALID_CONFIDENCE');return db.query('insert into trust_autonomy_actions (tenant_id,agent_id,capability,decision,reason,confidence,risk,estimated_cost,payload) values ($1,$2,$3,$4,$5,$6,$7,$8,$9)',[a.tenantId,a.agentId,a.capability,a.decision,a.reason,a.confidence,a.risk,a.estimatedCost,JSON.stringify(a.payload)]);}
export async function recordFraudAssessment(db:any,a:any){tenant(a.tenantId);if(a.score<0||a.score>100)throw new Error('INVALID_FRAUD_SCORE');return db.query('insert into trust_fraud_assessments (tenant_id,subject_id,score,risk,signals) values ($1,$2,$3,$4,$5)',[a.tenantId,a.subjectId,a.score,a.risk,JSON.stringify(a.signals)]);}
