import { query } from '../platform/db/postgres';
import { CUSTOMER_PREFERENCE_KEYS,type PreferenceScope } from './contracts';
export type Channel='EMAIL'|'SMS'|'WHATSAPP'|'PUSH'|'IN_APP';
export type ConsentReason='PREFERENCE_DISABLED'|'PROFILE_DELETED'|'TRANSACTIONAL_ALLOWED'|'MISSING_CONSENT'|'CHANNEL_UNAVAILABLE';
export interface ConsentDecision{allowed:boolean;reason:ConsentReason;scope:PreferenceScope;key:string;channel:Channel;}
const channelKey:Record<Channel,string>={EMAIL:'email',SMS:'sms',WHATSAPP:'whatsapp',PUSH:'push',IN_APP:'in_app'};
export function preferenceForChannel(channel:Channel):string{if(channel==='IN_APP')return 'push';return channelKey[channel];}
export async function resolveConsent(customerId:string,scope:PreferenceScope,channel:Channel,keyOverride?:string):Promise<ConsentDecision>{const key=keyOverride??preferenceForChannel(channel);if(scope==='TRANSACTIONAL')return {allowed:true,reason:'TRANSACTIONAL_ALLOWED',scope,key,channel};if(!CUSTOMER_PREFERENCE_KEYS[scope]?.includes(key))return {allowed:false,reason:'CHANNEL_UNAVAILABLE',scope,key,channel};const profile=await query(`select lifecycle from trust_customer_profiles where id=$1`,[customerId]);if(!profile.rows[0]||profile.rows[0].lifecycle==='DELETED')return {allowed:false,reason:'PROFILE_DELETED',scope,key,channel};const pref=await query(`select enabled from trust_customer_preferences where customer_id=$1 and scope=$2 and key=$3`,[customerId,scope,key]);if(!pref.rows[0]?.enabled)return {allowed:false,reason:'PREFERENCE_DISABLED',scope,key,channel};return {allowed:true,reason:'TRANSACTIONAL_ALLOWED',scope,key,channel};}
export async function resolveBulkConsent(customerId:string,requests:Array<{scope:PreferenceScope;channel:Channel;key?:string}>){const out=[];for(const request of requests)out.push(await resolveConsent(customerId,request.scope,request.channel,request.key));return out;}
export async function marketingEligibility(customerId:string){const [profile,email,sms,wa]=await Promise.all([query(`select lifecycle,marketing_opt_in from trust_customer_profiles where id=$1`,[customerId]),resolveConsent(customerId,'MARKETING','EMAIL'),resolveConsent(customerId,'MARKETING','SMS'),resolveConsent(customerId,'MARKETING','WHATSAPP')]);return {eligible:Boolean(profile.rows[0]?.lifecycle==='ACTIVE'&&profile.rows[0]?.marketing_opt_in&&email.allowed),channels:{email:email.allowed,sms:sms.allowed,whatsapp:wa.allowed}};}
export async function personalizationEligibility(customerId:string){const r=await query(`select lifecycle,personalization_opt_in from trust_customer_profiles where id=$1`,[customerId]);if(!r.rows[0]||r.rows[0].lifecycle!=='ACTIVE')return {eligible:false,reason:'PROFILE_DELETED'};if(!r.rows[0].personalization_opt_in)return {eligible:false,reason:'PREFERENCE_DISABLED'};const p=await resolveConsent(customerId,'PERSONALIZATION','IN_APP','recommendations');return {eligible:p.allowed,reason:p.reason};}
export async function analyticsEligibility(customerId:string){const r=await resolveConsent(customerId,'ANALYTICS','IN_APP','product_analytics');return {eligible:r.allowed,reason:r.reason};}
