import { query } from '../platform/db/postgres';
import { getProfile,listAddresses } from './profile';
import { listWishlists } from './wishlist';
import { listSavedCarts } from './saved-carts';
import { listCustomerReviews } from './reviews';
import { listPreferences } from './preferences';
import { listPrivacyJobs } from './privacy';
import type { CustomerDashboard } from './contracts';
export async function listTimeline(customerId:string,limit=100,cursor?:string){const safe=Math.min(Math.max(Math.floor(limit),1),200);const params=[customerId];let where='customer_id=$1';if(cursor){params.push(cursor);where+=' and occurred_at < $2::timestamptz'}const r=await query(`select id,customer_id as "customerId",kind,entity_type as "entityType",entity_id as "entityId",action,summary,occurred_at as "occurredAt",metadata from trust_customer_timeline where ${where} order by occurred_at desc,id desc limit ${safe}`,params);return r.rows;}
export async function customerDashboard(customerId:string):Promise<CustomerDashboard>{const [profile,addresses,wishlists,savedCarts,reviews,preferences,timeline,privacyJobs]=await Promise.all([getProfile(customerId),listAddresses(customerId),listWishlists(customerId),listSavedCarts(customerId),listCustomerReviews(customerId),listPreferences(customerId),listTimeline(customerId,100),listPrivacyJobs(customerId)]);if(!profile)throw new Error('PROFILE_NOT_FOUND');return {profile,addresses,wishlists,savedCarts,reviews:reviews.slice(0,20),preferences,timeline,privacyJobs};}
export async function customerOrderSnapshot(customerId:string){const orders=await query(`select o.id,o.status,o.total,o.currency,o.created_at as "createdAt",o.updated_at as "updatedAt",coalesce(json_agg(json_build_object('id',oi.id,'productId',oi.product_id,'quantity',oi.quantity,'unitPrice',oi.unit_price,'sellerOrderId',oi.seller_order_id)) filter(where oi.id is not null),'[]'::json) as items from trust_orders o left join trust_order_items oi on oi.order_id=o.id where o.customer_id=$1 group by o.id order by o.created_at desc limit 50`,[customerId]);return orders.rows;}
export async function customerSecuritySnapshot(customerId:string){const sessions=await query(`select id,created_at as "createdAt",expires_at as "expiresAt",revoked_at as "revokedAt" from auth_sessions where user_id=$1 order by created_at desc limit 20`,[customerId]);const activity=await query(`select action,entity_type as "entityType",entity_id as "entityId",created_at as "createdAt" from trust_customer_activity where customer_id=$1 and action like 'SECURITY_%' order by created_at desc limit 100`,[customerId]);return {sessions:sessions.rows,activity:activity.rows};}
