import { randomUUID, createHash } from 'node:crypto';
import { query, withPgTransaction } from '../platform/db/postgres';
import { appendAuditTrail, appendTimeline, normalizeOptionalText, normalizeText } from './helpers';
export type CustomerEventName='VIEWED_PRODUCT'|'SEARCHED'|'ADDED_TO_CART'|'REMOVED_FROM_CART'|'CHECKOUT_STARTED'|'CHECKOUT_COMPLETED'|'ORDER_VIEWED'|'SHIPMENT_VIEWED'|'RETURN_STARTED'|'RETURN_COMPLETED'|'REVIEW_VIEWED'|'REVIEW_SUBMITTED'|'SUPPORT_OPENED'|'SUPPORT_RESOLVED'|'PREFERENCE_CHANGED'|'WISHLIST_ADDED'|'WISHLIST_REMOVED';
export type CustomerEvent={id:string;customerId:string;name:CustomerEventName;entityType:string|null;entityId:string|null;properties:Record<string,unknown>;occurredAt:string;idempotencyKey:string|null;};
export const CUSTOMER_EVENTS:CustomerEventName[]=['VIEWED_PRODUCT','SEARCHED','ADDED_TO_CART','REMOVED_FROM_CART','CHECKOUT_STARTED','CHECKOUT_COMPLETED','ORDER_VIEWED','SHIPMENT_VIEWED','RETURN_STARTED','RETURN_COMPLETED','REVIEW_VIEWED','REVIEW_SUBMITTED','SUPPORT_OPENED','SUPPORT_RESOLVED','PREFERENCE_CHANGED','WISHLIST_ADDED','WISHLIST_REMOVED'];
export function validateEventName(name:string):name is CustomerEventName{return CUSTOMER_EVENTS.includes(name as CustomerEventName);}
export function eventFingerprint(customerId:string,name:string,entityId:string|null,properties:Record<string,unknown>,idempotencyKey:string|null){return createHash('sha256').update(JSON.stringify({customerId,name,entityId,properties,idempotencyKey})).digest('hex');}
export async function appendCustomerEvent(input:{customerId:string;name:CustomerEventName;entityType?:string;entityId?:string;properties?:Record<string,unknown>;idempotencyKey?:string}){if(!validateEventName(input.name))throw new Error('INVALID_CUSTOMER_EVENT');const fingerprint=eventFingerprint(input.customerId,input.name,input.entityId??null,input.properties??{},input.idempotencyKey??null);return withPgTransaction(async client=>{const r=await client.query(`insert into trust_customer_events(id,customer_id,name,entity_type,entity_id,properties,fingerprint,idempotency_key,occurred_at) values($1,$2,$3,$4,$5,$6::jsonb,$7,$8,now()) on conflict(fingerprint) do nothing returning id,customer_id as "customerId",name,entity_type as "entityType",entity_id as "entityId",properties,occurred_at as "occurredAt",idempotency_key as "idempotencyKey"`,[randomUUID(),input.customerId,input.name,input.entityType??null,input.entityId??null,JSON.stringify(input.properties??{}),fingerprint,input.idempotencyKey??null]);if(!r.rows[0]){const existing=await client.query(`select id,customer_id as "customerId",name,entity_type as "entityType",entity_id as "entityId",properties,occurred_at as "occurredAt",idempotency_key as "idempotencyKey" from trust_customer_events where fingerprint=$1`,[fingerprint]);return existing.rows[0];}await appendAuditTrail({customerId:input.customerId,action:'CUSTOMER_EVENT_APPENDED',entityType:input.entityType??'customer_event',entityId:input.entityId??r.rows[0].id,metadata:{name:input.name}},client);return r.rows[0];});}
export async function listCustomerEvents(customerId:string,limit=100){const safe=Math.min(Math.max(Math.floor(limit),1),500);const r=await query(`select id,name,entity_type as "entityType",entity_id as "entityId",properties,occurred_at as "occurredAt",idempotency_key as "idempotencyKey" from trust_customer_events where customer_id=$1 order by occurred_at desc,id desc limit ${safe}`,[customerId]);return r.rows;}
export async function eventCount(customerId:string,name?:CustomerEventName){if(name&&!validateEventName(name))throw new Error('INVALID_CUSTOMER_EVENT');const r=name?await query(`select count(*)::int as count from trust_customer_events where customer_id=$1 and name=$2`,[customerId,name]):await query(`select count(*)::int as count from trust_customer_events where customer_id=$1`,[customerId]);return Number(r.rows[0]?.count??0);}
export async function eventFunnel(customerIds:string[],names:CustomerEventName[]){if(!customerIds.length||!names.length)return [];names.forEach(n=>{if(!validateEventName(n))throw new Error('INVALID_CUSTOMER_EVENT')});const r=await query(`select name,count(distinct customer_id)::int as customers,count(*)::int as events from trust_customer_events where customer_id=any($1) and name=any($2) group by name order by array_position($2,name)`,[customerIds,names]);return r.rows;}
export async function purgeCustomerEvents(beforeDays=730){if(beforeDays<90)throw new Error('EVENT_RETENTION_TOO_SHORT');const r=await query(`delete from trust_customer_events where occurred_at<now()-($1||' days')::interval returning id`,[String(beforeDays)]);return {deleted:r.rowCount??0};}
