import { randomUUID } from 'node:crypto';
import { query, withPgTransaction } from '../platform/db/postgres';
import { appendAuditTrail, appendTimeline, normalizeText } from './helpers';
import { resolveConsent } from './consent';
export type JourneyStatus='DRAFT'|'ACTIVE'|'PAUSED'|'COMPLETED'|'CANCELLED';
export type JourneyTrigger='ORDER_CONFIRMED'|'ORDER_DELIVERED'|'RETURN_CREATED'|'SUPPORT_CREATED'|'INACTIVITY'|'REVIEW_SUBMITTED'|'MANUAL';
export interface JourneyStep{position:number;kind:'NOTIFY'|'TASK'|'WAIT'|'TAG';channel?:'EMAIL'|'SMS'|'WHATSAPP'|'PUSH'|'IN_APP';templateKey?:string;delayMinutes?:number;metadata?:Record<string,unknown>}
export async function listJourneys(){const r=await query(`select id,name,status,trigger,definition,created_at as "createdAt",updated_at as "updatedAt" from trust_customer_journeys order by updated_at desc`);return r.rows;}
export async function createJourney(input:{name:string;trigger:JourneyTrigger;steps:JourneyStep[]}){if(!input.steps.length)throw new Error('JOURNEY_STEPS_REQUIRED');const id=randomUUID();const steps=input.steps.map((s,i)=>({...s,position:i+1}));const r=await query(`insert into trust_customer_journeys(id,name,status,trigger,definition,created_at,updated_at) values($1,$2,'DRAFT',$3,$4::jsonb,now(),now()) returning id,name,status,trigger,definition`,[id,normalizeText(input.name,120),input.trigger,JSON.stringify({steps})]);return r.rows[0];}
export async function activateJourney(id:string){const r=await query(`update trust_customer_journeys set status='ACTIVE',updated_at=now() where id=$1 and status in ('DRAFT','PAUSED') returning id,status`);if(!r.rows[0])throw new Error('JOURNEY_NOT_ACTIVATABLE');return r.rows[0];}
export async function pauseJourney(id:string){const r=await query(`update trust_customer_journeys set status='PAUSED',updated_at=now() where id=$1 and status='ACTIVE' returning id,status`);if(!r.rows[0])throw new Error('JOURNEY_NOT_ACTIVE');return r.rows[0];}
export async function cancelJourney(id:string){return withPgTransaction(async client=>{const r=await client.query(`update trust_customer_journeys set status='CANCELLED',updated_at=now() where id=$1 and status not in ('COMPLETED','CANCELLED') returning id,status`,[id]);if(!r.rows[0])throw new Error('JOURNEY_NOT_CANCELLABLE');await client.query(`update trust_customer_journey_runs set status='CANCELLED',completed_at=now() where journey_id=$1 and status in ('QUEUED','RUNNING')`,[id]);return r.rows[0];});}
export async function enrollCustomer(customerId:string,journeyId:string,trigger:JourneyTrigger,context:Record<string,unknown>){return withPgTransaction(async client=>{const j=await client.query<{definition:any;status:string;trigger:JourneyTrigger}>(`select definition,status,trigger from trust_customer_journeys where id=$1 for update`,[journeyId]);if(!j.rows[0]||j.rows[0].status!=='ACTIVE')throw new Error('JOURNEY_NOT_ACTIVE');if(j.rows[0].trigger!==trigger)throw new Error('JOURNEY_TRIGGER_MISMATCH');const existing=await client.query(`select id,status from trust_customer_journey_runs where journey_id=$1 and customer_id=$2 and status in ('QUEUED','RUNNING') limit 1`,[journeyId,customerId]);if(existing.rows[0])return existing.rows[0];const id=randomUUID();const r=await client.query(`insert into trust_customer_journey_runs(id,journey_id,customer_id,status,current_position,context,started_at) values($1,$2,$3,'QUEUED',1,$4::jsonb,now()) returning id,status,current_position as "currentPosition"`,[id,journeyId,customerId,JSON.stringify(context)]);await appendTimeline({customerId,kind:'PROFILE',entityType:'journey_run',entityId:id,action:'JOURNEY_ENROLLED',summary:'Customer enrolled in journey',metadata:{journeyId,trigger}},client);return r.rows[0];});}
export async function advanceJourneyRun(runId:string){return withPgTransaction(async client=>{const run=await client.query<any>(`select r.id,r.customer_id as "customerId",r.status,r.current_position as "currentPosition",r.context,j.definition from trust_customer_journey_runs r join trust_customer_journeys j on j.id=r.journey_id where r.id=$1 for update`,[runId]);if(!run.rows[0])throw new Error('JOURNEY_RUN_NOT_FOUND');if(!['QUEUED','RUNNING'].includes(run.rows[0].status))return run.rows[0];const steps=run.rows[0].definition?.steps??[];const position=Number(run.rows[0].currentPosition);if(position>steps.length){await client.query(`update trust_customer_journey_runs set status='COMPLETED',completed_at=now() where id=$1`,[runId]);return {id:runId,status:'COMPLETED'};}const step=steps[position-1];if(step.channel&&step.kind==='NOTIFY'){const consent=await resolveConsent(run.rows[0].customerId,'TRANSACTIONAL',step.channel);if(!consent.allowed)throw new Error('JOURNEY_CHANNEL_NOT_ALLOWED');}await client.query(`insert into trust_customer_journey_steps(id,run_id,position,kind,status,payload,executed_at) values($1,$2,$3,$4,'COMPLETED',$5::jsonb,now())`,[randomUUID(),runId,position,step.kind,JSON.stringify(step)]);await client.query(`update trust_customer_journey_runs set status='RUNNING',current_position=current_position+1,updated_at=now() where id=$1`,[runId]);await appendAuditTrail({customerId:run.rows[0].customerId,action:'JOURNEY_STEP_COMPLETED',entityType:'journey_run',entityId:runId,metadata:{position,kind:step.kind}},client);return {id:runId,status:'RUNNING',completedPosition:position};});}
