import { randomUUID } from 'node:crypto';
import { query, withPgTransaction } from '../platform/db/postgres';
import { appendAuditTrail, appendTimeline, normalizeOptionalText, normalizeText, rating } from './helpers';

const blockedTerms=['spam','scam','http://','https://'];
export function moderateReview(body:string,title:string|null){const combined=`${title??''} ${body}`.toLowerCase();const matched=blockedTerms.filter(term=>combined.includes(term));if(matched.length)return {status:'REJECTED' as const,reason:'CONTENT_POLICY',matched};if(body.length<10)return {status:'REJECTED' as const,reason:'BODY_TOO_SHORT',matched:[]};return {status:'PENDING' as const,reason:null,matched:[]};}
export async function listProductReviews(productId:string,limit=50){const r=await query(`select r.id,r.customer_id as "customerId",r.product_id as "productId",r.order_id as "orderId",r.rating,r.title,r.body,r.status,r.source,r.verified_purchase as "verifiedPurchase",r.created_at as "createdAt",r.updated_at as "updatedAt" from trust_customer_reviews r where r.product_id=$1 and r.status='PUBLISHED' order by r.verified_purchase desc,r.created_at desc limit $2`,[productId,Math.min(Math.max(limit,1),100)]);return r.rows;}
export async function listCustomerReviews(customerId:string){const r=await query(`select id,customer_id as "customerId",product_id as "productId",order_id as "orderId",rating,title,body,status,source,verified_purchase as "verifiedPurchase",moderation_reason as "moderationReason",created_at as "createdAt",updated_at as "updatedAt" from trust_customer_reviews where customer_id=$1 order by created_at desc`,[customerId]);return r.rows;}
export async function submitReview(customerId:string,input:Record<string,unknown>){const productId=normalizeText(input.productId,120);const orderId=normalizeOptionalText(input.orderId,120);const title=normalizeOptionalText(input.title,160);const body=normalizeText(input.body,4000);const score=rating(input.rating);if(!productId||body.length<10)throw new Error('INVALID_REVIEW');const verified=orderId?await query(`select 1 from trust_orders o join trust_order_items oi on oi.order_id=o.id where o.id=$1 and o.customer_id=$2 and oi.product_id=$3 and o.status='delivered' limit 1`,[orderId,customerId,productId]):{rows:[]};const verifiedPurchase=Boolean(verified.rows[0]);if(orderId&&!verifiedPurchase)throw new Error('REVIEW_REQUIRES_DELIVERED_PURCHASE');const moderation=moderateReview(body,title);return withPgTransaction(async client=>{const duplicate=await client.query(`select id from trust_customer_reviews where customer_id=$1 and product_id=$2 and coalesce(order_id,'')=coalesce($3,'') and status<>'REMOVED'`,[customerId,productId,orderId]);if(duplicate.rows[0])throw new Error('REVIEW_ALREADY_EXISTS');const id=randomUUID();const r=await client.query(`insert into trust_customer_reviews(id,customer_id,product_id,order_id,rating,title,body,status,source,verified_purchase,moderation_reason,created_at,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8,'CUSTOMER_SUBMITTED',$9,$10,now(),now()) returning id,status,verified_purchase as "verifiedPurchase",created_at as "createdAt"`,[id,customerId,productId,orderId,score,title,body,moderation.status,verifiedPurchase,moderation.reason]);await appendTimeline({customerId,kind:'REVIEW',entityType:'customer_review',entityId:id,action:'REVIEW_SUBMITTED',summary:'Product review submitted',metadata:{productId,verifiedPurchase,status:moderation.status}},client);return r.rows[0];});}
export async function editReview(customerId:string,id:string,input:Record<string,unknown>){const title=normalizeOptionalText(input.title,160);const body=normalizeText(input.body,4000);const score=rating(input.rating);const moderation=moderateReview(body,title);const r=await query(`update trust_customer_reviews set title=$3,body=$4,rating=$5,status=$6,moderation_reason=$7,updated_at=now() where id=$1 and customer_id=$2 and status in ('PENDING','PUBLISHED') returning id,status`,[id,customerId,title,body,score,moderation.status,moderation.reason]);if(!r.rows[0])throw new Error('REVIEW_NOT_EDITABLE');await appendAuditTrail({customerId,action:'REVIEW_EDITED',entityType:'customer_review',entityId:id});return r.rows[0];}
export async function removeReview(customerId:string,id:string){const r=await query(`update trust_customer_reviews set status='REMOVED',updated_at=now() where id=$1 and customer_id=$2 and status<>'REMOVED' returning id`,[id,customerId]);if(!r.rows[0])throw new Error('REVIEW_NOT_FOUND');await appendTimeline({customerId,kind:'REVIEW',entityType:'customer_review',entityId:id,action:'REVIEW_REMOVED',summary:'Customer review removed'});return {removed:true,id};}
export async function moderateReviewByOperator(reviewId:string,decision:'PUBLISHED'|'REJECTED'|'REMOVED',reason?:string){if(!['PUBLISHED','REJECTED','REMOVED'].includes(decision))throw new Error('INVALID_MODERATION_DECISION');const r=await query(`update trust_customer_reviews set status=$2,moderation_reason=$3,updated_at=now() where id=$1 returning id,customer_id as "customerId",status`,[reviewId,decision,normalizeOptionalText(reason,500)]);if(!r.rows[0])throw new Error('REVIEW_NOT_FOUND');await appendTimeline({customerId:r.rows[0].customerId,kind:'REVIEW',entityType:'customer_review',entityId:reviewId,action:`REVIEW_${decision}`,summary:`Review moderated as ${decision}`});return r.rows[0];}
export async function reviewSummary(productId:string){const r=await query<{count:string;avg:string;verified:string}>(`select count(*)::text as count,coalesce(round(avg(rating)::numeric,2),0)::text as avg,count(*) filter(where verified_purchase)::text as verified from trust_customer_reviews where product_id=$1 and status='PUBLISHED'`,[productId]);return {count:Number(r.rows[0]?.count??0),average:Number(r.rows[0]?.avg??0),verifiedCount:Number(r.rows[0]?.verified??0)};}
