import { randomUUID } from 'node:crypto';
import { query, withPgTransaction } from '../platform/db/postgres';
import { appendTimeline, normalizeOptionalText, normalizeText, positiveInt } from './helpers';

export async function listSavedCarts(customerId:string){const r=await query(`select c.id,c.customer_id as "customerId",c.name,c.status,c.currency,c.created_at as "createdAt",c.updated_at as "updatedAt",c.expires_at as "expiresAt",count(i.id)::int as "itemCount" from trust_saved_carts c left join trust_saved_cart_items i on i.saved_cart_id=c.id where c.customer_id=$1 group by c.id order by c.updated_at desc`,[customerId]);return r.rows;}
export async function createSavedCart(customerId:string,input:Record<string,unknown>){const id=randomUUID();const name=normalizeText(input.name,100)||'Saved cart';const currency=normalizeText(input.currency,3).toUpperCase()||'EGP';const expiresAt=normalizeOptionalText(input.expiresAt,80);if(currency.length!==3)throw new Error('INVALID_CURRENCY');const r=await query(`insert into trust_saved_carts(id,customer_id,name,status,currency,expires_at,created_at,updated_at) values($1,$2,$3,'ACTIVE',$4,$5::timestamptz,now(),now()) returning id,customer_id as "customerId",name,status,currency,created_at as "createdAt",updated_at as "updatedAt",expires_at as "expiresAt"`,[id,customerId,name,currency,expiresAt]);await appendTimeline({customerId,kind:'PROFILE',entityType:'saved_cart',entityId:id,action:'SAVED_CART_CREATED',summary:'Saved cart created'});return r.rows[0];}
export async function getSavedCart(customerId:string,id:string){const r=await query(`select id,customer_id as "customerId",name,status,currency,created_at as "createdAt",updated_at as "updatedAt",expires_at as "expiresAt" from trust_saved_carts where id=$1 and customer_id=$2`,[id,customerId]);if(!r.rows[0])throw new Error('SAVED_CART_NOT_FOUND');const items=await query(`select id,saved_cart_id as "savedCartId",product_id as "productId",variant_id as "variantId",quantity,unit_price_cents as "unitPriceCents",currency,added_at as "addedAt" from trust_saved_cart_items where saved_cart_id=$1 order by added_at`,[id]);return {...r.rows[0],items:items.rows};}
export async function addSavedCartItem(customerId:string,cartId:string,input:Record<string,unknown>){const productId=normalizeText(input.productId,120);const variantId=normalizeOptionalText(input.variantId,120);const quantity=positiveInt(input.quantity,1,100);const unitPriceCents=positiveInt(input.unitPriceCents,0,100000000);const currency=normalizeText(input.currency,3).toUpperCase();if(!productId||currency.length!==3)throw new Error('INVALID_CART_ITEM');return withPgTransaction(async client=>{const cart=await client.query<{currency:string;status:string}>(`select currency,status from trust_saved_carts where id=$1 and customer_id=$2 for update`,[cartId,customerId]);if(!cart.rows[0])throw new Error('SAVED_CART_NOT_FOUND');if(cart.rows[0].status!=='ACTIVE')throw new Error('SAVED_CART_NOT_ACTIVE');if(cart.rows[0].currency!==currency)throw new Error('CURRENCY_MISMATCH');const id=randomUUID();const r=await client.query(`insert into trust_saved_cart_items(id,saved_cart_id,product_id,variant_id,quantity,unit_price_cents,currency,added_at) values($1,$2,$3,$4,$5,$6,$7,now()) on conflict(saved_cart_id,product_id,coalesce(variant_id,'')) do update set quantity=least(trust_saved_cart_items.quantity+excluded.quantity,100),unit_price_cents=excluded.unit_price_cents returning id,saved_cart_id as "savedCartId",product_id as "productId",variant_id as "variantId",quantity,unit_price_cents as "unitPriceCents",currency,added_at as "addedAt"`,[id,cartId,productId,variantId,quantity,unitPriceCents,currency]);await client.query(`update trust_saved_carts set updated_at=now() where id=$1`,[cartId]);return r.rows[0];});}
export async function removeSavedCartItem(customerId:string,cartId:string,itemId:string){const r=await query(`delete from trust_saved_cart_items i using trust_saved_carts c where i.id=$1 and i.saved_cart_id=c.id and c.id=$2 and c.customer_id=$3 returning i.id`,[itemId,cartId,customerId]);if(!r.rows[0])throw new Error('SAVED_CART_ITEM_NOT_FOUND');await query(`update trust_saved_carts set updated_at=now() where id=$1`,[cartId]);return {deleted:true,id:itemId};}
export async function markSavedCartStatus(customerId:string,id:string,status:string){if(!['ACTIVE','CHECKED_OUT','ABANDONED','EXPIRED'].includes(status))throw new Error('INVALID_SAVED_CART_STATUS');const r=await query(`update trust_saved_carts set status=$3,updated_at=now() where id=$1 and customer_id=$2 returning id,status`,[id,customerId,status]);if(!r.rows[0])throw new Error('SAVED_CART_NOT_FOUND');await appendTimeline({customerId,kind:'PROFILE',entityType:'saved_cart',entityId:id,action:`SAVED_CART_${status}`,summary:`Saved cart status changed to ${status}`});return r.rows[0];}
export async function purgeExpiredSavedCarts(){const r=await query(`update trust_saved_carts set status='EXPIRED',updated_at=now() where status='ACTIVE' and expires_at is not null and expires_at<=now() returning id,customer_id as "customerId"`);for(const row of r.rows)await appendTimeline({customerId:row.customerId,kind:'PROFILE',entityType:'saved_cart',entityId:row.id,action:'SAVED_CART_EXPIRED',summary:'Saved cart expired'});return r.rowCount??0;}
