import { query, withPgTransaction } from '../platform/db/postgres';
import { randomUUID } from 'node:crypto';
import { appendAuditTrail, appendTimeline, positiveInt } from './helpers';
export type SegmentOperator='EQ'|'NEQ'|'GT'|'GTE'|'LT'|'LTE'|'IN'|'NOT_IN'|'EXISTS';
export type SegmentRule={field:string;operator:SegmentOperator;value:unknown};
export type SegmentDefinition={id:string;name:string;priority:number;enabled:boolean;rules:SegmentRule[]};
export const SEGMENT_FIELDS=['orderCount','lifetimeValue','averageOrderValue','daysSinceLastOrder','openOrderCount','returnedOrderCount','reviewCount','wishlistItemCount','savedCartValue','supportOpenCount','preferenceCount'];
export function compareRule(actual:unknown,operator:SegmentOperator,expected:unknown):boolean{switch(operator){case'EQ':return actual===expected;case'NEQ':return actual!==expected;case'GT':return Number(actual)>Number(expected);case'GTE':return Number(actual)>=Number(expected);case'LT':return Number(actual)<Number(expected);case'LTE':return Number(actual)<=Number(expected);case'IN':return Array.isArray(expected)&&expected.includes(actual);case'NOT_IN':return Array.isArray(expected)&&!expected.includes(actual);case'EXISTS':return actual!==null&&actual!==undefined;default:return false;}}
export function validateRule(rule:SegmentRule){if(!SEGMENT_FIELDS.includes(rule.field))throw new Error('INVALID_SEGMENT_FIELD');if(!['EQ','NEQ','GT','GTE','LT','LTE','IN','NOT_IN','EXISTS'].includes(rule.operator))throw new Error('INVALID_SEGMENT_OPERATOR');if(['IN','NOT_IN'].includes(rule.operator)&&!Array.isArray(rule.value))throw new Error('SEGMENT_ARRAY_REQUIRED');return true;}
export function evaluateSegment(definition:SegmentDefinition,metrics:Record<string,unknown>){if(!definition.enabled)return false;if(definition.rules.length===0)return false;return definition.rules.every(rule=>{validateRule(rule);return compareRule(metrics[rule.field],rule.operator,rule.value);});}
export function scoreSegment(definition:SegmentDefinition,metrics:Record<string,unknown>){const matched=definition.rules.filter(rule=>{validateRule(rule);return compareRule(metrics[rule.field],rule.operator,rule.value)}).length;return definition.rules.length?Math.round(matched/definition.rules.length*100):0;}
export async function listSegments(){const r=await query(`select id,name,priority,enabled,rules,created_at as "createdAt",updated_at as "updatedAt" from trust_customer_segments order by priority desc,name`);return r.rows;}
export async function getSegment(id:string){const r=await query(`select id,name,priority,enabled,rules,created_at as "createdAt",updated_at as "updatedAt" from trust_customer_segments where id=$1`,[id]);if(!r.rows[0])throw new Error('SEGMENT_NOT_FOUND');return r.rows[0];}
export async function createSegment(input:{name:string;priority?:number;enabled?:boolean;rules:SegmentRule[]}){if(!input.rules.length)throw new Error('SEGMENT_RULES_REQUIRED');input.rules.forEach(validateRule);const id=randomUUID();const r=await query(`insert into trust_customer_segments(id,name,priority,enabled,rules,created_at,updated_at) values($1,$2,$3,$4,$5::jsonb,now(),now()) returning id,name,priority,enabled,rules`,[id,input.name.trim().slice(0,120),positiveInt(input.priority,1,1000),input.enabled??true,JSON.stringify(input.rules)]);return r.rows[0];}
export async function updateSegment(id:string,input:Partial<SegmentDefinition>){const current=await getSegment(id);const rules=input.rules??current.rules;if(!Array.isArray(rules)||!rules.length)throw new Error('SEGMENT_RULES_REQUIRED');rules.forEach(validateRule);const r=await query(`update trust_customer_segments set name=$2,priority=$3,enabled=$4,rules=$5::jsonb,updated_at=now() where id=$1 returning id,name,priority,enabled,rules`,[id,String(input.name??current.name).trim().slice(0,120),positiveInt(input.priority??current.priority,1,1000),input.enabled??current.enabled,JSON.stringify(rules)]);return r.rows[0];}
export async function deleteSegment(id:string){const r=await query(`delete from trust_customer_segments where id=$1 returning id`,[id]);if(!r.rows[0])throw new Error('SEGMENT_NOT_FOUND');await query(`delete from trust_customer_segment_members where segment_id=$1`,[id]);return {deleted:true,id};}
export async function assignSegment(customerId:string,segmentId:string,score:number,metrics:Record<string,unknown>){return withPgTransaction(async client=>{const seg=await client.query(`select id from trust_customer_segments where id=$1 and enabled for update`,[segmentId]);if(!seg.rows[0])throw new Error('SEGMENT_NOT_ACTIVE');const r=await client.query(`insert into trust_customer_segment_members(segment_id,customer_id,score,metrics,evaluated_at) values($1,$2,$3,$4::jsonb,now()) on conflict(segment_id,customer_id) do update set score=excluded.score,metrics=excluded.metrics,evaluated_at=now() returning segment_id as "segmentId",customer_id as "customerId",score,evaluated_at as "evaluatedAt"`,[segmentId,customerId,score,JSON.stringify(metrics)]);await appendTimeline({customerId,kind:'PROFILE',entityType:'customer_segment',entityId:segmentId,action:'SEGMENT_ASSIGNED',summary:'Customer segment assignment evaluated',metadata:{score}},client);return r.rows[0];});}
export async function removeSegmentMembership(customerId:string,segmentId:string){const r=await query(`delete from trust_customer_segment_members where customer_id=$1 and segment_id=$2 returning segment_id as "segmentId"`,[customerId,segmentId]);return {removed:Boolean(r.rows[0]),customerId,segmentId};}
export async function listCustomerSegments(customerId:string){const r=await query(`select m.segment_id as "segmentId",s.name,s.priority,m.score,m.evaluated_at as "evaluatedAt" from trust_customer_segment_members m join trust_customer_segments s on s.id=m.segment_id where m.customer_id=$1 and s.enabled order by s.priority desc,m.score desc`,[customerId]);return r.rows;}
export async function segmentHealth(){const [segments,members,stale]=await Promise.all([query(`select count(*)::int as count from trust_customer_segments where enabled`),query(`select count(*)::int as count from trust_customer_segment_members`),query(`select count(*)::int as count from trust_customer_segment_members where evaluated_at<now()-interval '24 hours'`)]);return {enabledSegments:segments.rows[0].count,totalMemberships:members.rows[0].count,staleMemberships:stale.rows[0].count};}
