import { randomUUID } from 'node:crypto';
import { query, withPgTransaction } from '../platform/db/postgres';
import { appendAuditTrail, appendTimeline, normalizeOptionalText, normalizeText, positiveInt } from './helpers';
import type { Wishlist, WishlistItem } from './contracts';

export async function listWishlists(customerId:string){const r=await query(`select w.id,w.customer_id as "customerId",w.name,w.visibility,w.created_at as "createdAt",w.updated_at as "updatedAt",count(i.id)::int as "itemCount" from trust_wishlists w left join trust_wishlist_items i on i.wishlist_id=w.id where w.customer_id=$1 group by w.id order by w.created_at desc`,[customerId]);return r.rows;}
export async function getWishlist(customerId:string,id:string){const r=await query(`select id,customer_id as "customerId",name,visibility,created_at as "createdAt",updated_at as "updatedAt" from trust_wishlists where id=$1 and customer_id=$2`,[id,customerId]);if(!r.rows[0])throw new Error('WISHLIST_NOT_FOUND');const items=await query(`select id,wishlist_id as "wishlistId",product_id as "productId",variant_id as "variantId",note,priority,added_at as "addedAt" from trust_wishlist_items where wishlist_id=$1 order by priority desc,added_at desc`,[id]);return {...r.rows[0],items:items.rows};}
export async function createWishlist(customerId:string,input:Record<string,unknown>){const id=randomUUID();const name=normalizeText(input.name,80)||'My Wishlist';const visibility=String(input.visibility??'PRIVATE');if(!['PRIVATE','SHARED'].includes(visibility))throw new Error('INVALID_VISIBILITY');const r=await query(`insert into trust_wishlists(id,customer_id,name,visibility,created_at,updated_at) values($1,$2,$3,$4,now(),now()) returning id,customer_id as "customerId",name,visibility,created_at as "createdAt",updated_at as "updatedAt"`,[id,customerId,name,visibility]);await appendTimeline({customerId,kind:'PROFILE',entityType:'wishlist',entityId:id,action:'WISHLIST_CREATED',summary:'Wishlist created'});return r.rows[0];}
export async function renameWishlist(customerId:string,id:string,nameInput:unknown){const name=normalizeText(nameInput,80);if(!name)throw new Error('WISHLIST_NAME_REQUIRED');const r=await query(`update trust_wishlists set name=$3,updated_at=now() where id=$1 and customer_id=$2 returning id,name,visibility`,[id,customerId,name]);if(!r.rows[0])throw new Error('WISHLIST_NOT_FOUND');return r.rows[0];}
export async function deleteWishlist(customerId:string,id:string){const r=await query(`delete from trust_wishlists where id=$1 and customer_id=$2 returning id`,[id,customerId]);if(!r.rows[0])throw new Error('WISHLIST_NOT_FOUND');await appendTimeline({customerId,kind:'PROFILE',entityType:'wishlist',entityId:id,action:'WISHLIST_DELETED',summary:'Wishlist deleted'});return {deleted:true,id};}
export async function addWishlistItem(customerId:string,wishlistId:string,input:Record<string,unknown>){const productId=normalizeText(input.productId,120);if(!productId)throw new Error('PRODUCT_ID_REQUIRED');const variantId=normalizeOptionalText(input.variantId,120);const note=normalizeOptionalText(input.note,300);const priority=positiveInt(input.priority,1,100);return withPgTransaction(async client=>{const owner=await client.query(`select id from trust_wishlists where id=$1 and customer_id=$2 for update`,[wishlistId,customerId]);if(!owner.rows[0])throw new Error('WISHLIST_NOT_FOUND');const count=await client.query<{count:string}>(`select count(*)::text as count from trust_wishlist_items where wishlist_id=$1`,[wishlistId]);if(Number(count.rows[0]?.count??0)>=500)throw new Error('WISHLIST_LIMIT_REACHED');const id=randomUUID();const r=await client.query(`insert into trust_wishlist_items(id,wishlist_id,product_id,variant_id,note,priority,added_at) values($1,$2,$3,$4,$5,$6,now()) on conflict(wishlist_id,product_id,coalesce(variant_id,'')) do update set note=excluded.note,priority=excluded.priority returning id,wishlist_id as "wishlistId",product_id as "productId",variant_id as "variantId",note,priority,added_at as "addedAt"`,[id,wishlistId,productId,variantId,note,priority]);await appendAuditTrail({customerId,action:'WISHLIST_ITEM_ADDED',entityType:'wishlist_item',entityId:id,metadata:{wishlistId,productId,variantId}},client);return r.rows[0];});}
export async function removeWishlistItem(customerId:string,wishlistId:string,itemId:string){return withPgTransaction(async client=>{const r=await client.query(`delete from trust_wishlist_items i using trust_wishlists w where i.id=$1 and i.wishlist_id=w.id and w.id=$2 and w.customer_id=$3 returning i.id`,[itemId,wishlistId,customerId]);if(!r.rows[0])throw new Error('WISHLIST_ITEM_NOT_FOUND');await appendTimeline({customerId,kind:'PROFILE',entityType:'wishlist_item',entityId:itemId,action:'WISHLIST_ITEM_REMOVED',summary:'Wishlist item removed'},client);return {deleted:true,id:itemId};});}
export async function moveWishlistItem(customerId:string,fromId:string,toId:string,itemId:string){return withPgTransaction(async client=>{const check=await client.query(`select i.id from trust_wishlist_items i join trust_wishlists w on w.id=i.wishlist_id where i.id=$1 and i.wishlist_id=$2 and w.customer_id=$3 for update`,[itemId,fromId,customerId]);if(!check.rows[0])throw new Error('WISHLIST_ITEM_NOT_FOUND');const target=await client.query(`select id from trust_wishlists where id=$1 and customer_id=$2`,[toId,customerId]);if(!target.rows[0])throw new Error('TARGET_WISHLIST_NOT_FOUND');const r=await client.query(`update trust_wishlist_items set wishlist_id=$2 where id=$1 returning id`,[itemId,toId]);await appendAuditTrail({customerId,action:'WISHLIST_ITEM_MOVED',entityType:'wishlist_item',entityId:itemId,metadata:{fromId,toId}},client);return r.rows[0];});}
