import {NextRequest,NextResponse} from 'next/server';
import {query} from '../../../modules/platform/db/postgres';
import {getCurrentUser} from '../../../modules/platform/auth/current-user';
import {loadGuardianOverview} from '../../../modules/commerce/purchase-guardian';
import {approveGuardianAction,planGuardianActions,persistGuardianPlan} from '../../../modules/platform/purchase-guardian-agent';
import {executeApprovedAction} from '../../../modules/platform/purchase-guardian-execution';
export const dynamic='force-dynamic';export const runtime='nodejs';
export async function GET(request:NextRequest){const user=await getCurrentUser(request);if(!user||user.role!=='customer')return NextResponse.json({ok:false,error:'AUTH_REQUIRED'},{status:401});try{const overview=await loadGuardianOverview({query} as any,user.id);const actions=await query(`select id,order_id,action_type,risk,confidence,reversible,status,reason,created_at,approved_at,executed_at from trust_purchase_guardian_actions where customer_id=$1 order by created_at desc limit 100`,[user.id]);return NextResponse.json({ok:true,overview,actions:actions.rows},{headers:{'Cache-Control':'no-store'}})}catch(e){return NextResponse.json({ok:false,error:e instanceof Error?e.message:'GUARDIAN_UNAVAILABLE'},{status:400});}}
export async function POST(request:NextRequest){const user=await getCurrentUser(request);if(!user||user.role!=='customer')return NextResponse.json({ok:false,error:'AUTH_REQUIRED'},{status:401});try{const body=await request.json();if(body?.operation==='plan'){const overview=await loadGuardianOverview({query} as any,user.id);const plan=planGuardianActions(user.id,overview.purchases);const count=await persistGuardianPlan({query} as any,plan);return NextResponse.json({ok:true,policyVersion:plan.policyVersion,created:count,actions:plan.actions});}if(body?.operation==='approve'&&typeof body.actionId==='string'){return NextResponse.json({ok:true,action:await approveGuardianAction({query} as any,user.id,body.actionId)});}
if(body?.operation==='execute'&&typeof body.actionId==='string'){return NextResponse.json({ok:true,result:await executeApprovedAction({query} as any,{actionId:body.actionId,customerId:user.id})});}return NextResponse.json({ok:false,error:'INVALID_OPERATION'},{status:400});}catch(e){return NextResponse.json({ok:false,error:e instanceof Error?e.message:'GUARDIAN_AGENT_UNAVAILABLE'},{status:400});}}
