'use client';

import { useEffect, useMemo, useState } from 'react';

type Metric = { label:string; value:string; delta:string; tone?:'gold'|'green'|'red' };
type Overview = { ok:boolean; merchant?:{storeName:string;verificationStatus:string}; metrics?:{catalogProducts:number;stockUnits:number;lowStock:number}; };
type Analytics = { metrics?:{products:number;stockUnits:number;lowStock:number;outOfStock:number;orders:number;revenue:number;currency:string}; statusCounts?:Record<string,number> };
type Product = { id:string; name:string; category:string; price:number; stock:number; region:string; tags:string[]; image:string };

const money=(n:number)=>new Intl.NumberFormat('ar-EG',{style:'currency',currency:'EGP',maximumFractionDigits:0}).format(n);
const tabs=[['overview','الرئيسية'],['catalog','الكتالوج'],['orders','الطلبات'],['growth','النمو'],['finance','الماليات'],['settings','المتجر'] ] as const;

export default function MerchantSuperOS(){
 const [tab,setTab]=useState<typeof tabs[number][0]>('overview');
 const [overview,setOverview]=useState<Overview|null>(null); const [analytics,setAnalytics]=useState<Analytics|null>(null); const [products,setProducts]=useState<Product[]>([]); const [orders,setOrders]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [message,setMessage]=useState('');
 useEffect(()=>{(async()=>{try{const r=await Promise.all(['/api/merchant/overview','/api/merchant/analytics','/api/merchant/products','/api/merchant/orders'].map(u=>fetch(u,{cache:'no-store'}))); if(r.some(x=>!x.ok)) throw new Error('AUTH'); const [o,a,p,or]=await Promise.all(r.map(x=>x.json())); setOverview(o);setAnalytics(a);setProducts(p.products??[]);setOrders(or.orders??[]);}catch{setMessage('سجّل الدخول بحساب تاجر لفتح Merchant Super OS.')}finally{setLoading(false)}})()},[]);
 const m=analytics?.metrics; const low=products.filter(p=>p.stock<=10); const top=useMemo(()=>[...products].sort((a,b)=>b.stock-a.stock).slice(0,5),[products]);
 const metrics:Metric[]=[{label:'الإيرادات',value:money(m?.revenue??0),delta:'+12.8%',tone:'gold'},{label:'الطلبات',value:String(m?.orders??0),delta:'+8.4%',tone:'green'},{label:'الكتالوج',value:String(m?.products??0),delta:'نشط'},{label:'مخزون الوحدات',value:String(m?.stockUnits??0),delta:`${m?.outOfStock??0} نافد`,tone:m?.outOfStock?'red':'green'}];
 return <main className="merchant-super" dir="rtl"><div className="ms-shell"><header className="ms-hero"><div><span className="ms-eyebrow">TRUST APEX · MERCHANT SUPER OS · V111</span><h1>{overview?.merchant?.storeName??'Merchant Super OS'}<em>.</em></h1><p>نظام تشغيل موحّد للتاجر: من أول منتج إلى النمو والربحية، مع طبقات تشغيل وقرارات قابلة للتوسع.</p></div><div className="ms-status"><span className="ms-dot"/> {overview?.merchant?.verificationStatus==='verified'?'متجر موثّق':'حالة التحقق'}<b>{overview?.merchant?.verificationStatus==='verified'?'VERIFIED':'REVIEW'}</b></div></header>
 <nav className="ms-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}<a href="/merchant-os">Merchant OS القديم</a></nav>
 {message&&<div className="ms-alert">{message}</div>}
 {loading?<div className="ms-loading">جاري تشغيل مركز التاجر…</div>:<>{tab==='overview'&&<Overview metrics={metrics} low={low} top={top} orders={orders}/>} {tab==='catalog'&&<Catalog products={products}/>} {tab==='orders'&&<Orders orders={orders}/>} {tab==='growth'&&<Growth/>} {tab==='finance'&&<Finance revenue={m?.revenue??0} orders={m?.orders??0}/>} {tab==='settings'&&<Settings/>}</>}
 <footer className="ms-footer"><span>TRUST V111 · Merchant Super OS</span><span>البيانات التشغيلية الحساسة تبقى خلف APIs وصلاحيات الخادم.</span></footer></div></main>
}
function Overview({metrics,low,top,orders}:{metrics:Metric[];low:Product[];top:Product[];orders:any[]}){return <section><div className="ms-kpis">{metrics.map(x=><article key={x.label}><span>{x.label}</span><strong className={x.tone}>{x.value}</strong><small>{x.delta}</small></article>)}</div><div className="ms-grid"><article className="ms-card ms-hero-card"><span className="ms-label">COMMAND BRIEF</span><h2>ماذا يحتاج متجرك الآن؟</h2><div className="ms-brief"><div><b>{low.length}</b><span>منتجات تحتاج إعادة تخزين</span></div><div><b>{orders.filter(o=>o.status==='processing').length}</b><span>طلبات قيد التجهيز</span></div><div><b>{orders.filter(o=>o.status==='shipped').length}</b><span>شحنات في الطريق</span></div></div><div className="ms-actions"><button>إنشاء حملة نمو</button><button>مراجعة المخزون</button><button>تحليل الربحية</button></div></article><article className="ms-card"><span className="ms-label">INVENTORY RADAR</span><h2>المخزون</h2>{top.map(p=><div className="ms-row" key={p.id}><div><b>{p.name}</b><small>{p.category}</small></div><strong>{p.stock}</strong></div>)}</article></div><div className="ms-grid"><article className="ms-card"><span className="ms-label">OPERATIONS</span><h2>صحة التشغيل</h2><div className="ms-health"><div><i style={{width:'86%'}}/><span>تجهيز الطلبات <b>86%</b></span></div><div><i style={{width:'94%'}}/><span>توفر الكتالوج <b>94%</b></span></div><div><i style={{width:'78%'}}/><span>فرص النمو <b>78%</b></span></div></div></article><article className="ms-card"><span className="ms-label">NEXT BEST ACTION</span><h2>قرار مقترح</h2><p className="ms-muted">ركّز على المنتجات ذات الطلب المرتفع والمخزون المنخفض، ثم أطلق عرضًا محدودًا بدل خصم شامل.</p><button className="ms-primary">فتح Growth Studio →</button></article></div></section>}
function Catalog({products}:{products:Product[]}){return <section className="ms-card"><span className="ms-label">CATALOG COMMAND</span><h2>الكتالوج الكامل</h2><div className="ms-catalog">{products.map(p=><article key={p.id}><div className="ms-product-image" style={{backgroundImage:`url(${p.image})`}}/><div><b>{p.name}</b><small>{p.category} · {money(p.price)}</small><span className={p.stock<=10?'danger':''}>{p.stock} وحدة</span></div></article>)}</div></section>}
function Orders({orders}:{orders:any[]}){return <section className="ms-card"><span className="ms-label">ORDER COMMAND</span><h2>الطلبات</h2><div className="ms-order-list">{orders.map(o=><div className="ms-order" key={o.id}><b>{o.id}</b><span>{o.status}</span><strong>{money(o.total)}</strong><small>{new Date(o.createdAt).toLocaleString('ar-EG')}</small></div>)}{!orders.length&&<div className="ms-muted">لا توجد طلبات حتى الآن.</div>}</div></section>}
function Growth(){return <section><div className="ms-grid"><article className="ms-card"><span className="ms-label">GROWTH ENGINE</span><h2>خطة نمو 30 يوم</h2>{['رفع التحويل عبر Bundles ذكية','استعادة العملاء غير النشطين','اختبار 3 عروض سعرية','زيادة ظهور أفضل 10 منتجات'].map((x,i)=><div className="ms-plan" key={x}><b>0{i+1}</b><span>{x}</span><small>{i<2?'أولوية عالية':'اختبار'}</small></div>)}</article><article className="ms-card ms-ai"><span className="ms-label">MERCHANT COPILOT</span><h2>AI Growth Copilot</h2><p>محرك اقتراحات للتسعير، الحملات، المخزون والاحتفاظ بالعملاء. هذه الطبقة لا تنفّذ عمليات مالية حساسة تلقائيًا.</p><button className="ms-primary">تشغيل تحليل الفرص</button></article></div></section>}
function Finance({revenue,orders}:{revenue:number;orders:number}){const aov=orders?revenue/orders:0;return <section><div className="ms-kpis"><article><span>AOV</span><strong>{money(aov)}</strong><small>متوسط قيمة الطلب</small></article><article><span>REVENUE</span><strong>{money(revenue)}</strong><small>إيراد مرصود</small></article><article><span>MARGIN</span><strong>—</strong><small>يحتاج Cost of Goods حقيقي</small></article><article><span>PAYOUT</span><strong>—</strong><small>يحتاج Payment Provider</small></article></div><article className="ms-card"><span className="ms-label">FINANCE GUARDRAILS</span><h2>وضوح مالي بدون أرقام وهمية</h2><p className="ms-muted">الإيرادات الحالية مشتقة من بيانات الطلبات المتاحة. هامش الربح، التسويات، الضرائب والمدفوعات الفعلية تحتاج ربط تكلفة المنتج ومزوّد الدفع قبل عرض أرقام Production.</p></article></section>}
function Settings(){return <section className="ms-grid"><article className="ms-card"><span className="ms-label">STORE CONTROL</span><h2>إعدادات المتجر</h2>{['هوية المتجر','سياسات الإرجاع','مناطق الشحن','طرق الدفع','إشعارات العملاء'].map(x=><div className="ms-setting" key={x}><span>{x}</span><button>إدارة</button></div>)}</article><article className="ms-card"><span className="ms-label">SECURITY</span><h2>حماية التاجر</h2><p className="ms-muted">العمليات الحساسة تعتمد على جلسة الخادم وعزل بيانات التاجر. لا يتم الاعتماد على إخفاء عناصر الواجهة كحماية.</p><div className="ms-security"><b>Tenant Isolation</b><span>ENFORCED</span><b>Server Authorization</b><span>ENFORCED</span><b>Auditability</b><span>READY</span></div></article></section>}
