import { NextRequest, NextResponse } from 'next/server';
import { getCurrentUser } from '../../../../modules/platform/auth/current-user';
import { query, withPgTransaction } from '../../../../modules/platform/db/postgres';
import { createReplacement, getReplacement, listCustomerReplacements, listOperationsReplacements, transitionReplacement, cancelReplacement } from '../../../../modules/commerce/reverse-commerce';
import type { ReplacementStatus } from '../../../../modules/commerce/reverse-commerce';
export const dynamic='force-dynamic'; export const runtime='nodejs';
const privileged=(role:string)=>['admin','operations','support'].includes(role);
const response=(body:unknown,status=200)=>NextResponse.json(body,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(req:NextRequest){const u=await getCurrentUser(req);if(!u)return response({ok:false,error:'AUTH_REQUIRED'},401);try{const id=req.nextUrl.searchParams.get('id');const status=req.nextUrl.searchParams.get('status') as ReplacementStatus|null;if(id){const item=await getReplacement({query,transaction:withPgTransaction},{replacementOrderId:id,customerId:u.id,privileged:privileged(u.role)});return item?response({ok:true,replacement:item,surfaceStatus:'LIVE'}):response({ok:false,error:'REPLACEMENT_NOT_FOUND'},404);}const replacements=privileged(u.role)?await listOperationsReplacements({query,transaction:withPgTransaction},status||undefined,Number(req.nextUrl.searchParams.get('limit')||100)):await listCustomerReplacements({query,transaction:withPgTransaction},u.id,Number(req.nextUrl.searchParams.get('limit')||50));return response({ok:true,replacements,surfaceStatus:'LIVE'});}catch(e){return response({ok:false,error:e instanceof Error?e.message:'REPLACEMENT_LIST_FAILED'},500);}}
export async function POST(req:NextRequest){const u=await getCurrentUser(req);if(!u)return response({ok:false,error:'AUTH_REQUIRED'},401);const key=req.headers.get('idempotency-key')?.trim();if(!key)return response({ok:false,error:'IDEMPOTENCY_KEY_REQUIRED'},400);try{const b=await req.json();const result=await createReplacement({query,transaction:withPgTransaction},{...b,customerId:u.id,idempotencyKey:key});return response({ok:true,replacement:result,surfaceStatus:'LIVE'},201);}catch(e){const c=e instanceof Error?e.message:'REPLACEMENT_CREATE_FAILED';return response({ok:false,error:c,surfaceStatus:'ERROR'},c.includes('NOT_FOUND')?404:c.startsWith('INVALID_')?400:409);}}
export async function PATCH(req:NextRequest){const u=await getCurrentUser(req);if(!u)return response({ok:false,error:'AUTH_REQUIRED'},401);if(!privileged(u.role))return response({ok:false,error:'FORBIDDEN'},403);const key=req.headers.get('idempotency-key')?.trim();try{const b=await req.json();if(b.action==='cancel'){if(!key)return response({ok:false,error:'IDEMPOTENCY_KEY_REQUIRED'},400);return response({ok:true,result:await cancelReplacement({query,transaction:withPgTransaction},{replacementOrderId:String(b.replacementOrderId||''),actorId:u.id,reason:String(b.reason||''),idempotencyKey:key}),surfaceStatus:'LIVE'});}return response({ok:true,result:await transitionReplacement({query,transaction:withPgTransaction},{replacementOrderId:String(b.replacementOrderId||''),to:b.status as ReplacementStatus,actorId:u.id,note:b.note,source:'operations'}),surfaceStatus:'LIVE'});}catch(e){return response({ok:false,error:e instanceof Error?e.message:'REPLACEMENT_ACTION_FAILED',surfaceStatus:'ERROR'},409);}}
